### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by jme2712** [jef/streetmerchant#1005]
Below is my log. Any ideas on how to fix?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle streetmerchant@~prestart: streetmerchant@
6 info lifecycle streetmerchant@~start: streetmerchant@
7 verbose lifecycle streetmerchant@~start: unsafe-perm in lifecycle true
8 verbose lifecycle streetmerchant@~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jme2712/Desktop/bot/node_modules/.bin:/Users/jme2712/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle streetmerchant@~start: CWD: /Users/jme2712/Desktop/bot
10 silly lifecycle streetmerchant@~start: Args: [ '-c', 'npm run build && node build/index.js' ]
11 silly lifecycle streetmerchant@~start: Returned: code: 130  signal: null
12 info lifecycle streetmerchant@~start: Failed to exec start script
13 verbose stack Error: streetmerchant@ start: `npm run build && node build/index.js`
13 verbose stack Exit status 130
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid streetmerchant@
15 verbose cwd /Users/jme2712/Desktop/bot
16 verbose Darwin 20.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 130
22 error streetmerchant@ start: `npm run build && node build/index.js`
22 error Exit status 130
23 error Failed at the streetmerchant@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 130, true ]

**Comment by jef** [comment]
I would retry this. I fixed some issues with Docker recently.

```shell
docker run --cap-add=SYS_ADMIN \
  -it --rm --env-file ./.env \
  ghcr.io/jef/streetmerchant:nightly
```

**Comment by jme2712** [comment]
I tried with the test notification command and below is what I get.

#!/usr/bin/env zsh
cd /Users/jme2712/Desktop/bot
docker run --cap-add=SYS_ADMIN \
  -it --rm --env-file ./.env \
  ghcr.io/jef/streetmerchant:nightly test:notification:production
exec zsh




ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.0.0

(node:18) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at Printf.template (/app/build/logger.js:14:54)
    at Printf.transform (/app/node_modules/logform/printf.js:11:26)
    at Format.transform (/app/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/app/node_modules/winston/lib/winston/logger.js:305:29)
    at DerivedLogger.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/app/node_modules/pushover-notifications/lib/pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (/app/node_modules/pushover-notifications/lib/pushover.js:146:13)
    at IncomingMessage.<anonymous> (/app/node_modules/pushover-notifications/lib/pushover.js:250:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streetmerchant@ test:notification:production: `node build/__test__/notification-test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streetmerchant@ test:notification:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appuser/.npm/_logs/2020-12-08T19_46_53_077Z-debug.log
jme2712@Justins-MacBook-Pro bot %

**Comment by jef** [comment]
Interestingly enough, the latest `nightly` build is off a few versions which is strage. Gotta look into that.

@jme2712, can you use the `latest` tag instead and see what happens?

**Comment by jef** [comment]
Okay, I've update the `nightly` image.

Another thing you want to look into is remove _all_ quotes in the `.env`. This has side effects with Docker. See: https://github.com/jef/streetmerchant/issues/875#issuecomment-740985802

**Comment by jme2712** [comment]
That did it! Thank you much

**Comment by jef** [comment]
You're very welcome!
