### ISSUE TITLE
help error chromium

### ISSUE THREAD

**Issue by ncclucal** [jef/streetmerchant#1009]
[21:38:23] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: \"(\" unexpected\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)\n    at Interface.<anonymous> (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)\n    at Interface.emit (events.js:327:22)\n    at Interface.close (readline.js:424:8)\n    at Socket.onend (readline.js:202:10)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
[21:38:28] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/wiki/Installation:-Windows

**Comment by MujiSayed** [comment]
@jef looks like this might be a raspberry pi.
@ncclucal I'd recommend Following this: https://github.com/jef/streetmerchant/wiki/Installation:-Linux:-Raspberry-Pi-OS

**Comment by ncclucal** [comment]
@jef @MujiSayed at least its working now so far that i dont have this error message, but now its just completely doin timeouts...

[10:02:06] error :: ✖ [amazon] sony sonyps5c ps5 console - Navigation timeout of 30000 ms exceeded
[10:02:08] error :: ✖ [playstation] sony sonyps5c ps5 console - Navigation timeout of 30000 ms exceeded
[10:02:08] error :: ✖ [saturn] sony sonyps5c ps5 console - Navigation timeout of 30000 ms exceeded
[10:02:11] error :: ✖ [mediamarkt] sony sonyps5c ps5 console - Navigation timeout of 30000 ms exceeded

**Comment by jef** [comment]
Thanks @MujiSayed, good eye!

@ncclucal, I believe you'll get these because the browser is probably running out of memory and crashed. Depending how many sites you're trying to scrape, this will happen frequently. Especially on machines less than 4GB of RAM (all Pi's).

This doesn't limit you, you'll just have to decide what sites you'd like to monitor in priority with some update configuration.

**Comment by ncclucal** [comment]
@jef thank you very much for your help. Ur an awesome person that wrote a awesome code... THX

**Comment by StarLordRammi** [comment]
is this a file that needs editing or commands?

```
which chromium
which chromium-browser
/usr/bin/chromium-browser # Use this output for the next command
export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
```
