### ISSUE TITLE
the script doesnt seem to get a return result 

### ISSUE THREAD

**Issue by huntinganswers** [jef/streetmerchant#1010]
### Description

I can't seem to get a response from the merchants scraping for consoles

![env](https://user-images.githubusercontent.com/75166450/100525574-88c6ad80-3187-11eb-819e-3324ddf259a6.JPG)
![script](https://user-images.githubusercontent.com/75166450/100525577-8ebc8e80-3187-11eb-89f4-3d6552bff6ef.JPG)

**Comment by huntinganswers** [comment]
its probably something stupid on my part, but i cant seem to get opera to open either.  the script as written before modification works fine with the card search, but still doesn't open opera.

**Comment by controledxchaos** [comment]
Your series are wrong....it should be
"xboxsx, sonyps5c"

I suggest you remove brands and models since your searching for exact series

**Comment by huntinganswers** [comment]
ty!  

I'm assuming itll only open the browser if something is found?
![finally](https://user-images.githubusercontent.com/75166450/100527512-be27c700-3198-11eb-9190-14c8e5e1c463.JPG)

**Comment by controledxchaos** [comment]
yes unless you made that option false.. its true by default.... 

good luck!

**Comment by huntinganswers** [comment]
thanks again for your help.  fwiw - im not greedy and am simply looking to buy for my nephew for christmas.

**Comment by jef** [comment]
Seems like this is solved. Do you mind closing it out if so?

**Comment by huntinganswers** [comment]
sure thing ..sorry jef!
