### ISSUE TITLE
Paterson NJ Mirco Center Doesn't Exist According to Bot 

### ISSUE THREAD

**Issue by thearkisleaving** [jef/streetmerchant#1013]
### Description

tried multiple times to add micro center in Paterson, NJ and keep getting there is no location named Paterson.

![ScreenShot 1 ](https://user-images.githubusercontent.com/75191062/100530735-8bdf8f00-31c3-11eb-9734-7b81d2383250.png)

### Possible solution

 Could have spelled it wrong or didn't include it for some reason.

**Comment by erocconi** [comment]
A quick look at the list of MicroCenter stores in the readme shows that you should be using 'north-jersey'.
