### ISSUE TITLE
Gamestop 403 Error PS5

### ISSUE THREAD

**Issue by CLO2099** [jef/streetmerchant#1015]
### Description

 When running the command, GameStop returned a 403 error and is now issuing an "Access Denied" error when attempting to go to the site.

warn :: ✖ [gamestop] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
warn :: ✖ [gamestop] [sony (sonyps5de)] ps5 digital :: STATUS CODE ERROR 403

### Possible solution
Removing gamestop from the command?
<img width="924" alt="gamestop 403 error" src="https://user-images.githubusercontent.com/75194039/100533762-df5ad880-31d5-11eb-9209-b6aff59cc060.PNG">

**Comment by Niswendel** [comment]
Ya your IP is now blacklisted, gamestop just doesnt work, I hope u used a vpn

**Comment by CLO2099** [comment]
> Ya your IP is now blacklisted, gamestop just doesnt work, I hope u used a vpn

I saw it on the list of supported stores so I assumed it would work. I suggest removing it from the list or adding this to the FAQs as this will cause issues for anyone running this command.
