### ISSUE TITLE
.env file won't work

### ISSUE THREAD

**Issue by poneill4497** [jef/streetmerchant#1021]
ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART=""
BROWSER_TRUSTED=""
COUNTRY="great_britain"
DESKTOP_NOTIFICATIONS=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3070=""
MAX_PRICE_SERIES_3080=""
MAX_PRICE_SERIES_3090=""
MAX_PRICE_SERIES_RX6800=""
MAX_PRICE_SERIES_RX6800XT=""
MAX_PRICE_SERIES_RX6900XT=""
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_CORSAIR_SF=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS="microsoft"
SHOW_ONLY_MODELS="xbox series x"
SHOW_ONLY_SERIES="xboxsx"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="amazon-uk,box,game,very,currys,argos"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT="Chrome/87.0.4280.66"
WEB_PORT=""

is this right? it only shows the default env settings.

when I edit this do I have to write up anything before 'npm run start'

**Comment by huntinganswers** [comment]
what wont work?  you realize this is maintained by one guy ..that being said you could take the time to accurately describe the issue instead of saying ..it wont work.

**Comment by poneill4497** [comment]
> what wont work? you realize this is maintained by one guy ..that being said you could take the time to accurately describe the issue instead of saying ..it wont work.

it only shows the default env when i write npm run start. ive edited the env file and nothing happens

**Comment by huntinganswers** [comment]
why not try to copy the default to your desktop and make your adjustments there?  Delete the env file in the streetmerchant folder.  Then, copy the env file you created on your desktop to the streetmerchant folder?

**Comment by poneill4497** [comment]
> why not try to copy the default to your desktop and make your adjustments there? Delete the env file in the streetmerchant folder. Then, copy the env file you created on your desktop to the streetmerchant folder?
> 
> start the streetmerchant script with :dev

> start:dev
> nodemon --config nodemon.json

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\* .env
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --files ./src/index`
'ts-node' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

this came up when I done this.

**Comment by huntinganswers** [comment]
in order...
npm install -g typescript
npm install -g ts-node

**Comment by poneill4497** [comment]
> in order...
> npm install -g typescript
> npm install -g ts-node

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\* .env
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --files ./src/index`

This worked but it still shows the default env settings. 
do i move the env file to src\**\* .env or keep it in the main streetmerchant folder
