### ISSUE TITLE
FAQ/Country Codes Link doesn't work

### ISSUE THREAD

**Issue by MrAmos123** [jef/streetmerchant#1033]
### Description

![image](https://user-images.githubusercontent.com/4959320/100598011-11635c00-32f6-11eb-996c-b12fe9e2ca56.png)

This link doesn't work anymore, goes nowhere. 

https://github.com/jef/streetmerchant#supported-countries

I assume the 3 character country code for the UK is GBR?

**Comment by jef** [comment]
Sorry about that. Here it is here:

![image](https://user-images.githubusercontent.com/12074633/100622579-048f3a00-32ef-11eb-9875-d9912ebe766f.png)

Bear in mind, that this is only relevant when using the store `nvidia`, which is deprecated in favor of `bestbuy`. (Perhaps not in your region, but in US.)

**Comment by MrAmos123** [comment]
I see. Thank you.

**Comment by jef** [comment]
You're welcome!
