### ISSUE TITLE
Add Max Price for AMD Cards

### ISSUE THREAD

**Issue by trinitron79** [jef/streetmerchant#1039]
### Description

Newegg now has 3rd party offerings for Big Navi (rx6800,rx6800xt,rx6900xt) with prices in the $1600.  I'm sure others will come online as well.

### Possible solution

Add ability to set max price in .env file

E.g.
MAX_PRICE_SERIES_rx6800=
MAX_PRICE_SERIES_rx6800xt=
MAX_PRICE_SERIES_rx6900xt=

**Comment by cloutid** [comment]
it's already there: 
MAX_PRICE_SERIES_RX6800
MAX_PRICE_SERIES_RX6800XT
MAX_PRICE_SERIES_RX6900XT

**Comment by trinitron79** [comment]
O_O I did not see it in the README.ts file, just 3080/PS5/Ryzen.   
Will dig into it.

**Comment by cloutid** [comment]
it's in the .env example

**Comment by trinitron79** [comment]
Ahhh was looking at an old file.  Thanks!

**Comment by trinitron79** [comment]
Ability already in code.
