### ISSUE TITLE
Is there a way to limit how many times the bot can check? 

### ISSUE THREAD

**Issue by DankDoodles69** [jef/streetmerchant#1050]
I want to use the bot but I am afraid of being banned from newegg and etc from bot detection.
Is there a way to change how many times it will refresh to check?

**Comment by jef** [comment]
Great question! Set `PAGE_SLEEP_MIN` to something like `30000`. That'll scrape a product every 30 seconds.

**Comment by pxpew** [comment]
PAGE_SLEEP_MIN doesn't work on newegg (this is set to 6000)
![bot-ne](https://user-images.githubusercontent.com/75292517/100697423-903eb000-335b-11eb-999d-4657365ebe68.png)

**Comment by MaxCarlson** [comment]
@pxpew from the description of PAGE_SLEEP_MIN 

`Minimum sleep time between queries of the same product page`

It looks like it might not apply to the store as a whole, but for each product page (haven't looked at the code though).

**Comment by DankDoodles69** [comment]
I tried different values but nothing seemed to change in how many times it checked

**Comment by dmsolutionz** [comment]
> PAGE_SLEEP_MIN doesn't work on newegg (this is set to 6000)
> ![bot-ne](https://user-images.githubusercontent.com/75292517/100697423-903eb000-335b-11eb-999d-4657365ebe68.png)

PAGE_SLEEP_MIN="6000"
PAGE_SLEEP_MAX="16000"

Make sure you enclose in quotations, could you post your .env file?

**Comment by DankDoodles69** [comment]
I have tried this
PAGE_SLEEP_MIN="10000"
PAGE_SLEEP_MAX="20000"

...and it doesn't work. Also I just got banned from Newegg and trying to get an appeal, so that's fun.

Is there no way to have it like "Check website Example1... 10 seconds later... Check website Example 2... etc"
Like in between each search there is a timeout period of how long until it can check the next website

**Comment by Dimitah** [comment]
Would you suggest checking in a larger time window rather than a smaller one to avoid getting banned?

**Comment by tonezz9** [comment]
Are any bans happening on Best Buy? I know they drop a lot less but I'm about to just run it there

**Comment by briankelly** [comment]
@tonezz9 I haven't been banned on best buy, but I did get hit with a 24 hour IP ban on newegg. GL!

**Comment by phreeque** [comment]
I have managed to get banned from Gamestop.com, Not sure how to get that fixed, But I did not let it run for very long
![Capture](https://user-images.githubusercontent.com/9125152/101182068-a1b5df80-361b-11eb-9d37-75db91ab53dd.JPG)
.

**Comment by adrjmz** [comment]
@phreeque try using a vpn when running the script

**Comment by phreeque** [comment]
I will moving forward, I am just trying to figure out how to fix this for everyone else in my  house.
