### ISSUE TITLE
MAX_PRICE_SERIES_RX6800XT= not being honored

### ISSUE THREAD

**Issue by trinitron79** [jef/streetmerchant#1052]
### Description
.env file has price set to 900 - This should cover MSRP prices but ignore insane prices.   The hit was on a 3rd party selling of the card for $1699.
In testing I've set this max price to 100 to see if changes any behavior, it still seems to check stock so I'm not 100%  how its suppose to look with the max price set.  I've done the same with the 3080 max price and did not see any changes in the logs.

`.env`:

```
MAX_PRICE_SERIES_RX6800XT=900
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=rx6800xt
STORES=bestbuy:30000:60000,target:30000:60000,walmart:30000:60000,newegg:30000:60000,amazon:30000:60000,amd:60000:90000,bandh:30000:60000
```

`logs`:

```
[1:46:03 AM] info :: ✖ [newegg] [msi (rx6800xt)] amd reference :: OUT OF STOCK 
[1:46:07 AM] info :: ✖ [bestbuy] [xfx (rx6800xt)] amd reference :: OUT OF STOCK 
[1:46:09 AM] info :: 🚀🚨 [newegg] [sapphire (rx6800xt)] amd reference :: IN STOCK 🚨🚀 
https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202388 
[1:46:09 AM] info :: ✔ telegram message sent 
[1:46:10 AM] info :: ✔ email sent 
[1:46:11 AM] info :: ✔ sms sent 
[1:46:14 AM] info :: ✖ [newegg] [asrock (rx6800xt)] amd reference :: OUT OF STOCK 
[1:46:19 AM] info :: ✖ [newegg] [asus (rx6800xt)] amd reference :: OUT OF STOCK 
[1:46:19 AM] info :: ✖ [amazon] [gigabyte (rx6800xt)] amd reference :: OUT OF STOCK 
[1:46:22 AM] info :: ✖ [amazon] [sapphire (rx6800xt)] amd reference :: OUT OF STOCK
``` 

Running last night "nightly" docker code. (11/29/2020)

```
docker version
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        feb6e8a9b5
 Built:             Mon Nov  2 04:16:37 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       feb6e8a9b5
  Built:            Mon Nov  2 04:17:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Hopefully if I'm missing something it will be pretty apparent, I guess I was thinking that if the card is above x price it wouldn't look for it, but I could see that it still needs to look / understand price, see its over max price and move on w/o alerting it's in stock...   
If that's the case please inform and I'll close this PR.

Ugh I can't get the damn logs to format correctly.  Sorry :\\

**edit (jef): no worries 😄 fixed it up for ya**

**Comment by trinitron79** [comment]
Anyone have ideas on this?  I saw the other day on the discord server someone showing their logs, it looks like I should be seeing a message about the card being over the max set.

**Comment by jef** [comment]
Probably has to do with the container not correct. I'll do some testing.

**Comment by jef** [comment]
Reopen if it seems to persist. That should do it though.

**Comment by trinitron79** [comment]
I'll grab the next nightly docker build and will test out.

**Comment by trinitron79** [comment]
> 
> 
> Probably has to do with the container not correct. I'll do some testing.

Is there anything you'd like me to look at as well?
I'm just doing a 
docker pull ghcr.io/jef/streetmerchant:nightly
once image is down i'm just starting the container with a simple 
docker run --cap-add=SYS_ADMIN -it --rm -d --env-file ./.env ghcr.io/jef/streetmerchant:nightly
The only thing that's different is all .env file does NOT have any " (quotes) in it.

**Comment by trinitron79** [comment]
when I ran into it last yes, but figured it might have been doing something wrong.   I haven't been running app the last few days so not sure, can run again to see.
