### ISSUE TITLE
How do I add a new product?

### ISSUE THREAD

**Issue by TheRealSunder** [jef/streetmerchant#1053]
### Description

I wanted to add 3060ti as well as Ryzen 5 3600, however I can't seem to navigate how to include them, any ideas how?

**Comment by ryandh** [comment]
go to src/store/model

find the merchant, and insert new links there. 
you can just copy and paste, then replace the titles and links

![image](https://user-images.githubusercontent.com/5561911/100782081-c2362d80-33c0-11eb-86bb-90639693f59d.png)

then restart the app
