### ISSUE TITLE
Some Stores Stop Getting Pinged

### ISSUE THREAD

**Issue by joshstubble** [jef/streetmerchant#1055]
### Description

Running bot on Ubuntu Linux through Window VM. 

After the bot runs for roughly 2-3 hours, some stores stop getting pinged. Best Buy seems to be the most problematic of the stores and Amazon is the most reliable as it is always getting hit. 

### Possible solution

I ran a cron job restarting the bot every 15 min. 

In `$ Crontab -e`, add: 
`*/15 * * * * docker start <container #>` save with `ctrl X` > `Y` > `ENTER`

Must have user added to 'docker groups' to avoid `sudo` for cronjob. 

Add user to docker to avoid `sudo`: 

https://www.configserverfirewall.com/ubuntu-linux/add-user-to-docker-group-ubuntu/

**Comment by Duck3y** [comment]
Is Bestbuy giving you a captcha when you try to visit it manually on the machine? Are you receiving any rate limit errors?

**Comment by joshstubble** [comment]
No I don't get captcha'd on bestbuy site myself, and I'm not getting rate limited as I see no errors. Best Buy starts popping back up like normal on reboot

**Comment by rocketeer55** [comment]
Having the same issue - using Docker on Centos8. Certain stores will just stop showing up in the logs, without any errors (for me, Amazon and Playstation stores always keep working). Restarting the container fixes the issue temporarily.

**Comment by jef** [comment]
This isn't great :disappointed: There are few other issues like this. I'll take some time to debug in the near future.

In the mean time, let me know if you end up finding anything else related.

Thanks!

**Comment by jef** [comment]
I updated the lookup logic. This should be resolved now.
