### ISSUE TITLE
Add Configuration file in Linux (Kubuntu / Debian Based) 

### ISSUE THREAD

**Issue by Bteogaming** [jef/streetmerchant#1063]
No configuration file for Debian-based Linux. 

Configuration is set to defaults, which may not be great for all people. 
Solution is very simple, just add a config/env file. 
Maybe (most likely) I am dumb and this is already there, but I couldn't find.

Im using the latest release of Kubuntu by the way.

**Comment by thefl0yd** [comment]
if you read the instructions under "installation":

"Copy .env-example to a new file .env and edit the .env file to your liking using your favorite text editor
More on this in customization"

You could have saved yourself the time and embarrassment of opening a pointless issue!

**Comment by Bteogaming** [comment]
I tried looking for the .env file before I made this post (I should've been more specific), but I couldn't find it. I also did this on a windows install perfectly fine, just for some reason it didn't work on Linux. I have git and nodejs installed. 

![image](https://user-images.githubusercontent.com/75320181/100876484-70031400-3475-11eb-8b5c-c628483ccab5.png)

**Comment by joshstubble** [comment]
your hiding your hidden files. Im not sure how to do it on Debian, but in Ubuntu its in the right side folder settings hit "show hidden files"

**Comment by joshstubble** [comment]
you're

**Comment by Bteogaming** [comment]
Oh okay thanks i figured it out :)
