### ISSUE TITLE
Add ASUS ROG Crosshair VIII Dark Hero Motherboard

### ISSUE THREAD

**Issue by FrankFioretti** [jef/streetmerchant#1064]
### Description
I can't believe I'm asking, but this is the world we live in now. Would it be possible to add the ASUS ROG Crosshair VIII Dark Hero Motherboard?

**Comment by diamondshark1** [comment]
As a fellow Dark Hero enthusiast I agree that would be great if this had it. Alternatively though, I think if there was a more cohesive way for us to add products on our own that may be the better way of handling the additional requests.

**Comment by FrankFioretti** [comment]
I agree. I just figured since the pattern in the past has been individual official product additions that I would ask.

**Comment by jef** [comment]
> As a fellow Dark Hero enthusiast I agree that would be great if this had it. Alternatively though, I think if there was a more cohesive way for us to add products on our own that may be the better way of handling the additional requests.

Working on something that would make it easy for everyone to use. Otherwise you can also add the links to the current models!

Thanks all.

**Comment by FrankFioretti** [comment]
Thank you. I was able to add it for 3 stores by replacing an existing model.

**Comment by GameSyns** [comment]
Anyway you could provide the format that you did that, or something I can use to merge in? I would appreciate it!

**Comment by FrankFioretti** [comment]
Sure, I replaced the links for the asus 3070 dual model in 5 of the stores .ts files and then configured the .env file to only look for that model at those stores. Here's an example from Amazon.ts

`		{
			brand: 'asus',
			cartUrl:
				'https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08MTKJ6HM&Quantity.1=1',
			model: 'dual',
			series: '3070',
			url: 'https://www.amazon.com/dp/B08MTKJ6HM'
		}`

I'm CERTAIN if this didnt "just work" i would have put more effort into actually adding the proper name etc. instead of just replacing an existing model.

**Comment by GameSyns** [comment]
Appreciate it, fortunately, through all of this research, I found the VIII Hero at Best Buy! It was for in-store pick-up on the 11th if this interests you.

**Comment by FrankFioretti** [comment]
Can i have this listing url for it?

**Comment by GameSyns** [comment]
https://www.bestbuy.com/site/asus-rog-crosshair-viii-hero-socket-am4-usb-c-gen2-amd-motherboard-with-led-lighting/6356982.p?skuId=6356982

**Comment by GameSyns** [comment]
It's not the dark hero, but I'll take what I can get.

**Comment by FrankFioretti** [comment]
Ah, gotcha. The main differences are the passive PCH cooling and the dynamic OC switching between single and multi-core. That's why alot of people are looking for the newer "Dark" version.

**Comment by GameSyns** [comment]
Gotcha, makes sense! The regular Hero was the one I was looking at specifically, which is also completely sold out almost everywhere as well. Good luck on your search!
