### ISSUE TITLE
Cannot Get Twitch notifications to work.

### ISSUE THREAD

**Issue by kings431** [jef/streetmerchant#1068]
I've requested api though twitch dev and setup most of the tokens but still cannot get it to work.

Does anyone have a guide on how to set this up?
Would be appriciated!

Thanks

**Comment by gmanc2** [comment]
https://twitchtokengenerator.com Im not sure how to incorporate the client secret though.

**Comment by jef** [comment]
Unfortunately, I don't use Twitch. Although, I believe others have it working. Perhaps one of these days I will set it up to help. Sorry :cry: 

But hopefully someone else can give you the help you're looking for!
