### ISSUE TITLE
how do I edit and add new stores in program

### ISSUE THREAD

**Issue by 100to1000aday** [jef/streetmerchant#1075]
### Description

how do I edit and add new stores in program and how do I change and edit products or delete product search

**Comment by riskynacho** [comment]
take a look in `src/store/model`

**Comment by ithahn** [comment]
https://github.com/jef/streetmerchant/wiki/Help:-Configuration:-Adding-a-store

**Comment by jef** [comment]
Here's a live example as well: https://github.com/jef/streetmerchant/commit/af96c5f2e808af7496f3c3299e4cf173105de48b

Thanks all!

**Comment by Sloth-on-meth** [comment]
> https://github.com/jef/streetmerchant/wiki/Help:-Configuration:-Adding-a-store

dead link

**Comment by jef** [comment]
https://jef.codes/streetmerchant/help/general/#adding-a-store
