### ISSUE TITLE
Docker - Not opening browser when item is in stock

### ISSUE THREAD

**Issue by ohmygawd408** [jef/streetmerchant#1078]
### DESKTOP_NOTIFICATIONS="true"
OPEN_BROWSER="true"

DESKTOP_NOTIFICATIONS="true"
OPEN_BROWSER="true"

Not sure what I'm doing wrong. I'm running mac

docker run --cap-add=SYS_ADMIN   -it --rm --env-file ./file.env   ghcr.io/jef/streetmerchant:nightly

**Comment by jef** [comment]
Unfortunately, I don't know if you are able to open from Docker. I haven't spent much time on trying to forward any system calls either, but yeah, you definitely can't as-is. (Unless someone knows otherwise.)

**Comment by ohmygawd408** [comment]
> Unfortunately, I don't know if you are able to open from Docker. I haven't spent much time on trying to forward any system calls either, but yeah, you definitely can't as-is. (Unless someone knows otherwise.)

Thanks Jef. How about opening it in native? When I run "npm run start:dev" it seems to not locate my file.env and I'm not sure how to to call it using npm run start:dev

**Comment by jef** [comment]
Your `.env` file should be in the same directory everything else is located. You can also start by using `npm run start` if you're not actively developing.

**Comment by ohmygawd408** [comment]
> Your `.env` file should be in the same directory everything else is located. You can also start by using `npm run start` if you're not actively developing.

Hi Jef,

Yes, the file is in the "streetmerchant" root folder. The file I named my .env was "botit.env". However, when running npm runstart it will run default settings but not my custom configuration.

Thank you for your help so far.

**Comment by ohmygawd408** [comment]
Hi Jef, I figured out issue. Mac doesn't allow you to name a file .env. I had to switch to a windows
