### ISSUE TITLE
sms only works when vpn is off. is there a work around?

### ISSUE THREAD

**Issue by controledxchaos** [jef/streetmerchant#1080]
sms doesn't work when vpn is on. This is verizon.
added friends number which is tmobil and his goes through with vpn on or off.

is there a work around?

**Comment by thefl0yd** [comment]
SMS works by sending email via SMTP using the email server you specify.

If your VPN provider blocks SMTP ports (probably likely, to prevent abuse), SMS won't work.
If your email provider blocks your VPN provider's IP range[s] (also possible), SMS won't work.

This has nothing to do with streetmerchant. It's not a bug.

**Comment by controledxchaos** [comment]
Thank you for the explanation. I assume there isn’t a work around?

Sent from my iPhone

On Dec 2, 2020, at 7:25 AM, thefl0yd <notifications@github.com> wrote:

﻿

SMS works by sending email via SMTP using the email server you specify.

If your VPN provider blocks SMTP ports (probably likely, to prevent abuse), SMS won't work.
If your email provider blocks your VPN provider's IP range[s] (also possible), SMS won't work.

This has nothing to do with streetmerchant. It's not a bug.

**Comment by thefl0yd** [comment]
Before you read into my troubleshooting steps below, have you considered switching to another notification type? I was using email/sms but just changed to 'pushover' and it was really simple. Just pushes into the pushover app on your phone. There's about 5 minutes of setup required and a small fee, but in my opinion it's probably worth it.

Sadly, this requires a bit of knowledge in the internet infrastructure domain to truly troubleshoot but let me try and lay it out.

To figure out if your VPN provider is blocking outbound SMTP (email, TCP port 25) you could connect to VPN and do some testing. A good means of testing is trying to connect to various SMTP servers around the internet and see if your connection is accepted. There are ways of finding this - you'd look for the domain's MX record, like so:

$ host -tmx gmail.com
gmail.com mail is handled by 5 gmail-smtp-in.l.google.com.
gmail.com mail is handled by 40 alt4.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 20 alt2.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 30 alt3.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 10 alt1.gmail-smtp-in.l.google.com.
$ host -tmx hotmail.com
hotmail.com mail is handled by 2 hotmail-com.olc.protection.outlook.com.
$ host -tmx yahoo.com
yahoo.com mail is handled by 1 mta6.am0.yahoodns.net.
yahoo.com mail is handled by 1 mta5.am0.yahoodns.net.
yahoo.com mail is handled by 1 mta7.am0.yahoodns.net.
$ host -tmx verizon.com
verizon.com mail is handled by 15 mxb-0024a201.gslb.pphosted.com.
verizon.com mail is handled by 15 mxa-0024a201.gslb.pphosted.com.
$


Anyway, these are the public SMTP mail servers that accept email for those domains. So next up, you could try and connect to any of those on port 25. If you're on a unix (linux/bsd/etc) host, you could use telnet or nc:

$ telnet mxb-0024a201.gslb.pphosted.com 25
Trying 148.163.153.92...
Connected to mxb-0024a201.gslb.pphosted.com.
Escape character is '^]'.
220 mx0b-0024a201.pphosted.com ESMTP mfa-m0115887
^]
telnet> q
Connection closed.
$

(or using nc)

$ nc hotmail-com.olc.protection.outlook.com 25
220 DM6NAM12FT011.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Wed, 2 Dec 2020 12:34:14 +0000
^C
$

Note the connection string is generally {telnet,nc} [hostname] [port], where port is 25.

If you get a greeting (the line 220 above) then you've successfully connected. If you get a timeout or any other issue then your VPN is blocking port 25. You could try switching the port to 587 (there's an option in streetmerchant) but that's ONLY for what they call local delivery, IE you couldn't deliver mail to the gmail server using that port expecting it to get relayed to verizon/tmobile/att/whomever. It would only accept the mail destined for THAT domain.

**Comment by abeth66** [comment]
The easy solution: after connecting to your VPN, sign in to Gmail via your browser. Notifications should now work.

**Comment by controledxchaos** [comment]
The easy solution fixed all my problems. Thanks again!!

Sent from my iPhone

On Dec 2, 2020, at 10:47 AM, abeth66 <notifications@github.com> wrote:

﻿

The easy solution: after connecting to your VPN, sign in to Gmail via your browser. Notifications should now work.
