### ISSUE TITLE
All cards notified as InStock for BestBuy.ca after last update

### ISSUE THREAD

**Issue by sebspas** [jef/streetmerchant#1093]
Hello,

all the cards (3070,3080) are notified as in stock even though there are not on bestbuy-ca.

My config didn't change and it was working yesterday I just did a pull request this morning and it stopped working :/

Thanks for the help!

**Comment by munasef** [comment]
Can confirm, this is also happening with PS5 entries

**Comment by SamP301** [comment]
I managed to fix that issue by adding a trigger when the button contains the disabled class. Working fine now on my side. Just add that element to the labels of the bestbuy-ca model : 

```js
outOfStock: {
	container: "button.addToCartButton.disabled_XY3i_",
	text: ["Add to Cart"],
}
```
