### ISSUE TITLE
Amazon Basket not working

### ISSUE THREAD

**Issue by ithahn** [jef/streetmerchant#1095]
### Description

There is an error page shown by Amazon.

This link is beeing used throwing an error:
https://www.amazon.de/gp/aws/cart/add.html?ASIN.1=B087VM5XC6&Quantity.1=1

### Possible solution

No idea for a solution.

**Comment by jef** [comment]
Probably has something to do with the options you're given when adding to the cart.

![image](https://user-images.githubusercontent.com/12074633/100936275-3fe06300-34bf-11eb-8201-7b8af23e0f65.png)

I think it should be disabled for now. Thanks!

**Comment by ithahn** [comment]
I think this is for all links...
Tested Xbox Series X too... Not working...
