### ISSUE TITLE
MAX_PRICE_SERIES_3080 setting not enforced on "topachat" store

### ISSUE THREAD

**Issue by axcawef** [jef/streetmerchant#1097]
### Description

Hi, 

I have a max price for the RTX 3080 with MAX_PRICE_SERIES_3080=750 in .env file.
The limit is respected for all stores (see "pccomponentes" as example in screenshot below).However, for "topachat" store, cards in stock are being notified even though the price limit is reached (see store price).

![](https://i.imgur.com/Nqo9VG2.png)

![](https://i.imgur.com/Tf4vkMe.png)

I have the done a git pull of the repo this morning, and using it on a Win 10 machine.

### Possible solution

Label "maxPrice" is not set for "topachat" store (see https://github.com/jef/streetmerchant/blob/main/src/store/model/topachat.ts), whereas it is for "pccomponentes" store (see https://github.com/jef/streetmerchant/blob/main/src/store/model/pccomponentes.ts).

**Comment by jef** [comment]
Ah! Yeah, we can add this in. Thanks!

**Comment by jef** [comment]
Should be fixed now! Let me know otherwise.
