### ISSUE TITLE
Add AIBs for Big Navi

### ISSUE THREAD

**Issue by jaw20** [jef/streetmerchant#1098]
### Description

Add the AIB cards for amazon and AIBs cards available on Newegg and Bestbuy for the RX 6800 and RX 6800 XT
I do not have the links for Amazon, but they are there. This is a continuation of #931 and #937  which _still_ hasn't been addressed.

### Newegg:
		{   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930047',
			model: 'challenger',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-rx6800-clp-16go/p/N82E16814930047'
		},

        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930048',
			model: 'phantom gaming',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-rx6800-pgd-16go/p/N82E16814930048'
		},
        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930049',
			model: 'phantom gaming',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-pgd-16go/p/N82E16814930049'
		},
        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930050',
			model: 'taichi',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-tcx-16go/p/N82E16814930050'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126478',
			model: 'tuf',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-tuf-rx6800-o16g-gaming/p/N82E16814126478'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126476',
			model: 'tuf',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-xt-tuf-rx6800xt-o16g-gaming/p/N82E16814126476'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126477',
			model: 'strix',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-rog-strix-rx6800-o16g-gaming/p/N82E16814126477'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126475',
			model: 'strix lc',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-xt-rog-strix-lc-rx6800xt-o16g-gaming/p/N82E16814126475'
		},
        {   
			brand: 'sapphire',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202391',
			model: 'nitro+',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-02-20g/p/N82E16814202391'
		},
        {   
			brand: 'sapphire',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202390',
			model: 'nitro+',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-01-20g/p/N82E16814202390'
		},
        {   
			brand: 'xfx',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814150844',
			model: 'merc',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/xfx-radeon-rx-6800-xt-rx-68xtacbd9/p/N82E16814150844'
		},

### Bestbuy

		{   
			brand: 'xfx',
			model: 'merc',
			series: 'rx6800xt',
			url:
				'https://www.bestbuy.com/site/xfx-merc-319-amd-radeon-rx-6800xt-16gb-gddr6-pci-express-4-0-gaming-graphics-card-black/6442585.p?skuId=6442585'
		},

**Comment by jef** [comment]
The build is breaking. If this is all that is needed, I can add in later today.

**Comment by jaw20** [comment]
The one on the pull request is a bit different, as the terms in store.ts are Merc, Phantom Gaming, and there is no nitro+ se. What I have posted should conform to the store.ts unlike the other one.

**Comment by jef** [comment]
Thanks for doing the work. Pushing up now.
