### ISSUE TITLE
amazon is getting false hits. 

### ISSUE THREAD

**Issue by botissues** [jef/streetmerchant#1117]
### Description

hello, I have everything working correctly i think. however, for some reason I am getting false hits from amazon on the zotac 3070 and evga 3070. it opens my browser to an undefined page. I will include screen shots of the issue as well as my .env file. Any help would be greatly appreciated.
![Untitled](https://user-images.githubusercontent.com/75399183/100944655-54275e80-34c5-11eb-9316-9e46d8b6ad6a.png)
![fsdf](https://user-images.githubusercontent.com/75399183/100944941-e3347680-34c5-11eb-8765-ebcc2f16393f.png)

**Comment by jef84142** [comment]
in the .env file, set the "Auto Add to Cart" to false, this feature is not working for amazon.

**Comment by thefl0yd** [comment]
not a false hit, the card is gone before you get to it.

**Comment by jef** [comment]
> in the .env file, set the "Auto Add to Cart" to false, this feature is not working for amazon.

This feature is working, but when an item is out of stock, this page is shown (sometimes, depending on the item).
