### ISSUE TITLE
Amazon store pings, even though price limit is set below amount

### ISSUE THREAD

**Issue by lyon812345** [jef/streetmerchant#1125]
![L8lSjBV](https://user-images.githubusercontent.com/6926388/100958637-cc3f5580-34c0-11eb-9e5d-cc3d915b2519.png)

Basically, for some reason, when the bot finds that this amazon page is in stock, it decides to ping all my things, even though it's much higher then what my price limit is set at (650). 
![4vYmQau](https://user-images.githubusercontent.com/6926388/100958633-cba6bf00-34c0-11eb-8570-c4aa7ee806a9.png)

**Comment by GameSyns** [comment]
+1
This is the store url: https://www.amazon.com/dp/B08L8L9TCZ

**Comment by brooksrockett** [comment]
+1, getting the same thing today although it's now for the gigabyte 3070. Tempted to turn off Amazon.

**Comment by jef** [comment]
Thanks. I'll update

**Comment by jef** [comment]
```
ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.1.0

[11:45:15 AM] info :: ℹ selected stores: amazon
[11:45:15 AM] info :: ℹ selected models: ftw3
[11:45:15 AM] info :: ℹ selected series: 3070
[11:45:31 AM] info :: ✖ [amazon] [evga (3070)] ftw3 :: PRICE 999.99 EXCEEDS LIMIT 600
[nodemon] restarting due to changes...
[nodemon] starting `ts-node --files ./src/index`
[nodemon] still waiting for 3 sub-processes to finish...
ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.1.0

[11:45:38 AM] info :: ℹ selected stores: amazon
[11:45:38 AM] info :: ℹ selected models: ftw3
[11:45:38 AM] info :: ℹ selected series: 3070
[11:45:51 AM] info :: 🚀🚨 [amazon] [evga (3070)] ftw3 :: IN STOCK 🚨🚀
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08L8L9TCZ&Quantity.1=1
^C
```

Looks good here. I'll push this up.

I need to add the option to disable cart links... I'll do that in a separate commit.

**works:** https://www.amazon.com/gp/aws/cart/add.html?&ASIN.1=B00TKFCYP0&Quantity.1=1
**doesn't work:** https://www.amazon.com/gp/aws/cart/add.html?&ASIN.1=B08L8L9TCZ&Quantity.1=1
