### ISSUE TITLE
LinksBuilder loop on latest update

### ISSUE THREAD

**Issue by creeperdude997** [jef/streetmerchant#1129]
### Description

consstant loop of Running linksBuilder, never actually searching for anything. Worked fine on the previous update, not sure what happened. Tried reinstalling same thing. Win10

![image](https://user-images.githubusercontent.com/75228915/100970048-0b56c080-352c-11eb-92a9-91b7b1ae1787.png)

**Comment by gigi2006** [comment]
i have the same but only on amazon-uk

**Comment by Tychi007** [comment]
did any one fix this?

**Comment by Tychi007** [comment]
Hi all got the same issue, 
![image](https://user-images.githubusercontent.com/59968325/101089973-d8eda780-35ad-11eb-9534-081d111774f0.png)

**Comment by R7-40** [comment]
any fix yet i got the same problem

**Comment by jef** [comment]
Is this still the case on latest? 15ec12b0a3a95716243bfd06f6d41959bff7c36e as of this writing.

**Comment by R7-40** [comment]
I changed some stuff around in the env file and got it working

**Comment by AlphaOmega2020** [comment]
> I changed some stuff around in the env file and got it working

maybe share that information to help others that are in or come across the same situation?

**Comment by AlphaOmega2020** [comment]
@jef i have the same issue on some of my instances docker containers), however have some working correctly, all run exactly the same version (nightly) as they update each morning, all running the same .env other than searching for AMD CPU or AMD GPU, or Nvidia GPU.

**Comment by H5N1Duck** [comment]
Same issue with LinksBuilder when searching UK Shops although Amazon does work

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/issues/1200

**Comment by joshstubble** [comment]
Im getting the same problem with LinkBuilder on a clean install of the most recent push. I tried to mess with the code to get it to stop but just couldnt get it. I went back down to commit `364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b` and am getting no errors at all. You can get back to previous commits by using `git check out 364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b` or `git reset 364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b --hard` at the root of your project. Thats my only fix at the moment.

**Comment by joshstubble** [comment]
I just did a clean install and the problem solved itself 🤷‍♂️. Not getting any errors now. Maybe a late night push did something but I'm back on `nightly` working fine.

**Comment by jef** [comment]
I didn't run into this, but 9dc04b36388907f07da5555d19fa517ed0b207ed should help to see what's actually building.

**Comment by Jason-Murray** [comment]
I experienced this issue when running in docker due to following a tutorial that had placed double quotes around options in the dotenv file like this:
```
SHOW_ONLY_SERIES="sonyps5c"
STORES="amazon-uk,argos,box,xbox,currys,game,johnlewis,scan,shopto,smythstoys,very,gamestop-ie,smythstoys-ie,argos-ie,tesco-ie"
```

I adjusted these options to have no quotes, and now it's all working fine for me:
```
SHOW_ONLY_SERIES=sonyps5c
STORES=amazon-uk,argos,box,xbox,currys,game,johnlewis,scan,shopto,smythstoys,very,gamestop-ie,smythstoys-ie,argos-ie,tesco-ie
```

**Comment by jef** [comment]
Great news. Thanks @Jason-Murray.
