### ISSUE TITLE
amazon.DE false Alarms

### ISSUE THREAD

**Issue by gigi2006** [jef/streetmerchant#1132]
at Amazon.DE there are many false alarms.
the problem is that Amazon probably redirects automatically from the PS5 console to the controller and then the crawler here thinks that this is still the console.

is there a way to correct this?

**Comment by Nuggzan** [comment]
i never had a false alarm at amazon-de

**Comment by gigi2006** [comment]
> i never had a false alarm at amazon-de

I have only today 20-30

**Comment by jef** [comment]
This is a side effect of the playstation's link, as they have no direct link to the console.

Feel free to change your `IN_STOCK_WAIT_TIME=""` variable to something else so you don't get alerted repeatedly. The value is in milliseconds.

**Comment by jef** [comment]
Perhaps this can be fixed by adding another label helper to confirm that it's the item we're looking for. I'll keep this open for now.

**Comment by gigi2006** [comment]
> Perhaps this can be fixed by adding another label helper to confirm that it's the item we're looking for. I'll keep this open for now.

Thank you Jef :)

I really have to thank you again, with this tool I was able to buy what I was looking for a long time...

**Comment by jef** [comment]
That's awesome to hear!

**Comment by jef** [comment]
Take a look at that PR and let me know if that looks good (in terms of what the text should say).

**Comment by gigi2006** [comment]
@jef Hey bro, the problem we have unfortunately now at amazon.fr and I think also at amazon.es... today for example I get for the 100th time the notification that at amazon.fr the PS5 is available, but unfortunately it is only a redirect to the controller.

do you think your fix from amazon.de is also applicable to the other.

**Comment by jef** [comment]
Unfortunately there isn't a fix for this. You'll have to disable those sites until they get the URLs properly adjusted.

Or you can update your in stock notification to only notify you every hour or so, so you don't get bombarded with notifications.

**Comment by gigi2006** [comment]
> Unfortunately there isn't a fix for this. You'll have to disable those sites until they get the URLs properly adjusted.
> 
> Or you can update your in stock notification to only notify you every hour or so, so you don't get bombarded with notifications.

the problem is if i reduce it i'm scared of missing it.  maybe an idea would be to specify the minimum price.  So I would start with the ps5 350 and so I would not get a notification for the controller that only costs 80 €.  just don't know how difficult that is to implement.

**Comment by ithahn** [comment]
MIN_PRICES_SERIES could help?!

**Comment by gigi2006** [comment]
> MIN_PRICES_SERIES could help?!

Do you believe me that I haven't seen Min Price the whole time.

**Comment by jef** [comment]
> > MIN_PRICES_SERIES could help?!
> 
> Do you believe me that I haven't seen Min Price the whole time.

Haha, well it's not a thing so no need to worry! That being said, we could definitely add this in. I personally have more priority to refactor some of the config in general, but I don't mind if someone takes the time to add this in!

**Comment by Sly8383** [comment]
Thank you for the awsome job jf.

Any idea where we can add the Min_price parametr ?
I'm facing the same issue.
