### ISSUE TITLE
item being incorrectly flagged as a 30** series

### ISSUE THREAD

**Issue by AlphaOmega2020** [jef/streetmerchant#1134]
The following item keeps being flagged as a 3090 yet there seems to be nothing on the page that reflects how?

[Image](https://imgur.com/a/xCUYqNk)

https://www.scan.co.uk/products/3m-club-3d-cac-1373-10k-120hz-hdmi-v21-performance-48gb-s-cable-aluminum-hood-black

**Comment by AlphaOmega2020** [comment]
yes i appreciate people can use brand filters but for those that dont (like me) will be plagued with this in the UK.

**Comment by jef** [comment]
No idea, because we don't have a `3m` brand in the source code...

https://github.com/jef/streetmerchant/blob/main/src/store/model/scan.ts

Perhaps you've made changes to the links?

**Comment by AlphaOmega2020** [comment]
exactly why im confused, ive made not changes to your code however i was running on "latest", ive just switched to "nightly" and will see if the error still occurs.

**Comment by AlphaOmega2020** [comment]
happy to say that moving to nightly from latest resolved the issue
