### ISSUE TITLE
email notif won't work

### ISSUE THREAD

**Issue by CluelessNova** [jef/streetmerchant#1153]
I have the email setup, but when I run a test notification, it gives me an error of 'Invalid login:353-5.7.8 Username and Password not accepted'. I have tried switching emails but nothing seems to work.

**Comment by CluelessNova** [comment]
Update: I have been able to troubleshoot the issue

**Comment by BaileyMillerSSI** [comment]
Can you update how you were able to troubleshoot the error?

**Comment by CluelessNova** [comment]
I used a gmail account to use as the email account and you need to go to the google account settings, third-party access, and then turn off the Google Account sign-in prompts.
