### ISSUE TITLE
Color not showingh

### ISSUE THREAD

**Issue by essah4life** [jef/streetmerchant#1167]
Color Problem:

Unfortunately the "OUT OF STOCK" messages is not displayed in red for me.  "info" is displayed in green.
I tried to install Chalk to solve the problem because i saw it in the logger.ts file but it didn't help.
Anyone got the same problem and knows how to fix it?

Thanks!

**Comment by R3PTIL3** [comment]
Use Windows cmd instead git cmd :)

**Comment by essah4life** [comment]
> 
> 
> Use Windows cmd instead git cmd :)

That actually worked, didn't expect it to be an issue of git cmd. Thanks mate!
