### ISSUE TITLE
amazon-de.ts false negative

### ISSUE THREAD

**Issue by DerHOgi** [jef/streetmerchant#1175]
For a test I changed the url of the ps5 console to the controller, which is available and the bot still says no stock. I don't check this for other amazon countrys but it should be the same. Maybe the container changed?

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/issues/1132

**Comment by DerHOgi** [comment]
No, thats another problem. There is no redirect. It says the controller is not mavailable!

**Comment by DerHOgi** [comment]
> #1132
No, thats another problem. I set the url to the controller 'https://www.amazon.de/dp/B08H99BPJN'
There is no redirect. It says the controller is not available!
