### ISSUE TITLE
amazon-de.ts false negative NOT #1132

### ISSUE THREAD

**Issue by DerHOgi** [jef/streetmerchant#1178]
This is NOT > #1132

For a test I changed the url of the ps5 console to the controller, which is available and the bot still says no stock. I don't check this for other amazon countrys but it should be the same. Maybe the container changed?

**I set the url to the controller 'https://www.amazon.de/dp/B08H99BPJN' in the amazon-de.ts file. There is no redirect. It says the controller is not available! This is why I said it is a false negative and not a false positiv.**

**Comment by jef** [comment]
Sorry about that. Pushing a fix now.
