### ISSUE TITLE
Max Price not working for 3070 or 3090 cards on Amazon

### ISSUE THREAD

**Issue by FawnPat** [jef/streetmerchant#1187]
## Expected Behavior

I set the  max price variable for the 3070 cards to 700, and 1900 for the 3090 cards

## Current Behavior

The bot appears to be ignoring the max price variables, and sending notifications for 3070 and 3090 cards that are above those prices. Thus far, I have only seen this happen with amazon.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

**OS:**
**.env file:**

```dotenv

```

**Comment by FawnPat** [comment]
I am running this on windows 10.

Here is my .env file:

# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY="usa"
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK="https://discord.com/api/webhooks/778053339023540225/ly_CARYvD93mIfS6C8KNIe2pv52BFqT8Sf9CHJuqmVo8EQk_hdhu35JNgc6csQpoD9U8"
EMAIL_PASSWORD="oafp fzpk oyhb xyup"
EMAIL_TO=
EMAIL_USERNAME="thomassamuelmitchell@gmail.com"
HEADLESS=
IN_STOCK_WAIT_TIME="1800"
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI="650"
MAX_PRICE_SERIES_3070="700"
MAX_PRICE_SERIES_3080="1000"
MAX_PRICE_SERIES_3090="1900"
MAX_PRICE_SERIES_RYZEN5600="400"
MAX_PRICE_SERIES_RYZEN5800="550"
MAX_PRICE_SERIES_RYZEN5900="650"
MAX_PRICE_SERIES_RYZEN5950="900"
MAX_PRICE_SERIES_SONYPS5C="600"
MAX_PRICE_SERIES_SONYPS5DE="500"
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER="false"
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN="15000"
PAGE_SLEEP_MAX="20000"
PAGE_TIMEOUT="60000"
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER="tmobile"
PHONE_NUMBER="3017751704"
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS="amd,asus,evga,gigabyte,microsoft,msi,nvidia,sony,zotac"
SHOW_ONLY_MODELS="5600x,5800x,5900x,5950x,amd reference,dual,dual oc,strix,strix oc,tuf,tuf oc,ftw3,ftw3 ultra,xc3,xc3 black,xc3 ultra,aorus master,aorus xtreme,eagle,eagle oc,gaming,gaming oc,turbo,vision,vision oc,xbox series x,xbox series s,gaming x trio,ventus 2x oc,ventus 3x,ventus 3x oc,founders edition,ps5 console,ps5 digital,amp holo,amp extreme holo,trinity,trinity oc,twin edge,twin edge oc"
SHOW_ONLY_SERIES="ryzen5600,ryzen5800,ryzen5900,ryzen5950,rx6800,rx6800xt,rx6900xt,3060ti,3070,3080,3090,sonyps5c,sonyps5de,xboxss,xboxsx"
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES="bestbuy,blt,walmart,target,newegg,tigerdirect,adorama,amazon,amazon-ca,amd,asus,bandh,bestbuy-ca,gamestop,evga,newegg-ca,nvidia,officedepot"
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT=
WEB_PORT=

**Comment by Brusalk** [comment]
Same issue - currently happening with this card: https://www.amazon.com/MSI-GeForce-RTX-3090-24G/dp/B08HR9D2JS

Price looking at amazon is currently " $3,098.98"

```
<span id="priceblock_ourprice" class="a-size-medium a-color-price priceBlockBuyingPriceString">$3,098.98</span>
```

.env
```
SHOW_ONLY_SERIES="3080,3090,sonyps5de,rx6800xt,rx6900xt"
DESKTOP_NOTIFICATIONS="true"
LOG_LEVEL="info"
STORES="adorama:10000:30000,amazon,amd,bandh:10000:30000,bestbuy,evga,microcenter,newegg,nvidia,playstation,pny,target,walmart,zotac:10000:30000"
MAX_PRICE_SERIES_3090="2000"
MAX_PRICE_SERIES_3080="1000"
```

**Comment by jef** [comment]
Crap, I only updated germany. Updating now...

Thanks!

**Comment by FawnPat** [comment]
> Crap, I only updated germany. Updating now...
> 
> 
> 
> Thanks!

Glad I could be of help. Thanks for building and supporting street merchant!

**Comment by sabryno** [comment]
i have the same problem with the 3080 on amazon-es

**Comment by sabryno** [comment]
![success-1622288773707](https://user-images.githubusercontent.com/85020180/120069223-0d39b080-c085-11eb-9104-716c548f6f54.png)

MAX_PRICE_SERIES_3080="1200"

**Comment by sabryno** [comment]
my env file confiuration:

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART="false"
BROWSER_TRUSTED=""
COUNTRY="Italy"
DESKTOP_NOTIFICATIONS="false"
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3060="700"
MAX_PRICE_SERIES_3060TI="800"
MAX_PRICE_SERIES_3070="900"
MAX_PRICE_SERIES_3080="1200"
MAX_PRICE_SERIES_3090="1500"
MAX_PRICE_SERIES_RX6800="600"
MAX_PRICE_SERIES_RX6800XT="800"
MAX_PRICE_SERIES_RX6900XT="1.000"
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_SERIES_SONYPS5C="500"
MAX_PRICE_CORSAIR_SF=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER="false"
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES="3060,3060ti,3070,3080,3090,rx6700xt, rx6800, rx6800xt, rx6900xt,sonyps5c"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="amazon-it,amazon-de,evga,unieuro,comet,amazon-es,amazon-fr,amd-it,asus,euronics,nvidia-de,nvidia-es,nvidia-fr"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""
