### ISSUE TITLE
Show Price in Discord Notification

### ISSUE THREAD

**Issue by FawnPat** [jef/streetmerchant#1188]
## Description

I would like to be able to display the price of the product in the discord notification messages I send. 

From what I can tell the bot does not currently capture the price of the product into a variable.

## Possible solution

My suggestion would be to update the "link" variable in the Discord notification template to have a "price" property.

**Comment by jef** [comment]
Good idea!

**Comment by jef** [comment]
Let me know what you think, I'll be pulling it in shortly.

**Comment by FawnPat** [comment]
> Let me know what you think, I'll be pulling it in shortly.

Thanks for adding this in. It's quite helpful to be able to see the price before clicking on a product link.

I may be wrong, but did you set up the code to only display the price one could be captured?

**Comment by jef** [comment]
> I may be wrong, but did you set up the code to only display the price one could be captured?

Yeah! That's correct. If you don't see a price, it means we don't have a container for it and the code needs to get updated.
