### ISSUE TITLE
What do I do when it says "INFO: Could not find files for the given pattern(s)."?

### ISSUE THREAD

**Issue by Yng-Ducky09** [jef/streetmerchant#1189]

**Comment by gigi2006** [comment]
Thats Info come from your alarm.wav

**Comment by jef** [comment]
> I think the Problem is:
> PLAY_SOUND="./Wake_up.wav"

I'll have to confirm on my Windows machine. Cool find otherwise! This seems to make sense to me.

**Comment by Yng-Ducky09** [comment]
I fixed the problem. Thank you.

**Comment by johnedwardfry** [comment]
PLAY_SOUND="./CantinaBand3.wav"
still produces the error I am unsure if the sound will play anyway.

**Comment by jef** [comment]
This happens because it looks for libraries that don't exist on your machine. I plan to create another library.
