### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by DerHOgi** [jef/streetmerchant#1194]
For a few tests:
Is it possible to take a screenshot everytime and not only on success?
What do I have to change in the code?

**Comment by jef** [comment]
This should do it for you.

```diff
diff --git a/src/store/lookup.ts b/src/store/lookup.ts
index 275557a..8082177 100644
--- a/src/store/lookup.ts
+++ b/src/store/lookup.ts
@@ -284,13 +284,13 @@ async function lookupCard(
 				inStock[link.url] = false;
 			}, 1000 * config.page.inStockWaitTime);
 		}
+	}
 
-		if (config.page.screenshot) {
-			logger.debug('ℹ saving screenshot');
+	if (config.page.screenshot) {
+		logger.debug('ℹ saving screenshot');
 
-			link.screenshot = `success-${Date.now()}.png`;
-			await page.screenshot({path: link.screenshot});
-		}
+		link.screenshot = `success-${Date.now()}.png`;
+		await page.screenshot({path: link.screenshot});
 	}
 
 	return statusCode;
```

**Comment by DerHOgi** [comment]
Thanks @jef for you reply!
Now I can see what's going on and why I allways get false negative results. Item is available but bot result is OUT OF STOCK!
![success-1607193640887](https://user-images.githubusercontent.com/67831862/101260868-22b3ca80-3733-11eb-9f21-c0b1192a99b6.png)
What can we do against this. All amazon-*.ts sites!

**Comment by jef** [comment]
I actually just fixed this bug too! Not sure how it ever happened, but #1209

**Comment by gigi2006** [comment]
> Thanks @jef for you reply!
> Now I can see what's going on and why I allways get false negative results. Item is available but bot result is OUT OF STOCK!
> What can we do against this. There is a new captcha-check that concerns all Europe amazon-*.ts sites!
> ![success-1607193640887](https://user-images.githubusercontent.com/67831862/101260868-22b3ca80-3733-11eb-9f21-c0b1192a99b6.png)

hey @jef 

how do you think we can solve the problem with the captcha? i don't think there will be a perfect solution, i already set and tried PAGE_BACKOFF_MIN and PAGE_BACKOFF_MAX as well as PAGE_SLEEP_MIN and PAGE_SLEEP_MAX. But it did not help much.

now a consideration, couldn't we just let the browser open when the captcha warning appears and then the real human could solve the captcha from time to time? so i would do it.

@DerHOgi 
how could you solve the problem?
with me it is just the most important contact points, like amazon.de etc.

**Comment by DerHOgi** [comment]
@gigi2006 No, I have no solution for this problem until now. I tested the bot with an item that is on stock and I allways got false negative result from the bot. First I thought this is a problem with the container but I can't find any error. This is why I asked @jef if it is possible to make a screenshot everytime and not only on success. Then I saw, why the bot is not working correctly. The captcha check. I allready tried different things but with noch success until now. I run the bot in a virtual machine with ubutu. The strage thing: If I open my normal desktop browser (Chrome) I can reload the website without any captcha checks.

**Comment by gigi2006** [comment]
@DerHOgi i think, but I am Not Sure.
You have no captchas Whit Login User in your normal Browser.

**Comment by DerHOgi** [comment]
@gigi2006 No, I tried this with no user logged in!

**Comment by DerHOgi** [comment]
@gigi2006 I just wrote my own little bot only for amazon.de which uses the "normal" windows browser. No user is logged in. This is running now since 1 hour and there are no captchas.

**Comment by jef** [comment]
Try using `PUPPETEER_EXECUTABLE_PATH`. This will use your regular browser.

This is what it looks like on my machine:

```
PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable npm run start
```

You can add before running or add to your `.env`. Up to you.

**Comment by DerHOgi** [comment]
@jef My ubuntu is running in a virtual machine only with command line interface - no gui...

**Comment by SAMLCSE** [comment]
It's works on Raspberry Pi. No issues. Running with Chromium browser[not
the Chromium].

**Comment by DerHOgi** [comment]
@SAMLCSE Will this work on ubuntu console only version? What do i have to do?

**Comment by SAMLCSE** [comment]
I'm not sure I'm running HEADLESS = "true" on my .env

**Comment by gigi2006** [comment]
> Try using `PUPPETEER_EXECUTABLE_PATH`. This will use your regular browser.
> 
> This is what it looks like on my machine:
> 
> ```
> PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable npm run start
> ```
> 
> You can add before running or add to your `.env`. Up to you.

hey @jef how can i test it on a windows machine?

i have this error here:

[19:26:39] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable npm run start {
  "stack": "Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable npm run start\n    at ChromeLauncher.launch (C:\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:79:23)\n    at async PuppeteerExtra.launch (C:\\streetmerchant\\node_modules\\puppeteer-extra\\dist\\index.cjs.js:129:25)\n    at async main (C:\\streetmerchant\\build\\index.js:36:15)\n    at async Timeout.loopMain [as _onTimeout] (C:\\streetmerchant\\build\\index.js:70:9)"

**Comment by prettyboyy** [comment]
> Try using `PUPPETEER_EXECUTABLE_PATH`. This will use your regular browser.
> 
> This is what it looks like on my machine:
> 
> ```
> PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable npm run start
> ```
> 
> You can add before running or add to your `.env`. Up to you.

i tried this and it still pops up with captcha, even on incongnito mode it still pop up.

**Comment by SWEETDREAMSIV** [comment]
> > Try using `PUPPETEER_EXECUTABLE_PATH`. This will use your regular browser.
> > This is what it looks like on my machine:
> > ```
> > PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable npm run start
> > ```
> > 
> > 
> > You can add before running or add to your `.env`. Up to you.
> 
> hey @jef how can i test it on a windows machine?
> 
> i have this error here:
> 
> [19:26:39] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable npm run start {
> "stack": "Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable npm run start\n at ChromeLauncher.launch (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79:23)\n at async PuppeteerExtra.launch (C:\streetmerchant\node_modules\puppeteer-extra\dist\index.cjs.js:129:25)\n at async main (C:\streetmerchant\build\index.js:36:15)\n at async Timeout.loopMain [as _onTimeout] (C:\streetmerchant\build\index.js:70:9)"


you should use correct exe file location for your operating system with windows 10 is like:

C:\Program Files (x86)\Google\Chrome\Application\Chrome.exe


keep detecting captcha even with this fix I can't understand, for now the bot is unusable for 3 amazon stores.

**Comment by nsar1907** [comment]
> @gigi2006 I just wrote my own little bot only for amazon.de which uses the "normal" windows browser. No user is logged in. This is running now since 1 hour and there are no captchas. If this works fine, I will add some other european amazon websites.

does it works good until now ?
