### ISSUE TITLE
The bot isn't working for me.

### ISSUE THREAD

**Issue by Yng-Ducky09** [jef/streetmerchant#1198]
When I type npm run start, it loads the stores and the series I selected but after it just does nothing.

**Comment by Yng-Ducky09** [comment]
and know there are a bunch of errors.

**Comment by Heli0saurus** [comment]
...care to elaborate on the solution if you've found it?

**Comment by Yng-Ducky09** [comment]
here are the errors:
'tsc' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\streetmerchant
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shall\AppData\Local\npm-cache\_logs\2020-12-17T13_40_07_311Z-debug.log
npm ERR! code 1
npm ERR! path C:\streetmerchant
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build && node build/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shall\AppData\Local\npm-cache\_logs\2020-12-17T13_40_07_330Z-debug.log

**Comment by Yng-Ducky09** [comment]
> ...care to elaborate on the solution if you've found it?

I didn't find any solutions. I had to stop using it but I need to use it again.

**Comment by jef** [comment]
What version of node are you using? `node --version`

**Comment by Yng-Ducky09** [comment]
> What version of node are you using? `node --version`

15.3.0

**Comment by jef** [comment]
You should download `14.15.2`. This should solve your issue.

https://jef.codes/streetmerchant/getting-started/#prerequisites

Thanks!
