### ISSUE TITLE
Linksbuilder random loop

### ISSUE THREAD

**Issue by SWEETDREAMSIV** [jef/streetmerchant#1200]
added model 3060ti for various European shops, everything works.
the bot finds out of stock products on amazon uk but reports sometimes
"[amazon-uk] running linksbuilder ..."
Where am i wrong?

![image](https://user-images.githubusercontent.com/75524658/101255753-68ff2e80-371f-11eb-893f-208d2bce0721.jpeg)

**Comment by gigi2006** [comment]
i have the same issues, but i dont know how i can check why this happen 👍 

![05-12-_2020_17-47-05](https://user-images.githubusercontent.com/32102113/101258311-f8a5dc80-3721-11eb-930c-f9b0f9d35167.png)

**Comment by SWEETDREAMSIV** [comment]
@jef

**Comment by nplusprime** [comment]
similair issue with currys and novatech [
![Capture](https://user-images.githubusercontent.com/75540058/101259346-399cf180-3720-11eb-86c3-2df41b178212.PNG)
](url)

**Comment by AlphaOmega2020** [comment]
@SWEETDREAMSIV did you fix it? if so how?

**Comment by SWEETDREAMSIV** [comment]
@AlphaOmega2020 
i did a clean reinstall and the problem is gone

**Comment by AlphaOmega2020** [comment]
> @AlphaOmega2020
> i did a clean reinstall and the problem is gone

thanks

**Comment by joshstubble** [comment]
Im getting the same problem with LinkBuilder on a clean install of the most recent push. I tried to mess with the code to get it to stop but just couldnt get it. I went back down to commit `364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b` and am getting no errors at all. You can get back to previous commits by using `git check out 364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b` or `git reset 364c6c25dfe9dcbeb29cb20cb46e9e8dcc2fe86b --hard` at the root of your project. Thats my only fix at the moment.
