### ISSUE TITLE
.env file is cached

### ISSUE THREAD

**Issue by evilsephiroth** [jef/streetmerchant#1203]
.env (and process.env variables) get cached and there is no way to set another value.

i.e.=> MAX_PRICE_SERIES_3080="999" is read as an older value of 999999.

Is there some cache to purge in the project? I've also tried to rebuild removing build/* before.

Thanks

**Comment by thefl0yd** [comment]
cached where? If you kill the process and restart it, it reads the CURRENT values of .env. Alternatively, you can run 'npm run start:dev' and it'll restart the process in realtime whenever you change .env.

**Comment by evilsephiroth** [comment]
Solved. I executed the script in "screen" and .env variables were not changing in that same screen session.
Killing and recreating screen with screen -S "namescreen" solved the issue.
