### ISSUE TITLE
Return light state with Philips Hue notification

### ISSUE THREAD

**Issue by nplusprime** [jef/streetmerchant#1205]
Can the Philips Hue notification be set up to return the lights to original state after code notification code has been execute? For example, light are off, blink notification activates lights for 30sec, then light turns off or returns to original colour.

**Comment by jef** [comment]
Good question! I didn't write this, so I don't know all the ins and outs of the API, but I can look and see if I can get the state prior to the change!

I'll link the commit if I update.

Thanks!

**Comment by jef** [comment]
I don't have any lights, but do you mind changing the code to do this and test for me?

In file `src/notification/philips-hue.ts`, replace this code:

```typescript
	if (lightIds) {
		const arrayOfIDs = lightIds.split(',');
		arrayOfIDs.forEach((light) => {
			logger.debug('adjusting all hue lights');
			(hueBridge.lights.setLightState(light, lightState) as Promise<any>).catch(
				(error: Error) => {
					logger.error('Failed to adjust all lights.');
					logger.error(error);
					throw error;
				}
			);
		});
```

with this code:

```typescript
	if (lightIds) {
		const arrayOfIDs = lightIds.split(',');
		arrayOfIDs.forEach((light) => {
			logger.debug('adjusting all hue lights');
			hueBridge.lights.getLightState(light).then((state) => {
				(hueBridge.lights.setLightState(light, lightState) as Promise<any>).then(() => {
					(hueBridge.lights.setLightState(light, state) as Promise<any>).catch(
						(error: Error) => {
							logger.error('failed to adjust lights', error);
							throw error;
						}
					);
				}).catch(
					(error: Error) => {
						logger.error('failed to adjust lights', error);
						throw error;
					}
				);
			});

		});
```

**Comment by JeremieLeblanc** [comment]
I tried this and it did not work.

**Comment by jef** [comment]
Unfortunately I don't have anyway to mock the lightbulb to test. I can only do so much with understanding the API without functional tests 😢

**Comment by JeremieLeblanc** [comment]
I'll give it a go myself and if I get it to work I'll do a pull request.
