### ISSUE TITLE
npm run start failure

### ISSUE THREAD

**Issue by SAMLCSE** [jef/streetmerchant#1210]
I tried to start on my Raspberry Pi. I got this error . Any solution appreciated. 

## Expected Behavior

pi@raspberrypi:~/Downloads/streetmerchant $ npm run start

> streetmerchant@ start /home/pi/Downloads/streetmerchant
> npm run build && node build/index.js

> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.2.0

[1:23:05 AM] warn :: nvidia is deprecated in favor of bestbuy
[1:23:05 AM] info :: ℹ selected stores: nvidia, amazon, bestbuy, bandh, newegg
[1:23:05 AM] info :: ℹ selected series: 3080, 3070, 3060ti, 6800xt
[1:23:10 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n/home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: \"(\" unexpected\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/pi/Downloads/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)\n    at Interface.<anonymous> (/home/pi/Downloads/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)\n    at Interface.emit (events.js:327:22)\n    at Interface.close (readline.js:424:8)\n    at Socket.onend (readline.js:202:10)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
[1:23:15 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/Downloads/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

## Steps to Reproduce

1.
2.
3.
4.

## Environment 

**OS:**  Raspberry Pi 
**.env file:**
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART="true"
BROWSER_TRUSTED="false"
COUNTRY="usa"
DESKTOP_NOTIFICATIONS=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK="https://discord.com/api/webhooks/xxxxxxxxxxxxxxx"
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH="false"
MAX_PRICE_SERIES_3060TI="500"
MAX_PRICE_SERIES_3070="600"
MAX_PRICE_SERIES_3080="800"
MAX_PRICE_SERIES_3090="1000"
MAX_PRICE_SERIES_CORSAIR_SF=""
MAX_PRICE_SERIES_RX6800=""
MAX_PRICE_SERIES_RX6800XT="800"
MAX_PRICE_SERIES_RX6900XT="900"
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_SERIES_SONYPS5C="600"
MAX_PRICE_SERIES_SONYPS5DE="600"
MAX_PRICE_SERIES_TEST=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS="10"
NVIDIA_SESSION_TTL=""
OPEN_BROWSER="true"
PAGE_BACKOFF_MIN="10000"
PAGE_BACKOFF_MAX="3600000"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
PAGE_TIMEOUT="0"
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL="http"
PROXY_PORT="80"
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT="true"
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES="3080,3070,3060ti,6800xt"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="nvidia,amazon,bestbuy,bandh,newegg"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""

```dotenv

```

**Comment by SAMLCSE** [comment]
Change the BROWSER_TRUSTED="true"
But same issue here.

**Comment by SAMLCSE** [comment]
Try these steps still have same issue.


pi@raspberrypi:~/Downloads/streetmerchant $ which chromium
/usr/bin/chromium
pi@raspberrypi:~/Downloads/streetmerchant $ which chromium-browser
pi@raspberrypi:~/Downloads/streetmerchant $ export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
pi@raspberrypi:~/Downloads/streetmerchant $ export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
pi@raspberrypi:~/Downloads/streetmerchant $ npm run start

> streetmerchant@ start /home/pi/Downloads/streetmerchant
> npm run build && node build/index.js


> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.2.0

[1:50:20 AM] warn :: nvidia is deprecated in favor of bestbuy
[1:50:20 AM] info :: ℹ selected stores: nvidia, amazon, bestbuy, bandh, newegg
[1:50:20 AM] info :: ℹ selected series: 3080, 3070, 3060ti, 6800xt
[1:50:25 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/chromium-browser {
  "stack": "Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/chromium-browser\n    at ChromeLauncher.launch (/home/pi/Downloads/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)\n    at async PuppeteerExtra.launch (/home/pi/Downloads/streetmerchant/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)\n    at async main (/home/pi/Downloads/streetmerchant/build/index.js:36:15)\n    at async loopMain (/home/pi/Downloads/streetmerchant/build/index.js:72:9)"
}
^C
pi@raspberrypi:~/Downloads/streetmerchant $ which chromium
/usr/bin/chromium
pi@raspberrypi:~/Downloads/streetmerchant $ which chromium-browser
pi@raspberrypi:~/Downloads/streetmerchant $ export PUPPETEER_EXECUTABLE_PATH='chromium'
pi@raspberrypi:~/Downloads/streetmerchant $ export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
pi@raspberrypi:~/Downloads/streetmerchant $ npm run start

> streetmerchant@ start /home/pi/Downloads/streetmerchant
> npm run build && node build/index.js


> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.2.0

[1:59:11 AM] warn :: nvidia is deprecated in favor of bestbuy
[1:59:11 AM] info :: ℹ selected stores: nvidia, amazon, bestbuy, bandh, newegg
[1:59:11 AM] info :: ℹ selected series: 3080, 3070, 3060ti, 6800xt
[1:59:19 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: chromium {
  "stack": "Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: chromium\n    at ChromeLauncher.launch (/home/pi/Downloads/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)\n    at async PuppeteerExtra.launch (/home/pi/Downloads/streetmerchant/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)\n    at async main (/home/pi/Downloads/streetmerchant/build/index.js:36:15)\n    at async loopMain (/home/pi/Downloads/streetmerchant/build/index.js:72:9)"

**Comment by SAMLCSE** [comment]
Install Chromium Broser instead of Chromium on Raspberry Pi 4. Now its working.

**Comment by frankjawn** [comment]
Having this same issue could anyone help? First time trying anything related to programming. 

C:\Users\Frank\Desktop\New Files\streetmerchant>npm run start

> streetmerchant@3.5.0 prestart
> npm run compile


> streetmerchant@3.5.0 compile
> tsc


> streetmerchant@3.5.0 start
> node build/src/index.js

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[8:03:17 AM] info :: ℹ selected brands: asus, evga, gigabyte, pny, zotac, msi, nvidia
[8:03:17 AM] info :: ℹ selected series: 3060, 3070, 3080, rx6700, rx6800, rx6800xt, rx6900xt
[8:03:17 AM] info :: ℹ selected stores: bestbuy, microcenter, newegg, officedepot, walmart
[8:03:18 AM] info :: ℹ puppeteer config:  {
  "0": "--no-sandbox",
  "1": "--disable-setuid-sandbox"
}
[8:03:18 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583). {
  "stack": "Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).\n    at ChromeLauncher.launch (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:80:27)\n    at async main (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\build\\src\\index.js:72:15)\n    at async loopMain (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\build\\src\\index.js:109:9)"
}
[8:03:23 AM] info :: ℹ puppeteer config:  {
  "0": "--no-sandbox",
  "1": "--disable-setuid-sandbox"
}
[8:03:23 AM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583). {
  "stack": "Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).\n    at ChromeLauncher.launch (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:80:27)\n    at async main (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\build\\src\\index.js:72:15)\n    at async Timeout.loopMain [as _onTimeout] (C:\\Users\\Frank\\Desktop\\New Files\\streetmerchant\\build\\src\\index.js:109:9)"

**Comment by jef** [comment]
`node ./node_modules/puppeteer/install.js`

**Comment by meunited** [comment]
@jef that fixed it for me! Thank you!

**Comment by jef** [comment]
You bet!

**Comment by PietroMilani** [comment]
Thx @jef Good Work !
