### ISSUE TITLE
Amazon add to cart links don't work.

### ISSUE THREAD

**Issue by briandilley** [jef/streetmerchant#1222]
Here's an example URL that I got:

https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08HR9D2JS&Quantity.1=1

And here's what happened:

![Screen Shot 2020-12-06 at 10 17 43 AM](https://user-images.githubusercontent.com/1068495/101288613-4830ea80-37ac-11eb-8b60-965f998fdca7.png)

**Comment by prettyboyy** [comment]
that's just because that's being sold by a third party.

**Comment by jef** [comment]
This is intentional unfortunately.

A. Out of stock
B. Third party seller
