### ISSUE TITLE
Split Stores by country or region

### ISSUE THREAD

**Issue by Gusymochis** [jef/streetmerchant#1225]
## Description
Current list of stores is mixed making it hard to find which stores to enable in my country.

## Possible solution

Splitting the list of stores by country or region will make it easier to find which stores to enable. It will also make it easier to find which stores to add new products to.

**Comment by jef** [comment]
I didn't think they were mixed or perhaps I'm not understanding. Can you give an example?

**Comment by zethussuen** [comment]
My guess is @Gusymochis is saying on the reference filters page that there's no way to filter or sort by country. mkdocs material table actually supports this functionality out of the box which you could potentially leverage to set and sort  `STORES`. If  this solves the issue use case, happy to push the code up on a branch.

![image](https://user-images.githubusercontent.com/754158/101517307-9aaa0c80-394e-11eb-865f-b8a48a20eb29.png)

**Comment by jef** [comment]
> My guess is @Gusymochis is saying on the reference filters page that there's no way to filter or sort by country. mkdocs material table actually supports this functionality out of the box which you could potentially leverage to set and sort `STORES`. If this solves the issue use case, happy to push the code up on a branch.
> 
> ![image](https://user-images.githubusercontent.com/754158/101517307-9aaa0c80-394e-11eb-865f-b8a48a20eb29.png)

Yeah, I would love to see how this works. Just started working with mkdocs, so I'd be happy to see how this looks.

**Comment by zethussuen** [comment]
@jef I'm not expert on mkdocs either, but did find a bit on the sorting here: https://squidfunk.github.io/mkdocs-material/reference/data-tables/

Just opened #1258 for you to take a look at the potential changes. I honestly am not sure about all of the countries listed, so that would definitely need a review before any merge!

**Comment by R3PTIL3** [comment]
Otto and Expert = DE 👍🏼

**Comment by jef** [comment]
Fixed from https://github.com/jef/streetmerchant/pull/1258
