### ISSUE TITLE
how to configure multiple useragents?

### ISSUE THREAD

**Issue by Tumtum2814** [jef/streetmerchant#1228]
hey all, I was hoping someone could help me with useragent formatting. I know it won't fully protect me and i've increased my sleep between scrapes but i wanted to put a couple useragents in the .env 
running streetmerchant in docker it's been working great but getting this error when adding new UAs
variable 'Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 \n' contains whitespaces.
See 'docker run --help'.

my env file line is 
USER-AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0 \n
Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 \n
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"

**Comment by jef** [comment]
I have this changing in 4.0.0, but in 3.x, it needs changing. The way it works now isn't great. Your format looks correct, but I'll post again when this changes.

Thanks!
