### ISSUE TITLE
RX6800XT Stock on Newegg Generates Alert When Priced over MAX_PRICE_SERIES_RX6800XT Parameter

### ISSUE THREAD

**Issue by zoenberger** [jef/streetmerchant#1230]
## Expected Behavior

I should only receive and alert if the RX6800XT is BELOW the max price set in my .env file.

## Current Behavior

A Sapphire RX6800XT Nitro+ card on Newegg is generating an alert at $1,099.67 when my MAX_PRICE_SERIES_RX6800XT parameter is set to 800

## Steps to Reproduce

1.Set variables with max RX6800XT Price at $800 and include Newegg as an included store
2. Run bot
3. Receive Alert to add to cart: https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202391
4. Add to cart link fails, but page shows card with price above limit: https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-02-20g/p/N82E16814202391

## Environment

**OS:**
**.env file:**

```
MAX_PRICE_SERIES_3060TI="501"
MAX_PRICE_SERIES_3070="600"
MAX_PRICE_SERIES_3080="850"
MAX_PRICE_SERIES_RX6800XT="800"
MAX_PRICE_SERIES_RX6800="800"
MAX_PRICE_SERIES_SONYPS5C="500"
MAX_PRICE_SERIES_SONYPS5DE="400"
SHOW_ONLY_SERIES="rx6800xt,3060ti,3070,3080,sonyps5c,sonyps5de"
STORES="amazon,bestbuy,walmart,target,newegg"
DESKTOP_NOTIFICATIONS="true"
```

**Comment by VincentWu1998** [comment]
Having the same issue with the following parameters in my .env file.
`DESKTOP_NOTIFICATIONS="true"
MAX_PRICE_SERIES_RX6800XT="850"
SHOW_ONLY_SERIES="rx6800xt, rx6900xt, 3080"
STORES="amazon, amd, bestbuy, newegg"`

**Comment by jef** [comment]
Will look into this. Thanks!
