### ISSUE TITLE
couldn't find sound player 

### ISSUE THREAD

**Issue by seanma711** [jef/streetmerchant#1231]
## Expected Behavior
Plays sound in "done-for-you-612.mp3" on notification.

## Current Behavior

Notification goes through but no sound is played. The warning "couldn't find sound player" is thrown in console.

Windows 10
PowerShell

## Logs

INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
[6:10:20 PM] warn :: ✖ couldn't find sound player
[6:10:21 PM] info :: ✔ desktop notification sent
[6:10:22 PM] info :: ✔ email sent
[6:10:23 PM] info :: ✔ sms sent

(NOTE: .env file was changed to a .txt to be uploaded to GitHub)
[myenv.txt](https://github.com/jef/streetmerchant/files/5649743/myenv.txt)

**Comment by Itsplenty** [comment]
what was the solution here?

**Comment by Ninjaneer324** [comment]
Was the solution posted elsewhere?

**Comment by Ninjaneer324** [comment]
Found it: https://github.com/jef/streetmerchant/issues/1116
