### ISSUE TITLE
Adding the ability to have different Alert sounds for different products

### ISSUE THREAD

**Issue by jaw20** [jef/streetmerchant#1242]
## Description
Implement a way for a user to specify specific mp3s to play when specific products come in stock rather than having the ability to only play one notification sound for all products

## Possible solution

Modify playSound to take a link variable (which would be passed from sendNotification ), with playSound being able to have a condition for if a specific sound as been specified for a product in .env. And if it has, take the custom link. This could be implemented the same way the phone numbers match with carriers, in order to allow for a custom amount of links and specific products.

**Comment by jaw20** [comment]
Bump for some semblance of visibility. I may work on trying to come up with an implementation.

**Comment by jef** [comment]
Superseded by discussion

https://github.com/jef/streetmerchant/discussions/1272
