### ISSUE TITLE
unable to find the .env example file

### ISSUE THREAD

**Issue by longj18** [jef/streetmerchant#1243]
I have installed node.js and xcode since it has a binary package of Git. I cloned and installed the project in terminal once that finished I went to my user folder to manage the .env file and I am not able to actually find it. I checked to see if it was a hidden file but I am not able to find the toggle to enable viewing of hidden files. In addition to that when ever I try to open the READ ME to read the instructions in the file I am greeted with html source code of the features and quick start sections of the website. I am having the same issue when I open any text file in the docs folder. I am not familiar at all with figuring this out on Mac OS and was hoping someone would be able to possibly help me.  So basically I cant find the .ENV example file and I cant open any of the text files correctly.

**Comment by sarwhale** [comment]
To see hidden files on Mac, press Command-Shift-Period. You can edit the .env file with textedit.

**Comment by alenknight** [comment]
excellent. that's what I needed too. thanks
