### ISSUE TITLE
Program does not check stocks

### ISSUE THREAD

**Issue by IHateLaptops** [jef/streetmerchant#1247]
When I start the program it runs, tells me my configurations, then does nothing. It just sits there forever. Not telling me if anything is in stock.

I'm very sure I installed it correctly. I don't know what's happening.

**Comment by IHateLaptops** [comment]
![Screenshot 2020-12-07 171036](https://user-images.githubusercontent.com/75649937/101424034-28361f80-38af-11eb-9b3c-c4441ad6f457.png)
Here's a screenshot

**Comment by IHateLaptops** [comment]
![Screenshot 2020-12-07 171036](https://user-images.githubusercontent.com/75649937/101424180-70edd880-38af-11eb-9115-4a45a918e7f8.png)
Here's a screenshot

**Comment by Nephaleem** [comment]
Since updating, same here. I've completely reinstalled everything and now it doesn't move, at all...

![image](https://user-images.githubusercontent.com/75652031/101429182-4f511900-38d0-11eb-9383-420990d43340.png)

**Comment by davidhan1120** [comment]
You need to set your stores to something else. As you can see the nvidia store does not hold CPU's or graphics cards.

Nvidia no longer sells graphics cards on their site. The nvidia store is the option by default.

**Comment by IHateLaptops** [comment]
Ok I will try that.

**Comment by IHateLaptops** [comment]
![Screenshot 2020-12-07 233428](https://user-images.githubusercontent.com/75649937/101453820-c8f30200-38e4-11eb-9ea3-c2521f88995b.png)
The issue still persists.

**Comment by davidhan1120** [comment]
Please post your .env file, may be caused by other settings.

**Comment by IHateLaptops** [comment]
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART="false"
BROWSER_TRUSTED=""
COUNTRY=""
DESKTOP_NOTIFICATIONS="true"
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3060TI=""
MAX_PRICE_SERIES_3070=""
MAX_PRICE_SERIES_3080=""
MAX_PRICE_SERIES_3090=""
MAX_PRICE_SERIES_CORSAIR_SF=""
MAX_PRICE_SERIES_RX6800=""
MAX_PRICE_SERIES_RX6800XT=""
MAX_PRICE_SERIES_RX6900XT=""
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_SERIES_SONYPS5C=""
MAX_PRICE_SERIES_SONYPS5DE=""
MAX_PRICE_SERIES_TEST=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS="asus"
SHOW_ONLY_MODELS="strix"
SHOW_ONLY_SERIES="3070"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="newegg"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""

**Comment by davidhan1120** [comment]
![image](https://user-images.githubusercontent.com/50039916/101456041-52580380-38e8-11eb-98da-fb63c0d33985.png)
Your settings look fine to me. As you can see the script runs perfectly fine.

Try adding more models and stores to it.

**Comment by IHateLaptops** [comment]
ok, ill try this again

**Comment by davidhan1120** [comment]
So I looked at your screenshot again, try saving the folder in Documents or the Desktop rather than in the Windows folder which may cause permission issues.

**Comment by IHateLaptops** [comment]
oh ok.

**Comment by IHateLaptops** [comment]
![Screenshot 2020-12-07 233428](https://user-images.githubusercontent.com/75649937/101457447-656bd300-38ea-11eb-9924-9d4e018c7f26.png)
I believe it works now, thank you so much!
