### ISSUE TITLE
Last changes to bestbuy canada broke the notifications

### ISSUE THREAD

**Issue by JeremieLeblanc** [jef/streetmerchant#1269]
The last commit that made changes to bestbuy-ca broke Bestbuy canada and now posts a false positive on every check.

**Comment by jef** [comment]
Will fix. Sorry.

**Comment by JeremieLeblanc** [comment]
I just got another false positive, but only on one card this time and not all of them like last time.
I'll keep an eye out and let you know if it happens again.

Thanks!

**Comment by jef** [comment]
Please do!
