### ISSUE TITLE
Amazon alert on 3070 when price exceeds max

### ISSUE THREAD

**Issue by IShouldHaveBeenAQATester** [jef/streetmerchant#1294]
Hello,
I'm seeing some weirdness with price detection on Amazon (US) evga 3070 ftw in-stock @ price detection.

If I set my max price to 100

`MAX_PRICE_SERIES_3070="100"` 

I get correctly notified that it exceeds the price limit.
`[7:50:28 AM] info :: ✖ [amazon] [evga (3070)] ftw3 :: PRICE 1144 EXCEEDS LIMIT 100
`
If I set my max price to 200 (or anything above): I get an alert:

```
[7:51:51 AM] info :: 🚀🚨 [amazon] [evga (3070)] ftw3 :: IN STOCK 🚨🚀
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08L8L9TCZ&Quantity.1=1
[7:51:52 AM] info :: ✔ sms sent
[7:51:52 AM] info :: ✔ email sent
[7:51:52 AM] info :: ✔ sms sent
```
If I can do anything to help assist, please let me know. The e-mailed screenshots show the 1149 price as well.  I've done a "view source" on my browser for the page & zipped it & attached.

[evgaftw3_amazon.zip](https://github.com/jef/streetmerchant/files/5666310/evgaftw3_amazon.zip)

**Comment by IShouldHaveBeenAQATester** [comment]
Just wanted to add:

I'm on commit 54ef0ef9950babd86d1fb0e2a1cc91030fbdb068

**Comment by Utherellus** [comment]
Same issue here. On exact same card.

**Comment by jef** [comment]
Oddly, I can't duplicate

![image](https://user-images.githubusercontent.com/12074633/101649789-444dd400-3a09-11eb-96e5-b8aa34016723.png)

![image](https://user-images.githubusercontent.com/12074633/101649819-4b74e200-3a09-11eb-9958-1e85cf4e3886.png)

**Comment by IShouldHaveBeenAQATester** [comment]
Any additional info you need that I can give you?

**Comment by Goobleency** [comment]
Having this happen repeatedly with this listing: https://www.amazon.com/dp/B08NS4W2ZY
Limiting it to $800, but being notified about a $1,599.97 listing.
Worth noting that the success image generated looks different from what opens in chromium, despite using the same user agent and URL:

Success image:
![success-1608075790962](https://user-images.githubusercontent.com/76077622/102286741-c3ea1000-3eed-11eb-8d16-49e47a58ac30.png)

Opened in browser:
![Screenshot from 2020-12-15 15-57-08](https://user-images.githubusercontent.com/76077622/102286959-38bd4a00-3eee-11eb-9a99-6555c8fd0b03.png)

It looks like a mobile version is being opened by streetmerchant, and I suspect the html tag is slightly different in whatever that version is?

**Comment by karnag3** [comment]
Seeing issue on 3070 with newegg too.  

```[8:26:32 PM] info :: 🚀🚨 [newegg] [gigabyte (3070)] gaming oc :: IN STOCK 🚨🚀
https://www.newegg.com/gigabyte-geforce-rtx-3070-gv-n3070gaming-oc-8gd/p/N82E16814932342
[8:26:32 PM] info :: ✔ discord message sent
[8:26:33 PM] info :: ✔ sms sent```

``` 
MAX_PRICE_SERIES_3070=950
SHOW_ONLY_SERIES=ryzen5600,3080,3070,3060ti
```

***Running in a docker container so no quotes on values

**Comment by Utherellus** [comment]
Can confirm getting `gigabyte-geforce-rtx-3070-gv-n3070gaming` with newegg too.

**Comment by jef** [comment]
Do you mind opening a new ticket if it's a new site. Let's keep it related to Amazon.

Thank you.
