### ISSUE TITLE
Discord notifications incorrectly use dollar ($) sign by default

### ISSUE THREAD

**Issue by sohaiiil** [jef/streetmerchant#1318]
## Expected Behavior

Notifications should show the price with the correct currency, e.g. £ for UK, $ for USA and € for EU countries.

## Current Behavior

With the latest commits being pulled, notifications are showing Price with a dollar ($) sign preceding it. This is incorrect as I am searching UK stores and my currency is GBP (£). I believe this would also affect Euro (€) stores as well.

## Steps to Reproduce

1. Search for an in stock product. Make sure notifications are set correctly (e.g. Discord webhook).
2. Notice that for a UK store, the price will show as $499.99.

PR opened that fixes this issue: https://github.com/jef/streetmerchant/pull/1328

**Comment by jef** [comment]
Resolved by #1328
