### ISSUE TITLE
SMS alert issue

### ISSUE THREAD

**Issue by smithcut3** [jef/streetmerchant#1322]
## Expected Behavior

Send a text alert when a product is in stock

## Current Behavior

I get a Certification error when testing my SMS notifications. I've tried my real Verizon number and a google voice number.

## Steps to Reproduce

1 .npm run test:notification

## Environment

**windows 10:**
**.env file:**

```dotenv

```

## Logs
[10:27:58 AM] error :: ✖ couldn't send sms to 2164381888 for carrier google self signed certificate in certificate chain {
  "code": "ESOCKET",
  "command": "CONN",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"
}

**Comment by jef** [comment]
Have you setup email properly?

**Comment by smithcut3** [comment]
> Have you setup email properly?

im entirely sure, i didnt know what username and password it was asking for so i just made one up that corresponded to my gmail account.

**Comment by oregonducktaylor** [comment]
> > Have you setup email properly?
> 
> im entirely sure, i didnt know what username and password it was asking for so i just made one up that corresponded to my gmail account.

For email setup at least with gmail you need to use an app password found in google settings.

**Comment by jef** [comment]
> > Have you setup email properly?
> 
> im entirely sure, i didnt know what username and password it was asking for so i just made one up that corresponded to my gmail account.

If you use MFA, take a look at https://support.google.com/accounts/answer/185833?hl=en

```
EMAIL_ADDRESS=youremail@gmail.com
EMAIL_PASSWORD=yourpassword
```

**Comment by kewtz** [comment]
I get this:
![image](https://user-images.githubusercontent.com/64649301/101901994-eee80300-3b7f-11eb-8a02-e6b0c55ad8a8.png)

I do have MFA setup, followed the instructions for that.

**Comment by jef** [comment]
Oh interesting. So you are getting the email, but not the way you'd like -- is that correct?

**Comment by kewtz** [comment]
> 
> 
> Oh interesting. So you are getting the email, but not the way you'd like -- is that correct?

I am getting the email just fine, however I am not getting the SMS. 
I receive 2 emails every drop - one "normal" email, and a second above which is an error which I assume to be about the SMS.

**Comment by jef** [comment]
How are you setting your phone number? Should look something like this:

![image](https://user-images.githubusercontent.com/12074633/101939271-c1687d00-3bb2-11eb-8c62-319e97fe4dc3.png)


`PHONE_NUMBER="6467470820"` or `PHONE_NUMBER="16467470820"` (country code)

**Comment by kewtz** [comment]
Format is this one: 
`PHONE_NUMBER="16467470820"`

**Comment by jef** [comment]
> Format is this one:
> `PHONE_NUMBER="16467470820"`

I just tested with country code and it didn't work. Perhaps try to remove it and see what happens.

**Comment by kewtz** [comment]
> 
> 
> > Format is this one:
> > `PHONE_NUMBER="16467470820"`
> 
> I just tested with country code and it didn't work. Perhaps try to remove it and see what happens.

Removing the country code fixed it.
All set.

**Comment by jef** [comment]
This needs to either be fixed or put as a note. I'll keep this open until we do either. Thanks for the report!
