### ISSUE TITLE
streetmerchant falsely reports AMD RX6800XT in stock for AMD Store

### ISSUE THREAD

**Issue by l0ppi** [jef/streetmerchant#1329]
## Expected Behavior

The program should report "not in stock" when it's not in stock. This worked perfectly fine until the last drop on 12/08/2020.

## Current Behavior

Card is reported "in stock", notification is sent and the browser opened.

## Steps to Reproduce

Just added only the AMD RX6800XT and only the AMD Store. Also changed the Wait time when a card is in stock to prevent banning. Rest is left on default.
## Environment

Win10 using the latest code of streetmerchant
## Logs
[17:46:07] info :: ℹ selected stores: amd
[17:46:07] info :: ℹ selected series: rx6800xt
[17:46:19] info :: 🚀🚨 [amd] [amd (rx6800xt)] amd reference :: IN STOCK 🚨🚀
https://www.amd.com/en/direct-buy/5458372800/us?add-to-cart=true
[17:46:19] info :: ✔ desktop notification sent
[17:46:25] info :: ℹ [amd] [amd (rx6800xt)] amd reference :: IN STOCK, WAITING

**Comment by jef** [comment]
Unfortunately, I can't reproduce.

![image](https://user-images.githubusercontent.com/12074633/101824317-07add580-3afa-11eb-9e33-45c9d1fd0bd6.png)

**Comment by l0ppi** [comment]
That is extremely strange. I deleted streetmerchant and cloned the whole thing again, this time to a different directory and then only set the series and the store. It still shows "in stock". So there must be something else that's "stuck" with the wrong status. Is there anything else that i could reset?

**Comment by thefl0yd** [comment]
can't reproduce either. you must be hitting a cache somewhere that the rest of us aren't:


> streetmerchant@ start:dev C:\Users\thefloyd\streetmerchant
> nodemon --config nodemon.json

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\* .env
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --files ./src/index`
∩╝│∩╝┤∩╝▓∩╝Ñ∩╝Ñ∩╝┤∩╝¡∩╝Ñ∩╝▓∩╝ú∩╝¿∩╝í∩╝«∩╝┤
3.2.0

[4:03:27 PM] info :: Γä╣ selected stores: amd
[4:03:27 PM] info :: Γä╣ selected series: rx6800xt
[4:03:38 PM] info :: Γ£û [amd] [amd (rx6800xt)] amd reference :: OUT OF STOCK
[4:03:49 PM] info :: Γ£û [amd] [amd (rx6800xt)] amd reference :: OUT OF STOCK

thefloyd@office-pc MINGW64 ~/streetmerchant (main)
$

**Comment by hideouspenguinboy** [comment]
I'm also getting this after newegg drops a 6800xt card. I don't even know if the card is actually available or not. Once it says it is, the card will continue flagging as in stock for up to 30 minutes. This happened yesterday at around 11, first for the Merc and then a few minutes later with the strix. (I'm assuming newegg is trying out bot detection)

**Comment by l0ppi** [comment]
I'm still getting "In stock" results. It has never stopped since the last drop. I completely deleted streetmerchant a few times but nothing has changed.
As I have almost no knowledge about coding, i can't figure out how streetmerchant exactly gets its results. IS there any thing that might be acting as a cache?

**Comment by jef** [comment]
> I'm still getting "In stock" results. It has never stopped since the last drop. I completely deleted streetmerchant a few times but nothing has changed.
> As I have almost no knowledge about coding, i can't figure out how streetmerchant exactly gets its results. IS there any thing that might be acting as a cache?

This is for the store `amd` and the series `rx6800xt`, correct?

**Comment by l0ppi** [comment]
> This is for the store amd and the series rx6800xt, correct?

Exactly. I'm only interested in the AMD cards from their own store.

> Can you post a screenshot of what the bot took when it said it was in stock?

Of course. Thanks for your support.

![Streetmerchant](https://user-images.githubusercontent.com/75801942/102556349-fbf97a80-40c8-11eb-93dc-2c926ba101f2.PNG)

**Comment by jef** [comment]
It looks like you're running an old version of streetmerchant. Do you mind doing a `git pull origin main` and running `npm install`?

**Comment by l0ppi** [comment]
Oh, there's the 3.3.0. Didn't notice that.
I updated the files, but the results remains the same a you can see :/

![Streetmerchant 2](https://user-images.githubusercontent.com/75801942/102633364-9e107580-4150-11eb-8f0e-d6028e2850a9.PNG)

**Comment by jef** [comment]
Sorry, it's hard to tell what's going on. Perhaps we're getting redirects and I don't like that. One solution is ensuring we don't get redirected. Another solution is that we check for selectors that give us the name of the product to ensure what we're looking for.

Either way, this is probably intermittent.

**Comment by fabitrox** [comment]
I just had the same problem: I tried to run the bot on AMD-de from switzerland. Since the store always redirects to the swiss store, the alert popped up and showed "in stock", but wasn't available. So that might be the same problem.

**Comment by nextinfinity** [comment]
I have a similar issue - getting a false positive on RX6900XT. At least in this case, it is clearly a redirect from the product page to the general store page. This is the screenshot that was captured:

![success-1621447862437](https://user-images.githubusercontent.com/10286358/118863219-9e9e6b00-b8ac-11eb-955c-6a6a5d4e95d4.png)

...while this is the console output:

![image](https://user-images.githubusercontent.com/10286358/118863433-e0c7ac80-b8ac-11eb-9f80-61615be31201.png)

In my browser, I land on https://www.amd.com/en/direct-buy/us.
