### ISSUE TITLE
Sony Direct Queue doesn't work

### ISSUE THREAD

**Issue by jeffboone** [jef/streetmerchant#1351]
Is this supposed to notify when the Sony Direct queue opens?  It opens at 14:20 EST and still just stayed out of stock in the output stream....

Thanks,

Jeff

**Comment by datreic** [comment]
Playstation adds inventory _after_ they've started the queue.

**Comment by jeffboone** [comment]
Thanks for the reply!  I didn't see the code ever notify me there was inventory, even after the queue opened.  Should it have?  Will the code try to add to cart for me once the inventory is available, or do i need to monitor playstation site manually?

Thanks,  Jeff

**Comment by datreic** [comment]
I've only found the project yesterday so haven't looked too closely. It doesn't appear that the playstation store supports auto-adding to the cart. The last ps direct only had digital stock (no disc). Not sure what you were filtering - but yes it should have told you about stock.

**Comment by jeffboone** [comment]
@datreic that's it - i forgot that - i was only searching for disc!  we can close this...
