### ISSUE TITLE
Missing DISCORD_NOTIFY lines for XBox in dotenv

### ISSUE THREAD

**Issue by Jack1424** [jef/streetmerchant#1352]
I'm not sure if the lines work, but they are missing from the dotenv-example file. I double-checked the repo to be sure.

I added:
```dotenv
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORDNOTIFY_GROUP_XBOXS=
```
to my dotenv file, but I don't know if they work.

**Comment by jef** [comment]
They do work! Good catch, they didn't get added to the example. I'll add now.

Thanks!
