### ISSUE TITLE
MAX_PRICE_SERIES_3080= not being honored @ newegg

### ISSUE THREAD

**Issue by ams3401** [jef/streetmerchant#1356]
In my.env file, the max price is set as follows:
`MAX_PRICE_SERIES_3080="850"`

However, it's pulling up In-stock alert for a EVGA 3080 FTW3 Ultra on Newegg that's listed for over $1,400.

I'm also getting alerts from some discord servers for the same item, so I assume this to be a common issue.

![Screen Shot 2020-12-11 at 6 30 54 PM](https://user-images.githubusercontent.com/70864968/101968946-0c988500-3bdf-11eb-9223-bf26c5eb3264.png)

**Comment by Dankleberg** [comment]
Glad I checked, I was just about to write an issues on this too.  Annoying to get false alarms every two minutes.

**Comment by zimmertr** [comment]
Can confirm.
