### ISSUE TITLE
Insane data usage

### ISSUE THREAD

**Issue by BaturalNoobs** [jef/streetmerchant#1357]
![Data usage](https://i.imgur.com/mrB8VCf.png)

I let this run for three days and it transmitted 319GB of data!

My ISP is Comcast and I have a 1.2TB data cap, and get charged fees for going over, which I will this month because of Street Merchant.

You need to put a huge warning on the README.md that this **uses extremely high amounts of data** and should only be used in small durations if you have a data cap.

🤯

**Comment by phtp** [comment]
Have you tried turning on LOW_BANDWIDTH="true"? I think that's why it's there.
