### ISSUE TITLE
El Corte Inglés store in docs labeled as US

### ISSUE THREAD

**Issue by EQXTFL** [jef/streetmerchant#1368]
This store serves Spain, United Kingdom, Andorra, France and Portugal - is it correctly labeled as US in the filter list?

https://jef.codes/streetmerchant/reference/filter/

**Comment by jef** [comment]
Probably needs fixing. Do you mind fixing it?

**Comment by EQXTFL** [comment]
:) Should have done that right away..

https://github.com/jef/streetmerchant/pull/1369

**Comment by jef** [comment]
_And it's fixed!_ Thank you very much!
