### ISSUE TITLE
Request Interception is not enabled! and adblocker.js

### ISSUE THREAD

**Issue by ratlaf** [jef/streetmerchant#1381]
This issue was opened, and then closed [here](https://github.com/jef/streetmerchant/issues/826) after an attempted fix. 

Unfortunately, I'm still seeing it off of a fresh pull today. 

![image](https://user-images.githubusercontent.com/27832/102002088-5d2ee180-3cb6-11eb-81ff-eeb6177c2e60.png)

App will run for a random length of time (~30sec - 10min) before failing. I don't (currently) know puppeteer well enough to say why.

**Comment by ratlaf** [comment]
Adding this:

        if(!this._allowInterception) {
            console.log('>>>>INTERCEPTION FAILED!!!<<<<<');
            return
        }

To `node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPRequest.js:270` seems to work as an extremely quick and dirty fix.

**Comment by ratlaf** [comment]
[Also looks like there might be a fix waiting](https://github.com/jef/streetmerchant/pull/1379)

**Comment by jef** [comment]
Just pushed this in. Feel free to pull down and test. Let me know if we need to make more updates.

Thanks!

**Comment by jef** [comment]
Also depending on when the last time you updated streetmerchant, this should've fixed it: https://github.com/jef/streetmerchant/pull/1312
