### ISSUE TITLE
Configuration wont save from web

### ISSUE THREAD

**Issue by MitchellPT** [jef/streetmerchant#1385]
## Expected Behavior

Saved configuration after reopening

## Current Behavior

I have to untick everything and retick the items i want.

## Steps to Reproduce

Save a configuration via web and then restart program.

## Environment

**OS:** Windows 10
**dotenv file:**

```dotenv
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY=england
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=REMOVEDx2
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=REMOVEDx2
DISCORD_WEB_HOOK=REMOVED
EMAIL_PASSWORD=REMOVED
EMAIL_TO=EMAILSx3REMOVED
EMAIL_USERNAME=REMOVED
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=D:\Documents\Mitch\github\streetmerchant\got-it-done-613.ogg
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=8090
SOUND_PLAYER=D:\Program Files\VLC\vlc.exe

```

## Logs
[14:06:46] info :: ℹ selected stores: nvidia
[14:06:46] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, 
[14:09:05] info :: ℹ selected stores: amazon-uk, argos, currys, game, very, xbox
[14:09:05] info :: ℹ selected brands: microsoft
[14:09:05] info :: ℹ selected models: xbox series x
[14:09:05] info :: ℹ selected series: xboxsx
[14:09:09] info :: [amazon-uk] Running linksBuilder...
[14:09:09] info :: ✖ [xbox] [microsoft (xboxsx)] xbox series x :: OUT OF STOCK
[14:09:10] info :: [very] Running linksBuilder...
[14:09:11] info :: ✖ [game] [microsoft (xboxsx)] xbox series x :: OUT OF STOCK
[14:09:12] info :: [currys] Running linksBuilder...
[14:09:13] info :: ✖ [amazon-uk] [microsoft (xboxsx)] xbox series x :: OUT OF STOCK

## Other Issues
I also have a couple of other issues,
SOUND_PLAYER isnt in env by default so i had to add it but it still cannot find the player
I also get [14:14:49] error :: ✖ [nvidia] Unknown country england
When no nvidia items are selected

**Comment by MitchellPT** [comment]
Also when it timesout/stops doing anything. i have to manaully press enter into the window to get "[argos] microsoft xboxsx xbox series x - Navigation timeout of 30000 ms exceeded" then it carries on as normal.

**Comment by MitchellPT** [comment]
Fixed all isseus apart from sound_player

**Comment by metriics** [comment]
For those trying to fix the configuration not saving from the web interface, the solution is specifying it in the .env file. I think the save button on the web interface is more of an apply button. You can set a default start up config with these parameters:

`STORES="bestbuy-ca"`
`SHOW_ONLY_BRANDS="nvidia"`
`SHOW_ONLY_MODELS="founders edition"`
`SHOW_ONLY_SERIES="3070"`

That would be an example to only look for 3070 FE from BestBuy Canada. I assume you can have multiple values separated by commas but someone will have to verify as that is not my use case.
