### ISSUE TITLE
Some stores marked as having stock, browser opens, but no stock

### ISSUE THREAD

**Issue by simonk83** [jef/streetmerchant#1392]
## Expected Behavior

These seem to be false positives, so they should be seen as Out of Stock

## Current Behavior

Bot marks them as in stock and opens the browser page

## Steps to Reproduce

Here's a snippet of the output

```[8:55:08 am] info :: ℹ selected stores: bpctech, centrecom, cpl, mwave, pccg, scorptec, umart
[8:55:08 am] info :: ℹ selected series: 3080, ryzen5900, xboxss
[8:55:20 am] info :: 🚀🚨 [mwave] [gigabyte (3080)] vision oc :: IN STOCK 🚨🚀
https://www.mwave.com.au/product/gigabyte-geforce-rtx-3080-vision-oc-10gb-video-card-ac38364
[8:55:20 am] info :: ✖ [cpl] [asus (3080)] strix oc :: OUT OF STOCK
[8:55:22 am] info :: ✖ [centrecom] [asus (3080)] tuf oc :: OUT OF STOCK
[8:55:23 am] info :: ✖ [pccg] [asus (3080)] tuf :: OUT OF STOCK
[8:55:23 am] info :: ✖ [umart] [asus (3080)] strix :: OUT OF STOCK
[8:55:27 am] info :: ✖ [scorptec] [asus (3080)] strix :: OUT OF STOCK
[8:55:28 am] info :: ✖ [cpl] [asus (3080)] tuf :: OUT OF STOCK
[8:55:28 am] info :: ✖ [centrecom] [galax (3080)] sg oc :: OUT OF STOCK
[8:55:28 am] info :: ✖ [umart] [asus (3080)] strix oc :: OUT OF STOCK
[8:55:29 am] info :: 🚀🚨 [mwave] [gigabyte (3080)] gaming oc :: IN STOCK 🚨🚀
https://www.mwave.com.au/product/gigabyte-geforce-rtx-3080-gaming-oc-10gb-video-card-ac38091
[8:55:34 am] info :: ✖ [umart] [asus (3080)] tuf :: OUT OF STOCK
[8:55:34 am] info :: ✖ [centrecom] [gigabyte (3080)] aorus master :: OUT OF STOCK
[8:55:35 am] info :: ✖ [pccg] [asus (3080)] tuf oc :: OUT OF STOCK
[8:55:35 am] info :: ✖ [cpl] [asus (3080)] tuf oc :: OUT OF STOCK
[8:55:37 am] info :: ✖ [scorptec] [asus (3080)] strix oc :: OUT OF STOCK
[8:55:37 am] info :: 🚀🚨 [bpctech] [asus (3080)] tuf :: IN STOCK 🚨🚀
https://www.bpctech.com.au/tuf-rtx3080-10g-gaming-asus-geforce-rtx-3080-tuf-gaming-10gb-video-card.html
[8:55:38 am] info :: 🚀🚨 [mwave] [gigabyte (3080)] aorus xtreme :: IN STOCK 🚨🚀
https://www.mwave.com.au/product/gigabyte-aorus-geforce-rtx-3080-xtreme-10gb-video-card-ac38093
```
![success-1607896520620](https://user-images.githubusercontent.com/518440/102025381-b0568080-3deb-11eb-9601-48d74783d52c.png)
![success-1607896529456](https://user-images.githubusercontent.com/518440/102025385-b3ea0780-3deb-11eb-8bef-9fe4b3222cfa.png)
![success-1607896537512](https://user-images.githubusercontent.com/518440/102025386-b51b3480-3deb-11eb-8eec-352206e2b21c.png)
![success-1607896538349](https://user-images.githubusercontent.com/518440/102025387-b64c6180-3deb-11eb-960f-ba482d5d4b13.png)

## Environment

**OS:** Mac OS Catalina
**dotenv file:**

```
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3080,ryzen5900,xboxss
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=bpctech,centrecom,cpl,mwave,pccg,scorptec,umart
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=34000

```

**Comment by simonk83** [comment]
Just seems to be those two stores, so I've disabled them for now. The rest are behaving

**Comment by simonk83** [comment]
Hmm now it’s doing it for Umart as well

**Comment by TDCroPower** [comment]
there all is well, you are probably just too slow and the purchase bots faster ;)

**Comment by jef** [comment]
> there all is well, you are probably just too slow and the purchase bots faster ;)

Perhaps, but also the selectors may be off as well 😀 Did streetmerchant happen to get any screenshots for you? That'll help in debugging.

**Comment by simonk83** [comment]
Pretty sure it's not bots, as the stock situation here in Aus is pretty dire and they're not coming in that quickly, plus it's firing off way to many times to be real stock.  I did attach some screenshots to the issue above, but here's everything I have.

If you need me to do any debugging or anything just yell out :)

![success-1607896538349](https://user-images.githubusercontent.com/518440/102146202-aea8bd80-3ebc-11eb-8798-61b003e926a9.png)
![success-1607897660725](https://user-images.githubusercontent.com/518440/102146225-b2d4db00-3ebc-11eb-92a3-dc48e53b5cc1.png)
![success-1607897671093](https://user-images.githubusercontent.com/518440/102146226-b36d7180-3ebc-11eb-9fe5-1e49482b1c74.png)
![success-1607897674455](https://user-images.githubusercontent.com/518440/102146228-b4060800-3ebc-11eb-800b-01e94f78913d.png)
![success-1607897690537](https://user-images.githubusercontent.com/518440/102146229-b49e9e80-3ebc-11eb-87d1-98e38e8e428c.png)
![success-1607897702936](https://user-images.githubusercontent.com/518440/102146230-b5373500-3ebc-11eb-9426-1f9cea1ca26b.png)
![success-1607897708329](https://user-images.githubusercontent.com/518440/102146234-b5cfcb80-3ebc-11eb-95f8-fcb939b132e1.png)
![success-1607897716332](https://user-images.githubusercontent.com/518440/102146238-b6686200-3ebc-11eb-9efd-4a709dd7667b.png)
![success-1607897723832](https://user-images.githubusercontent.com/518440/102146239-b700f880-3ebc-11eb-9689-2dfec8a9b50b.png)
![success-1607897727708](https://user-images.githubusercontent.com/518440/102146240-b7998f00-3ebc-11eb-80be-5277f4873d09.png)
![success-1607918825848](https://user-images.githubusercontent.com/518440/102146241-b8322580-3ebc-11eb-9f8c-010c39042b18.png)
![success-1607918855040](https://user-images.githubusercontent.com/518440/102146243-b8cabc00-3ebc-11eb-83ca-0e80fcd26053.png)
![success-1607918878558](https://user-images.githubusercontent.com/518440/102146248-b9fbe900-3ebc-11eb-82ea-c57972ec8aac.png)
![success-1607918961861](https://user-images.githubusercontent.com/518440/102146249-ba947f80-3ebc-11eb-814e-8e7eba088cbb.png)
![success-1607920608944](https://user-images.githubusercontent.com/518440/102146253-bb2d1600-3ebc-11eb-9840-8e8639a298ee.png)














![Uploading success-1607897622952.png…](
![success-1607897631617](https://user-images.githubusercontent.com/518440/102146208-afd9ea80-3ebc-11eb-864a-6d014a7cee37.png)
![success-1607897638746](https://user-images.githubusercontent.com/518440/102146213-b0728100-3ebc-11eb-9789-2506c22c415b.png)
![success-1607897653843](https://user-images.githubusercontent.com/518440/102146217-b10b1780-3ebc-11eb-8363-b6be00b1151d.png)





![success-1607896529456](https://user-images.githubusercontent.com/518440/102146191-ab153680-3ebc-11eb-8ce9-d21f4dbb3a6f.png)
![success-1607896537512](https://user-images.githubusercontent.com/518440/102146195-ac466380-3ebc-11eb-9b86-73bb32753a09.png)



![success-1607896520620](https://user-images.githubusercontent.com/518440/102146179-a781af80-3ebc-11eb-8f88-bce07b4b98fe.png)

**Comment by simonk83** [comment]
Pretty sure it's not bots, as the stock situation here in Aus is pretty dire and they're not coming in that quickly, plus it's firing off way too many times to be real stock.  I did attach some screenshots to the issue above, but here's everything I have from running just now.

If you need me to do any debugging or anything just yell out :)

![success-1607987261240](https://user-images.githubusercontent.com/518440/102146798-bddc3b00-3ebd-11eb-81ef-87e44c65d1e5.png)
![success-1607987269872](https://user-images.githubusercontent.com/518440/102146808-c16fc200-3ebd-11eb-95ee-bb243ac818da.png)
![success-1607987274748](https://user-images.githubusercontent.com/518440/102146812-c2a0ef00-3ebd-11eb-9490-9e1f412c53b8.png)
![success-1607987294916](https://user-images.githubusercontent.com/518440/102146814-c3398580-3ebd-11eb-87a8-284bd668d06d.png)
![success-1607987303593](https://user-images.githubusercontent.com/518440/102146816-c3d21c00-3ebd-11eb-8737-7c2a907045bd.png)
![success-1607987307486](https://user-images.githubusercontent.com/518440/102146819-c46ab280-3ebd-11eb-9e0b-69e0b131a140.png)
![success-1607987311842](https://user-images.githubusercontent.com/518440/102146821-c5034900-3ebd-11eb-9024-6e19a9e23113.png)
![success-1607987321657](https://user-images.githubusercontent.com/518440/102146822-c59bdf80-3ebd-11eb-9f26-edd02da19194.png)
![success-1607987344691](https://user-images.githubusercontent.com/518440/102146823-c59bdf80-3ebd-11eb-93dd-07013db480c7.png)
![success-1607987359735](https://user-images.githubusercontent.com/518440/102146824-c6347600-3ebd-11eb-8b51-06775e96e99b.png)
![success-1607987370508](https://user-images.githubusercontent.com/518440/102146827-c6cd0c80-3ebd-11eb-8e46-a1181ec72eee.png)
![success-1607987390533](https://user-images.githubusercontent.com/518440/102146830-c6cd0c80-3ebd-11eb-8a19-b778f1aca0cb.png)
![success-1607987400082](https://user-images.githubusercontent.com/518440/102146831-c765a300-3ebd-11eb-835e-f8570dcba88e.png)
![success-1607987404732](https://user-images.githubusercontent.com/518440/102146832-c7fe3980-3ebd-11eb-98eb-2e92698fcd15.png)

**Comment by simonk83** [comment]
I had a look at the code for Mwave:

```
		outOfStock: {
			container: '.stockAndDelivery > li:nth-child(1) > dl > dd',
			text: ['Currently No Stock']
		}
	},
```

![image](https://user-images.githubusercontent.com/518440/102150268-452cad00-3ec4-11eb-860c-c2d5b2e20ac6.png)

I've tried to mess around with this but as my html is non-existent I'm just clutching at straws really. One strange thing though is that this page produces a false positive:

https://www.mwave.com.au/product/asus-geforce-rtx-3080-tuf-gaming-oc-10gb-video-card-ac38205

But this page doesn't:

https://www.mwave.com.au/product/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-video-card-ac38322

I can't see a difference in the elements personally, but again I don't really know what I'm doing :)

**Comment by jef** [comment]
I see the problem. The user agent that it's using was a mobile user agent and the selectors are different for user agents. This needs to get updated.

Thanks!

**Comment by simonk83** [comment]
Ah great, happy to do it and push it up if you like as I think it needs to happen for a few of the Aussie ones. I'll see if I can find the right spot, otherwise I'll ask back here ;)

**Comment by StanZha** [comment]
as mentioned above pages are rendered for mobile device. Selectors are different
ui-mobile used
![1](https://user-images.githubusercontent.com/6751192/102181041-7dee6700-3e6f-11eb-8f8a-90e4647ef98c.JPG)

no stock found twice
![2](https://user-images.githubusercontent.com/6751192/102181043-7e86fd80-3e6f-11eb-8825-47366101d9a4.JPG)

this thing works properly for a page opened in desktop browser: `.stockAndDelivery > li:nth-child(1) > dl > dd`

**Comment by simonk83** [comment]
So streetmerchant *always* uses a mobile user agent? Or it cycles through different agents and sometimes it uses a mobile one?
Presumably the latter as that would explain why sometimes it detects properly.  If that’s the case it’s probably beyond me to try and account for both mobile and non mobile 😄

**Comment by kin3tik** [comment]
When the store model was submitted the `USER_AGENT` config item had just been deprecated in favour of a package that pulls in a random user-agent string - is that right @jef ? As per #1335 

Am I correct in saying there are two options to fix this?

1. Add inStock and outOfStock selectors for mobile
2. Explicitly specify a non-mobile `USER_AGENT` ([is this still possible?](https://github.com/jef/streetmerchant/commit/3386e8f50da27a800c5289c3b6bd7a1f76e77a49))

**Comment by simonk83** [comment]
For now I'm using a non-mobile USER_AGENT (so yep, still possible) which has done the trick for mwave, but bpctech is really stubborn and constantly brings up in stock messages regardless, so I assume something else is going on there. They're extra expensive anyway so I've just disabled that store for now.

Also, and this likely can't be helped, but looks like Centrecom are smart and are detecting the activity and blocking IP's pretty quickly.

**Comment by StanZha** [comment]
1. I can't tell how useful it is to randomize user agents. In below example it uses weird mix of mobile browsers and desktop browsers across different OS. One of them is chrome 45 on android 4.2, that is very old. I removed all calls to `getRandomUserAgent()` and got all pages opened properly in desktop mode, at least for test 5 min run against Mwave. When user agent not set explicitly via `page.setUserAgent` correct user agent for corresponding chromium version will be used. On screenshot every time when user agent for mobile device was used, page was opened in mobile mode and produced false positive.
![1_2](https://user-images.githubusercontent.com/6751192/102308367-1813e500-3f2c-11eb-8f24-3fcd4a9ddf36.JPG)

2. It seems second argument for winston logger should be some type of collection. When string passed it prints nothing in console output. I added square brackets and it started printing properly
![1_1](https://user-images.githubusercontent.com/6751192/102308499-5f01da80-3f2c-11eb-9eb6-f03dd366b816.JPG)

**Comment by StanZha** [comment]
The random-useragent has property deviceType for user agents. If necessary this condition `ua.browserName === 'Chrome' && ua.browserVersion > '20'` can be modified to exclude mobile and tablet user agents. I don't see single deviceType defined as desktop, so I would assume when deviceType is empty it means desktop: https://github.com/skratchdot/random-useragent/blob/master/useragent-data.json

**Comment by jef** [comment]
Hey @StanZha, I've updated the user agent library and it's pulling from the top 50 UAs (not mobile). Can you see if this is still an issue for you?

Thanks!

**Comment by StanZha** [comment]
Thank you @jef, I tried to run recent code from main for 10 minutes and got all appropriate results - no pages opened in mobile or tablet mode for 3080/mwave store, no false positives observed.

I was just troubleshooting this problem, issue was opened by different user. @simonk83 can you confirm that changes are working as expected?

**Comment by simonk83** [comment]
Yep looking good! Thanks Jef

**Comment by jef** [comment]
Awesome! Thank you for the confirmation 😁
