### ISSUE TITLE
Deprecate nvidia-api and update nvidia store

### ISSUE THREAD

**Issue by YiIdirim** [jef/streetmerchant#1393]
## Expected Behavior

We should be able to search for Founders Edition cards from the NVIDIA store for all officially supported countries, namely:

- France, Belgium and Luxembourg via LDLC
- Germany and Austria via NBB
- UK and Ireland via Scan
- Spain via LDLC

Ever since NVIDIA updated their store around 3 months ago, the Founders Edition are no longer sold by Nvidia themselves and they have opted to partner with some retailers in those respective countries to sell the FE cards instead. We should be able to capture FE card availability with the updated process.

This therefore makes `nvidia-api` obsolete and should now be deprecated.

## Current Behavior

- Must be able to scan for FE card availability for all RTX 3000 series products in the supported countries
- `nvidia-api` should be deprecated
- `nvidia` should be updated

## Steps to Reproduce

1. Try using the `nvidia` store to search for FE cards in the supported countries.
2. Notice that they don't work.

**Comment by sohaiiil** [comment]
@jef I'm going to work on updating this shortly.
