### ISSUE TITLE
Series Specific Discord Notify Groups not working

### ISSUE THREAD

**Issue by Dboard52** [jef/streetmerchant#1397]
## Expected Behavior

dotenv file includes:
DISCORD_NOTIFY_GROUP_3070="The <@&787788255050727432> is now in stock"

When a 3070 is found in stock it should send a message to the discord server including the "<@&787788255050727432> " which would ping any member of the server with the corresponding role.

## Current Behavior
I have streetmerchant setup with a discord webhook to notify a server that I am on
I have this set up in my dotenv file:
DISCORD_NOTIFY_GROUP_3070="The <@&787788255050727432> is now in stock"

When streetmerchant found a card in stock it sent a notification but without the message like this
![image](https://user-images.githubusercontent.com/75964869/102040558-fd9e0800-3d81-11eb-827b-ab9ea7f1182a.png)

## Steps to Reproduce

1. Add message into one of the series specific discord notify groups 
2. Run streetmerchant
3. When streetmerchant finds a card in stock for that specific series it will send a message to the discord server with the product links but without the custom message

## Environment

**OS: Windows 10 64 bit**
**dotenv file: **

```dotenv

```

**Comment by jef** [comment]
Okay, interesting. I need to test this today. Thank you for the report!

**Comment by Dboard52** [comment]
bit of an update, it sent the message correctly when a 3060ti was found in stock so it might be a problem with sending a message for the 3070 in particular.

**Comment by jef** [comment]
Oh, I see your problem now.

`DISCORD_NOTIFY_GROUP_3070="The <@&787788255050727432> is now in stock"`

needs to be

`DISCORD_NOTIFY_GROUP_3070="<@&787788255050727432>"`

**Comment by Dboard52** [comment]
Thanks for the help

**Comment by tripp396** [comment]
Do we use quotes or not. I have the following:

DISCORD_NOTIFY_GROUP_3070="<@&numbersforrolehere>" 

and it sent a message but did not tag the role. Confirmed that the numbers are all correct. Do I need the quotes as you said above?

It saw a 3090 last night and tagged the right group, and same with 3060. But the 3070 did not go

**Comment by tripp396** [comment]
> Do we use quotes or not. I have the following:
> 
> DISCORD_NOTIFY_GROUP_3070="<@&numbersforrolehere>"
> 
> and it sent a message but did not tag the role. Confirmed that the numbers are all correct. Do I need the quotes as you said above?
> 
> It saw a 3090 last night and tagged the right group, and same with 3060. But the 3070 did not go

Scratch my question. Appears I fat fingered something.

**Comment by jef** [comment]
> Thanks for the help

No problem!

> Do we use quotes or not. I have the following:

I would suggest not using quotes at this time. It's usually fine with quotes, unless you're running in Docker, than it's not. So I prefer to not use them in most situations.

**Comment by jef** [comment]
Going to close this now! If this is still a problem, feel free to comment and I'll reopen.

Thanks!

**Comment by CheekiSkrub** [comment]
I'm experiencing the same behavior with these discord notifications too. Correctly posting to a channel via the webhook, but not mentioning the role

**Comment by jef** [comment]
I believe https://github.com/jef/streetmerchant/pull/1788 fixes this. Perhaps pull from latest main.
