### ISSUE TITLE
"No store named amd-uk, skipping."

### ISSUE THREAD

**Issue by ketz** [jef/streetmerchant#1423]
When adding "amd-uk" to the list of stores (as described in the filters), the app starts with a warning that the store doesn't exist.

The expected behaviour would be for it to correctly crawl that store for the selected cards.

To reproduce, add the following list of stores for example:
STORES="amazon-uk,nvidia,scan,overclockers,novatech,ebuyer,currys,box,aria,ccl,amd-uk"

**Comment by ketz** [comment]
bump!

**Comment by sohaiiil** [comment]
This should work as I added that store in and already tested it and verified working. I’ll take a look...

**Comment by sohaiiil** [comment]
@ketz Yeah I checked with the latest version of StreetMerchant and it works fine. Make sure you pull the latest commits to get the latest features.
