### ISSUE TITLE
store amazon-it add camera on cart

### ISSUE THREAD

**Issue by bibidinu** [jef/streetmerchant#1424]
please fix link on amazon-it link add camera on cart

**Comment by zuzolo** [comment]
Amazon put a redirect on the Camera, if you try to open the url of console will open the camera;

@jef there is a way to bypass? Thanks

**Comment by razor992fg** [comment]
same problem, false positive on amazon italian

**Comment by wofnull** [comment]
Still the same for amazon-it , disabled amazon-it for ps5 for now

**Comment by razor992fg** [comment]
Fix?
