### ISSUE TITLE
Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by silkyclouds** [jef/streetmerchant#1433]
Hi there,

I just installed streetmerchant, thank you for this great tool ! 

I currently run it on a headless server and only send notifications on a discord chan. 

issue I do have i that I'm getting a lot of these errors:
Navigation timeout of 30000 ms exceeded

I also get a lot of 404 errors

Any clue of why this is happening ?

**Comment by absolutelyNoClue** [comment]
I do get the navigation timeout error on gamestop-de and computeruniverse all of the time. 

When running in non-headless mode, I can see that the pages are valid and correctly opened, but there is a cookie request on each page which seems to block the process. Hence the timeout.

**Comment by lucairr** [comment]
> Hi there,
> 
> I just installed streetmerchant, thank you for this great tool !
> 
> I currently run it on a headless server and only send notifications on a discord chan.
> 
> issue I do have i that I'm getting a lot of these errors:
> Navigation timeout of 30000 ms exceeded
> 
> I also get a lot of 404 errors
> 
> Any clue of why this is happening ?

same here. It was working great until I updated the bot this morning

**Comment by kzoneat** [comment]
same for me...

**Comment by clanier9** [comment]
I also have this issue. I checked out v3.3.0 which was released 5 days ago since someone said it was working fine until today's updates, but that older version has the same timeouts:
```
[1:58:49 PM] error :: ✖ [newegg] asus 3080 tuf - Navigation timeout of 30000 ms exceeded
[1:58:51 PM] error :: ✖ [gamestop] asus 3080 tuf oc - Navigation timeout of 30000 ms exceeded
[1:58:52 PM] error :: ✖ [amazon] pny 3080 xlr8 revel - Navigation timeout of 30000 ms exceeded
[1:58:52 PM] error :: ✖ [bestbuy] nvidia 3080 founders edition - Navigation timeout of 30000 ms exceeded
[1:58:52 PM] error :: ✖ [officedepot] pny 3080 xlr8 revel - Navigation timeout of 30000 ms exceeded```

**Comment by absolutelyNoClue** [comment]
I can reproduce it now. As soon as I set LOW_BANDWIDTH="true" the Navigation timeout will pop up. If I change it to false then no issues at all.

**Comment by clanier9** [comment]
I tried this and it improved things for me but still getting a lot of timeouts:
![image](https://user-images.githubusercontent.com/5515905/102646687-56bac280-4119-11eb-8724-0895204f2881.png)

**Comment by absolutelyNoClue** [comment]
Have you set HEADLESS to true and checked whether your IP Is not blocked or anything else?

**Comment by clanier9** [comment]
I have not, but will try that and report back

**Comment by kzoneat** [comment]
I figured out that you can either set the timeout-limit higher in the dotenv file (page_timeout), or reduce the sites/items checked or run this on a system with a more powerful CPU, to get it to work without any issues.

**Comment by philosophics** [comment]
I have tried headess=false, page shows up but log still shows the error
I have tried low bandwidth=false and this did not change anything
I have changed my ip, I have changed wait times. Nothing seems to resolve this error.

**Comment by ProfScrap** [comment]
Same issue here, got some stock checks before the latest update

**Comment by davidneff** [comment]
> Hi there,
> 
> I just installed streetmerchant, thank you for this great tool !
> 
> I currently run it on a headless server and only send notifications on a discord chan.
> 
> issue I do have i that I'm getting a lot of these errors:
> Navigation timeout of 30000 ms exceeded
> 
> I also get a lot of 404 errors
> 
> Any clue of why this is happening ?

Me too

**Comment by absolutelyNoClue** [comment]
Guys, can you post a bit more relevant details, e.g. version of streetmerchant, your config, and the shops?

**Comment by patlux** [comment]
![Screenshot 2021-01-14 at 13 31 22](https://user-images.githubusercontent.com/4481570/104591334-ccf50b00-566c-11eb-86b2-196dd786659e.png)

My env:
```
COUNTRY=germany
STORES=amazon-de,amazon-de-warehouse,notebooksbilliger,nvidia-api,asus-de,computeruniverse,cyberport,euronics-de,expert,gamestop-de,mindfactory,alternate,acompc,arlt,caseking,equippr,futurex,medimax,otto,pcking,saturn,spielegrotte,mediamarkt
SHOW_ONLY_SERIES=3080
PUSHOVER_TOKEN=aodxpcqxuikr7rhxu4v5yvxmhwhf7x
PUSHOVER_USER=u4etdm96k1bhictgoqybpuk8r41jhn
MAX_PRICE_SERIES_3080=900
```

Running in docker.

**Comment by IEPiXI** [comment]
I still have the issue, any new insights on the error here?
