### ISSUE TITLE
Error with sound alerts

### ISSUE THREAD

**Issue by reVolt1984** [jef/streetmerchant#1443]
Hello, I get the following error every time a sound alert should be played: 

`error opening sound file: ENOENT: no such file or directory, access 'true'`

Is there any solution?

Thanks
reVolt

**Comment by selop** [comment]
Seems like the node app does not have the rights to access the sound file. Try to follow the steps posted in this issue: 

https://github.com/jef/streetmerchant/issues/1116

Cheers
