### ISSUE TITLE
Error : Cannot find module '@doridian/puppeteer-page-proxy'

### ISSUE THREAD

**Issue by TurkeyPuncher** [jef/streetmerchant#1445]
## Expected Behavior
git pulled latest today. Got the following error on `npm run start`

src/store/lookup.ts(27,22): error TS2307: Cannot find module '@doridian/puppeteer-page-proxy' or its corresponding type declarations.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! streetmerchant@ build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the streetmerchant@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Glen\AppData\Roaming\npm-cache\_logs\2020-12-17T15_05_40_869Z-debug.log

## Steps to Reproduce

1.npm run start

2.
3.
4.

## Environment

**OS:**
**dotenv file:**

```dotenv

```

## Logs

[2020-12-17T15_05_40_869Z-debug.log](https://github.com/jef/streetmerchant/files/5710280/2020-12-17T15_05_40_869Z-debug.log)

**Comment by neatchee** [comment]
Some changes when pulled require you to re-run "npm install"
In this case you are missing a package. Re-run the install process should fix.

**Comment by sohaiiil** [comment]
As @neatchee said, run `npm i` to fix your issue.

**Comment by TurkeyPuncher** [comment]
sweet thanks
