### ISSUE TITLE
Question: How to limit discord notifications to only stock changes

### ISSUE THREAD

**Issue by carlmacdiarmada** [jef/streetmerchant#1448]
Hey,

Love the program, very cool and easy to extend. I was wondering if theres an option or a way to limit discord notifications to only happen when theres a change in stock.

eg:
```
product a: out of stock
product b: out of stock 
product c: out of stock
fin - restart
product a: in stock - send message
product b: out of stock 
product c: out of stock
fin - restart
product a: in stock - currently sends message (should not)
product b: out of stock 
product c: out of stock
fin - restart
product a: out of stock - currently doesnt send message (should?)
product b: out of stock 
product c: out of stock
fin - restart
product a: in stock - currently sends message (should cause first time)
product b: out of stock 
product c: out of stock
```

if that makes sense?

Thanks

**Comment by TDCroPower** [comment]
Interesting topic, because currently you can only set a timeout of the notifications with the variable "IN_STOCK_WAIT_TIME=".
Especially if a wrong article was offered for example at Amazon Warehousedeals, the notification chat is quickly spammed.
