### ISSUE TITLE
does not work for nvidia germany

### ISSUE THREAD

**Issue by TeleTesch** [jef/streetmerchant#1457]
## Expected Behavior

yesterday there was stock at nvidia germany (nvidea.de - FE) . Various bots have triggered. streetmerchant, however, remained silent.
Can anyone confirm this?

notebooksbilliger.de also does not trigger despite stock (FE). I think this is because the last numbers of the link change every time.
https://www.notebooksbilliger.de/nvidia+geforce+rtx+3080+founders+edition+XXXXXX

**Comment by reVolt1984** [comment]
I think notebooksbilliger installed a waiting page which prevented streetmerchant from detecting the stock. There was no alert for Nvidia Germany yesterday.

**Comment by erwinc1** [comment]
You could always open a PR for this @TeleTesch 💯
