### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:80

### ISSUE THREAD

**Issue by kiowadriver** [jef/streetmerchant#1466]
## Expected Behavior

Attempting to enable web_port when running in a docker.  I found this post that eludes to this being a permission issue when attempting to start the server
https://github.com/puppeteer/puppeteer/issues/1303

## Current Behavior
events.js:292
throw er; // Unhandled 'error' event
Error: listen EACCES: permission denied 0.0.0.0:80

at Server.setupListenHandle [as _listen2] (net.js:1301:21)
at listenInCluster (net.js:1366:12)
at Server.listen (net.js:1452:7)
at Object.startAPIServer (/app/build/web/index.js:139:16)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async main (/app/build/index.js:60:5)
at async loopMain (/app/build/index.js:81:9)
Emitted 'error' event on Server instance at:

## Steps to Reproduce

1. Set WEB_PORT = 80 (no other value seems to work)
2. Map container port to external port of your choice
3. Start the container
4. View the console and logs

## Environment

**OS:**
Linux 4.19.107-Unraid

**dotenv file:**

N/A, passing value directly as an env variable on start

## Docker start command
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='streetmerchant' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'WEB_PORT'='80' -e 'env-file'='/config/dotenv' -e 'LOG_LEVEL'='info' -e 'HEADLESS'='true' -p '7279:80/tcp' -v '/mnt/user/appdata/streetmerchant/logs':'/home/appuser/.npm/_logs':'rw' -v '/mnt/user/appdata/streetmerchant/config':'/config':'rw' 'ghcr.io/jef/streetmerchant:latest'

## Logs

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:production'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'prestart:production', 'start:production', 'poststart:production' ]
5 info lifecycle streetmerchant@~prestart:production: streetmerchant@
6 info lifecycle streetmerchant@~start:production: streetmerchant@
7 verbose lifecycle streetmerchant@~start:production: unsafe-perm in lifecycle true
8 verbose lifecycle streetmerchant@~start:production: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/s
bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle streetmerchant@~start:production: CWD: /app
10 silly lifecycle streetmerchant@~start:production: Args: [ '-c', 'node build/index.js' ]
11 silly lifecycle streetmerchant@~start:production: Returned: code: 1  signal: null
12 info lifecycle streetmerchant@~start:production: Failed to exec start:production script
13 verbose stack Error: streetmerchant@ start:production: `node build/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid streetmerchant@
15 verbose cwd /app
16 verbose Linux 4.19.107-Unraid
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:production"
18 verbose node v14.15.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error streetmerchant@ start:production: `node build/index.js`
22 error Exit status 1
23 error Failed at the streetmerchant@ start:production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kiowadriver** [comment]
I figured out the problem.  The container port must be higher than say 2000 or it won't work.  I used port 8081 and now it works fine

**Comment by jonmes** [comment]
just change the port and it will work(like 4000 or any )

**Comment by kiowadriver** [comment]
Yes that is what my resolution states above from 13 days ago. I closed the issue.
