### ISSUE TITLE
I run it and an error doesn't pop up just nothing happens after a point

### ISSUE THREAD

**Issue by RealityMyx** [jef/streetmerchant#1476]
## Current Behavior
stops after it says the following when i run it
> npm run build && node build/index.js

> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.3.0

[12:57:50 AM] info :: ℹ selected stores: amazon, bestbuy, gamestop, newegg, target, walmart
[12:57:50 AM] info :: ℹ selected models: xboxsx
[12:57:50 AM] info :: ℹ selected series: xboxsx
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
[12:57:52 AM] info :: ✔ sound player found: cmdmp3

## Steps to Reproduce

i just followed the wiki thing

## Environment

**OS: Windows 10**
**dotenv file:**

```HEADLESS=false
AUTO_ADD_TO_CART=
COUNTRY=usa
EMAIL_PASSWORD=
EMAIL_USERNAME=
IN_STOCK_WAIT_TIME=3
LOG_LEVEL=info
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=alarm.mp3
PUSHOVER_TOKEN=
PUSHOVER_USER=
SCREENSHOT=true
SHOW_ONLY_MODELS=xboxsx
SHOW_ONLY_SERIES=xboxsx
STORES=amazon,bestbuy,gamestop,newegg,target,walmart
USER_AGENT=
WEB_PORT:true

```

**Comment by neatchee** [comment]
Your dotenv is dramatically underpopulated.
Please do not construct your own.
Instead, copy and edit the dotenv-example file that is distributed with the package

Additionally, do not modify or remove ANY files from the package unless you are a developer working on code changes that you intend to push upstream.

If it's reporting that files are missing, it's likely that you have damaged the source tree in some way.

If you download a fresh copy following my instructions above and still run into issues please report back.

**Comment by RealityMyx** [comment]
> Your dotenv is dramatically underpopulated.
> Please do not construct your own.
> Instead, copy and edit the dotenv-example file that is distributed with the package
> 
> Additionally, do not modify or remove ANY files from the package unless you are a developer working on code changes that you intend to push upstream.
> 
> If it's reporting that files are missing, it's likely that you have damaged the source tree in some way. Make sure you are getting the ENTIRE package, preferably by using "git clone"
> 
> If you download a fresh copy following my instructions above and still run into issues please report back.

I have repopulated my dotenv file and same result. The only things i ran for installing it are the git clone, npm i install, it told me to go to the puppeteer previosly and run an install there so i did, and i have run npm start never deleted any files or anything just ran those

**Comment by neatchee** [comment]
If the guide you're using is showing errors then that guide is wrong.

Please follow the instructions here: https://jef.codes/streetmerchant/getting-started/

> Download Node.js 14
Clone this project: `git clone https://github.com/jef/streetmerchant.git`
Navigate to this project by entering `cd streetmerchant`.
Run `npm install`.
Make a copy of `dotenv-example` and name it `dotenv`.
Edit the `dotenv `file to your liking using a text editor (like vscode).
Run `npm run start` to start.

**Comment by RealityMyx** [comment]
@neatchee thats the guide I followed, I did that exactly and an error popped telling me to go to the puppeteer folder and do an npm install there. so I did that and other than that I have done nothing outside of what the guide says. I'm not dumb and like I said the file not found is not the problem because is the streamer running this with out problems 24/7 gets that exact same thing when starting then it's normal. the problem is just completely does nothing after it says sound player found. it gives no reason for the problem or anything, it just does nothing at all.

**Comment by neatchee** [comment]
I understand that whatever stream your watching appears to have it working despite errors, but _there should not be errors like that_. If there are then something is wrong.

I have never heard of needing to go into the puppeteer directory and run npm install from there.

For good measure I just installed NodeJS v14 on my PC (Win10), cloned the repo, ran npm install, placed my dotenv, and ran npm start run.
There are no errors. Everything runs as expected. I did not need to do any additional install steps other than "npm install" in the root of the streetmerchant directory.

So at the moment this is "unable to reproduce".

- Where did you install NodeJS from?
- Do you have multiple versions of Python installed?
- Did you choose the option to install the ms build tools when prompted by the NodeJS installer?

I know you're not dumb, and I never suggested you were. But at this point something about what you're doing, or your environment, is wrong.
