### ISSUE TITLE
Used products in amazon-ca bypasses MAX_PRICE_SERIES_3080 price filter

### ISSUE THREAD

**Issue by rchenzheng** [jef/streetmerchant#1509]
## Expected Behavior

Product gets filtered and no alerts are sent

## Current Behavior

Used products in Amazon Canada bypass price filter

## Steps to Reproduce

MAX_PRICE_SERIES_3080=1300
STORES=amazon-ca
SHOW_ONLY_SERIES=3080

https://www.amazon.ca/EVGA-10G-P5-3885-KR-GeForce-Cooling-Backplate/dp/B08HR55YB5/

Start to check

## Environment

**OS:** Docker
**dotenv file:**
MAX_PRICE_SERIES_3080=1300
STORES=amazon-ca
SHOW_ONLY_SERIES=3080

## Logs

```
[2:27:43 PM] info :: ✖ [amazon-ca] [evga (3080)] ftw3 ultra :: PRICE 1699.99 EXCEEDS LIMIT 1300
[2:27:50 PM] info :: 🚀🚨 [amazon-ca] [evga (3080)] xc3 ultra :: IN STOCK 🚨🚀
```

- $1699 is the new one  and gets filtered
- $1799 is the used one

**Comment by neatchee** [comment]
Can you please attach the screenshot that streetmerchant saves (to its own directory) when it detects an in-stock item?

I'm looking at that link and in its current state it should not be triggering in-stock notification (there is no "add to cart" button). It's likely that the pricing block is different for used items and the selector we're using doesn't pick it up properly when it's a used item, thus defaulting to just showing that it's in-stock

**Comment by rchenzheng** [comment]
> Can you please attach the screenshot that streetmerchant saves (to its own directory) when it detects an in-stock item?
> 
> I'm looking at that link and in its current state it should not be triggering in-stock notification (there is no "add to cart" button). It's likely that the pricing block is different for used items and the selector we're using doesn't pick it up properly when it's a used item, thus defaulting to just showing that it's in-stock

That might be the case: https://ibb.co/ykzbL8b

**Comment by neatchee** [comment]
Yeah, pretty sure my hunch is right. The inStock check (container: '#desktop_buybox') looks like it will trigger on that page, but not the price check (container: '#priceblock_ourprice'). Probably should be "usedprice or some such thing.

Can you get to a page that looks like that now? When I go to what I believe is the correct page I don't see that exact UI; there's no Buy Used offer in the top right, just a "see all buying options" button.

This should be the link it's going to: https://www.amazon.ca/dp/B08HR55YB5/

If you can reproduce the issue, please right-click the page and select "View Source" then place that in a text file and attach here.

**Comment by neatchee** [comment]
Please ignore that mention. Wrong issue tagged
