### ISSUE TITLE
Add Costco store for PS5

### ISSUE THREAD

**Issue by dyndragon** [jef/streetmerchant#1510]
Think it's a good idea to add the Costco bundle?
https://www.costco.com/sony-playstation-5-gaming-console-bundle.product.100691489.html

**Comment by neatchee** [comment]
Because this is a member-only product it requires sign-in. I don't have a member account so I can't be sure but I don't think is doable because we can't see if it's in stock or not without an account.

**Comment by anthonytam** [comment]
While it looks like we wouldn't be able to see the price for the max price checks, I think it may be possible to verify stock. It looks like an "Out of Stock" watermark is being overlayed on the product image.
![image](https://user-images.githubusercontent.com/15911331/103423758-60f7aa80-4b76-11eb-9af9-2fedac26e152.png)

A quick look in the page source shows that it's an `img` tab being placed on top
![image](https://user-images.githubusercontent.com/15911331/103423804-b59b2580-4b76-11eb-9657-9fa09a19be3b.png)

I'm not sure how the current implementation would be able to handle searching for the existence of a css selector, but it shouldn't be too hard to implement if there is demand for it

**Comment by dyndragon** [comment]
Thank you @anthonytam I was about to reply with this. Sorry I wasn't specific in the initial request. I had thought at least checking stock would be possible, even if you need a membership to buy.
