### ISSUE TITLE
Probelms sending email Notifications: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by augustynr** [jef/streetmerchant#1515]
## Expected Behavior

When a product is found the email should be sent to the configured user.
It looks like comunication with the mail server fails.
The log on the mail server shows following:
Dec 27 23:43:24 mail postfix/smtpd[103535]: connect from Robert-Desk-Mint.domain.com[192.168.1.32]
Dec 27 23:43:24 mail postfix/smtpd[103535]: lost connection after STARTTLS from Robert-Desk-Mint.domain.com[192.168.1.32]
Dec 27 23:43:24 mail postfix/smtpd[103535]: disconnect from Robert-Desk-Mint.domain.com[192.168.1.32] ehlo=1 starttls=1 commands=2

When tested with sendmail from the same machine it works fine.
It looks like the

## Current Behavior
The program fails with following error:

[9:32:05 p.m.] info :: 🚀🚨 [amazon-ca] [evga (3070)] xc3 ultra :: IN STOCK 🚨🚀
https://www.amazon.ca/gp/aws/cart/add.html?ASIN.1=B08L8L71SM&Quantity.1=1
[9:32:05 p.m.] info :: ✔ desktop notification sent
/home/robert/projects/streetmerchant/node_modules/winston/lib/winston/logger.js:307
      throw ex;
      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Printf.winston_1.default.format.printf [as template] (/home/robert/projects/streetmerchant/build/logger.js:14:54)
    at Printf.transform (/home/robert/projects/streetmerchant/node_modules/logform/printf.js:11:26)
    at Format.info [as transform] (/home/robert/projects/streetmerchant/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/home/robert/projects/streetmerchant/node_modules/winston/lib/winston/logger.js:305:29)
    at DerivedLogger.Transform._read (/home/robert/projects/streetmerchant/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/home/robert/projects/streetmerchant/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/robert/projects/streetmerchant/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/robert/projects/streetmerchant/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/home/robert/projects/streetmerchant/node_modules/readable-stream/lib/_stream_writable.js:307:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streetmerchant@ start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streetmerchant@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robert/.npm/_logs/2020-12-26T02_32_05_218Z-debug.log

## Steps to Reproduce

1. set dotenv as per bellow
2. run npm run start
3.
4.

## Environment

**OS:**
**dotenv file:**

```dotenv
AUTO_ADD_TO_CART="true"
BROWSER_TRUSTED=
COUNTRY=canada
DESKTOP_NOTIFICATIONS="true"
NVIDIA_ADD_TO_CART_ATTEMPTS="true"
STORES=amazon-ca,bestbuy-ca,canadacomputers,newegg-ca,walmart-ca
EMAIL_USERNAME="user@domain.com"
```

## Logs

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle streetmerchant@~prestart: streetmerchant@
6 info lifecycle streetmerchant@~start: streetmerchant@
7 verbose lifecycle streetmerchant@~start: unsafe-perm in lifecycle true
8 verbose lifecycle streetmerchant@~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/robert/projects/streetmerchant/node_modules/.bin
:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle streetmerchant@~start: CWD: /home/robert/projects/streetmerchant
10 silly lifecycle streetmerchant@~start: Args: [ '-c', 'npm run build && node build/index.js' ]
11 silly lifecycle streetmerchant@~start: Returned: code: 1  signal: null
12 info lifecycle streetmerchant@~start: Failed to exec start script
13 verbose stack Error: streetmerchant@ start: `npm run build && node build/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid streetmerchant@
15 verbose cwd /home/robert/projects/streetmerchant
16 verbose Linux 5.8.0-31-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error streetmerchant@ start: `npm run build && node build/index.js`
22 error Exit status 1
23 error Failed at the streetmerchant@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by neatchee** [comment]
Your dotenv is missing multiple required parameters for email. It's also missing almost all other parameters.
Please do not create your own dotenv from scratch. Instead, copy dotenv-example to a new file named dotenv and edit that.

**Comment by augustynr** [comment]
Thank you for looking into it.
Sorry, I included only what I thought would be relevant. 
The same problem though. Once I set EMAIL_USERNAME I get that error.

My full dotenv:
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################
REDIS_URL=redis://localhost:6379/1
ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART="true"
BROWSER_TRUSTED=
COUNTRY="canada"
DESKTOP_NOTIFICATIONS="true"
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=info
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=699
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=1599
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=30000
PAGE_SLEEP_MAX=60000
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND="../../falling.wav"
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
SCREENSHOT="true"
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES="3060ti,3080"
SMTP_ADDRESS="192.168.199.25"
SMTP_PORT="25"
STORES="amazon-ca,bestbuy-ca,newegg-ca,walmart-ca,canadacomputers,zotac,amd-ca"
WEB_PORT=

**Comment by neatchee** [comment]
That is missing all the email settings still :)

You cannot just set the username. You must also set the TO and PASSSWORD lines.

**Comment by augustynr** [comment]
Sorry :)
 that part is not there because it crashes the program.
normally it would be:
EMAIL_PASSWORD=""
EMAIL_TO="myemail@mydomain.com"
EMAIL_USERNAME="myemail@mydomain.com"
Since I am sending the email through my email server I do not need to set up a password. 
The same way as you would send an email using Sendmail on Linux.


Is there anything else I should be setting up?
