### ISSUE TITLE
Location based stores require login

### ISSUE THREAD

**Issue by kiowadriver** [jef/streetmerchant#1535]
Stores such as Target show console and other volatile stock based on location.  When running headless and/or using a proxy these stores can't be used.

Suggest adding a login/pass parameters for each store so that when checking stock the correct location is used by setting a home store preference in each store account.  As a bonus this would also fix not being able to use the add-cart function when headless in a container.  _Note, MFA would probably need to be disabled for each store in use._

**for ref:**
https://browsee.io/blog/web-scraper-using-puppeteer-how-to-login-to-a-website/

**Comment by neatchee** [comment]
We have something like this working for Microcenter. Could probably be adapted for other stores. However I don't think it's a good idea to encourage users to disable MFA even if it's "for a good reason." Not something I think we should be doing heh.

**Comment by kiowadriver** [comment]
Some stores don't have MFA to start with so it would be on a per store
basis.  Ultimately is would be up to the user.

**Comment by neatchee** [comment]
Sure. I'm mostly just saying I wouldn't want to put that recommendation in the docs. Rather, I'd prefer "Will not work with sites using MFA". If a user wants to figure it out beyond that they are welcome to.
