### ISSUE TITLE
Ability to edit sms template for sms messages to reduce text size

### ISSUE THREAD

**Issue by collinmyers** [jef/streetmerchant#1544]
Ive been finding sms messages are becoming longer then the max allowed characters and are causing the links coming through when a product is found to be broken apart. this has happened on several ones on newegg and the zotac store. if you could inform me of a way to edit what is included in what is sent in the contents of the sms to avoid the links from getting broken that would be appreciated. Thanks

**Comment by neatchee** [comment]
Looking at the source we only pass the URL directly (src/notification/sms.ts@57) for the body-text of the email message we send.

This service relies on email-to-SMS conversion. We send an email to the carrier's custom address (see config.ts @252 for the list of carrier domains) which gets forwarded to your phone as an SMS by your carrier.

What is most likely happening is that your carrier is converting the email we send to an SMS message in a way that makes it too large. My guess is they're including the sender address, subject line, AND body text in the SMS.

The only reasonable resolution here would be make the subject line shorter (we currently use the same string you see printed to console i.e. the line ending in ":: IN STOCK"), but even that wouldn't be bulletproof.

I can't think of another good solution. You may need to edit the source locally if this is a problem for you :(
