### ISSUE TITLE
False positives for mediamarkt.de and saturn.de

### ISSUE THREAD

**Issue by YoBii** [jef/streetmerchant#1545]
## Expected Behavior

Vendors do not have the card in stock. No notification or alert should occur.

## Current Behavior

Streetmerchant alerts about the item being in stock while it's actually not.
The problem has just recently started to occur. Like an hour ago. Before that it was working as expected.

## Steps to Reproduce

Example link: https://www.mediamarkt.de/de/product/-2681866.html

Run streetmerchant with one of those shops active. 
See screenshots attached 

![success-1609248769113](https://user-images.githubusercontent.com/22051355/103287809-b5b6ec00-49e3-11eb-80a3-ff55121b0b32.png)
![success-1609248770197](https://user-images.githubusercontent.com/22051355/103287816-b8194600-49e3-11eb-916a-8607e1e5d816.png)

**Comment by carrierfry** [comment]
Same for me. Maybe they both changed their Website Layout (e.g. other ids for divs etc.?)

**Comment by wofnull** [comment]
The layout of the site changed. Aswell as the report back itself, fixxed the problem in the meantime. You need just to modify both files in streetmerchant-main/src/store/model/ : 
saturn.ts:
Simply add following after } in Line 23:

> 			,
> 			{
> 				container: '#root',
> 				text: ['Nicht verfügbar']
> 			},
> 			{
> 				container: '#root',
> 				text: ['Dieser Artikel ist dauerhaft ausverkauft']
> 			}

mediamarkt.ts:
Simply add following after } in Line 23:

> 			,
> 			{
> 				container: '#root',
> 				text: ['Nicht verfügbar']
> 			},
> 			{
> 				container: '#root',
> 				text: ['Dieser Artikel ist dauerhaft ausverkauft']
> 			}

This fixxes the false positives for now and makes the script working for Mediamarkt / Saturn site again.

**Comment by HebelHuber** [comment]
Im, getting false positives on mediamarkt again.
I checked the mentioned files and they have all the outOfStock entries (latest version on main).

Also, the price check seems to not work on mediamarkt, means false positives for price too high and out of stock.
