### ISSUE TITLE
Shutdown while running

### ISSUE THREAD

**Issue by Wootstapler** [jef/streetmerchant#1557]
## Expected Behavior

PC should stay on.

## Current Behavior

Kernel-Power logged in Windows Event Viewer

## Steps to Reproduce

?

## Environment

**OS:** Win10
**dotenv file:**

ASCII_BANNER=true		
ASCII_COLOR=true
AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=
COUNTRY=usa
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=Deviance.mp3
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=evga,nvidia,asus
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3080,3060ti
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=amazon,bandh,bestbuy,newegg
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=

**Comment by wofnull** [comment]
Without wanting to play down anything from your issue:

Can you please exactly explain what has happened / was shown / for how long it was running beforehand? You gave little to no information about anything, we only know that your System Crashed, that its a Windows 10 Computer and that the given "Error Message" comes from a bluescreen and reffers to a variety of hardware causes, software and driver issues.

It would be wise first to check for a minidump in your system and to analyze it for the exact cause. Most likely the error comes from a defective / weak powersupply that could not hold up high load from the components ( commonly with cheap powersupplys from china , but as said before defectiv or to weak at all could be the cause as well ). Since we have no other information about this, i would not assume that this is caused from Smartmerchant.

Keep in mind, many users are running the script on Windows 10 without any issues.

**Comment by Wootstapler** [comment]
Sorry bud I know I was very vague just frustrated is all.   
  

  
I had it running fine in the background and would walk away. I made some adjustments to the .env and what I posted is what parameters it's currently looking at.   
  

  
Not sure what changed but now upon running it will shut down in a few minutes with no other background apps running.   
  

  
I have a corsair 650cx and when I checked event viewer for the Kernel Power 41 there was no hexadecimal bug code given (just 0).   
  

  
Maybe I'll try and reapply thermal paste to my CPU maybe it's the BIOS shutting it off, not sure haven't had much time to tinker with it.   
  

  
How would I go extracting a mini dump from Windows?
  

  
Appreciate the response, thank you for your time.   
  

  
-Conrad
  

  

  

  
  
  
  
>

**Comment by shindouj** [comment]
I have observed a similar behavior on my setup. I use StreetMerchant on Debian as a dockerized service. About twenty to sixty minutes after detecting a card that's in stock, my whole server (!) reboots. Both the container or the system logs contain absolutely no clues as to why it happens. I'm going to run StreetMerchant in debug mode and send you any logs if they're usable, but needless to say, the script is close to being unusable in this state, definitely not on any kind of server.

Parameters set:
```
STORES=alternate,amazon-de,amazon-uk,asus-de,euronics-de,mediamarkt,saturn
SHOW_ONLY_SERIES=3070,3080
DISCORD_WEB_HOOK=<redacted_webhook>
DISCORD_NOTIFY_GROUP_3070=<redacted_group_id>
DISCORD_NOTIFY_GROUP_3080=<redacted_group_id>
MAX_PRICE_SERIES_3080=1050
MAX_PRICE_SERIES_3070=800
SCREENSHOT=false
AUTO_ADD_TO_CART=false
BROWSER_TRUSTED=false
OPEN_BROWSER=false
```

**Comment by Wootstapler** [comment]
Guess all I had to do was clean my CPU cooler as when I started monitoring my temps it was no bueno. I feel like an idiot but never reseated it with new paste. That solved my issues as my temps dropped by over 30C.
