### ISSUE TITLE
sms not working with tmobile through gmail (gmail arrives)

### ISSUE THREAD

**Issue by undecided2013** [jef/streetmerchant#1560]
[##]Expected Behavior

sms should arrive to designated phone when npm run test:notification is executed

## Current Behavior

Email arrives with test product alert but sms does not

## Steps to Reproduce

1. 8 digit number set up 1-areacode-number with no dashes
PHONE_CARRIER=tmobile
PHONE_NUMBER=########
2. Gmail set up with app password
EMAIL_PASSWORD=somepass
EMAIL_TO=someuser@gmail.com
EMAIL_USERNAME=someuser
3.
Open cmd prompt go to main folder and run 
npm run test:notification
4.
I see 
3.3.0

[10:04:40 AM] info :: ✔ email sent
[10:04:41 AM] info :: ✔ sms sent

## Environment

**OS:**
Win 10 x64 latest
**dotenv file:**
(url
[dotenv.test.txt](https://github.com/jef/streetmerchant/files/5754677/dotenv.test.txt)
) 
```dotenv

```

**Comment by eric99r** [comment]
phone number should be a 9 digit number omitting the 1 before the rest of the number
PHONE_NUMBER=7735551234

**Comment by theweicode** [comment]
i see the same issue even when using the 9 digit # with Mint mobile which also uses the same email SMS as tmobile. looks like the problem is tmobile is filtering SMS sent from streetmerchant. verified by manually sending the email to the same address and the SMS arrived immediately.  i'm using gmail filter to automate this as a workaround.

**Comment by ThreeHAN** [comment]
I have tmobile and gmail. I tested with latest version and it functions as expected with the text arriving instantly.

What shows in the "sent" section of the gmail account used? You should see the email that streetmerchant sent to your mobile phone number (xxxxxxxxxx@tmomail.net).

**Comment by undecided2013** [comment]
I do see it in the 'sent' in my gmail.
I tried both with 1 in front of area code and without.
Without 1 (10 numbers )
##########@tmomail.net
With 1 (11 numbers )
###########@tmomail.net


________________________________

**Comment by undecided2013** [comment]
p.s. just tried it manually myself in gmail (without the 1) and I got the sms.

________________________________
