### ISSUE TITLE
Amazon Offer Listing doesnt work properly

### ISSUE THREAD

**Issue by Vedo63** [jef/streetmerchant#1598]
Hey, I think amazon.de changed something on their logic. When I call the url https://www.amazon.de/gp/offer-listing/B08H93ZRK9 it redirects me to the standard buy page https://www.amazon.de/dp/B08H93ZRK9/ref=olp_dp_redir.

**Comment by jef** [comment]
Unfortunately, Amazon will continue to offer strange redirects when products are unavailable. This behavior is sort of inconsistent, so it's hard to determine when this happens.

Seems like the links are working currently thought.
