### ISSUE TITLE
Streetmerchant not adding anything to cart

### ISSUE THREAD

**Issue by ThinkSalat** [jef/streetmerchant#1602]
Hi,

When it's finding a 3080 in stock at best buy, it just opens a bunch of empty best buy carts. This isn't working at all. I just end up with 70 new tabs of empty carts and I can barely use my computer because it constantly pops up empty best buy shopping carts.

**Comment by JustMaier** [comment]
It looks like BestBuy may have changed the way that things work or they couldn't add the item you requested to your cart and so it just displayed an empty one.

**Comment by jingo5** [comment]
Yeah drop from Best Buy occurred. I don't think there's an issue merely they got hammered and we didn't get to add it to cart. Not the apps fault.  But good test to see sms texting functional.
