### ISSUE TITLE
Shorten best buy urls

### ISSUE THREAD

**Issue by kiowadriver** [jef/streetmerchant#1610]
## Expected Behavior

The most efficient means of cataloging and updating product URLs

## Current Behavior

We are using a more verbose url format than necessary in the bestbuy.ts store model. The BB api has a very very simple url that support both the product page and add cart function.

Examples:

Current URL in bestbuy.ts:
https://www.bestbuy.com/site/evga-geforce-rtx-3070-xc3-black-gaming-8gb-gddr6x-pci-express-4-0-graphics-card/6439300.p?skuId=.....

Shorter version using api:

Tracked Page:
https://api.bestbuy.com/click/-/6439300/pdp

Cart link:
https://api.bestbuy.com/click/-/6439300/cart

**Comment by wofnull** [comment]
i have done a patch for this in #1613 , now we wait until jef approves / adds it to the working tree ;)
