### ISSUE TITLE
Outdated/missing store.asus.com links

### ISSUE THREAD

**Issue by JesterEE** [jef/streetmerchant#1637]
## Expected Behavior
Query and report on stock of 30 series cards from store.asus.com

## Current Behavior
3060ti, 3070 cards are not present.  3080 and 3090 series card links are missing or outdated.

## Other
I created a feature branch to fix this, however I am not operating a development environment for this project and have no good way to test it for pull.  I request that @jef or one of the other project developers review the branch and pull/implement the updates I made to enhance streetmerchant.

JesterEE/streetmerchant@d04ba972c49e3e6f1371ccea9eee15b3a2b6a18c

**Comment by wofnull** [comment]
you can open a pull request from your repo on github from within the branch with the regarding changes.

So jef can implement this directly, if the branch with the asus fix works on your end and is tested / runs through the github pretests, jef can directly import it on your behalf.

**Comment by kiowadriver** [comment]
I tested the changes he made and they work if you also ensure you have added the "ko oc" to the store.ts file as well.

**Comment by JesterEE** [comment]
@wofnull @kiowadriver
Thanks for helping with the testing!  I will submit it as a PR.
