### ISSUE TITLE
Only searches some stores

### ISSUE THREAD

**Issue by sevigny245** [jef/streetmerchant#1647]
## Expected Behavior

I should get OOS notifications from amazon, bestbuy, newegg, adorama, asus, bandh, and gamestop 

## Current Behavior

I only get OOS notifications from amazon and asus. Adorama gives me Error 403. The rest are silent.

When I play around with the dotenv, if it's amazon exclusive, it works. The asus store works too. When it's exclusively bestbuy, newegg, bandh, or gamestop, nothing happens. Adorama consistently produces 403 Errors.

## Environment

- OS: Mac OS 10.14.6

```[dotenv.txt](https://github.com/jef/streetmerchant/files/5793876/dotenv.txt)```

# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=false
COUNTRY=usa
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=true
IN_STOCK_WAIT_TIME=0
LOG_LEVEL=info
LOW_BANDWIDTH=true
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=2100
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=10
NVIDIA_SESSION_TTL=60000
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=10000
PAGE_BACKOFF_MAX=3600000
PAGE_SLEEP_MIN=5000
PAGE_SLEEP_MAX=10000
PAGE_TIMEOUT=30000
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=/Users/privateuser/Downloads/got-it-done-613.mp3
PROXY_ADDRESS=
PROXY_PROTOCOL=http
PROXY_PORT=80
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=true
SHOW_ONLY_BRANDS=asus
SHOW_ONLY_MODELS=strix oc
SHOW_ONLY_SERIES=3090
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=amazon,bestbuy,newegg,adorama,asus,bandh,gamestop
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=

## Logs
[2021-01-11T02_48_41_298Z-debug copy.log](https://github.com/jef/streetmerchant/files/5793878/2021-01-11T02_48_41_298Z-debug.copy.log)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.11
3 info using node@v14.15.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle streetmerchant@~prestart: streetmerchant@
6 info lifecycle streetmerchant@~start: streetmerchant@
7 verbose lifecycle streetmerchant@~start: unsafe-perm in lifecycle true
8 verbose lifecycle streetmerchant@~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/privateuser/streetmerchant/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle streetmerchant@~start: CWD: /Users/privateuser/streetmerchant
10 silly lifecycle streetmerchant@~start: Args: [ '-c', 'npm run build && node build/index.js' ]
11 silly lifecycle streetmerchant@~start: Returned: code: 130  signal: null
12 info lifecycle streetmerchant@~start: Failed to exec start script
13 verbose stack Error: streetmerchant@ start: `npm run build && node build/index.js`
13 verbose stack Exit status 130
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid streetmerchant@
15 verbose cwd /Users/privateuser/streetmerchant
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v14.15.4
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 130
22 error streetmerchant@ start: `npm run build && node build/index.js`
22 error Exit status 130
23 error Failed at the streetmerchant@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 130, true ]

**Comment by wofnull** [comment]
the dotenv file must be named "dotenv" not "dotenv.txt

**Comment by sevigny245** [comment]
It is named "dotenv" in practice, I double-checked. The behavior from Streetmerchant is as if the fact that "best buy can carry rog strix 3090's" isn't even considered

**Comment by jvanph** [comment]
I just started experiencing a similar issue a few days ago. I'm only getting OOS notifications for 2 out of 3 stores. Specifically, I am not getting OOS notifications for Newegg.

**Comment by bmn001** [comment]
Seeing the same with Newegg.  It's selected, but will not be searched by streetmerchant.

**Comment by wofnull** [comment]
i checked against the newegg search config in streetmerchant and the only available 3090 strix at newegg.

You configured "strix oc" as model for the 3090 on newegg, the only available card on site and in the config is just a "strix"

so please change the following line to:

`SHOW_ONLY_MODELS=strix oc, strix`

and it should work for newegg. Please bear in mind that the 3090 STRIX and STRIX OC are DIFFERENT! Cards ( only Max Boost Clock wise ), and only the non OC Version is  available on newegg!

**Comment by jvanph** [comment]
> 
> 
> i checked against the newegg search config in streetmerchant and the only available 3090 strix at newegg.
> 
> You configured "strix oc" as model for the 3090 on newegg, the only available card on site and in the config is just a "strix"
> 
> so please change the following line to:
> 
> `SHOW_ONLY_MODELS=strix oc, strix`
> 
> and it should work for newegg. Please bear in mind that the 3090 STRIX and STRIX OC are DIFFERENT! Cards ( only Max Boost Clock wise ), and only the non OC Version is available on newegg!

This worked for me once I opened it up to more models, I was able to search Newegg again. Thanks.

**Comment by wofnull** [comment]
then feel free to close up this Issue report, since neither jef or anyone else can change what newegg sells ;)

**Comment by sevigny245** [comment]
I ended up doing that and yes it searches Newegg, Best Buy, and Amazon consistently now, but I had to turn off the ASUS store due to constant false positives and it still doesn't search B and H at all for the strix or strix oc

**Comment by wofnull** [comment]
then i would suggest to pull the repo again, #1670 was added to the main repo just 1 hour ago, could be that you missed this update ;)

**Comment by sevigny245** [comment]
Ah yes! Thank you! BH is working now! Still having constant 403 problems with Adorama even though I'm using proxies, and false positives with ASUS, but this is amazing. Thank you for your patience, because I'm a total noob. This is the first time I've really used GitHub so I'm still figuring it out :)

Not sure what can be done about ASUS store false positives because when the page loads I do see "add to cart" for a fraction of a second before the page finishes loading and displays OOS

**Comment by jvanph** [comment]
> 
> 
> then feel free to close up this Issue report, since neither jef or anyone else can change what newegg sells ;)

Although the bot is searching Newegg again, I noticed it is still not searching for the evga 3080 xc3 ultra model like it once did. I am able to manually search for the model on the site, but do not know why the bot no longer searches for it.

**Comment by wofnull** [comment]
About the issue with Adorama, we cannot do much about, they configured the server to give out 403 errors if they get spammed with site requests from a single ip over amount X of time ... 

BH was fixxed yesterday with a big update to their cardlist from my end.

Asus on the other hand has as far as i was able to test over the past few days no issues at all with any of their Stock Checks:
![image](https://user-images.githubusercontent.com/449003/104693862-a4bbe980-570a-11eb-8270-ae46f6506a27.png)
So i assume it works as intended, at least i have no false positives so far.

As for the XC3 Ultra 3080 from EVGA on Newegg:
The card was removed from neweggs config on September 23rd from @jef in update 4cb52d31d57e5e28675771a0885bf8f07b3ce442 because the card is not available in the US ... i tend not to revert things other people had decided before to remove, so its up to jef if he corrects this.

**Comment by jvanph** [comment]
> 
> 
> About the issue with Adorama, we cannot do much about, they configured the server to give out 403 errors if they get spammed with site requests from a single ip over amount X of time ...
> 
> BH was fixxed yesterday with a big update to their cardlist from my end.
> 
> Asus on the other hand has as far as i was able to test over the past few days no issues at all with any of their Stock Checks:
> ![image](https://user-images.githubusercontent.com/449003/104693862-a4bbe980-570a-11eb-8270-ae46f6506a27.png)
> So i assume it works as intended, at least i have no false positives so far.
> 
> As for the XC3 Ultra 3080 from EVGA on Newegg:
> The card was removed from neweggs config on September 23rd from @jef in update [4cb52d3](https://github.com/jef/streetmerchant/commit/4cb52d31d57e5e28675771a0885bf8f07b3ce442) because the card is not available in the US ... i tend not to revert things other people had decided before to remove, so its up to jef if he corrects this.

Understood, thank you for the update.
