### ISSUE TITLE
nvidia-api does not support checking stock for 3060ti FE

### ISSUE THREAD

**Issue by Accelyte** [jef/streetmerchant#1713]
## Expected Behavior

Using "scan" as store should show "out of stock" similar to other stores.

## Current Behavior

The terminal repeatedly shows "[scan] Running linksBuilder..."

## Steps to Reproduce

Configure dotenv and run.

## Environment

- OS: Windows 10 x64

```
ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=nvidia
SHOW_ONLY_MODELS=founders edition
SHOW_ONLY_SERIES=3060ti
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=scan
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=
```

## Logs
```
[4:13:44 am] info :: ℹ selected stores: scan
[4:13:44 am] info :: ℹ selected brands: nvidia
[4:13:44 am] info :: ℹ selected models: founders edition
[4:13:44 am] info :: ℹ selected series: 3060ti
[4:13:53 am] info :: [scan] Running linksBuilder...
[4:19:00 am] info :: [scan] Running linksBuilder...
```

**Comment by wofnull** [comment]
simple solution for your question please remove "founders edition" and "nvidia" out of your config at these places:
SHOW_ONLY_BRANDS=nvidia
SHOW_ONLY_MODELS=founders edition

Cause: first of all Nvidia does not sell a 3060ti on scan.co.uk ... only third party cards, furthermore the script works in this way:

It looks on the listing page for 3060ti cards on scan and builds an index of cards and checks against it. Depending on what you are Filtering ( Brand / Models / Series ) the check will differ.

**Comment by Accelyte** [comment]
What if I want to only search for the 3060ti FE? I'm aware that scan is the retailer for the cards, but how would I setup my dotenv?

**Comment by wofnull** [comment]
since scan does not provide public links for the FE cards as other EU Partners from NVIDIA, the onyl way is to use the nvidia-api store setting with country setting uk ;)

**Comment by MRizkBV** [comment]
> since scan does not provide public links for the FE cards as other EU Partners from NVIDIA, the onyl way is to use the nvidia-api store setting with country setting uk ;)

@wofnull Does nvidia-api actually detect FE drops on Scan and gets their links?!

**Comment by Accelyte** [comment]
That's what I'd like to know as well, documentation doesn't provide much information either.

**Comment by Accelyte** [comment]
@wofnull I just tested a modified config following your advice, and I don't think streetmerchant supports checking 3060ti stock using nvidia-api.

This dotenv does not work at all.
```
ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY=great_britain
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=nvidia
SHOW_ONLY_MODELS=founders edition
SHOW_ONLY_SERIES=3060ti
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=nvidia-api
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=
```

However, changing the series value to 3090 shows that it is out of stock:
```
[7:04:39 pm] info :: ℹ selected stores: nvidia-api
[7:04:39 pm] info :: ℹ selected brands: nvidia
[7:04:39 pm] info :: ℹ selected models: founders edition
[7:04:39 pm] info :: ℹ selected series: 3090
[7:04:52 pm] info :: ✖ [nvidia-api] [nvidia (3090)] founders edition :: OUT OF STOCK
```

**Comment by wofnull** [comment]
After checking the documentation and the NVDIA Api configs, i did not find any 3060ti entrys there, this was not configured for 3060tis yet. This is the cause why the script defaults back to 3090 on your end.

@jef needs to take a look at this to work proper, as it looks the 3070 checks are aswell not properly implemented in the file

**Comment by Accelyte** [comment]
For anyone interested, I temporarily wrote a python script (30min effort) using hardcoded api links.

https://gist.github.com/Accelyte/3a880c4ab23531c427f79cbf534f8c82

**Comment by sohaiiil** [comment]
`nvidia-api` should be deprecated as it no longer a viable method of checking stock.

However, I have pushed this PR #1732 to fix the issue.

**Comment by wofnull** [comment]
the main problem with nvidia-api is, that it lacks at least 3060ti cards and as far as i can see the 3070 seems to be searched as some kind of 2060 super ...

was not able yet to take a closer look into this, but since most NVIDIA partner stores do list 30x0 FE Cards directly in their inventory (except scan for uk, their way of generating links for instock items differs alot and needs the links builder and overall does not include FE Cards) additional to the api-stock from NVIDIA, it would work to check the instock from the single stores.
However the API gives additional possibilitys if the stock is not properly displayed.

a) the api gets repaired 
b) the api gets removed 

one or another, but the stock check should work for the partnersites for 100% in this case.

**Comment by sohaiiil** [comment]
The benefit from the Nvidia store method is that as soon as it goes live and the add to cart button is displayed for any FE card, it shows the direct link to that nvidia store page and only needs 1 click to get to the correct partner site. It can only be done this way as the link is randomised and is different every time a FE card comes into stock.
