### ISSUE TITLE
Vuugo false positive

### ISSUE THREAD

**Issue by jbureau-qc** [jef/streetmerchant#1716]
## Expected Behavior

should see the product as out of stock

## Current Behavior

see the products as in stock

## Steps to Reproduce

enable vuugo in the stores
check the page source
see the label in stock commented whiich is causing false positives

## Environment

- OS: Windows 10

COUNTRY=canada
HEADLESS=false
MAX_PRICE_SERIES_3080=1210
PAGE_SLEEP_MIN="50000"
PAGE_SLEEP_MAX="90000"
STORES=vuugo
SHOW_ONLY_SERIES=3080

```

## Logs

[12:35:49 PM] info :: ✖ [vuugo] [evga (3080)] xc3 ultra :: OUT OF STOCK
[12:35:49 PM] info :: ✖ [canadacomputers] [asus (3080)] strix :: PRICE 1249 EXCEEDS LIMIT 1210
[12:35:51 PM] info :: ✖ [canadacomputers] [msi (3080)] suprim x :: PRICE 1249 EXCEEDS LIMIT 1210
[12:35:51 PM] info :: ✖ [amazon-ca] [msi (3080)] gaming x trio :: OUT OF STOCK
[12:35:52 PM] info :: ✖ [canadacomputers] [gigabyte (3080)] aorus xtreme waterforce wb :: PRICE 1349 EXCEEDS LIMIT 1210
[12:35:53 PM] info :: ✖ [vuugo] [gigabyte (3080)] aorus master :: OUT OF STOCK
[12:35:54 PM] info :: ✖ [canadacomputers] [gigabyte (3080)] aorus xtreme waterforce wb :: PRICE 1349 EXCEEDS LIMIT 1210
[12:35:58 PM] info :: ✖ [vuugo] [gigabyte (3080)] aorus xtreme :: PRICE 1231.04 EXCEEDS LIMIT 1210

**Comment by jbureau-qc** [comment]
![image](https://user-images.githubusercontent.com/33074411/104851121-0920a980-58c1-11eb-818c-f15eeebde838.png)

**Comment by jbureau-qc** [comment]
Adding a out of stock check in the vuugo store seems to fix the issue :
outOfStock: {
	container: '.red',
	text: ['Back Order']
},

**Comment by anthonytam** [comment]
I've been running Vuugo since the commit was merged in and haven't seen any false positives show up

Looking at the commented code, the In Stock text isnt within the same selector the application is looking for (.green). Would you be able to post one of the instock screenshots the application generated? Perhaps Vuugo defaults to an "In Stock" state until the actual stock data loads. This has caused me a few false positives in the past and required an increase in navigation time

**Comment by wofnull** [comment]
We had this in a few stores already where the instock check failed somehow to work properly, however the fix was to define simply the out of stock variable, to end the false positives, double checking should not harm at all, at least its an insurance that the script works as it should.

**Comment by jbureau-qc** [comment]
> I've been running Vuugo since the commit was merged in and haven't seen any false positives show up
> 
> Looking at the commented code, the In Stock text isnt within the same selector the application is looking for (.green). Would you be able to post one of the instock screenshots the application generated? Perhaps Vuugo defaults to an "In Stock" state until the actual stock data loads. This has caused me a few false positives in the past and required an increase in navigation time

Sure I will try to change my accepted price and remove the outOfStock check i added to test. Will update after I test, thanks



> We had this in a few stores already where the instock check failed somehow to work properly, however the fix was to define simply the out of stock variable, to end the false positives, double checking should not harm at all, at least its an insurance that the script works as it should.
> 
> Without out of Stock check:
> ![image](https://user-images.githubusercontent.com/449003/104944193-220b8680-59b7-11eb-8127-65d621a570f6.png)
> 
> With out of Stock check:
> ![image](https://user-images.githubusercontent.com/449003/104944249-36e81a00-59b7-11eb-8040-71a46e6830b7.png)
> 
> Which reflects the current state on the site 1 to 1

Seems to match what I am experiencing !

**Comment by wofnull** [comment]
i have published a patch for this to the main source, right now, should be added in a bit by @jef ( its a bit more precise in finding the correct selector as the one given here )

**Comment by jbureau-qc** [comment]
Seems like this morning it is not acting up so I cannot provide the instock false positive flag currently @anthonytam
