### ISSUE TITLE
Notifications test not working

### ISSUE THREAD

**Issue by robward-basemap** [jef/streetmerchant#1735]
## Expected Behavior

Running "docker run -it --rm --env-file ./dotenv ghcr.io/jef/streetmerchant:latest test:notification:production" should send a test notification

## Current Behavior

An error is thrown

## Steps to Reproduce

Run "docker run -it --rm --env-file ./dotenv ghcr.io/jef/streetmerchant:latest test:notification:production"

## Environment

- OS: Docker

## Logs

> streetmerchant@ test:notification:production /app
> node build/test/functional/test-notification.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/app/build/test/functional/test-notification.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streetmerchant@ test:notification:production: `node build/test/functional/test-notification.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the streetmerchant@ test:notification:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appuser/.npm/_logs/2021-01-18T21_11_14_742Z-debug.log

**Comment by magicmq** [comment]
I am receiving the same error with nightly build c13df2286403a1bd3cb5ee157f106e6f3c35cec9c1f8949b512b4237e7387a60. I am only using Pushbullet for notifications.

**Comment by magicmq** [comment]
I am also receiving the same issue when I try to test notifications on nightly build from commit 9695e29a02ea320842954db9f2ea51612b983490. I am only using Pushbullet for notifications.

**Comment by ryanqyao** [comment]
I'm having the same issue, however when I run `npm run test:notification`, it works fine. I can get notifications in Telegram. So I assume the code works, just the test-notificaiton not working with Docker.

**Comment by PacketShepard** [comment]
Same problem here. The path may be wrong based on the Dockerfile. It looks like build/build/ (duplicate directory) is being created and this is breaking the test notification path. I've noticed something similar with the web-api

**Comment by jef** [comment]
I'll test this in the near future. Thank you!
