### ISSUE TITLE
SHOW_ONLY_SERIES not working

### ISSUE THREAD

**Issue by Jason-Ross-SFDC** [jef/streetmerchant#1737]
Selected Series should process as in the dotenv file
SHOW_ONLY_SERIES="RX6800XT,RX6900XT,3080,xboxsx"

## Current Behavior
it is running all series.

selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx

**Comment by Jason-Ross-SFDC** [comment]
It is also doing this for stores

STORES="amazon,bandh:30000:40000,bestbuy,xbox,ebgames,target,toysrus"

[5:16:13 PM] info :: ℹ selected stores: amazon, bestbuy
[5:16:13 PM] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx

**Comment by Amran14** [comment]
Maybe leaving out the quotation marks? Works fine for me

**Comment by Jason-Ross-SFDC** [comment]
I'm getting the following when I install it. I have been running for 3 months with no problems till now.

jasonross@Jasons-Apple-Silicon-MacBook-Pro streetmerchant % npm i
npm WARN twilio@3.55.0 requires a peer of @types/express@^4.17.7 but none is installed. You must install peer dependencies yourself.
npm WARN twilio@3.55.0 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.

Looks like Dependabot doesn't have 3.55 it only has 3.54

**Comment by particledecay** [comment]
Having the same issue here. With the latest code and the exact same `.env` as I've had for weeks, suddenly `SHOW_ONLY_SERIES` is being ignored. Here is what my line looks like:

```
SHOW_ONLY_SERIES=ryzen5950,rx6900xt,3080,sonyps5c,xboxsx
```

Sucks because it's adding all sorts of overpriced items to my cart from marketplace sellers, since I don't have max price limits set on items that aren't part of my specified series.

**Comment by JeffyW** [comment]
I also noticed the other variables not working either.  Stores was using "bestbuy, amazon" even though I had "STORES=bestbuy,amd,amazon" and models wasn't being picked up at all.

Not extensive investigation, but f87053cb02e04b3cb2c0cf253187a9e9857c9858 looked suspicious, and a "git checkout dbde7814af79253de1552ff3a33a3b2446089bf7" seems to have resolved the issue.

**Comment by particledecay** [comment]
@JeffyW yep, this would be my guess right here: https://github.com/jef/streetmerchant/commit/f87053cb02e04b3cb2c0cf253187a9e9857c9858#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R8-R18

**Comment by blackflame007** [comment]
Im getting similar behavior, It inly seems to be running on the rx6800xt series only for me
```
SHOW_ONLY_BRANDS=amd,asus,evga,xfx
SHOW_ONLY_MODELS=tuf,tuf oc,merc,amd reference,strix,strix oc,strix white
SHOW_ONLY_SERIES=rx6800xt,rx6900xt
STORES=amd,bestbuy,newegg,asus,bandh,evga
```

**Comment by Jason-Ross-SFDC** [comment]
ok update.

I had to install the 2 dependencies.

once that was done I had 2 behaviors.

npm run start = Run with the dotenv file I created.

npm run start:dev = Run with default (This is what I have been running with for the past month)
