### ISSUE TITLE
Bestbuy "Check Stores"

### ISSUE THREAD

**Issue by killercam1020** [jef/streetmerchant#1762]
## Environment

- OS: Windows 10

```dotenv 
AUTO_ADD_TO_CART="true"
COUNTRY="usa"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PLAY_SOUND=tactical-nuke.mp3
SHOW_ONLY_BRANDS= sony,microsoft
SHOW_ONLY_MODELS= ps5 console,ps5 digital,xbox series x
SHOW_ONLY_SERIES="sonyps5c,sonyps5de,xboxsx"
STORES=bestbuy,target,amazon,walmart,antonline,amazon-ca,newegg,xbox
USER_AGENT="
LOW_BANDWIDTH="false"
HEADLESS="false"
IN_STOCK_WAIT_TIME=600
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=

## Logs

<!-- Provide a brief log -->

**Comment by wofnull** [comment]
If I understand correct you deactivated the headless mode, which leads to the bot showing what its doing?

if this is right: the bot reads not the add to cart page, it reads the normal product page and opens ( depending on  your setting ) the page on hit in your main browser with the add to cart link.

**Comment by killercam1020** [comment]
My main issue is that the bot is not detecting stock when it says check stores instead of add to cart
