### ISSUE TITLE
Update to new version without losing items I added

### ISSUE THREAD

**Issue by Speedmod88** [jef/streetmerchant#1776]
Hi
I'm new user of github and probably there a way to do that but I don't know how exactly... so is anyone can tell me how to update the streetmerchant without losing all items I added please?

Thank You
Best Regards

**Comment by HawkyYT** [comment]
- End the bot by pressing Ctrl + C.
- Type and run `git pull origin main`
- Type and run `npm install`
- Type and run `npm run start`

**Comment by Speedmod88** [comment]
ok done and I'm not sure why but my version.txt and when I start it, it still v3.3 instead of the new one and all my store isnt updated since I can see there all have been updated 6 days ago...
is it normal?

**Comment by HawkyYT** [comment]
That should have changed to v3.4.1. It doesn't sound like it updated. Did you follow the wiki when you set up your bot? I'm assuming you are on Windows: https://github.com/jef/streetmerchant/wiki/Installation:-Windows

Your best bet is to reinstall everything. To keep your items copy your `dotenv` file somewhere safe outside your streetmerchant folder (like your desktop). Delete your entire `streetmerchant` folder (not just the contents, the folder itself) and follow the guide from the beginning, including redownloading and installing git and node.js to make sure they are up-to-date.

Once done you can copy your `dotenv` back into your `streetmerchant` folder.

**Comment by Speedmod88** [comment]
Yes, I followed every step from the wiki
okk I will redo everything than :/

**Comment by Speedmod88** [comment]
I tested with the `git checkout .` before the  `git pull origin main`  and it work but it overwrite everything

is it still better I reinstall everything? or it didnt work because I added new items in somes store?

**Comment by HawkyYT** [comment]
Sorry, I misunderstood when you said you wanted to keep your items. Added custom items to the store model `.ts` files unfortunately does prevent you from updating, as git assumes you have created your own branch when you do that. You can force it to update using the commands below, but it overwrites anything you added to the `.ts` files. So you'd have to add your items back to the `.ts` files again anyways.

To make things easier you can copy your customized `.ts` files outside of streetmerchant before forcing the update. Then after updating, open the new `.ts` file and the old `.ts` file side-by-side and copy the lines over for your custom items. DO NOT copy your old `.ts` file into streetmerchant after updating, it might break things. Just manually add the lines.

commands:

`git stash`

`git pull origin main`

`npm install`

**Comment by Speedmod88** [comment]
okk and what do git stash?

**Comment by HawkyYT** [comment]
Honestly I'm only slightly more acquainted with git than you are.

I'm guessing when you've been trying to run `git pull origin main` you've been getting this error:

```
c:\streetmerchant>git pull origin main
From https://github.com/jef/streetmerchant
 * branch            main       -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        src/store/model/amazon.ts
Please commit your changes or stash them before you merge.
Aborting
Updating b97d581..ce609fb
```

Running `git stash` first prevents this.

Technically it also saves all your changes so you can revert back (which includes reverting to the older version of streetmerchant). 

You probably don't care for that though. I just looked this up and it turns out the better way to do this is to use `git checkout` with `-f` to force it:

`git checkout -f main`

`npm install`
