### ISSUE TITLE
Configuration files need to be in a separate directory to map docker volume

### ISSUE THREAD

**Issue by kiowadriver** [jef/streetmerchant#1777]
## Expected Behavior
Isolation of all configuration files *.proxy, dotenv, etc.. to a single folder such as "/config" to allow a docker to map that folder as a volume and retain settings between docker updates. 

Docker user's would only need to map a volume instead of passing an env file path.  The same volume would be used for proxy configuration files as well.

## Current Behavior
All of the configuration files are in the root directory.  Dockers can map this root directory but then the entire docker source is mapped to a volume instead of just the isolated configuration files intended to be retained between updates. 

## Steps to Reproduce
Run any version

## Environment
Docker

- OS:
- All

Recommendation:
Move all configuration files to a separate directory.  Suggest "/config" and update paths for appropriate isolation

**Comment by bossanovaorca** [comment]
is there a workaround for this? streetmerchant resets the list of watched stores whenever the container is updated

**Comment by Seiya82** [comment]
Any news on this?

**Comment by Hukuma1** [comment]
The whole point of being in a container is to retain the settings and update the core. Any updates?
