### ISSUE TITLE
Street merchant not using my edited code

### ISSUE THREAD

**Issue by JDuggal760** [jef/streetmerchant#1789]
## Expected Behavior
I have edited code of streetmerchant and different stores/products

Should check those stores and only the select products
## Current Behavior
Checks only amazon and BestBuy and all products

## Steps to Reproduce
Download streetmerchant then install node then install it in system32 terminal, admin cmd

## Environment

- OS:
Windows 10

```# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=
COUNTRY=great_britain
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=false
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=false
MAX_PRICE_SERIES_3060TI=470
MAX_PRICE_SERIES_3070=490
MAX_PRICE_SERIES_3080=800
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=25
NVIDIA_SESSION_TTL=
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=true
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3060ti,3080,3070
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=amazon-uk:15000:30000,argos,box:15000:55000,awd,ccl:40000:65000,currys,ebuyer,game,johnlewis,novatech:40000:65000,overclockers:15000:45000,scan:25000:70000,smythstoys,very,nvidia-gb,shopto,aria
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=
```

## Logs
> npm run build && node build/index.js

> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.3.0

[8:46:29 AM] info :: ℹ selected stores: amazon, bestbuy
[8:46:30 AM] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx
[8:48:51 AM] error :: ✖ [amazon] asus 3060ti dual - Navigation timeout of 30000 ms exceeded
[8:48:52 AM] error :: ✖ [bestbuy] nvidia 3070 founders edition - Navigation timeout of 30000 ms exceeded
[8:49:08 AM] info :: ✖ [amazon] [gigabyte (3060ti)] gaming oc :: OUT OF STOCK
[8:49:10 AM] warn :: ✖ [amazon] [gigabyte (3060ti)] gaming oc pro :: CAPTCHA
[8:49:12 AM] info :: ✖ [bestbuy] [evga (3070)] xc3 black :: OUT OF STOCK
[8:49:27 AM] info :: ✖ [bestbuy] [gigabyte (3070)] eagle :: OUT OF STOCK
[8:49:38 AM] info :: ✖ [amazon] [gigabyte (3060ti)] eagle :: OUT OF STOCK

dont worry about the captvha or nav timeout im not worried abt those im worried abt my code not working

**Comment by wofnull** [comment]
How should we at all be able to check whats wrong, when we dont know the code changes? 
i checked your repos, there is no fork of streetmerchant, therefore nobody can now what was changed and if it was changed properly.
However it looks like your changes could have interfered with some basic functions, which are pulled from the dotenv file.

could you please test first if streetmerchant ( current Version 3.4.1 ) runs without these issues?

**Comment by JDuggal760** [comment]
wdym the code changes r right there thats what i changed,  i git cloned it in is that the same as a fork sry idk much abt git
I just updated it a couple hrs ago and still had the issue

**Comment by wofnull** [comment]
ah ok ... you didnt change the code, you changed the config.

The behaviour you are mentioning comes up when the streetmerchant script does not find an dotenv file in the main folder of the script, or if there is nothing configured at all.

first of all, did you rename the config from dotenv-example to dotenv ? ( as it is stated in the first line of the config? )

Please verify that there is no extension behind the dotenv ( such as .txt ). If file extensions are not shown at all for any file:
https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/
Follow these instructions to get them visible.

**Comment by JDuggal760** [comment]
![dddddddddddddddddddddddddddd](https://user-images.githubusercontent.com/77640905/105750564-e7ec3880-5f12-11eb-8939-2684c2ba1276.PNG)

**Comment by JDuggal760** [comment]
I have all the files in the right place and format

**Comment by swe22344** [comment]
This is a guess because I've never tried, but I always have the values in "value", also what are the numbers in the stores line?
i would put this 

`STORES=amazon-uk:15000:30000,argos,box:15000:55000,awd,ccl:40000:65000,currys,ebuyer,game,johnlewis,novatech:40000:65000,overclockers:15000:45000,scan:25000:70000,smythstoys,very,nvidia-gb,shopto,aria
`
as this 
`STORES="amazon-uk, argos, box,  awd, ccl, currys, ebuyer, game, johnlewis, novatech, overclockers,scan, smythstoys, very, nvidia-gb, shopto, aria"`

unless you have a stores file called that, im pretty sure it's looking for a string type value of the file names and that is all so any configuration done on the stores="example" wouldn't work so only the name of the store is accepted.

**Comment by wofnull** [comment]
@swe22344 the numbers define a per store setting for waiting for nav timeout and waiting for page, for slow loading sites.

**Comment by JDuggal760** [comment]
yeah
