### ISSUE TITLE
Huge Memory Usuage on 3.4.1

### ISSUE THREAD

**Issue by pressplay01** [jef/streetmerchant#1801]
Hi!

I am running streetmerchant for some time now on vps with vpn and never had problems.

Since 3.4.1 the memory usuage of SM is huge.
The problem is, as far as i can see, that SM does not close "old" chromium instances. 

So when i start SM the memory, the memory goes up by time and let my OS crash after some hours, when the ram is full (8 GB on windows server). At the end there are more than 100 chromium instances active.

As you can see i do not scan a lot of stores:

SHOW_ONLY_BRANDS="sony"
SHOW_ONLY_MODELS="ps5 console,ps5 digital"
SHOW_ONLY_SERIES="sonyps5c,sonyps5de"
STORES="amazon-de,amazon-de-warehouse,amazon-es,amazon-fr,amazon-uk,expert,mediamarkt,saturn

**Comment by pressplay01** [comment]
i could figure out, that the problem is caused by  mediamarkt and saturn stores.
i am running now 2 instances of SM:   mediamarkt / saturn as seperate instance on 3.3.0 and never had any problems again.

i just dont know how to fix it

**Comment by YoBii** [comment]
I can confirm this problem. And indeed removing mediamarkt and saturn fixes the issue.

**Comment by jef** [comment]
I can try and take a look at it today. I've been pretty busy lately, so if anyone does find a fix for it, please feel free to open a PR!
