### ISSUE TITLE
Amazon Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by Cachencho1337** [jef/streetmerchant#1802]
i had streetmerchant running all night, when i wake up i see these error message of this issue

[17:20:20] error :: ✖ [amazon] asus 3080 tuf oc - Navigation timeout of 30000 ms exceeded 

in all the 3080 series...  this log appears after 5 or 7 min running, this gpu are out of stock, i dont know it is because of that. but i cant traking the stock because of that

**Comment by wofnull** [comment]
raise the navigation timeout time for amazon only or in general to the 60000 or higher.

If amazon is under heavy load ( on other sites aswell ) it tends to slow down the site for users who are doing many querrys to the site, raising the page load ( and nav load time ) for them.
