### ISSUE TITLE
 npm run start

### ISSUE THREAD

**Issue by baggot4** [jef/streetmerchant#1806]
when i run " npm run start" I get this error

> $ npm run start
> 
> > start
> > npm run compile && node build/src/index.js
> 
> '"node"' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code 9009
> npm ERR! path C:\Users\baggot4\streetmerchant
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "npm run compile && node build/src/index.js"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\baggot4\AppData\Local\npm-cache\_logs\2021-01-27T03_57_57_858Z-debug.log

here is the full error

> 0 verbose cli [
> 0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 0 verbose cli   'run',
> 0 verbose cli   'start'
> 0 verbose cli ]
> 1 info using npm@7.0.8
> 2 info using node@v15.1.0
> 3 timing config:load:defaults Completed in 1ms
> 4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
> 5 timing config:load:builtin Completed in 1ms
> 6 timing config:load:cli Completed in 1ms
> 7 timing config:load:env Completed in 1ms
> 8 timing config:load:file:C:\Users\baggot4\streetmerchant\.npmrc Completed in 0ms
> 9 timing config:load:project Completed in 1ms
> 10 timing config:load:file:C:\Users\baggot4\.npmrc Completed in 0ms
> 11 timing config:load:user Completed in 0ms
> 12 timing config:load:file:C:\Users\baggot4\AppData\Roaming\npm\etc\npmrc Completed in 0ms
> 13 timing config:load:global Completed in 0ms
> 14 timing config:load:cafile Completed in 0ms
> 15 timing config:load:validate Completed in 1ms
> 16 timing config:load:setUserAgent Completed in 0ms
> 17 timing config:load:setEnvs Completed in 1ms
> 18 timing config:load Completed in 7ms
> 19 verbose npm-session 4073c658eadecdbe
> 20 timing npm:load Completed in 16ms
> 21 timing command:run-script Completed in 39ms
> 22 verbose stack Error: command failed
> 22 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
> 22 verbose stack     at ChildProcess.emit (node:events:327:20)
> 22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
> 22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
> 23 verbose cwd C:\Users\baggot4\streetmerchant
> 24 verbose Windows_NT 10.0.18363
> 25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
> 26 verbose node v15.1.0
> 27 verbose npm  v7.0.8
> 28 error code 9009
> 29 error path C:\Users\baggot4\streetmerchant
> 30 error command failed
> 31 error command C:\WINDOWS\system32\cmd.exe /d /s /c "npm run compile && node build/src/index.js"
> 32 verbose exit 9009

**Comment by baggot4** [comment]
update just needed to get the correct version of node

**Comment by baggot4** [comment]
nvm still cant figure it out

**Comment by wofnull** [comment]
did you 
npm install 
once before trying 
npm run start

**Comment by alemmer** [comment]
It seems I am having the same problem as well, I've followed the instructions shown here: https://github.com/PeterPlatt/nvidia-snatcher and once i ran "npm run start" It flashed this error "npm ERR! missing script: start" here are the logs:

0 verbose cli [
0 verbose cli   'D:\\Node\\node.exe',
0 verbose cli   'D:\\Node\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@7.4.3
2 info using node@v15.7.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:D:\Node\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\Users\Alemm\OneDrive\Desktop\.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\Alemm\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\Alemm\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session e81b74b5a005db99
20 timing npm:load Completed in 10ms
21 timing command:run-script Completed in 1ms
22 verbose stack Error: missing script: start
22 verbose stack     at runScript (D:\Node\node_modules\npm\lib\run-script.js:54:11)
23 verbose cwd C:\Users\Alemm\OneDrive\Desktop
24 verbose Windows_NT 10.0.19042
25 verbose argv "D:\\Node\\node.exe" "D:\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
26 verbose node v15.7.0
27 verbose npm  v7.4.3
28 error missing script: start
29 verbose exit 1



and the json file in my npm folder



 {
  "version": "7.4.3",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "install",
    "modules",
    "package manager",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me)",
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/cli"
  },
  "bugs": {
    "url": "https://github.com/npm/cli/issues"
  },
  "directories": {
    "bin": "./bin",
    "doc": "./doc",
    "lib": "./lib",
    "man": "./man"
  },
  "main": "./lib/npm.js",
  "bin": {
    "npm": "bin/npm-cli.js",
    "npx": "bin/npx-cli.js"
  },
  "exports": {
    ".": [
      {
        "default": "./lib/npm.js"
      },
      "./lib/npm.js"
    ],
    "./package.json": "./package.json"
  },
  "dependencies": {
    "@npmcli/arborist": "^2.0.6",
    "@npmcli/ci-detect": "^1.2.0",
    "@npmcli/config": "^1.2.8",
    "@npmcli/run-script": "^1.8.1",
    "abbrev": "~1.1.1",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "aproba": "^2.0.0",
    "archy": "~1.0.0",
    "byte-size": "^7.0.0",
    "cacache": "^15.0.5",
    "chalk": "^4.1.0",
    "chownr": "^2.0.0",
    "cli-columns": "^3.1.2",
    "cli-table3": "^0.6.0",
    "columnify": "~1.5.4",
    "glob": "^7.1.4",
    "graceful-fs": "^4.2.3",
    "hosted-git-info": "^3.0.6",
    "ini": "^2.0.0",
    "init-package-json": "^2.0.1",
    "is-cidr": "^4.0.2",
    "leven": "^3.1.0",
    "libnpmaccess": "^4.0.1",
    "libnpmfund": "^1.0.2",
    "libnpmhook": "^6.0.1",
    "libnpmorg": "^2.0.1",
    "libnpmpack": "^2.0.0",
    "libnpmpublish": "^4.0.0",
    "libnpmsearch": "^3.1.0",
    "libnpmteam": "^2.0.2",
    "libnpmversion": "^1.0.7",
    "make-fetch-happen": "^8.0.13",
    "minipass": "^3.1.3",
    "minipass-pipeline": "^1.2.4",
    "mkdirp": "^1.0.4",
    "mkdirp-infer-owner": "^2.0.0",
    "ms": "^2.1.2",
    "node-gyp": "^7.1.2",
    "nopt": "^5.0.0",
    "npm-audit-report": "^2.1.4",
    "npm-package-arg": "^8.1.0",
    "npm-pick-manifest": "^6.1.0",
    "npm-profile": "^5.0.2",
    "npm-registry-fetch": "^9.0.0",
    "npm-user-validate": "^1.0.1",
    "npmlog": "~4.1.2",
    "opener": "^1.5.2",
    "pacote": "^11.2.3",
    "parse-conflict-json": "^1.1.1",
    "qrcode-terminal": "^0.12.0",
    "read": "~1.0.7",
    "read-package-json": "^3.0.0",
    "read-package-json-fast": "^1.2.1",
    "readdir-scoped-modules": "^1.1.0",
    "rimraf": "^3.0.2",
    "semver": "^7.3.4",
    "ssri": "^8.0.0",
    "tar": "^6.1.0",
    "text-table": "~0.2.0",
    "tiny-relative-date": "^1.3.0",
    "treeverse": "^1.0.4",
    "uuid": "^8.3.1",
    "validate-npm-package-name": "~3.0.0",
    "which": "^2.0.2",
    "write-file-atomic": "^3.0.3"
  },
  "bundleDependencies": [
    "@npmcli/arborist",
    "@npmcli/ci-detect",
    "@npmcli/config",

I am in no means an expert just a novice trying to get himself a graphics card, I would very much appreciate the help
,Thank you!

**Comment by wofnull** [comment]
First of all, the used instructions are from a repo which is way over 600 commits behind.

Please use this repo here ( its the origin one ) and the instructions provided here and on https://jef.codes/streetmerchant/

1.) download the Repo
2.) install at least nodejs 15 ( if not already )
3.) go with commandline into the repo folder and run:
npm install
4.) in the same folder on commandline:
npm run start

The script should be running without issues. If this works, go ahead and make a copy of the dotenv-example file and name the copy dotenv, change the settings as needed in there  ( corresponding to the documentation and / refference on https://jef.codes/streetmerchant/getting-started/  )

**Comment by alemmer** [comment]
This worked out perfectly, thank you very much sir!!!

**Comment by baggot4** [comment]
> First of all, the used instructions are from a repo which is way over 600 commits behind.
> 
> Please use this repo here ( its the origin one ) and the instructions provided here and on https://jef.codes/streetmerchant/
> 
> 1.) download the Repo
> 2.) install at least nodejs 15 ( if not already )
> 3.) go with commandline into the repo folder and run:
> npm install
> 4.) in the same folder on commandline:
> npm run start
> 
> The script should be running without issues. If this works, go ahead and make a copy of the dotenv-example file and name the copy dotenv, change the settings as needed in there ( corresponding to the documentation and / refference on https://jef.codes/streetmerchant/getting-started/ )

I tried that and this is what Happens

`baggot4@TodsPC MINGW64 ~/documents/JSBOT/streetmerchant (main)
$ npm run start

> start
> npm run compile && node build/src/index.js

'npm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\baggot4\documents\JSBOT\streetmerchant
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run compile && node build/src/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\baggot4\AppData\Local\npm-cache\_logs\2021-02-04T19_50_00_103Z-debug.log
`

**Comment by wofnull** [comment]
'npm' is not recognized as an internal or external command,

Looks like your nodejs installation is somehow broken. Please uninstall NodeJS and install only the version 15 of nodejs
