### ISSUE TITLE
amazon captcha

### ISSUE THREAD

**Issue by rickjaruiz** [jef/streetmerchant#1837]
## Expected Behavior

show status

## Current Behavior

shows CAPTCHA

## Steps to Reproduce

add amazon to the list of stores

## Environment

windows 10 pro 

```AUTO_ADD_TO_CART=true
LOW_BANDWIDTH=true
MAX_PRICE_SERIES_3060TI=440
MAX_PRICE_SERIES_3070=550
MAX_PRICE_SERIES_3080=770
PLAY_SOUND=Alarm01.wav
SHOW_ONLY_SERIES=3060ti,3070,3080
STORES=amazon,bestbuy,newegg,pny,microcenter,target,walmart
```

## Logs

[3:52:51 PM] warn :: ✖ [amazon] [asus (3060ti)] dual :: CAPTCHA

**Comment by DeeJayhX** [comment]
@rickjaruiz why did you close this issue? It still exists. If you found a resolution, you should put it in a comment here...
