### ISSUE TITLE
MAX_PRICE_SERIES_3080 doesn't work for a used card listing on Amazon CA

### ISSUE THREAD

**Issue by ryanqyao** [jef/streetmerchant#1846]
## Expected Behavior

I set the MAX_PRICE_SERIES_3080 to 1300, so it shouldn't notify me for a used 3080 that sells for $1984 on Amazon CA.

## Current Behavior

It notifies me of this listing https://www.amazon.ca/dp/B08HR3DPGW every minute 
![CleanShot 2021-01-31 at 19 57 11@2x](https://user-images.githubusercontent.com/72620073/106413582-488de080-63ff-11eb-9861-5b3ee2a39594.jpg)

## Steps to Reproduce

I just followed the doc to install it on my VPS. 

## Environment

- OS: Ubuntu

```
MAX_PRICE_SERIES_3070=900
MAX_PRICE_SERIES_3080=1300
MAX_PRICE_SERIES_RX6800XT=1000
MAX_PRICE_SERIES_SONYPS5C=610
MAX_PRICE_SERIES_SONYPS5DE=510
MAX_PRICE_SERIES_XBOXSS=610
MAX_PRICE_SERIES_XBOXSX=510
SHOW_ONLY_MODELS=ftw3,ftw3 black,ftw3 ultra,gaming x trio,vision oc,strix,strix oc,strix white,tuf oc
SHOW_ONLY_SERIES=3080,sonyps5c,sonyps5de,xboxss,xboxsx,rx6800xt
STORES=amazon-ca,amazon,amd,amd-ca,bandh,bestbuy,bestbuy-ca,gamestop,memoryexpress,microcenter,walmart,target,canadacomputers
TELEGRAM_ACCESS_TOKEN=TOKEN HERE
TELEGRAM_CHAT_ID=ID HERE
```

**Comment by SpazShark** [comment]
I experienced the exact same issue with the exact same issue last night. I had a max price set for $1500. Have since disabled searching for the 3080.

**Comment by wofnull** [comment]
a patch is underway ;)
