### ISSUE TITLE
Newegg: Many False Positives for 5800X

### ISSUE THREAD

**Issue by KosherBacon** [jef/streetmerchant#1847]
## Expected Behavior

Doesn't notify for out of stock items.

## Current Behavior

Notifies out of stock items, so far only the 5800X.

When loading the item's page manually, there's an auto-notify button that appears first where the add-to-cart button normally appears, and it eventually disappears after the page loads more. I wonder if the script needs to let the page load a bit more?

<img width="746" alt="notify" src="https://user-images.githubusercontent.com/1435642/106419424-4f235480-640d-11eb-9112-1b82afcb782b.png">

## Steps to Reproduce

1. Filter to only newegg and 5800x
2. Run and wait
3. Script will log item is in-stock and open a new tab after trying to add to cart

## Environment

- OS: Windows 10

```dotenv
SHOW_ONLY_SERIES=ryzen5800
STORES=newegg
```

## Logs

```
[9:39:53 PM] info :: 🚀🚨 [newegg] [amd (ryzen5800)] 5800x :: IN STOCK 🚨🚀
https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16819113665
```

**Comment by leroydev** [comment]
> I wonder if the script needs to let the page load a bit more?

To try out of that's the problem, you can try adding the following to `newegg.ts`:
```waitUntil: 'networkidle0'```
Or
```waitUntil: 'networkidle2'```

Explanation about the two: https://github.com/puppeteer/puppeteer/issues/1552#issuecomment-350954419

**Comment by ajaybhullar** [comment]
it is worth noting that newegg has moved to a raffle system to buy these items, so you can only purchase them once you have passed the raffle, look up newegg product-shuffle
