### ISSUE TITLE
Amazon-it CAPTCHA for ever

### ISSUE THREAD

**Issue by totovic** [jef/streetmerchant#1873]
hello,
there is a problem with amazon-it, captcha error for ever...
please, how to fix the issue?

thanks

**Comment by razor992fg** [comment]
Usa una vpn

**Comment by RcrossF** [comment]
@razor992fg I get the same problem in Canada with amazon-ca so there is likely some amazon anti-spam going on

**Comment by razor992fg** [comment]
I got this problem and i tried to connect by NordVPN and i never get captcha

**Comment by Dracozny** [comment]
Did you follow https://jef.codes/streetmerchant/help/troubleshoot/ ?
once running in Headfull you should be able to solve the captcha. Most of the time it should not reoccur during the rest of the session. 
protip: drag that tab to it's own window so the other tabs appearing do not interrupt you. it can be closed after the redirect.

**Comment by VNnaD** [comment]
@Dracozny i`m a litle noob with this things and i dont know how to use that fix from your link , you can help me please with some tutorial or something ?

**Comment by Dracozny** [comment]
Edit your dotenv file
```
HEADLESS="false"
PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"
```
Puppeteer_executable_path will be wherever chrome-stable is. in this case in Ubuntu Studio 2.10. If your running Windows. it's likely ```C:\Program Files (x86)\Google\Application\chrome.exe```

**Comment by VNnaD** [comment]
> Edit your dotenv file
> 
> ```
> HEADLESS="false"
> PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"
> ```
> 
> Puppeteer_executable_path will be wherever chrome-stable is. in this case in Ubuntu Studio 2.10. If your running Windows, it's likely `C:\Program Files (x86)\Google\Application\chrome.exe`
I edited dotenv with that 2 lines but i think need to do someting else becouse i recive this error :
 Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable
