### ISSUE TITLE
"Amazon IT" I've added 3 3060Ti to the Italian Amazon Store

### ISSUE THREAD

**Issue by eliasasl** [jef/streetmerchant#1894]
Not much to say actually.

For italians that would like to use this amazing software to search any 3060Ti but never really found one,I've modified the "store/model/amazon-it" file and added 3 3060Ti, all categorized with the keyword used to feed the bot. 

e.g.: "vision oc", "gaming x trio" and so on.

[amazon-it.txt](https://github.com/jef/streetmerchant/files/5932993/amazon-it.txt)

Further on I will certainly add whatever 3060Ti GPU I will find.

Hope this helps.

Thank you.

**Comment by wofnull** [comment]
you should open up a fork then and update a separate branch there, so that @jef is able to merge your changes into the project ;)
