### ISSUE TITLE
[Feature Request] Per store sleep time

### ISSUE THREAD

**Issue by defaultsecurity** [jef/streetmerchant#1899]
Per store sleep time would be very helpful. Per page sleep time can still get you banned, if multiple items are queried from the same website.

**Comment by wofnull** [comment]
the feature you are asking for is already implemented for a long time:
in dotenv file line for STORES

for example:
STORES=alternate:10000:30000, amazon-de:250000:30000
Would set the page timeout for alternate to 10000ms (10 seconds ) and the page nav wait time to 30000ms ( 30 seconds )
and for amazon-de it would take the timeout for the amazon-de store to 250000ms ( 250 seconds / 4 minutes and 10 seconds ) and the nav wait time to 30000ms ( 30 seconds )

**Comment by YoBii** [comment]
@wofnull so the documentation is not up to date?

**Comment by defaultsecurity** [comment]
@wofnull 
Thanks for the info, but I tried those parameters beforehand. @YoBii is right. Those are indeed **per page sleep times, not per store sleep times**. The stores get bombarded with queries regardless of those parameters.

**Comment by OptimalMising** [comment]
If I'm following, you're essentially asking to be able to set a rate at which links within a store are checked.

In streetmerchant today you can set a sleep timer for a store to say only check amazon every 5 minutes.  However if your amazon store has 10 links in the store model, that would mean every 5 minutes its going to ping amazon 10 times, every 4 odd seconds as it loops through those 10 products (which could just as easily result in a ban for some stores).

So you'd want to be able to specify something like this in the dotenv:  Amazon:300000:300000:15000 so it would check amazon every 5 minutes but only check each link within amazon every 15 seconds.

**Comment by defaultsecurity** [comment]
@OptimalMising 

> If I'm following, you're essentially asking to be able to set a rate at which links within a store are checked.

Yes, essentially.

> In streetmerchant today you can set a sleep timer for a store to say only check amazon every 5 minutes. However if your amazon store has 10 links in the store model, that would mean every 5 minutes its going to ping amazon 10 times, every 4 odd seconds as it loops through those 10 products (which could just as easily result in a ban for some stores).

Yes, that is the problem exactly.

> So you'd want to be able to specify something like this in the dotenv: Amazon:300000:300000:15000 so it would check amazon every 5 minutes but only check each link within amazon every 15 seconds.

That is a possible way to go. I rather envisioned, that a STORE_SLEEP_MIN/MAX would completely override PAGE_SLEEP_MIN/MAX. Thus when set, products belonging to the same store would have the store sleep time between them, regardless of the page sleep time setting. The per store setting could look like _dotenv: Amazon!30000_ perhaps. 

**In any case, both our solutions would solve the ban problem and make streetmerchant safer.**
