### ISSUE TITLE
Asus store reports in stock cards but no stock is shown in browser.

### ISSUE THREAD

**Issue by LFAdams** [jef/streetmerchant#1901]
## Expected Behavior

The program should not report in-stock from the asus store when none are available.

## Current Behavior

the program constantly reports in-stock cards from the asus store, including pictures showing an add to cart button. When I click the link to go to the site there are none available. This happens every couple of minutes per card such that I get a constant stream of in stock notifications for asus, so i know im not just missing the stock by being slow.

## Steps to Reproduce

Install streetmerchant via dock container on unraid
include asus in STORES variable
Set notifications to use a gmail account
Receive endless in stock notifications for asus cards.
## Environment

- OS:
Unraid

```dotenv
```

**Comment by bakamano** [comment]
also running into same issue

**Comment by zkghost** [comment]
the pages show "add to cart" for a moment and then it reverts to "unavailable" or something, it's probably a cheap anti bot measure. Or rather makes the bot too spammy. i'd have to look at the code to see how easy this would be, but we need to essentially sleep for a few seconds and then check the state

**Comment by PacketShepard** [comment]
Same issue here. I've disabled Asus stores for a few weeks now.

**Comment by MuhsinunC** [comment]
Yup same issue here. @zkghost yes that is the issue. Any updates?

**Comment by Fmstrat** [comment]
Checking on an update as well, running into this, too.

**Comment by Fmstrat** [comment]
I think we need a delay option in the store `ts` that pulls through to `lookup.ts`. This way the anti-bot measure is thwarted. I thought at first this had something to do with the coming soon language, but that doesn't seem to be the case.

**Comment by Fmstrat** [comment]
Anyone here willing to test this out, please let me know how it worked.

**Comment by Fmstrat** [comment]
So this was tested and did not work. I'm wondering if somehow it is because the Asus config is out date. I'm seeing a number of cards who's model numbers have changed. I'm working through a PR on that and will see if it has any impact.

**Comment by Fmstrat** [comment]
Well, that seems to be it. The above change worked for me (for 3080 searches). The 3060s are not up on their site at the moment, so ymmv there.
