### ISSUE TITLE
UK store Very stuck on running links builder

### ISSUE THREAD

**Issue by melonpye** [jef/streetmerchant#1912]
## Environment

- OS:

```dotenv
```

**Comment by melonpye** [comment]
all other stores I'm using is working fine but very is not working if you could possible take a look and see if its just me or a wider problem it would be greatly appreciated

**Comment by mrkwse** [comment]
What item are you trying to track @melonpye?

**Comment by Lewis-Bright** [comment]
same here, items are: `SHOW_ONLY_SERIES=3060ti,sonyps5de,sonyps5c`

**Comment by lozbinks** [comment]
Might be because Very's product pages for the ps5's don't go live until they are ready to put the products live
