### ISSUE TITLE
Graphics Card Price Limit is Ignored on Amazon Intermittently

### ISSUE THREAD

**Issue by PacketShepard** [jef/streetmerchant#1919]
## Expected Behavior

Price limits should apply to Amazon graphics cards. The price should show in the Discord alert.

## Current Behavior

Amazon resellers trigger a stock alert because the price limit is often ignored on RTX 3080 and 3090

## Steps to Reproduce

Set a $1100 price limit on the 3080 and a $1980 price limit on the 3090. Enable amazon store. When it reaches the ASUS RTX 3090 Strix OC, 5 out of 10 times the alert will fire even though the lowest price is $2,749.00. See examples and time stamps below.

## Environment

- OS:

```
AUTO_ADD_TO_CART=false
DESKTOP_NOTIFICATIONS=false
DISCORD_NOTIFY_GROUP_3070=<@&800xxxxx>
DISCORD_NOTIFY_GROUP_3080=<@&800xxxxx>
DISCORD_NOTIFY_GROUP_3090=<@&800xxxxx>
DISCORD_NOTIFY_GROUP_RYZEN5900=<@&800xxxxxx>
DISCORD_WEB_HOOK=https://discord.com/api/webhooks/xxxxxxx
MAX_PRICE_SERIES_3080=1150
MAX_PRICE_SERIES_3090=1980
MAX_PRICE_SERIES_RX6800XT=900
MAX_PRICE_SERIES_RYZEN5900=601
MICROCENTER_LOCATION=xxxx
OPEN_BROWSER=false
SCREENSHOT=false
SHOW_ONLY_BRANDS=asus,evga,gigabyte,msi,nvidia,amd
SHOW_ONLY_SERIES=3080,3090
STORES=bestbuy,newegg,bandh,adorama,officedepot,target,walmart,amazon
```

## Logs

**Not working:**

[10:58:47 AM] info :: ��🚨🚨 [304/466] [amazon] [asus (3090)] strix oc :: IN STOK
https://www.amazon.com/dp/B08J6GMWCQ
[10:58:47 AM] info :: ✔ desktop notification sent
[10:58:47 AM] info :: ✔ discord message sent

**Working:**

[10:54:52 AM] info :: ✖ [113/466] [newegg] [asus (3080)] tuf :: OUT OF STOCK
[10:54:54 AM] info :: ✖ [284/466] [amazon] [asus (3090)] strix oc :: PRICE 2749 EXCEEDS LIMIT 1980
[10:54:55 AM] info :: ✖ [1/1] [bestbuy] [evga (3080)] ftw3 ultra :: OUT OF STOCK

**Comment by csoyuncu** [comment]
i live same problem... i hope this fix by developer
