### ISSUE TITLE
RU stores(403 and RATE LIMIT)

### ISSUE THREAD

**Issue by vadimka04** [jef/streetmerchant#1925]
P.S. Sorry for my english.-. trying not used translate
1. 403
Stores https://www.eldorado.ru/cat/detail/igrovaya-pristavka-playstation-5-digital-edition/ and https://www.mvideo.ru/products/igrovaya-konsol-sony-playstation-5-digital-edition-40074203
if u try refresh(F5) with time, store show u that
![image](https://user-images.githubusercontent.com/12530745/107514775-2ba19c00-6bbb-11eb-950c-14d5222d3796.png)
streetmerchant show that:
![image](https://user-images.githubusercontent.com/12530745/107514825-3ceaa880-6bbb-11eb-91f9-affab4128654.png)
![image](https://user-images.githubusercontent.com/12530745/107514842-42e08980-6bbb-11eb-9f3f-155d314a30d1.png)
It's not ban but technical support say "all normal it's not store problem"
and someone ask about that here https://stackoverflow.com/questions/66054190/python-parser-access-to-resource-was-blocked
decision
![image](https://user-images.githubusercontent.com/12530745/107848310-80cfee80-6e03-11eb-9b13-79f4b4626a56.png)
![image](https://user-images.githubusercontent.com/12530745/107848370-ed4aed80-6e03-11eb-84fc-b750b2f17ff0.png)

https://www.cyberforum.ru/powershell/thread2777644.html
2. RATE LIMIT
Store: https://www.citilink.ru/catalog/for_gamers/games_consoles/consoles/1438620/
after n time i see that on site
![image](https://user-images.githubusercontent.com/12530745/107515649-5dffc900-6bbc-11eb-8b12-015c876922bb.png)
and that streetmerchant:
![image](https://user-images.githubusercontent.com/12530745/107515685-66f09a80-6bbc-11eb-9119-1649ecae7401.png)
this is captcha but it's not work, streetmerchant doesn't detect that how captcha (p.s. captcha not work for example u can write any words in line and all be fixed but maybe streetmerchant can auto click?)

**Comment by vadimka04** [comment]
up

**Comment by AlexP11223** [comment]
> captcha not work for example u can write any words in line and all be fixed but maybe streetmerchant can auto click?

This was added recently: https://www.jef.buzz/streetmerchant/reference/captcha/ (see https://github.com/jef/streetmerchant/issues/2430#issuecomment-826148757 for store config example).
But currently it can only send the image to Discord or Slack.
Hopefully other methods of handling capthas will be added in the future, including the one you need.

**Comment by klords** [comment]
I have a PR in progress that should enable this captcha scenario.

**Comment by klords** [comment]
@vadimka04 is the 403 happening immediately every time or does it only happen after checking the page a few times first? Are you using proxies?
