### ISSUE TITLE
Caseking-DE RTX 3060 ti is incorrectly reported as being in stock

### ISSUE THREAD

**Issue by schoppfe** [jef/streetmerchant#1929]
## Expected Behavior

Caseking-DE RTX 3060 ti should be reported as out of stock

## Current Behavior

Caseking-DE RTX 3060 ti is incorrectly reported as being in stock

## source code

```
<span class="delivery_container">
<div class="status4">&nbsp;</div>
<p class="deliverable4">
<span class="frontend_plugins_index_delivery_informations">archiviert</span>
```
[https://www.caseking.de/msi-geforce-rtx-3060-ti-ventus-2x-oc-8192-mb-gddr6-gcmc-246.html](url)
![grafik](https://user-images.githubusercontent.com/37182137/107576963-26137880-6bf2-11eb-9b2a-dda6eacb9360.png)

**Comment by MZerbe** [comment]
Same here.

**Comment by YoBii** [comment]
It's due to the status being `archiviert`. Go to the store file and do this
```
    outOfStock: {
      container: '.delivery_container',
      text: ['unbekannt', 'archiviert'],
    },
```
