### ISSUE TITLE
server-side request forgery vulnerability

### ISSUE THREAD

**Issue by Crypto-Cowboy** [jef/streetmerchant#1941]
After running "npm install" I got a notification of a server-side request forgery vulnerability. I tried to fix it and it was not resolved. I have pasted the info from command prompt below. Is this something I should worry about and if so how do I fix it?

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

C:\streetmerchant>npm audit fix
npm WARN twilio@3.55.1 requires a peer of @types/express@^4.17.7 but none is installed. You must install peer dependencies yourself.
npm WARN twilio@3.55.1 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 4.004s

131 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 1194 scanned packages
  1 vulnerability required manual review and could not be updated

**Comment by JellyLama** [comment]
me too

**Comment by sadokx** [comment]
Same!
![image](https://user-images.githubusercontent.com/12555077/107891472-82bdae80-6ee4-11eb-8c8e-f7e42f12866d.png)

**Comment by hypercoyote** [comment]
The issue is the that the package @bridgerakol/samsung-smart-api specifies axios version 0.19.2 as a dependency, so no matter what it installs that.  You can fix this by creating a shrinkwrap file to override the dependency:

1. In the StreetMerchants folder you created when you did the git clone, create a file called npm-shrinkwrap.json and insert the following into it:
`{
  "lockfileVersion": 1,
  "dependencies": {
    "@bridgerakol/samsung-smart-api": {
      "version": "2.8.1",
      "resolved": "https://registry.npmjs.org/@bridgerakol/samsung-smart-api/-/samsung-smart-api-2.8.1.tgz",
      "integrity": "sha512-Ue7o8GT/ph00kejX3h8w6kVh2LuRmIpLyhwZ8d0eJGcCNmn4mKGXJWZO5iMq8j1iqGozsmIa50lj79ZkDxTIRw==",
      "requires": {
        "axios": "^0.19.2"
      },
      "dependencies": {
        "axios": {
          "version": "0.21.1",
          "resolved": "https://registry.npmjs.org/axios/-/axios-0.21.1.tgz",
          "integrity": "sha512-dKQiRHxGD9PPRIUNIWvZhPTPpl1rf/OxTYKsqKUDjBwYylTvV7SjSHJb9ratfyzM6wCdLCOYLzs73qpg5c4iGA==",
          "requires": {
            "follow-redirects": "^1.10.0"
          }
        }
      }
    }
  }
}
`
2. Run `npm install` and it should install the fixed version of axios and no longer report the vulnerability.  

If you already ran `npm install` once, that should be fine, as this should update the axios version for you and report 0 vulnerabilities when it finishes.

**Comment by JellyLama** [comment]
> The issue is the that the package @bridgerakol/samsung-smart-api specifies axios version 0.19.2 as a dependency, so no matter what it installs that. You can fix this by creating a shrinkwrap file to override the dependency:
> 
> 1. In the StreetMerchants folder you created when you did the git clone, create a file called `npm-shrinkwrap.json` and insert the following into it:
> 
> ```
> {
>   "lockfileVersion": 1,
>   "dependencies": {
>     "@bridgerakol/samsung-smart-api": {
>       "version": "2.8.1",
>       "resolved": "https://registry.npmjs.org/@bridgerakol/samsung-smart-api/-/samsung-smart-api-2.8.1.tgz",
>       "integrity": "sha512-Ue7o8GT/ph00kejX3h8w6kVh2LuRmIpLyhwZ8d0eJGcCNmn4mKGXJWZO5iMq8j1iqGozsmIa50lj79ZkDxTIRw==",
>       "requires": {
>         "axios": "^0.19.2"
>       },
>       "dependencies": {
>         "axios": {
>           "version": "0.21.1",
>           "resolved": "https://registry.npmjs.org/axios/-/axios-0.21.1.tgz",
>           "integrity": "sha512-dKQiRHxGD9PPRIUNIWvZhPTPpl1rf/OxTYKsqKUDjBwYylTvV7SjSHJb9ratfyzM6wCdLCOYLzs73qpg5c4iGA==",
>           "requires": {
>             "follow-redirects": "^1.10.0"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> 1. Run `npm install` and it should install the fixed version of axios and no longer report the vulnerability.
> 
> If you already ran `npm install` once, just run it again after adding the file above and it should update the axios version for you and report 0 vulnerabilities when it finishes.

it say this during the installation
![image](https://user-images.githubusercontent.com/56936481/109342348-058f2380-786c-11eb-8693-744421ac1bc4.png)

**Comment by hypercoyote** [comment]
> 
> 
> > The issue is the that the package @bridgerakol/samsung-smart-api specifies axios version 0.19.2 as a dependency, so no matter what it installs that. You can fix this by creating a shrinkwrap file to override the dependency:
> > 
> > 1. In the StreetMerchants folder you created when you did the git clone, create a file called `npm-shrinkwrap.json` and insert the following into it:
> > 
> > ```
> > {
> >   "lockfileVersion": 1,
> >   "dependencies": {
> >     "@bridgerakol/samsung-smart-api": {
> >       "version": "2.8.1",
> >       "resolved": "https://registry.npmjs.org/@bridgerakol/samsung-smart-api/-/samsung-smart-api-2.8.1.tgz",
> >       "integrity": "sha512-Ue7o8GT/ph00kejX3h8w6kVh2LuRmIpLyhwZ8d0eJGcCNmn4mKGXJWZO5iMq8j1iqGozsmIa50lj79ZkDxTIRw==",
> >       "requires": {
> >         "axios": "^0.19.2"
> >       },
> >       "dependencies": {
> >         "axios": {
> >           "version": "0.21.1",
> >           "resolved": "https://registry.npmjs.org/axios/-/axios-0.21.1.tgz",
> >           "integrity": "sha512-dKQiRHxGD9PPRIUNIWvZhPTPpl1rf/OxTYKsqKUDjBwYylTvV7SjSHJb9ratfyzM6wCdLCOYLzs73qpg5c4iGA==",
> >           "requires": {
> >             "follow-redirects": "^1.10.0"
> >           }
> >         }
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > 
> > 1. Run `npm install` and it should install the fixed version of axios and no longer report the vulnerability.
> > 
> > If you already ran `npm install` once, just run it again after adding the file above and it should update the axios version for you and report 0 vulnerabilities when it finishes.
> 
> it says this during the installation
> ![image](https://user-images.githubusercontent.com/56936481/109342348-058f2380-786c-11eb-8693-744421ac1bc4.png)

I believe that is fine.  It's just complaining that the shrinkwrap file is from an older version.  Looks like it ran fine to me.  I literally just figured this out and knew nothing about npm prior to this, so I really dunno more than I provided.

**Comment by JellyLama** [comment]
Ok thx

Il Ven 26 Feb 2021, 19:58 hypercoyote <notifications@github.com> ha scritto:

**Comment by jef** [comment]
I'm currently replacing this dependencies with using `node-fetch` instead. Can I have someone test this implementation out? I don't have smartthings.

**Comment by jef** [comment]
I have this PR up, but don't want to merge in until someone can verify if smartthings works.

https://github.com/jef/streetmerchant/pull/2182

**Comment by richintheveins** [comment]
Excuse my ignorance but how do you add a folder in the file. I went into my c drive opened streetmerchant, created a folder, and then named it the shrinkwrap.json, and then added a notepad with the script. I then received this error. 

![image](https://user-images.githubusercontent.com/82544744/114779895-466bca80-9d3c-11eb-8d66-1f84e0386117.png)

**Comment by richintheveins** [comment]
Nvmd I figured out my mistake. lol

**Comment by jef** [comment]
Does anyone here have smart-things? I'd like to test my PR so we can get rid of that module.
