### ISSUE TITLE
"npm i" results in warnings, "npm run start" fails

### ISSUE THREAD

**Issue by swpalmer** [jef/streetmerchant#1996]
## Expected Behavior

Following the instructions to build and run should work.

## Current Behavior

Warning about security vulnerabilities.  Running anyway fails:

## Steps to Reproduce

checkout the repo, cd into the checkout folder...
npm i
npm run start

## Environment

- OS: Windows 10 64-bit

## Logs

>npm i

up to date, audited 1174 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

>npm audit
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/@bridgerakol/samsung-smart-api/node_modules/axios
  @bridgerakol/samsung-smart-api  *
  Depends on vulnerable versions of axios
  node_modules/@bridgerakol/samsung-smart-api

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

>npm run start

> start
> npm run compile && node build/src/index.js

> compile
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.4.1

[7:25:06 p.m.] info :: ℹ selected stores: amazon, bestbuy
[7:25:06 p.m.] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sf, sonyps5c, sonyps5de, xboxss, xboxsx
[7:25:07 p.m.] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005). {
  "stack": "Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).\n    at ChromeLauncher.launch (C:\\dev\\opensource\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:80:27)\n    at async main (C:\\dev\\opensource\\streetmerchant\\build\\src\\index.js:72:15)\n    at async loopMain (C:\\dev\\opensource\\streetmerchant\\build\\src\\index.js:109:9)"
}

**Comment by andreadeluca** [comment]
You should try to install manually pupeteer, that worked for me: 
`node node_modules/puppeteer/install.js`
