### ISSUE TITLE
Didn't search for 3070 / 3080 on several websites / Shops

### ISSUE THREAD

**Issue by encravado** [jef/streetmerchant#2022]
Hello,

the bot didn't search for any RTX 3070 or 3080 on these several stores:

amazon-de-warehouse
euronics-de
expert
galaxus
gamestop-de
mediamarkt
medimax
otto
saturn
spielegrotte 

All other stores work, can anyone help?

This is my store config:
STORES=acompc,alternate,amazon-de,amazon-de-warehouse,arlt,asus-de,caseking,computeruniverse,cyberport,euronics-de,equippr,evga-eu,expert,futurex,galaxus,gamestop-de,mediamarkt,medimax,mindfactory,notebooksbilliger,nvidia-de,otto,pcking,proshop-de,saturn,spielegrotte

**Comment by laxness** [comment]
I have same problem i cant change stores to only amazon . The program still searching on amazon,bestbuy

![aaaaa](https://user-images.githubusercontent.com/79538754/109058802-7c091580-76f4-11eb-9afa-ec5336b1a4ec.png)

**Comment by DA-NDI** [comment]
You need to put list of stores, list of series, any other parameter in the quotes. Like that: STORES="amazon, bestbuy"
