### ISSUE TITLE
Failed to add products from Best buy with their new system

### ISSUE THREAD

**Issue by CyriouslyDylan** [jef/streetmerchant#2030]
## Expected Behavior

Products get added to cart

## Current Behavior

Best Buy has a new system where you have to click on the add to cart on the product page, and then wait on that page for the link to re-set to "add to cart" instead of "waiting for inventory". The current system also opens the cart page which will be empty, with no way to go back to the product page.

## Steps to Reproduce

Not sure how to reproduce without BB dropping more product.

## Suggested Solution

For Best Buy, have it open the product page after clicking add to cart, and keep attempting to add to cart for when the button switches. Also, if the text message could include the product link and not just the cart link that would be helpful.

**Comment by Dracozny** [comment]
That's if your button ever changes. site doesn't work correctly unless I am at my home PC. the button will just tell me to keep waiting indefinitely. the best case scenario is you are near your PC when you get the alert, and often times you'll still be too late.

**Comment by CyriouslyDylan** [comment]
A possible solution for this would be for BB, change it from taking you directly to your cart to taking you to the product page.

**Comment by Dracozny** [comment]
It takes you to the product page but it will be for the wrong location and
then ping you non-stop about it until that location sells out. My
workaround was to make sure headless is off and deliberately go to the
website and set my location. that way everytime the bot tries it will use
the last known store location based on session info. The downside is, what
if I have two locations I am willing to drive to...
