### ISSUE TITLE
Docker Image: Notification Test Doesn't Work

### ISSUE THREAD

**Issue by bdc2000** [jef/streetmerchant#2032]
## Expected Behavior

Notification Test Should Occur

## Current Behavior

Error: Cannot find module '/app/build/test/functional/test-notification.js'

## Steps to Reproduce

docker run -it --rm --env-file ./dotenv ghcr.io/jef/streetmerchant:nightly test:notification:production

## Proposed Fix

Add the following line to the Dockerfile:

`COPY test/ test/`

before `RUN npm run compile`

**Comment by aaronrunkle** [comment]
Can confirm!
