### ISSUE TITLE
Price notification problem

### ISSUE THREAD

**Issue by dasert3** [jef/streetmerchant#2042]
## Expected Behavior

report only the scehde with price up to the one set
## Current Behavior

when there is the possibility of financing as in amazon.es even if the limit is set at € 1000 it signals all the cards, even if it is from 2000 € 
## Steps to Reproduce

This is a photo of the "https://ibb.co/ThChGVS" report, the price was set at 850 €. 
Can I also set a minimum price to solve this problem?

## Environment

- OS:Windows

```ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART=""
BROWSER_TRUSTED=""
COUNTRY=""
DESKTOP_NOTIFICATIONS="true"
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS="false"
IN_STOCK_WAIT_TIME="5"
LOG_LEVEL=""
LOW_BANDWIDTH=""
MAX_PRICE_SERIES_3060ti="750"
MAX_PRICE_SERIES_3070="850"
MAX_PRICE_SERIES_3080="1200"
MAX_PRICE_SERIES_3090="1500"
MAX_PRICE_SERIES_RX6800="700"
MAX_PRICE_SERIES_RX6800XT="850"
MAX_PRICE_SERIES_RX6900XT="1100"
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_CORSAIR_SF=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN="8000"
PAGE_SLEEP_MAX="25000"
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUPPETEER_EXECUTABLE_PATH=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
RESTART_TIME=""
SCREENSHOT=""
SHOW_ONLY_BRANDS="sony,evga,kfa2,inno3d,asus,gigabyte,msi,palit,pny,zotac"
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES="3060ti,3070,3080"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="amazon-fr,amazon-it,amazon-es,amazon-uk,amazon-de"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""
```

**Comment by csoyuncu** [comment]
i live same problem... i access max 1000 but it shows me 20000 price cards!

example;
https://www.amazon.com.tr/Gigabyte-AORUS-GeForce-Master-ekran/dp/B08LNY8P5L/ref=sr_1_1?__mk_tr_TR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&tag=web-desktop-forum-21&ie=UTF8&language=tr_TR


but my limit 1000 in dotenv

**Comment by sokill76** [comment]
hello my friend, did you figure out how to freeze the prices? hello friend, you have

**Comment by jef** [comment]
Seems like this (#2153) should fix. Please test and let me know!

**Comment by sokill76** [comment]
Tkx you I test

Cordialement

________________________________

**Comment by maltemosler** [comment]
still not working.

![image](https://user-images.githubusercontent.com/20888573/111433749-f975e380-86fe-11eb-9047-7b29156c7c8c.png)

![image](https://user-images.githubusercontent.com/20888573/111433767-fed32e00-86fe-11eb-920d-ac6c16a91bbb.png)

dotenv:

MAX_PRICE_SERIES_3060=499
MAX_PRICE_SERIES_3060TI=599
MAX_PRICE_SERIES_3070=699
MAX_PRICE_SERIES_3080=999
MAX_PRICE_SERIES_3090=1500
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=699
MAX_PRICE_SERIES_RX6800XT=849
MAX_PRICE_SERIES_RX6900XT=999

**Comment by sokill76** [comment]
Great 😘😘😘 fix with '' 0.9'' for 900€

Cordialement

________________________________

**Comment by sokill76** [comment]
[Image]


Cordialement
________________________________

**Comment by jef** [comment]
Alright, I'm reverting these changes and going back to what we were doing originally until we can fully vet a different option. It's not that much overhead to go back to what we originally were doing.

Thank you.

**Comment by jef** [comment]
Reverted with 0ff8158511f4f90dc26407fffa22ab0a4ad3aa0b and 91c4f12308905f4e6d65341ba54ae814c8ad94d6.

Feel free to test and let me know.

Thanks!

**Comment by sokill76** [comment]
Tkx you very much..

How to add a graphics card model in search

Please

Cordialement
________________________________

**Comment by sokill76** [comment]
I whant add New modele graphic card rx 5600xt amazon or other store please help

Cordialement

________________________________

**Comment by jef** [comment]
Seems like this issue is fixed. Closing.
