### ISSUE TITLE
SCAN stuck at Running linksBuilder

### ISSUE THREAD

**Issue by wcf778** [jef/streetmerchant#2051]
Not working for scan.co.uk, other store works perfect

Now stuck at 
info :: [scan] Running linksBuilder...

**Comment by lozbinks** [comment]
Scan require a captcha to be solved on attempted reloads of their webpages from the same ip address

**Comment by wcf778** [comment]
Any way to avoid that catchall? should i use proxy to change my ip address then?

**Comment by lozbinks** [comment]
Scan will require captcha on multiple page refreshes from any ip, you could try using a vpn which randomly changes ip address over a period of time however it isn't guaranteed to work.

**Comment by JW6677** [comment]
Scan has a lot of auto-bot features on their website making it extremely difficult to bot.
