### ISSUE TITLE
Site Checking Times Normal?

### ISSUE THREAD

**Issue by dumdedumda** [jef/streetmerchant#2052]
First off, thanks to Jef for selflessly sharing his work.

I'm currently getting the following speed checking times from the bot. It appears to be checking every 10 seconds or so, despite my PAGE_BACKOFF_MIN, PAGE_BACKOFF_MAX, PAGE_SLEEP_MIN, PAGE_SLEEP_MAX, PAGE_TIMEOUT variables set to 2500, 3600000, 5000, 10000, 30000 respectively. I've seen other configurations where their bots are checking every second to two seconds. Any tips on tweaking my environmental variables to alleviating the issue?

Much appreciated.

![speedcheckingtimes](https://user-images.githubusercontent.com/7529824/109404293-8821ec80-7919-11eb-992f-cfeb4738c2b1.png)

![streetmerchant_env](https://user-images.githubusercontent.com/7529824/109404327-e77ffc80-7919-11eb-9eaf-b42d211111bc.png)

**Comment by daniel-arrick** [comment]
I would also like a way to slow queries down as page_sleep_min does not provide this

**Comment by joeish** [comment]
up vote

**Comment by kingazar** [comment]
Even with below config, the app will still rifle check all links to the point I get insta ban on newegg and canadacomputers

PAGE_BACKOFF_MIN=15000
PAGE_BACKOFF_MAX=360000
PAGE_SLEEP_MIN=90000
PAGE_SLEEP_MAX=240000
PAGE_TIMEOUT=20000
STORES="bestbuy-ca:90000:240000,canadacomputers:90000:240000,memoryexpress:90000:240000,newegg-ca:90000:240000,amazon-ca:90000:240000"

Really need to find a way to slowdown the per link check
