### ISSUE TITLE
Updated, Bot not scanning currys uk now.

### ISSUE THREAD

**Issue by XpeckyX** [jef/streetmerchant#2068]
I have updated the bot and its not scanning currys uk.

**Comment by breacher18** [comment]
I think currys has implemented a queue feature. I watched the automation and a queue page for currys came up once I clicked join it started stock checking again.

**Comment by marciomvm** [comment]
Same here. Currys not working.

**Comment by Alienwarez123** [comment]
Same
![image](https://user-images.githubusercontent.com/42479938/118735296-0b2b5280-b838-11eb-917b-fba52a23b7e2.png)
