### ISSUE TITLE
Smyths UK - "Error: Access Denied"

### ISSUE THREAD

**Issue by Lawdie** [jef/streetmerchant#2137]
## Expected Behavior

Page loads correctly

## Current Behavior

Page always reports a Error 403 access denied, this occurrs in headless and non headless modes and it not related to IP address ( an able to view it in a manual browser) 

## Steps to Reproduce

Run any check against smyths. 

## Environment

- OS: Ubuntu 20.04

Default dotenv, only changes are: Min check time 1min Max check time 2m

![image](https://user-images.githubusercontent.com/16335903/111077302-0ff62200-84e8-11eb-8a38-af676439662f.png)

**Comment by lozbinks** [comment]
They are IP banning now

**Comment by My-Name-Is-Adam** [comment]
I am also facing this error. They are not banning the IP as it works in the manual browser and using a VPN/residential IP does not go around this error. It's just when you use this.

**Comment by My-Name-Is-Adam** [comment]
Found this:

This is a typical error message as a result of Incapsula (now known as Imperva); they're a third-party group hired by Jagex to help prevent mass account creations, DDOS, and other areas that were common targets on the website. You might be wondering, why not just cloudflare?

The answer goes much deeper; Imperva is able to provide a full on audit specific to a clients need and no one has really been able to decipher which traffic is flagged by them and which isn't, I believe Farmaton was close to cracking it but I never kept up. The best open source attempt I've seen at mitigation against Imperva's (current) security implemented on the OSRS website is this: https://github.com/ziplokk1/incapsula-cracker 5 years old, and outdated.
