### ISSUE TITLE
Regression from #2131

### ISSUE THREAD

**Issue by tarkah** [jef/streetmerchant#2151]
Related to #2131

This change seems to break when you have thousands separator AND decimal separator...

```
source from amazon id="priceblock_ourprice": $1,799.00

replace = $1,799.00 (doesn't actually do anything?)
match = ["1", "799", 00")
join = 1.799.00
parseFloat = 1.799
```

Also, the regex shouldn't be "escaped" here. It's actually doing nothing (matching on literal `\` and `.` or literal `\` and `,`. However, even if it was replacing correctly, the number would parse as `179900` which is also incorrect.

_Originally posted by @tarkah in https://github.com/jef/streetmerchant/issues/2131#issuecomment-799815951_

**Comment by starcraft66** [comment]
I think I just ran into this issue. The latest nightly of streetmerchant is telling me that [this card](https://www.newegg.ca/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520) is selling for $2.498 when it is in fact for sale for $2,498.99 on the website.

**Comment by tarkah** [comment]
#2153 has a fix. However, I feel like the old way of defining the price in the model as "euro" and having much simpler logic that we _know_ will work, was the better solution. There is still a "hack" in #2153 that is sane, but will still potentially miss things.

**Comment by jef** [comment]
Agreed @tarkah. I might revert if it continues to cause problems. I'll close this for now and reopen if we see this becoming a problem.

**Comment by jef** [comment]
I ended up reverting everything, didn't want to hold this off much longer. We can revisit this when I have more time to test.

That being said, I have mocha and sinon as dev dependencies. Something like this in the future should really have testing around it.

Refs: 0ff8158511f4f90dc26407fffa22ab0a4ad3aa0b, 91c4f12308905f4e6d65341ba54ae814c8ad94d6
