### ISSUE TITLE
wrong message for AMD 6800xt/6900xt

### ISSUE THREAD

**Issue by gigi2006** [jef/streetmerchant#2180]
I get unfortunately since 3-4 days again and again the message that the 6800 and the 6900 xt is available at AMD, but unfortunately this is not so.

in the screenshot is also nothing of available.

![image](https://user-images.githubusercontent.com/32102113/111626835-ba26c000-87ee-11eb-8645-40b5f4e0e0af.png)

![image](https://user-images.githubusercontent.com/32102113/111626814-b5faa280-87ee-11eb-92c3-040b986f61dc.png)

here is something in the screenshot, maybe that helps more

![image](https://user-images.githubusercontent.com/32102113/111627068-fd812e80-87ee-11eb-8ffc-d3a9e72185d3.png)

am of course always in the latest build

**Comment by Fastjur** [comment]
Yes I am having the same issue! Getting a lot of false positives unfortunately, I have put a half hour cooldown on it using `IN_STOCK_WAIT_TIME=1800` for now.

**Comment by mika-pika** [comment]
It looks like some of the `amd-de ` URLs like `https://www.amd.com/de/direct-buy/5458374200/de` are redirecting.

**Comment by Fastjur** [comment]
Yeah they are redirecting because I am in the Netherlands, so all the
ending `/de` links are always redirected to `/nl`.
Maybe that could be a fix? Some way of configuring what country you want it
to check on amd-de.

>

**Comment by ctbays** [comment]
I am experiencing this issue in the us as well. lots of false positives on rx6900xt

**Comment by dohamann** [comment]
I'm experiencing the same issue. Streetmerchant claimed that the rx6800 (non-xt) was available on amd-de every couple hours. rx6800xt and rx6900xt are always logged as out-of-stock. I'm running Streetmerchant in a docker container on an AWS t2.micro instance. This morning I tightened up my filters quite a lot, so it only checks for reference cards, and shortened the restart time. This lead to a massive increase in false positives for the rx6800. I got so many notifications that I turned removed the rx6800 from my filters - which only lead to false positives for the rx6800xt.

Looks to me like querying that store the very first time sometimes produces a false positive, regardless of the item.

**Comment by dohamann** [comment]
To elaborate: I noticed that amd-de returns a 403 for repeated queries which can be circumvented by restarting chrome. I get deceiving alerts every couple minutes now.
These false positives make streetmerchant pretty much unusable to me.

Relevant parts of my config:

```
HEADLESS=true
LOW_BANDWIDTH=true
RESTART_TIME=90000
SHOW_ONLY_BRANDS=amd,nvidia
SHOW_ONLY_MODELS=amd reference,founders edition
#SHOW_ONLY_SERIES=rx6800,rx6800xt,rx6900xt,3060,3060ti,3070,3080
SHOW_ONLY_SERIES=rx6800xt,rx6900xt,3060,3060ti,3070,3080
```

[Logfile](https://github.com/jef/streetmerchant/files/6421659/streetmerchant_amd_bug.log)
