### ISSUE TITLE
A captcha right in the stock of a 3070

### ISSUE THREAD

**Issue by Zirbyx** [jef/streetmerchant#2188]
I set up the bot and it usually always gave me captcha after two hours. After some research online I discovered the useragent and after adding it apparently it's been 10 hours that it doesn't give me more captcha. Tonight, with telegram trackers, a rtx 3070 came out at 4.51. I went to check and on the bot, without any captcha for hours and hours, on that video card at that time when it was in stock it went into captcha. The store is amazon-it and the video cards are the rtx 3070 and rtx 3080. How can I solve? Maybe the different user agent from my browser is a problem? I saw another similar topic from a German guy where the same thing happened months ago.

**Comment by marvelmaster** [comment]
just curious where you put the useragent and what it is named

**Comment by Zirbyx** [comment]
Bottom in the dotenv file
________________________________
