### ISSUE TITLE
xbox.com - xbox.ts

### ISSUE THREAD

**Issue by hvownij** [jef/streetmerchant#2200]
## Expected Behavior

Should detect In Stock / Out of Stock

## Current Behavior

Currently it thinks it is always instock, and every scrape results in a now instock notification.  

## Steps to Reproduce

run streetmerchant, include xbox as a store to check as well as the xbox series x

## Environment

- OS: Windows Server ( Node.js )

```dotenv
```

**Comment by Found0415** [comment]
Add this right below the outOfStock label:

`inStock: {
	  container: 
	  '.src-pages-BundleBuilder-components-BundleBuilderHeader-__BundleBuilderHeader-module___checkoutButton',
	  text: ['Checkout']
},`

**Comment by Jwoods2019** [comment]
Hello there i tried to insert the code you provided do you mind posting the raw xbox.ts thanks
