### ISSUE TITLE
wrong alarm with AMD-GPUs on AMD.de

### ISSUE THREAD

**Issue by Eribaeri** [jef/streetmerchant#2219]
## Expected Behavior

sending discord notification, when in stock, opening window

## Current Behavior

sending discord message twice per minute per model, 6 messages per minute, opening 6 windows --> out of stock

OS: Windows, latest version
using cmd with node.js
Streetmerchant: 3.5.0

**Comment by carrierfry** [comment]
this problem also occurs to me. If I look into the screenshot the bot made, I see that he got redirected to the summary page (https://www.amd.com/de/direct-buy/de) instead of the detail page. Maybe AMD redirects the bot in some circumstances (e.g: when they change something on their website)?
