### ISSUE TITLE
amd rx6700xt

### ISSUE THREAD

**Issue by gabber3000** [jef/streetmerchant#2231]
Good evening,
I would like to know why the rx6700xt is not available in the "Supported series" section?
Thank you

**Comment by joeish** [comment]
I tried adding it manually into the store file but it throws errors still.

**Comment by ste032** [comment]
I created a new object in amd.ts using 6700xt's links while tagging it as a "rx6800xt."
Example:
```
{
      brand: 'amd',
      cartUrl:
        'https://www.amd.com/en/direct-buy/5496921400/it?add-to-cart=true',
      model: 'amd reference',
      series: 'rx6800xt',
      url: 'https://www.amd.com/en/direct-buy/5496921400/it',
    },
```


It's dirty but it works.

**Comment by bramevo** [comment]
> I tried adding it manually into the store file but it throws errors still.

It needs to be added to the store file (for example amd.ts) and to store.ts under Series.
