### ISSUE TITLE
Rasbian Error: "stack": "Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by MrTriske** [jef/streetmerchant#2235]
![2021-03-26-211203_2560x1440_scrot](https://user-images.githubusercontent.com/80903836/112687749-3cab2180-8e78-11eb-871d-c09ea5636551.png)

**Comment by MrTriske** [comment]
And This

![2021-03-26-222530_2560x1440_scrot](https://user-images.githubusercontent.com/80903836/112694232-46398700-8e82-11eb-8ef1-1c861648e487.png)

**Comment by yusy86** [comment]
same issue!

**Comment by Tekno68** [comment]
Same issue

**Comment by hibenji** [comment]
Same here
