### ISSUE TITLE
Unable to access websites with Cloudflare protection. 

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [jef/streetmerchant#2248]
Cloudflare-protected websites are not accessible on the Chromium browser. 

Headless browser is disabled. 

Upon pausing the script and manually going to a website with browser protection I also face the issue. 

It gets stuck on:

```
Checking your browser before accessing example.com.
Please allow up to 5 seconds.
```

It then refreshes the same page but the Ray ID is different. 

In the command prompt window it says WAITING, CLOUDFLARE. 
Then aborts after a while. 

Tried adding a user-agent but this doesn't resolve it.

`HEADLESS=true
SHOW_ONLY_SERIES="3070,3080,3090,3060ti"
STORES="amazon-uk,box,currys,game,scan,shopto,very,amd-uk,ao,awd,box,bt,ccl,corsair-uk,novatech,overclockers,ebuyer"
PLAY_SOUND=alarm.mp3
DESKTOP_NOTIFICATIONS="true"
AUTO_ADD_TO_CART=true
USER_AGENT=5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
PAGE_BACKOFF_MIN="20000"
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN="30000"
PAGE_SLEEP_MAX="60000"
PAGE_TIMEOUT="60000"
BROWSER_TRUSTED="true"`

**Comment by ctbays** [comment]
Also experiencing this. Had to remove zotac from store list due to this issue.
