### ISSUE TITLE
Drop happened last week and I got no notification

### ISSUE THREAD

**Issue by jonalange** [jef/streetmerchant#2252]
## Expected Behavior

Receive notification via discord

## Current Behavior

No notification received.

## Environment

- OS: Windows 10 Professional

Last week on 23.03 was a 3080 FE drop at notebooksbilliger.de (NBB) but I got no notification. Are there any logs to see what happened in the software? I can't find them.

Also, is there a way to check what page get checked when I select NBB? Maybe it's the wrong one.

**Comment by hickneller** [comment]
You can see what page is being checked by setting HEADLESS to false.
