### ISSUE TITLE
Chrome error

### ISSUE THREAD

**Issue by joanjgm** [jef/streetmerchant#2281]
Hello, I'm getting error 

`error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).`

`npm install` not fixing it

Tried with Node 15 and 14

**Comment by Dkvsb** [comment]
Try Node 14, fixed it for me

**Comment by joanjgm** [comment]
Didn't work

**Comment by joanjgm** [comment]
> Try Node 14, fixed it for me

Did not work

**Comment by KennyPowers91** [comment]
Hi, in the dotenv file, right click, open with notepad and then add the following line : PUPPETEER_EXECUTABLE_PATH=C:\Program Files (x86)\Google\Chrome\Application\Chrome.exe

**Comment by joanjgm** [comment]
> Hi, in the dotenv file, right click, open with notepad and then add the following line : PUPPETEER_EXECUTABLE_PATH=C:\Program Files (x86)\Google\Chrome\Application\Chrome.exe

That worked flawlessly!
