### ISSUE TITLE
I really messed up

### ISSUE THREAD

**Issue by Julian-of-Aland** [jef/streetmerchant#2288]
fatal: destination path 'streetmerchant' already exists and is not an empty directory. 
cd : Cannot find path 'C:\Users\Myname\streetmerchent' because it does not exist
 
 they are in direct contradiction of each other this happed because
I closed command prompt before I could say cd streetmerchent them npm install
is there any way to fix this?

**Comment by klords** [comment]
You've misspelled the directory name in the cd command. streetmerchAnt
