### ISSUE TITLE
Newegg temp banning IP

### ISSUE THREAD

**Issue by LTruhero** [jef/streetmerchant#2289]
It appears our systems have detected the possible use of an automated program to visit Newegg.com. For more information on appropriate use of the Newegg website, please see the excerpt from Newegg.com's Policy & Agreement below. If our systems do not detect any violations from your IP address within the next 24 hours, it may be unblocked. If you need faster assistance or feel you’ve reached this page in error, please send an email to webmaster@newegg.com with your IP address and the error code listed below.
You may also be interested in our Newegg Shuffle - our drawing system to purchase in-demand products that are currently limited in supply. Products may include GPUs, CPUs, consoles, or any other hard-to-buy items.

Error Code: 3

**Comment by jxjftw** [comment]
This isn't a bug. You need rotating proxies.
