### ISSUE TITLE
Could not find expected browser (chrome) locally.

### ISSUE THREAD

**Issue by c4dx** [jef/streetmerchant#2309]
## Expected Behavior

Install dependencies (including chrome) and start.

## Current Behavior

Says up to date, but throws error that the chrome-browser is missing.

## Steps to Reproduce

- git clone this project
- npm install
- npm start

## Environment

- OS: Windows 10
- npm: 7.6.0
- node: 15.11.0

## Logs

<pre>
C:\Web\streetmerchant><b>npm install</b>
up to date, audited 1184 packages in 2s

17 packages are looking for funding
  run `npm fund` for details
2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
A
C:\Web\streetmerchant><b>npm start</b>

> streetmerchant@3.5.0 prestart
> npm run compile

> streetmerchant@3.5.0 compile
> tsc

> streetmerchant@3.5.0 start
> node build/src/index.js

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[15:14:17] info :: ℹ selected stores: alternate, alternate-nl..... (truncated)
[15:14:17] info :: ℹ selected series: 3070
[15:14:18] error :: ✖ <b>something bad happened, resetting streetmerchant in 5 seconds Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).</b> {
  "stack": "Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).\n    at ChromeLauncher.launch (C:\\Web\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:80:27)\n    at async main (C:\\Web\\streetmerchant\\build\\src\\index.js:72:15)\n    at async loopMain (C:\\Web\\streetmerchant\\build\\src\\index.js:109:9)"
}
</pre>

### 1
I think  this is an issue with puppeteer.
`C:\Web\streetmerchant\node_modules\puppeteer\.local-chromium` is missing even tho I've executed `npm i`.

### 2
`...\node_modules\puppeteer\: node install.js` installs the needed local-chromium with the correct revision.
Does anyone know when/if this install-script is inteded to run? I dont think it is ment to be executed manually by the user?

**Comment by c4dx** [comment]
I think  this is an issue with puppeteer.
`C:\Web\streetmerchant\node_modules\puppeteer\.local-chromium` is missing even tho I've executed `npm i`.

I've got an older version of streetmerchant. When copying that folder over to the new version, it starts as expected.

**Comment by kepler-eyez** [comment]
I was running into this as well.  I ran the following and is working for me now.
node node_modules/puppeteer/install.js
