### ISSUE TITLE
adding CCLOnline

### ISSUE THREAD

**Issue by StarLordRammi** [jef/streetmerchant#2310]
is it possible to add the following site (https://www.cclonline.com/) with Add to basket ability using discord auto link opener?
https://github.com/clearyy/discord-link-opener

**Comment by AnxiousUK** [comment]
I wish it was working on cclonline in general. I dont think they found a way around cloudflare. Apparently there is a way since "ctrlaltstock" get notification from ccl. Sadly always too late :)
