### ISSUE TITLE
False positives on several stores

### ISSUE THREAD

**Issue by Putrefactium** [jef/streetmerchant#2315]
## Expected Behavior

Graphic card should not show if my MAX PRICE for it is under its value

## Current Behavior

Some models are showing even though the price is too high, both on Amazon-fr and LDLC. 

On LDLC, my problem is with a EVGA 3090 FTW3 (https://www.ldlc.com/fiche/PB00374837.html) showing at 2500€, while my parameters are under (I tried both MAX_PRICE_SERIES_3090=1900 and MAX_PRICE_SERIES_3090=10 to see if anything changed, but it always displays it)

I changed the container to '#activeOffer > div.product-info > div.wrap-aside > aside > div.price > div' instead of original one, and it changed nothing either.

On Amazon, it's the same problem with a RTX 3060 showing for 1070€, while my MAX_PRICE_SERIES_3060=680
And a  RTX 3070 going for 1749€, while my MAX_PRICE_SERIES_3070=800

In my amazon-fr.ts file and ldlc.ts file, I commented the faulty parts like this : 

/**{
      brand: 'evga',
      model: 'ftw3',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374837.html',
    }, */
    
to be sure the rest of the file works, and it does.

## Steps to Reproduce

Set your ldlc.ts with a new card named : 

{
      brand: 'evga',
      model: 'ftw3',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374837.html',
},

and run it with your dotenv file with MAX_PRICE_SERIES_3090=1700

You'll see the card pop but with a too high price.

## Environment

- OS: Windows 10

```

# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=3
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060=680
MAX_PRICE_SERIES_3060TI=750
MAX_PRICE_SERIES_3070=800
MAX_PRICE_SERIES_3080=1400
MAX_PRICE_SERIES_3090=1800
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=3000
PAGE_SLEEP_MAX=7412
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
PUSHOVER_SOUND=
RESTART_TIME=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3060,3060ti,3070,3080,3090
SLACK_CHANNEL=
SLACK_TOKEN=
SMARTTHINGS_TOKEN=
SMARTTHINGS_SWITCH_LABEL=
SMTP_ADDRESS=
SMTP_PORT=
STORES=ldlc, nvidia-fr, topachat amazon-fr 
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
WEB_PORT=

```

## Logs

I'd like to put some logs, but I don't know where to find them, and my console just vanish once it finds an item, but runs in the background... i'll reopen another ticket for this

**Comment by Putrefactium** [comment]
After a bit of tests, I found that on LDLC, it'll pop an alert and open Chrome if the card can be ordered (it says that's it'll be available in 7 days but you can purchase in advance).

But I don't get why the bot shows this result if the price is not matching my parameters...

**Comment by bramevo** [comment]
> After a bit of tests, I found that on LDLC, it'll pop an alert and open Chrome if the card can be ordered (it says that's it'll be available in 7 days but you can purchase in advance).
> 
> I guess it will trigger a false positive too if something is on stock but overpriced.
> 
> Seems like the .ts file doesn't get the price in the right way, but I can't figure how the bot reads price on a webpage
> 
> But I don't get why the bot shows this result if the price is not matching my parameters...

If the bot cannot find the price, it will not check if it matches with the values in the dotenv file. How it gets the price is configured in src/store/model/ldlc.ts here:
`    maxPrice: {
      container: '.price .price',
      euroFormat: true,
    },`
Although LDLC currently does not work for me because I get a "Navigation timeout of 30000 ms exceeded" so I cant troubleshoot it for you.
So if it does not get the correct price, maybe the maxPrice container needs to be updated. On my first check however, it seems fine.

**Comment by Putrefactium** [comment]
> If the bot cannot find the price, it will not check if it matches with the values in the dotenv file. How it gets the price is configured in src/store/model/ldlc.ts here:
> ` maxPrice: { container: '.price .price', euroFormat: true, },`
> Although LDLC currently does not work for me because I get a "Navigation timeout of 30000 ms exceeded" so I cant troubleshoot it for you.
> So if it does not get the correct price, maybe the maxPrice container needs to be updated. On my first check however, it seems fine.

I have the same problem on Amazon actually, however I checked the MaxPrice container, and tried to change it a bit to see if it does change the behavior, but still the same !
