### ISSUE TITLE
`PAGE_SLEEP_MIN/MAX` appears to not be respected?

### ISSUE THREAD

**Issue by NSExceptional** [jef/streetmerchant#2316]
## Expected Behavior

Lowering `PAGE_SLEEP_MIN/MAX` should speed up the rate at which requests are made

## Current Behavior

Lowering them has no discernable effect on the rate at which requests are made

## Environment

- OS: Windows

<details>
  <summary>dotenv</summary>
<pre>
ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=false
BROWSER_TRUSTED=
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=5
PAGE_BACKOFF_MAX=12
PAGE_SLEEP_MIN=5
PAGE_SLEEP_MAX=12
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=C:/Users/Tanner/Downloads/alert.mp3
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
PUSHOVER_SOUND=
RESTART_TIME=
SCREENSHOT=
SHOW_ONLY_BRANDS=nvidia,amd
SHOW_ONLY_MODELS=founders edition,5800x
SHOW_ONLY_SERIES=3060,3060ti,3070,3080
SLACK_CHANNEL=
SLACK_TOKEN=
SMARTTHINGS_TOKEN=
SMARTTHINGS_SWITCH_LABEL=
SMTP_ADDRESS=
SMTP_PORT=
STORES=bestbuy
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
WEB_PORT=
</pre>
</details>

**Comment by c4dx** [comment]
In the docs it says _Minimum/Maxmimum sleep time between queries of the same product page_. Its not about the store itself.
I assume that the bot is going in a circle through all products. When it comes back to the first one, it would check for the min-time to be passed for another check. But thats just an assumption.

## My config
STORES=alternate:5000:6000 => _min 5sec /  max 6sec_
SHOW_ONLY_SERIES=3080

## Output
```
[10:48:23] info :: ✖ [alternate] [asus (3080)] strix :: OUT OF STOCK
[10:48:27] info :: ✖ [alternate] [asus (3080)] strix oc :: OUT OF STOCK
[10:48:31] info :: ✖ [alternate] [asus (3080)] tuf :: OUT OF STOCK
[10:48:35] info :: ✖ [alternate] [asus (3080)] tuf oc :: OUT OF STOCK
[10:48:37] info :: ✖ [alternate] [evga (3080)] ftw3 :: OUT OF STOCK
[10:48:39] info :: ✖ [alternate] [evga (3080)] ftw3 ultra :: OUT OF STOCK
[10:48:41] info :: ✖ [alternate] [evga (3080)] xc3 black :: OUT OF STOCK
[10:48:43] info :: ✖ [alternate] [evga (3080)] xc3 :: OUT OF STOCK
[10:48:45] info :: ✖ [alternate] [evga (3080)] xc3 ultra :: OUT OF STOCK
[10:48:47] info :: ✖ [alternate] [gainward (3080)] phantom gs :: OUT OF STOCK
[10:48:50] info :: ✖ [alternate] [gainward (3080)] phoenix gs :: OUT OF STOCK
[10:48:54] info :: ✖ [alternate] [gigabyte (3080)] aorus master :: OUT OF STOCK
```

As you can see from the times, the requests to alternate happend like every 2-5 seconds. The first product (asus strix) never got requested again in this history.

My expectation would've been that the asus strix would've been requested at max 10:48:29 (+6 seconds).

I can confirm a weird behaviour.

**Comment by c4dx** [comment]
https://github.com/jef/streetmerchant/blob/113c9ce19f3ed1f140eec7cd555ec373f25d256f/src/store/model/index.ts#L374-L377

I haven't debugged it yet, but shouldnt be line 374 below 377? Saving before setting values?

**Comment by c4dx** [comment]
Ok. After playing around with the settings I found out that if you set MIN and MAX to the same value (e.g. _2500_) and only pick one store (e.g. _alternate_), the requests are send approx. every 6 seconds (MIN * 2 + 1 second).

I observed that with different values.
I think the problem is somewhere around here https://github.com/jef/streetmerchant/blob/113c9ce19f3ed1f140eec7cd555ec373f25d256f/src/index.ts#L73-L80
and here
https://github.com/jef/streetmerchant/blob/113c9ce19f3ed1f140eec7cd555ec373f25d256f/src/store/lookup.ts#L534-L550

It somehow waits twice. (Or its a visual bug with the logs?).

**Comment by NSExceptional** [comment]
The peculiar thing to me is I noticed exactly no difference when I used the default, and then 100/1000, then 10/50, then 5/12. They all ran at the same rate.

I think even if it is waiting twice you would notice a difference at least

**Comment by bramevo** [comment]
If you enable debugging mode (LOG_LEVEL=debug), you can see that it runs through all shops all the time. Maybe the run itself is slow which causes delays between checks?
