### ISSUE TITLE
how to stop the bot spamming the same item

### ISSUE THREAD

**Issue by itsyaboydavey** [jef/streetmerchant#2340]
hello how do i stop the stop spamming the same item over like the xbox the box just spams its instock     [https://i.imgur.com/FKNFJrj.png](url)

**Comment by davols** [comment]
https://i.imgur.com/FKNFJrj.png for whoever is lazy like me.

Solution:  PAGE_SLEEP for that store.

**Comment by itsyaboydavey** [comment]
> https://i.imgur.com/FKNFJrj.png for whoever is lazy like me.
> 
> Solution: PAGE_SLEEP for that store.

hello what do i put for the 

PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=

like 1 for min or something

**Comment by c0rrre** [comment]
I think the following parameter is what you are looking for. As far as i understand u dont want to get spamed with notifications if an item is in Stock.


IN_STOCK_WAIT_TIME | Time to wait between requests to the same link if it has that card in stock. In seconds, default: 0

Just add a higher value for this parameter in the dotenv file
