### ISSUE TITLE
Remove bestbuy and selected products automatically

### ISSUE THREAD

**Issue by Neffa87** [jef/streetmerchant#2345]
I can't remove bestbuy and amazon from the stores despite having added other stores. It also looks for me for products that I have not entered
![foto 1](https://user-images.githubusercontent.com/81470840/114406777-18ee1800-9ba8-11eb-897b-b1a27b478f34.JPG)
![foto 2](https://user-images.githubusercontent.com/81470840/114406782-1986ae80-9ba8-11eb-8b16-291b3643c509.JPG)
![foto 3](https://user-images.githubusercontent.com/81470840/114406785-1986ae80-9ba8-11eb-96c1-682adca50d06.JPG)

**Comment by xmpierce1** [comment]
What you are seeing is the DEFAULT if stores and series are blank. Your format for STORES is also incorrect.  It should be something like STORES=Amazon,bestbuy,newegg,target  (no quotes)
