### ISSUE TITLE
Scanning search instead of individual links.

### ISSUE THREAD

**Issue by joeish** [jef/streetmerchant#2353]
Scan entire search instead of individual links, is this possible?

**Comment by AlexP11223** [comment]
See `linksBuilder` (in the code, does not seem to be documented).

**Comment by joeish** [comment]
Do you know what would need to be changed in order to scan multiple items in search and display output instead of each product url?

**Comment by AlexP11223** [comment]
See examples in https://github.com/jef/streetmerchant/search?q=linksBuilder

**Comment by joeish** [comment]
import {Store} from './store';
import {getProductLinksBuilder} from './helpers/card';
export const CanadaComputers: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: 'div[class="pi-prod-availability"]',
      text: ['Online In Stock'],
    },
    maxPrice: {
      container: '.h2-big > strong:nth-child(1)',
      euroFormat: false,
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url:
        'https://www.canadacomputers.com/product_info.php?item_id=167320&cPath=27_1046_365&language=en',
    },
  ],
linksBuilder: {
    builder: getProductLinksBuilder({
      productsSelector: '.addCartSearch',
      sitePrefix: 'https://www.canadacomputers.com',
      titleSelector: '.text-center',
      urlSelector: 'a[href]',
    }),
    urls: [
     
      {
        series: '3070',
        url:
          'https://www.canadacomputers.com/search/results_details.php?language=en&keywords=3070&cpath=43;557',
      },
      {
        series: '3090',
        url:
          'https://www.canadacomputers.com/search/results_details.php?language=en&keywords=3090&cpath=43;557',
      },
    ],
  },
  name: 'canadacomputers',
  waitUntil: 'domcontentloaded',
};

Stuck running links builder, any ideas?

**Comment by AlexP11223** [comment]
It does not open for me.

Also format the code https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

See how link builder is implemented, maybe you are using selectors wrong.
https://github.com/jef/streetmerchant/blob/ba35706cca84a425da8d5a5bd6b86dbecbadffa1/src/store/model/helpers/card.ts#L19-L67

Also you can add logging there to make debugging easier, such as `logger.info(title)`.

**Comment by AlexP11223** [comment]
Also if the products in search are loaded via ajax, this may help: #2437
