### ISSUE TITLE
ASUS store blocks but this is not detected so backing-off never occurs.

### ISSUE THREAD

**Issue by kurt1288** [jef/streetmerchant#2358]
## Expected Behavior

Detect ASUS store blocking and back off appropriately.

## Current Behavior

The ASUS store seems to throw you to the following page if they detect page scrapping (i.e. botting): http://dlcdnmkt.asus.com/store/502.html. Note that the page has a normal 200 HTTP response. I know that the store is currently available since I can go to a different device and still access the store.

## Steps to Reproduce

Configure your dotenv file to scan the "asus" store. That should be it.

**Comment by abood101** [comment]
@jef Can you please help us with this, we can't ping asus it instantly blocks no matter if headless or incognito
