### ISSUE TITLE
AMD checks no longer working

### ISSUE THREAD

**Issue by bramevo** [jef/streetmerchant#2367]
## Expected Behavior

AMD checks should work when using rotating proxies, but for some reasons, it just stopped working. Not working with any type of proxy anymore. Is this a block on a combination of user agent and IP? How are user agents rotated?

## Current Behavior

AMD checks are not working anymore when using local proxies or rotating proxies for some reason. It's not that it's getting a 403 block but it just keeps running.

**Comment by bramevo** [comment]
With Proxies:
`[7:21:58 AM] error :: ✖ [1/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:23:58 AM] error :: ✖ [2/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:25:56 AM] error :: ✖ [3/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:27:58 AM] error :: ✖ [4/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:29:55 AM] error :: ✖ [5/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:31:51 AM] error :: ✖ [1/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:33:54 AM] error :: ✖ [2/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:35:46 AM] error :: ✖ [3/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded
[7:37:43 AM] error :: ✖ [4/5] [amd-be] amd rx6800 amd reference - Navigation timeout of 100000 ms exceeded`

Without any proxy:

`[7:40:28 AM] info :: ✖ [amd-be] [amd (rx6800)] amd reference :: OUT OF STOCK`

So for some reason, it detects the use of a proxy?

**Comment by tkoeck** [comment]
They check it with cookies. Would be good to be able to delete the cookies every access.

**Comment by bramevo** [comment]
> They check it with cookies. Would be good to be able to delete the cookies every access.

Are you sure. I know that if you see a specific 403 error reference code, it's a cookie block. Removing cookies fixes this. But in this case, the connection does a timeout. This seems to be another kind of protection. Also because it blocks when using a proxy and not when not using a proxy in this specific case. Cookies are the same in both cases I assume?

**Comment by tkoeck** [comment]
Well if I start it again with the same external IP it will work again. So I suspect it's at least a cookies block.

**Comment by tkoeck** [comment]
Did you adjust the waiting times as described in the documentation?

**Comment by bramevo** [comment]
> Did you adjust the waiting times as described in the documentation?

Yes, changing waiting time does not help. It's the bot protection that just keeps the connection open and does nothing with it.

**Comment by tkoeck** [comment]
Okay then unfortunately I don't know what the problem might be.

**Comment by jxjftw** [comment]
It is certainly cookie related, if you run headless off you will see the cookie ban page.

**Comment by tkoeck** [comment]
It works for me without any proxy after I increased the times between the checks.

**Comment by bramevo** [comment]
> It works for me without any proxy after I increased the times between the checks.

The thing is that it does not work with a proxy. And if you want to do a lot of checks, you need rotating proxies to avoid a ban.

**Comment by bramevo** [comment]
> It is certainly cookie related, if you run headless off you will see the cookie ban page.

Not really. It does not return any 403s (it does when you have a cookie or IP ban). But in this case, the bot protection just keeps the connection open so it will timeout. The question is, how can it detect that it's the same user when using rotating proxies? Is it the same cookie that is used for each request? I assume not right?

**Comment by tkoeck** [comment]
Just use several server with different IPs and increase the check rate for every server. On average you'll get a lower reaction time.

**Comment by bramevo** [comment]
> Just use several server with different IPs and increase the check rate for every server. On average you'll get a lower reaction time.

I use proxies. I think the check is based on something else, maybe a specific header or something.
