### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by StarLordRammi** [jef/streetmerchant#2368]
installing the script on Pi4 Lite OS

in this tutorial it says
https://github.com/jef/streetmerchant/wiki/Installation:-Linux:-Raspberry-Pi-OS

```
Configure following before typing npm run start to start:

which chromium
which chromium-browser
/usr/bin/chromium-browser # Use this output for the next command
export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
npm run start
```

**is this a file that needs editing or commands?**

which chromium
which chromium-browser
/usr/bin/chromium-browser # Use this output for the next command
export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

**Comment by AlexP11223** [comment]
It's commands. The first or the second one (depending on your distro/installed packages probably) is to find where chromium is located, and the 3rd line is an example of its' path.
