### ISSUE TITLE
Crashes on notification

### ISSUE THREAD

**Issue by FrankFioretti** [jef/streetmerchant#2369]
## Expected Behavior

Notification should be sent and script should continue to run

## Current Behavior

Notification is sent and script crashes/exits UNLESS running as local administrator on Windows 10. Is this expected?

## Environment

- OS:

<details>
<summary>dotenv</summary>

```dotenv
# Place your dotenv within these backticks. Be sure to remove any secrets/passwords.
```

</details>

**Comment by FrankFioretti** [comment]
Note: still crashes intermittently when running as administrator

**Comment by MieszkoT84** [comment]
I think it is the same behaviour as in this topic: https://github.com/jef/streetmerchant/issues/2232
As of now I don't know how to completely fix it but there is workaround which has to do for the time being. Please see the topic above for details.

**Comment by Austin-Wells** [comment]
Having the same issue, crashes immediately after opening a chromium instance. Powersehll/Git still running in process manager.

**Comment by Eribaeri** [comment]
i got the same problem

**Comment by jef** [comment]
Closed with https://github.com/jef/streetmerchant/pull/2461

**Comment by klords** [comment]
Note to anyone following this issue: the merged fix will only take effect when you (re)install node modules using `npm i`

**Comment by MieszkoT84** [comment]
> Note to anyone following this issue: the merged fix will only take effect when you (re)install node modules using `npm i`

I would also add that 'git clone https://github.com/jef/streetmerchant.git' command is also necessary because 'npm i' didn't really work for me but after cloning the entire project again all is dandy now. Thanks a lot!
