### ISSUE TITLE
Incorrect price for amd-de

### ISSUE THREAD

**Issue by YeapGuy** [jef/streetmerchant#2377]
## Expected Behavior

Streetmerchant grabs the correct price from the AMD direct buy website.

## Current Behavior
Streetmerchant parses the price incorrectly which results in not getting alerted (and me missing today's drop 😢)

`[21:06:42] info :: ✖ [amd-de] [amd (rx6800xt)] amd reference :: IN STOCK, PRICE 64900 EXCEEDS LIMIT 700`
![image](https://user-images.githubusercontent.com/43749899/115078306-bc6c5f00-9eff-11eb-841b-abb85d850f5d.png)

## Steps to Reproduce

1. Run streetmerchant with AMD store enabled
2. Wait for a restock or somehow emulate it
3. See incorrect price

## Environment

- OS: Windows

<details>
<summary>dotenv</summary>

Irrelevant as the configuration doesn't affect how the price gets parsed.

</details>

## Logs

Included above.

**Comment by AlexP11223** [comment]
What's the price format there?

Do you use VPN? Looks like it redirects based on country.

**Comment by YeapGuy** [comment]
I don't use a VPN, however I am located in Slovakia, so I changed all the
Direct Buy URL endings from /de to /sk, otherwise it would get redirected
and the checker would spit out a navigation error or whatever (not sure how
exactly it was called).
The price format *seems* to be USD? But it flickers when I visit the page
so maybe it's changing from one to another.

**Comment by AlexP11223** [comment]
If it uses dots (`650.99`), you need to remove
https://github.com/jef/streetmerchant/blob/4eb702b9a1187c8dcf159ea991ab1049c3c44bb2/src/store/model/amd-de.ts#L12

But I think they don't ship to your country

> Which countries does the AMD Store ship to?
>    US, Canada, Austria, Belgium, Czech Republic, Denmark, Finland, France, Germany, Ireland, Italy, Luxembourg, The Netherlands, Portugal, Spain, and Sweden
>    We are temporarily unable to process shipments to the United Kingdom.

https://www.amd.com/en/support/kb/faq/amdonlinestorefaq

**Comment by YeapGuy** [comment]
Hmm, okay, I'll check that, thanks for the advice.
Shipping's not an issue, I have friends in both Germany I'll send through
if I manage to get something from there.

**Comment by YeapGuy** [comment]
Yeah, it is using dots ($649.00), so I set euroFormat to false. Do I need to change the currency as well or that doesn't matter (does the currency field even do anything else except showing the currency on the notification)?

**Comment by AlexP11223** [comment]
> does the currency field even do anything else except showing the currency on the notification

Looks like no

![2021-04-17_12-49](https://user-images.githubusercontent.com/5680466/115108914-9be1ea80-9f7b-11eb-9dfd-da4bcf259f85.png)

**Comment by YeapGuy** [comment]
Okay, thanks for your help, I'll close this now. 😃
