### ISSUE TITLE
XBox Series S recognized as XBox Series X for Amazon de

### ISSUE THREAD

**Issue by tkoeck** [jef/streetmerchant#2387]
## Expected Behavior

It should only send messages if it has found an XBox Series X

## Current Behavior

It sends messages for an XBox Series S as X

## Steps to Reproduce

XBox Series S is availabe and X isn't like right now.

## Environment

- OS:
Debian 10, Latest Docker

<details>
<summary>dotenv</summary>

```dotenv
SHOW_ONLY_BRANDS=amd,sony,microsoft
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=rx6900xt,rx6800xt,sonyps5c,xboxsx
STORES=amd-de:240000:330000,amazon-de:37000:49344,alternate,gamestop-de,mediamarkt:500000:1000000,saturn:500000:1000000
```

</details>

**Comment by tkoeck** [comment]
![success-1618836456463](https://user-images.githubusercontent.com/42435353/115239676-48a89d00-a11f-11eb-8d1b-6f31a8ea5f56.png)

**Comment by lozbinks** [comment]
search using the offer page not the details page

**Comment by tkoeck** [comment]
That might be the case but then we don't need to differentiate between the xboxss and xboxsx SHOW_ONLY_SERIES variable.

**Comment by lozbinks** [comment]
This is what works for me..

`import {Store} from './store';

export const AmazonDe: Store = {
	backoffStatusCodes: [403, 429, 503],
	currency: '€',
	labels: {
		captcha: {
			container: 'body',
			text: [
				'geben sie die unten angezeigten zeichen ein',
				'geben sie die zeichen unten ein'
			]
		},
		inStock: {
			container: '#aod-offer-soldBy',
			text: ['Amazon', 'Amazon Warehouse', 'Amazon EU S.a.r.L.',]
		},
		maxPrice: {
			container: '#aod-offer-price',
			euroFormat: true
		},
		outOfStock: [
			{
				container: '#availability',
				text: ['Derzeit nicht verfügbar']
			}
		]`
		
		
`			brand: 'microsoft',
			labels: {
				inStock: {
					container: '#productTitle',
					text: ['Xbox Series X 1TB']
				}
			},
			model: 'xbox series x',
			series: 'xboxsx',
			url: 'https://www.amazon.de/gp/product/B08H93ZRLL/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=B08H93ZRLL'

		}
	],
	name: 'amazon-de'
};`

Adding the separate container sorts that out (container: '#productTitle',
					text: ['Xbox Series X 1TB'])

**Comment by tkoeck** [comment]
Nice. Can you create a MR for it?

**Comment by CalvinFriedrich** [comment]
@lozbinks 
Do I need to include this in the amazon-de.ts File? If not, can you tell me where to fix the issue?

**Comment by lozbinks** [comment]
> Nice. Can you create a MR for it?

What's an MR?

**Comment by lozbinks** [comment]
> @lozbinks
> Do I need to include this in the amazon-de.ts File? If not, can you tell me where to fix the issue?

Yes this goes in the amazon-de ts file

**Comment by tkoeck** [comment]
> 
> 
> > Nice. Can you create a MR for it?
> 
> What's an MR?
A Merge Request but in that case you can just include your changes to the Pull Request (https://github.com/jef/streetmerchant/pulls) and the dev can merge them.

**Comment by Stoyvo** [comment]
This issue happens for CA as well

**Comment by xmpierce1** [comment]
This happens in the United States as well.. 
![image](https://user-images.githubusercontent.com/74942520/115802852-ad792700-a3ad-11eb-9489-a20ee461a7c5.png)

**Comment by tkoeck** [comment]
Well as long as it's not implemented in the official docker image it will be hard to change.
