### ISSUE TITLE
Add Turkish Lira to Store?

### ISSUE THREAD

**Issue by csoyuncu** [jef/streetmerchant#2398]
How can i add Turkish Lira for max price in store  ?

**Comment by AlexP11223** [comment]
It does support any currencies, it simply compares the number you entered in max price with the store price.

Could be a problem if you monitor stores with different currencies (e.g. Amazon DE + your local store)...

For now you can simply run separate streetmerchant instances (e.g. copy the dir): one configured for Euro stores, the other for Lira stores.
