### ISSUE TITLE
Need a better README

### ISSUE THREAD

**Issue by H4TERAID** [jef/streetmerchant#2406]
Literally the only thing it does is link you to the wiki, which is actually more useless then the readme as it's nearly identical. No idea where to begin unless you code in java yourself, just tells you how to start the node, and this thing is a mess it needs heavy editing or at least a location cited where you can edit the list of items and price ranges.

**Comment by AlexP11223** [comment]
The linked page (https://jef.codes/streetmerchant/getting-started/) says this:

> To customize streetmerchant, make a copy of dotenv-example as dotenv and make any changes to your liking. View Reference for more information on variables and their usage.

**Comment by tkoeck** [comment]
Well, yes that's right it's easy to get it starting.

Other information isn't available. E.g. how the

SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=

variables play along if you want to use them all and filter it. Is it restrictive (e.g. an AND) or additive (e.g. OR).

**Comment by mcgrizzz** [comment]
Looking at the source, it's restrictive.

 See [https://github.com/jef/streetmerchant/blob/cac7c20193caaec5d41291104e66aa01a65adceb/src/store/filter.ts#L66-L72](url)
