### ISSUE TITLE
 The command "tsc" is either misspelled or could not be found

### ISSUE THREAD

**Issue by 1Roishi** [jef/streetmerchant#2427]
Everytime i type npm run start it says  The command "tsc" is either misspelled or could not be found
can someone help?

**Comment by AlexP11223** [comment]
Did you run `npm i`?

**Comment by 1Roishi** [comment]
yes but there is an probleme after i type npm install. 
Screenshots:
![2021-04-24 13_42_08-Eingabeaufforderung](https://user-images.githubusercontent.com/83096644/115957524-47061d00-a503-11eb-830a-32f35577ca8b.png)
![2021-04-24 13_42_46-Eingabeaufforderung](https://user-images.githubusercontent.com/83096644/115957527-4a99a400-a503-11eb-94a6-c0e2369f1b42.png)

**Comment by AlexP11223** [comment]
Could be the same as https://github.com/jef/streetmerchant/issues/2431

**Comment by 1Roishi** [comment]
I still have a Probleme when i type npm install[
![2021-04-26 22_42_50-Eingabeaufforderung](https://user-images.githubusercontent.com/83096644/116148299-06fc9100-a6e1-11eb-867b-fc102541e622.png)
![2021-04-26 22_43_55-Eingabeaufforderung](https://user-images.githubusercontent.com/83096644/116148311-09f78180-a6e1-11eb-86dd-5d220408af5e.png)

](url)

**Comment by AlexP11223** [comment]
This output seems fine. Try `npm run start`

**Comment by 1Roishi** [comment]
Yes finally it works thank you very much!
