### ISSUE TITLE
Slack ignores CAPTCHA_HANDLER_TOKEN

### ISSUE THREAD

**Issue by AlexP11223** [jef/streetmerchant#2428]
Looks like Slack always uses token from `SLACK_TOKEN` ignoring `CAPTCHA_HANDLER_TOKEN`.

https://github.com/jef/streetmerchant/blob/d652b4936435377d36268141a2b63c8798f7f95b/src/messaging/slack.ts#L6-L7

I guess it should either try `CAPTCHA_HANDLER_TOKEN` first when calling `getSlackCaptchaInputAsync`, and then maybe fallback to `SLACK_TOKEN` if empty, or the documentation needs to be updated.

@klords

**Comment by klords** [comment]
Thanks, will get this fixed right away. We definitely want both tokens to
be honored (even if they will practically always be the same).
