### ISSUE TITLE
No notification for Captch at Amazon DE

### ISSUE THREAD

**Issue by Loco360** [jef/streetmerchant#2430]
## Expected Behavior

streetmerchant shows me @ Amazon the Code Captcha. No PM is getting sent. 
When i test it with the test command it works flawlessly

preview: ![image](https://cdn.discordapp.com/attachments/776482351102427196/835477768950251520/unknown.png)
test: 
![image](https://user-images.githubusercontent.com/47069874/115959456-956be980-a50c-11eb-860c-f690d77ad81a.png)

**Comment by AlexP11223** [comment]
Yes, it is not added to the configs of other amazon.

You can try adding it like here
https://github.com/jef/streetmerchant/blob/d652b4936435377d36268141a2b63c8798f7f95b/src/store/model/amazon.ts#L20-L24

**Comment by Loco360** [comment]
@AlexP11223 I edited the file and it works! Thanks
![image](https://user-images.githubusercontent.com/47069874/116028957-8e51f200-a658-11eb-870a-8118f860e2e7.png)
