### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dimas228822** [jef/streetmerchant#2431]
Hello, I apologize in advance for possible errors (I'm from Russia), I tried to start the bot, but the following message appeared on the command line:
up to date, audited 1203 packages in 3s

145 packages are looking for funding
   run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  @bridgerakol/samsung-smart-api  *
  Depends on vulnerable versions of axios
  node_modules/@bridgerakol/samsung-smart-api

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by AlexP11223** [comment]
It's probably fine. Try `npm run start`.

**Comment by Dimas228822** [comment]
Hello again, thank you for your answer, I'm flattered. Of course, I tried
to obfuscate the "npm run start" command, but it was followed by:
***@***.*** prestart
> npm run compile


> ***@***.*** compile
> tsc

Version 4.2.4
Syntax: tsc [options] [file ...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @ args.txt
          tsc --build tsconfig.json

Options:
 -h, --help Print this message.
 -w, --watch Watch input files.
 --pretty Stylize errors and messages using color and context
(experimental).
 --all Show all compiler options.
 -v, --version Print the compiler's version.
 --init Initializes a TypeScript project and creates a tsconfig.json file.
 -p FILE OR DIRECTORY, --project FILE OR DIRECTORY Compile the project
given the path to its configuration file, or to a folder with a
'tsconfig.json'.
 -b, --build Build one or more projects and their dependencies, if out of
date
 -t VERSION, --target VERSION Specify ECMAScript target version: 'ES3'
(default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019',
'ES2020', or ' ESNEXT '.
 -m KIND, --module KIND Specify module code generation: 'none', 'commonjs',
'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'.
 --lib Specify library files to be included in the compilation.
                                                      'es5' 'es6' 'es2015'
'es7' 'es2016' 'es2017' 'es2018' 'es2019' 'es2020' 'esnext' 'dom'
'dom.iterable' 'webworker' 'webworker.importscripts'' webworker.iterable ''
scripthost '' es2015.core '' es2015.collection '' es2015.generator ''
es2015.iterable '' es2015.promise '' es2015.proxy '' es2015.reflect ''
es2015.symbol '' es2015.symbol.wellknown '' es2016.array.include ''
es2017.object '' es2017.sharedmemory '' es2017.string '' es2017.intl ''
es2017.typedarrays '' es2018.asyncgenerator '' es2018.asynciterable ''
es2018.intl '' es2018 .promise '' es2018.regexp '' es2019.array ''
es2019.object '' es2019.string '' es2019.symbol '' es2020.bigint ''
es2020.promise '' es2020.sharedmemory '' es2020.string '' es2020
.symbol.wellknown '' es2020.intl '' esnext.array '' esnext.symbol ''
esnext.asynciterable '' esnext.intl '' esnext.bigint '' esnext.string ''
esnext.promise '' esnext.weakref '
 --allowJs Allow javascript files to be compiled.
 --jsx KIND Specify JSX code generation: 'preserve', 'react-native',
'react', 'react-jsx' or 'react-jsxdev'.
 -d, --declaration Generates corresponding '.d.ts' file.
 --declarationMap Generates a sourcemap for each corresponding '.d.ts' file.
 --sourceMap Generates corresponding '.map' file.
 --outFile FILE Concatenate and emit output to single file.
 --outDir DIRECTORY Redirect output structure to the directory.
 --removeComments Do not emit comments to output.
 --noEmit Do not emit outputs.
 --strict Enable all strict type-checking options.
 --noImplicitAny Raise error on expressions and declarations with an
implied 'any' type.
 --strictNullChecks Enable strict null checks.
 --strictFunctionTypes Enable strict checking of function types.
 --strictBindCallApply Enable strict 'bind', 'call', and 'apply' methods on
functions.
 --strictPropertyInitialization Enable strict checking of property
initialization in classes.
 --noImplicitThis Raise error on 'this' expressions with an implied 'any'
type.
 --alwaysStrict Parse in strict mode and emit "use strict" for each source
file.
 --noUnusedLocals Report errors on unused locals.
 --noUnusedParameters Report errors on unused parameters.
 --noImplicitReturns Report error when not all code paths in function
return a value.
 --noFallthroughCasesInSwitch Report errors for fallthrough cases in switch
statement.
 --types Type declaration files to be included in compilation.
 --esModuleInterop Enables emit interoperability between CommonJS and ES
Modules via creati

сб, 24 апр. 2021 г. в 23:27, Alex Pantechovskis ***@***.***>:

**Comment by AlexP11223** [comment]
Are you running it from the streetmerchant dir?

```
cd /........./streetmerchant
npm i
npm run start
```

Also format the messages https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by Dimas228822** [comment]
Thank you very much, you helped me a lot.

вс, 25 апр. 2021 г. в 20:30, Alex Pantechovskis ***@***.***>:

**Comment by klords** [comment]
Duplicate #1941
