### ISSUE TITLE
Filtro venditore / Seller filter

### ISSUE THREAD

**Issue by DotHack88** [jef/streetmerchant#2445]
Ciao,
vorrei chiederti se c'è  la possibilità di poter settare il bot in modo che mi dia solo i prodotti venduti e spediti da Amazon.
----
Hello,
I would like to ask you if there is the possibility of being able to set the bot so that it only gives me the products sold and shipped by Amazon.

**Comment by AlexP11223** [comment]
No.

**Comment by DotHack88** [comment]
> No.

Are u sure ?

**Comment by AlexP11223** [comment]
All available filters: https://www.jef.buzz/streetmerchant/reference/filter/

"brand" here means Asus, EVGA, etc. from the link description in the config or (for store configs using `linksBuilder`) from the product name on the store page.

**Comment by DotHack88** [comment]
I mean by Amazon.  that the product is sold by Amazon.  can you filter?

**Comment by AlexP11223** [comment]
> No.

:arrow_up:

**Comment by DotHack88** [comment]
> > No.
> 
> ⬆️

Ok
