### ISSUE TITLE
Prices

### ISSUE THREAD

**Issue by DotHack88** [jef/streetmerchant#2451]
how can i enforce the price limit?  if you can attach some screenshots because I don't respect them.  find products with higher prices

**Comment by AlexP11223** [comment]
`MAX_PRICE_SERIES_3060`, etc.
https://www.jef.buzz/streetmerchant/reference/filter/

**Comment by DotHack88** [comment]
I do it
![Uploading SAVE_20210427_164507.jpg…]()

**Comment by DotHack88** [comment]
> `MAX_PRICE_SERIES_3060`, etc.
> https://www.jef.buzz/streetmerchant/reference/filter/

How can do ?
can you give me an example

**Comment by DotHack88** [comment]
How can resolve it ?
![image](https://user-images.githubusercontent.com/40268801/116286506-982a4100-a78f-11eb-8315-937a577434a1.png)

MAX_PRICE_SERIES_3060="700"
MAX_PRICE_SERIES_3060TI="800"
MAX_PRICE_SERIES_3070="900"
MAX_PRICE_SERIES_3080="1200"

**Comment by AlexP11223** [comment]
What price does it show in the notification in telegram?

**Comment by Fang86** [comment]
Not sure if this will help, but maybe remove the quotes?

**Comment by DotHack88** [comment]
> Not sure if this will help, but maybe remove the quotes?

I want to be notified if those products fall within the specified prices

**Comment by DotHack88** [comment]
> What price does it show in the notification in telegram?

the price is wrong.  as I hope I have correctly set the price of the product.

**Comment by meta-434** [comment]
> Not sure if this will help, but maybe remove the quotes?

this is correct. Mine enforces price limits with unquoted numbers.

**Comment by Jswaggy1224** [comment]
So do you just add the numebr you want after the = or do you wan to do comma then the price you want?

**Comment by WeDoSys** [comment]
no comma just the price
eg. MAX_PRICE_SERIES_3070=800
