### ISSUE TITLE
main loop could be optimized better

### ISSUE THREAD

**Issue by hnry** [jef/streetmerchant#2454]
I feel like streetmerchant uses more resources (cpu) than it needs to for it's doing. Here are some ideas that I think can improve this:
1. The main loop for checking sites creates a new Page and closes this Page afterwards. That is it's creating a new tab per link per try. This seems wasteful on resources, can't we just re-use Pages to not have to create a new tab all the time?
2. Main intercepts request regardless if proxy, adblock, low bandwidth options are enabled or not. Ideally it shouldn't intercept requests of none of these are on.

Tried these changes on a local fork, CPU improved a bit, and chromium processes more stable (less excessive spawning new processes).

**Comment by AlexP11223** [comment]
PRs are always welcome :)

**Comment by trillox9** [comment]
> I feel like streetmerchant uses more resources (cpu) than it needs to for it's doing. Here are some ideas that I think can improve this:
> 
> 1. The main loop for checking sites creates a new Page and closes this Page afterwards. That is it's creating a new tab per link per try. This seems wasteful on resources, can't we just re-use Pages to not have to create a new tab all the time?
> 2. Main intercepts request regardless if proxy, adblock, low bandwidth options are enabled or not. Ideally it shouldn't intercept requests of none of these are on.
> 
> Tried these changes on a local fork, CPU improved a bit, and chromium processes more stable (less excessive spawning new processes).

How to re-use same page without closing? Can you share your local fork changes? Thanks

**Comment by trillox9** [comment]
> First let me say saving a few CPU cycles does **not** mean higher chance at results.
> 
> The changes are simple, see https://github.com/jef/streetmerchant/blob/main/src/store/lookup.ts#L288 it closes the tab it created to check a link. It does it every link, create, close, create, close, etc. I am suggesting to just leave a tab open, either per link or per store. You can accomplish it by just storing the tab info somewhere and looking it up, if it doesn't exist then create it and store it, so the next loop it'll re-use that tab.
> 
> Other thing is request intercept:
> https://github.com/jef/streetmerchant/blob/main/src/store/lookup.ts#L194
> https://github.com/jef/streetmerchant/blob/main/src/store/lookup.ts#L228
> It's set twice, and it's only for people who use proxy, low bandwidth mode, adblock. It's extra overhead for those who don't use these things.
> 
> I just don't have the time to make the changes so it works with all the other options in streetmerchant. It's a good first time contribution PR for those who want to take a shot at it.

Can you help me to deploy this improvements? I want to just leave a tab open and avoid close, create, close ecc.
Also I use low bandwidth but i don'use proxy and adblock, what i have to do? Thanks for help

**Comment by trillox9** [comment]
+
