### ISSUE TITLE
 error TS1005: ',' expected.

### ISSUE THREAD

**Issue by DotHack88** [jef/streetmerchant#2466]
I tried to add the following product to the Amazon store list (it, de, fr, es, co.uk).

https://www.amazon.it/dp/B08WB6R2K4/ref=cm_sw_r_wa_awdb_imm_H9XHCW06FJWR4EWEGSKK?_encoding=UTF8&psc=1

But when I run with 'npm run start' the program gives me these errors.

![image](https://user-images.githubusercontent.com/40268801/116516597-1260df80-a8ce-11eb-9e5a-fc6cd3d8a031.png)

**Comment by klords** [comment]
The error says it all: you forgot to put a comma at the end of the line preceding the url. In your screenshot, line 218 needs a comma at the end.
