### ISSUE TITLE
amd-be false positives

### ISSUE THREAD

**Issue by alceausu** [jef/streetmerchant#2467]
## Expected Behavior

Streetmerchant should report out-of-stock for amd-be

## Current Behavior

Streetmerchant logs 
``[10:10:22 AM] info :: 🚀🚨 [amd-be] [amd (rx6800)] amd reference :: IN STOCK 🚨🚀
https://www.amd.com/en/direct-buy/5458374000/be
``
but the screenshot and the opened page does not show the product in stock.

## Steps to Reproduce

streetmerchant up to 
commit cac7c20193caaec5d41291104e66aa01a65adceb (HEAD -> main, origin/main, origin/HEAD)

## Environment

- OS: Windows 10.0.19041
- node.js v14.16.1

<details>
<summary>dotenv</summary>

```dotenv
AUTO_ADD_TO_CART=false
HEADLESS=true
INCOGNITO=false
IN_STOCK_WAIT_TIME=30
MAX_PRICE_SERIES_3070="1150"
MAX_PRICE_SERIES_3080="1600"
MAX_PRICE_SERIES_RX6800="1200"
MAX_PRICE_SERIES_RX6800XT="1400"
MAX_PRICE_SERIES_RX6900XT="1600"
PAGE_BACKOFF_MIN="180000"
PAGE_BACKOFF_MAX="540000"
PAGE_SLEEP_MIN="60000"
PAGE_SLEEP_MAX="180000"
RESTART_TIME=1800000
SHOW_ONLY_SERIES="rx6800,rx6800xt,rx6900xt,3070,3080"
STORES="amazon-de-warehouse,amd-be,asus-de,evga-eu,nvidia-fr"
```

</details>

**Comment by Eribaeri** [comment]
I gpt the same problem

**Comment by dohamann** [comment]
This seems to be a duplicate of #1329, #1995, #2180 and #2219.
