### ISSUE TITLE
Screenshot not working for Telegram

### ISSUE THREAD

**Issue by Bruceforce** [jef/streetmerchant#2529]
## Expected Behavior

I should receive a Telegram message with a screenshot attached.

## Current Behavior

I receive a Telegram message without screenshot attached.

## Steps to Reproduce

Just start the container with the provided dotenv. There is no error in the logs regarding this issue. My guess is that screenshots are not working in headless mode anyways, just wanted to make sure. If this is the case I think it should be added to documentation at least. Or maybe some kind of warning log at the beginning "Screenshot are not supported in headless mode"

## Environment

- OS: docker on Debian with nightly image tag from today.

<details>
<summary>dotenv</summary>

```dotenv
# App

TZ=Europe/Berlin
AUTO_ADD_TO_CART=false
BROWSER_TRUSTED=true
IN_STOCK_WAIT_TIME=600
LOG_LEVEL=error
PAGE_SLEEP_MIN=30000
PAGE_SLEEP_MAX=60000
OPEN_BROWSER=false
SCREENSHOT=true

# Filter
STORES=acompc,alternate,amazon-de,amazon-de-warehouse,amd-de,arlt,asus-de,caseking,computeruniverse,cyberport,equippr,euronics-de,expert,futurex,galaxus,gamestop-de,medimax,mindfactory,notebooksbilliger,otto,pcking,proshop-de,saturn,spielegrotte,mediamarkt
STORE=nvidia-de
SHOW_ONLY_SERIES=rx6700xt,3060ti
# Notification
... Telegram secret
```

</details>

## Logs

There is nothing in this log (because of log level error). I could produce other logs I had a starting point for debugging.

**Comment by klords** [comment]
Puppeteer can and does take screenshots in headless mode (I haven't specifically checked to see if there's a problem with Docker). Regardless, screenshots don't get sent to Telegram currently, only Pushover.

**Comment by Bruceforce** [comment]
Oh I see. Than this is the issue here and not docker. I think it's not stated that screenshots are only supported when using Pushover. But then this issue becomes more like a feature request or documentation enhancement I guess.

**Comment by Bruceforce** [comment]
Still valid. Remove stale label.

**Comment by Bruceforce** [comment]
Still valid.

**Comment by Bruceforce** [comment]
Not using this anymore. Most likely still not fixed but closing anyways.
