### ISSUE TITLE
Discord Captcha: No response from user

### ISSUE THREAD

**Issue by mikehobi** [jef/streetmerchant#2576]
## Expected Behavior

Discord Captcha DM bot correctly grabs the last message

## Current Behavior

- Timeout occurs with `no response from user` warning
- No message is received because `message.reference` is `null` at this filter call:
https://github.com/jef/streetmerchant/blob/main/src/messaging/discord.ts#L163

I can fix this behavior by removing the `.filter` call

## Steps to Reproduce

- Setup discord bot/app for captcha messages
- Run `npm run start`
- Get DM with correct captcha image
- Message with answer
- Nothing happens until it times out

## Environment

- OS:

<details>
<summary>dotenv</summary>

```dotenv
AUTO_ADD_TO_CART=true
SHOW_ONLY_SERIES=3080,3070
STORES=walmart,bestbuy,bandh,amazon
PLAY_SOUND=./echoed-ding-459.mp3
DISCORD_WEB_HOOK=********
LOW_BANDWIDTH=true
CAPTCHA_HANDLER_SERVICE=discord
CAPTCHA_HANDLER_USER_ID=********
CAPTCHA_HANDLER_TOKEN=********
```

</details>

**Comment by klords** [comment]
https://www.jef.buzz/streetmerchant/reference/captcha/#how-to-use

Note the Attention field in the link above. You have to reply directly to the message, not just DM the bot back.

**Comment by mikehobi** [comment]
> https://www.jef.buzz/streetmerchant/reference/captcha/#how-to-use
> 
> 
> 
> Note the Attention field in the link above. You have to reply directly to the message, not just DM the bot back.

Ah I see. The docs are very wordy, really easy to skip over these details.

**Comment by klords** [comment]
Yup, that's why we put it in a big yellow attention box and gave it its own FAQ entry as well.
