### ISSUE TITLE
Move dotenv into subfolder to support containers

### ISSUE THREAD

**Issue by kiowadriver** [jef/streetmerchant#2581]
## Expected Behavior
To be able to update the container and have the dotenv file located to a mapped share so that setting remain unchanged

## Current Behavior
Because the dotenv file is in the root of the container it is not possible to map a drive share and abstract away the dotenv from container updates.

Mucho inconvenience

## Environment

- OS: 
- all

Please create a folder in the root of the project that contains the dotenv.  This allows the docker container versions to map this folder as a host share and isolate the file between container updates.

**Comment by tunip** [comment]
Did you tried to mount your dotenv as file to your container?

`... -v /your/dotenv:/.dockerenv ...`

**Comment by kiowadriver** [comment]
Yes,

But in unraid you can only map a volume as a drive. Need to have the dotenv
in a directory below the root so that directory can be specified and
mounted.

**Comment by c0rrre** [comment]
Hi,
You can map a file in unraid, I also thought it isnt possible but i was wrong.
Just add a new path and point the host and container path to a file
