### ISSUE TITLE
Prices with thousands decimal separator not filtering properly

### ISSUE THREAD

**Issue by liam-maps** [jef/streetmerchant#2594]
## Expected Behavior

If I filter a product with a price under 1000€, a more expensive match of that product shouldn't be notified. I reported this behaviour back in the days, and even when the issue appears as closed, it keeps happening.
Maybe it has to do with decimal separators, because here we use the colon for thousands, and the comma for cents:
https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use

## Current Behavior

A product priced over the limit filter price appears on the log and I get notified

## Steps to Reproduce

https://www.amazon.es/dp/B08HH1BMQQ
This product is priced 2.199,00 €, which is over the limit I'm testing, which is 1000€, but I keep getting notifications.

## Environment

- OS: Kubuntu 19.10
Fresh install of Streetmerchant and npm
<details>
<summary>dotenv</summary>

```dotenv
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=""
ASCII_COLOR=""
AUTO_ADD_TO_CART=""
BROWSER_TRUSTED=""
COUNTRY="spain"
DESKTOP_NOTIFICATIONS=""
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_PASSWORD=""
EMAIL_TO=""
EMAIL_USERNAME=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH="true"
MAX_PRICE_SERIES_3060TI="500"
MAX_PRICE_SERIES_3070="800"
MAX_PRICE_SERIES_3080="1000"
MAX_PRICE_SERIES_3090="2000"
MAX_PRICE_SERIES_CORSAIR_SF=""
MAX_PRICE_SERIES_RX6800=""
MAX_PRICE_SERIES_RX6800XT=""
MAX_PRICE_SERIES_RX6900XT=""
MAX_PRICE_SERIES_RYZEN5600=""
MAX_PRICE_SERIES_RYZEN5800=""
MAX_PRICE_SERIES_RYZEN5900=""
MAX_PRICE_SERIES_RYZEN5950=""
MAX_PRICE_SERIES_SONYPS5C=""
MAX_PRICE_SERIES_SONYPS5DE=""
MAX_PRICE_SERIES_TEST=""
MICROCENTER_LOCATION=""
MQTT_BROKER_ADDRESS=""
MQTT_BROKER_PORT=""
MQTT_CLIENT_ID=""
MQTT_PASSWORD=""
MQTT_QOS=""
MQTT_TOPIC=""
MQTT_USERNAME=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER="false"
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN="10000"
PAGE_SLEEP_MAX="20000"
PAGE_TIMEOUT=""
PAGERDUTY_INTEGRATION_KEY=""
PAGERDUTY_SEVERITY=""
PHILIPS_HUE_API_KEY=""
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=""
PHILIPS_HUE_CLOUD_CLIENT_ID=""
PHILIPS_HUE_CLOUD_CLIENT_SECRET=""
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=""
PHILIPS_HUE_LAN_BRIDGE_IP=""
PHILIPS_HUE_LIGHT_COLOR=""
PHILIPS_HUE_LIGHT_IDS=""
PHILIPS_HUE_LIGHT_PATTERN=""
PHONE_CARRIER=""
PHONE_NUMBER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PROTOCOL=""
PROXY_PORT=""
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS=""
SHOW_ONLY_SERIES="3070, 3080, 3090"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT=""
STORES="pccomponentes, amazon-es, elcorteingles"
TELEGRAM_ACCESS_TOKEN="itsasecret"
TELEGRAM_CHAT_ID="itsasecret"
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITCH_ACCESS_TOKEN=""
TWITCH_CHANNEL=""
TWITCH_CLIENT_ID=""
TWITCH_CLIENT_SECRET=""
TWITCH_REFRESH_TOKEN=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""
WEB_PORT=""

```

</details>

## Logs

[17:30:23] info :: ✖ [pccomponentes] [asus (3070)] strix oc :: OUT OF STOCK
[17:30:25] info :: ✖ [amazon-es] [evga (3080)] xc3 :: OUT OF STOCK
[17:30:30] info :: 🚀🚨 [amazon-es] [evga (3080)] xc3 black :: IN STOCK 🚨🚀
https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HH1BMQQ&Quantity.1=1
[17:30:30] info :: ✔ telegram message sent
[17:30:31] info :: ✖ [pccomponentes] [gigabyte (3070)] vision oc :: OUT OF STOCK
[17:30:35] info :: ✖ [amazon-es] [gigabyte (3080)] gaming oc :: OUT OF STOCK
[17:30:38] info :: ✖ [pccomponentes] [pny (3070)] dual fan :: OUT OF STOCK
[17:30:40] info :: ✖ [amazon-es] [gigabyte (3080)] eagle oc :: OUT OF STOCK

**Comment by PaoloOranges** [comment]
Hey! this might help you: https://github.com/jef/streetmerchant/issues/2199#issuecomment-869541609
