### ISSUE TITLE
Store Error  "some of the selected stores (grayed out) dont have what you are looking for "

### ISSUE THREAD

**Issue by Blooddragoo** [jef/streetmerchant#2607]
Hello everyone!

First of all thanks for the nice bot m8. I really makes life more easy.

I am looking for a PS5 in Austria so i am looking at mediamarkt-at but there is always the error code: some of the selected stores (grayed out) dont have what you are looking for. But when I try using the german version "mediamarkt" the search works. Both Sides are set up the same so i think theres a bug.

Thanks!

**Comment by jef** [comment]
It's on purpose. It's because:

a. The stores you've selected do not have the products (literally)
b. The stores you've selected have the products, but we don't have them in our project. (See [Updating the models](https://www.jef.buzz/streetmerchant/help/general/#updating-the-models).)
