### ISSUE TITLE
Keep Getting False Positive Due to Price Check Failure

### ISSUE THREAD

**Issue by BzowK** [jef/streetmerchant#2655]
## Expected Behavior

Product should be skipped as not in price range, but reports as valid "IN STOCK" result thus stopping script

## Current Behavior

Product reported "In Stock" and, launches browser, and stops script.  My dotenv sets max price at 650, but this result is 849.  "Price exceeds limit" works for all other links - just not this specific model/link.  Have run into many times recently as item as come into stock frequently but stops script each time it does.

The only item that I've encountered with the issue is "EVGA GeForce RTX 3060 XC Gaming, 12G-P5-3657-KR, 12GB GDDR6, Dual-Fan, Metal Backplate" https://www.amazon.com/dp/B08WM28PVH

## Steps to Reproduce

Set "MAX_PRICE_SERIES_3060" to 650, include "amazon" in "STORES", include "3060" in "SHOW_ONLY_MODELS".

## Environment

- OS: Ubuntu (Have reproduced on two separate systems each running Ubunutu)
- Using RiseupVPN (running without temp put my IP on some sort of temp blacklist)
- Running with latest commits as of posting
Thanks!

<details>
<summary>dotenv</summary>

```dotenv

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
DESKTOP_NOTIFICATIONS=yes
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=xxxxxxxxxxxxx
EMAIL_TO=xxxxxxxxxxxxxxxxxxxx
EMAIL_USERNAME=xxxxxxxxxxxxxxxxxxx
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH="false"
MAX_PRICE_SERIES_3060=650
MAX_PRICE_SERIES_3060TI=650
MAX_PRICE_SERIES_3070=650
MAX_PRICE_SERIES_3080=650
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=xxxxxxxxxxxxx
MQTT_BROKER_PORT=1883
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=gpuscript/alert
MQTT_USERNAME=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN="1000"
PAGE_SLEEP_MAX="3000"
PAGE_TIMEOUT="60000"
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=att
PHONE_NUMBER=6155854518
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_DEVICE=
PUSHOVER_PRIORITY=
PUSHOVER_RETRY=
PUSHOVER_SOUND=
PUSHOVER_TOKEN=xxxxxxxxxxxxxxxxxxxxxxx
PUSHOVER_USER=xxxxxxxxxxxxxxxxxxxxx
RESTART_TIME=
SCREENSHOT=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3060,3060ti,3070
SLACK_CHANNEL=
SLACK_TOKEN=
SMARTTHINGS_TOKEN=
SMARTTHINGS_SWITCH_LABEL=
SMTP_ADDRESS=xxxxxxxxxxxxxx
SMTP_PORT=587
STORES=amazon,bestbuy,asus,newegg,officedepot,walmart
TELEGRAM_ACCESS_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TELEGRAM_CHAT_ID=-xxxxxxxxxxx
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
FREEMOBILE_ID=
FREEMOBILE_API_KEY=
WEB_PORT=3070

```

</details>

**Comment by coolmatt4321** [comment]
I'm having the same issue with the same item. It keeps opening check out every couple of minutes when it is above my max price. No other product does this, they all respect the max price parameter.

**Comment by BzowK** [comment]
Yeah, after not getting a reply here; I just went into ./streetmerchant/src/store/model, edited the file amazon.ts. removed the info for that model, saved, and it no longer detected it.  You may want to do the same until fixed.  

Hope it helps

**Comment by toneewa** [comment]
From what I gather, this is from items being listed as "Used" condition. Let us know when there is a remedy.

**Comment by andreperegrina** [comment]
It seems that the problem is that sometimes it doesn't extract the price and because is empty the price is not bigger than maxPrice.
I'll still debugging but I let you know if I solved

**Comment by toneewa** [comment]
Solution would be to add a filter too only check Amazon.com as the Seller. 3rd party sellers, "Used", pages with multiple products always seem to cause issues.

**Comment by toneewa** [comment]
E.g., where alerts are broken because of 3rd party sellers.
![image](https://user-images.githubusercontent.com/25932172/135844407-9ad7b8a3-d82f-4596-83e9-f812be2f0219.png)
