### ISSUE TITLE
[Bug]: STATUS CODE ERROR 403 for NVIDIA site (no IP ban)

### ISSUE THREAD

**Issue by marcel151** [jef/streetmerchant#2769]
### Expected Behavior

Streetmerchant should work normally for NVIDIA site (nvidia-de in my case). Problem occurs since a few days.

### Current Behavior

It seems that NVIDIA changed something on their site. After 2 fetching cycles I get the error message.

I don't think this is an IP ban, since when I restart streetmerchant it works again for two cycles.  Raising sleep time does not help. 

Can this be fixed?

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
STATUS CODE ERROR 403

Access Denied
You don't have permission to access "http://shop.nvidia.com/de-de/geforce/store/gpu/?" on this server.
```

### Configuration

```shell
Only changed lines:

HEADLESS="false"
SHOW_ONLY_BRANDS="nvidia"
SHOW_ONLY_MODELS="founders edition"
SHOW_ONLY_SERIES="3070,3070ti,3080,3080ti,3090"
STORES="nvidia-de:50000:100000"
TELEGRAM_ACCESS_TOKEN="xxx"
TELEGRAM_CHAT_ID="xxx"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crag-r** [comment]
Same problem here, but for nvidia-gb

Two cycles then 403 errors, if I restart the container it will check again for two cycles then 403 forever until restart.

Not IP banned.

**Comment by DjLex2021** [comment]
The same here. Nvidia Store is not working. I tried all the countries.
Is there any fix for this?

**Comment by itsWavs** [comment]
Is it still fixed for you guys? 
When I enable incognito mode, Error 403 starts right away without a running cycle.

**Comment by itsWavs** [comment]
Follow Up, maybe it works for other people too, I managed to solve the issue by adding some chrome resart time.

**Comment by notflip** [comment]
> Follow Up, maybe it works for other people too, I managed to solve the issue by adding some chrome resart time.

What do you mean with chrome restart time?

**Comment by arall** [comment]
> > Follow Up, maybe it works for other people too, I managed to solve the issue by adding some chrome resart time.
> 
> What do you mean with chrome restart time?

Adding (for example) `RESTART_TIME=60000` in the `doenv` file.

https://www.jef.buzz/streetmerchant/reference/application/
