### ISSUE TITLE
[Bug]: Amazon-uk is ignoring MAX_PRICE_SERIES filter

### ISSUE THREAD

**Issue by LilPeck1** [jef/streetmerchant#2813]
### Expected Behavior

Streetmerchant should have ignored the amazon-uk items that were coming back with higher price tags than what was specified in the MAX_PRICE_SERIES filter.

### Current Behavior

Streetmerchant is instead accepting amazon-uk items that have a higher price tag than what is specified in the MAX_PRICE_SERIES filter.

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
n/a
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.buzz/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################
EMAIL_PASSWORD=Password
EMAIL_USERNAME=Email
LOW_BANDWIDTH=true
MAX_PRICE_SERIES_3070=500
MAX_PRICE_SERIES_3070TI=600
MAX_PRICE_SERIES_3080=700
SHOW_ONLY_SERIES=3070,3080,3070ti
STORES=amazon-uk,amd-uk,ao,argos,aria,awd,box,bt,ccl,corsair-uk,currys,ebuyer,game,johnlewis,novatech,overclockers,scan,shopto,smythstoys,very,nvidia-gb
SMTP_ADDRESS=smtp-mail.outlook.com
SMTP_PORT=587
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LilPeck1** [comment]
I'm not a coder so bear with me... I looked through the src\store\model\amazon-uk file and saw that it was referencing the US priceblock_ourprice container. I don't think the UK uses the same one, although I'm not sure what its alternative is. I tried a few things in its place but it didn't seem to work. For all I know this could be completely irrelevant?

**Comment by Froghut** [comment]
For amazon.de at least it seems the fix is to open src\store\model\amazon-de.ts and change '#priceblock_ourprice' to '.a-text-price'.

**Comment by MurrayGroves** [comment]
> For amazon.de at least it seems the fix is to open src\store\model\amazon-de.ts and change '#priceblock_ourprice' to '.a-text-price'.

This fixed it for me on amazon-uk.

**Comment by cyandura** [comment]
> For amazon.de at least it seems the fix is to open src\store\model\amazon-de.ts and change '#priceblock_ourprice' to '.a-text-price'.

Can confirm this problem is happening for amazon US and this fix works. labels.maxPrice.container just needs to be updated
