### ISSUE TITLE
[Bug]: saturn, mediamarkt-de and smythstoys-de returning 403

### ISSUE THREAD

**Issue by Sanafan** [jef/streetmerchant#2861]
### Expected Behavior

Hey guys,
i'm new to streetmerchant but its a great solution to track the shops you want. As my setup i deployed a docker/portainer environment running a container for every page i like to poll so about 15.

But i'm running in problems with saturn, mediamarkt-de and smythstoys which will only give me status code 403 back and not a OUT OF STOCK or anything like that. 

Am i doing anything wrong? Is this a bug inside the software? I tried to add puppeteer-extra-stealth-plugin as i'm thinking that the sites are discovering my bot activitys but i couldn't figure out where to add it. 
So maybe someone can tell me how to get those shops running, any help would be appreciated!

These are my defined environment variables:

`DOCKER | true
HEADLESS | false
INCOGNITO | true
NODE_VERSION | 16.6.1
PAGE_SLEEP_MAX | 15000
PAGE_SLEEP_MIN | 10000
PAGE_TIMEOUT | 25000
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PUPPETEER_EXECUTABLE_PATH | /usr/bin/chromium-browser
SHOW_ONLY_SERIES | sonyps5c,sonyps5de
STORES | saturn
YARN_VERSION | 1.22.5
`

### Current Behavior

Those shops are not running and only return 403

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
[10:33:45 PM] warn :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
```

### Configuration

```shell
`DOCKER | true
HEADLESS | false
INCOGNITO | true
NODE_VERSION | 16.6.1
PAGE_SLEEP_MAX | 15000
PAGE_SLEEP_MIN | 10000
PAGE_TIMEOUT | 25000
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PUPPETEER_EXECUTABLE_PATH | /usr/bin/chromium-browser
SHOW_ONLY_SERIES | sonyps5c,sonyps5de
STORES | saturn
YARN_VERSION | 1.22.5
`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jensemann77** [comment]
Hi also happens with windows os, that behavior occurs when the website requests are to fast and to many, in headless mode you'll see the captcha button for "I'm human" and afterwards the captcha is popping up, this shops using the captchas with boots and buses.
