### ISSUE TITLE
[Bug]: Walmart's press-and-hold makes it unusable

### ISSUE THREAD

**Issue by michaelkrieger** [jef/streetmerchant#2866]
### Expected Behavior

streetmerchant will display the product page

### Current Behavior

Instead, we see this logic with a bot prevention script:
![success-1637869110750](https://user-images.githubusercontent.com/7321259/143493944-908ad994-f87a-455d-8081-21f5d3e0d2a1.png)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
✖ [walmart-ca] [microsoft (xboxsx)] xbox series x :: OUT OF STOCK
```

### Configuration

```shell
STORES=bestbuy-ca,costco-ca,walmart-ca,amazon-ca
SHOW_ONLY_MODELS=xbox series x,ps5 console,ps5 digital
SHOW_ONLY_SERIES=xboxsx,sonyps5c,sonyps5de
SHOW_ONLY_BRANDS=microsoft,sony
MAX_PRICE_SERIES_SONYPS5C=850
MAX_PRICE_SERIES_SONYPS5DE=750
MAX_PRICE_SERIES_XBOXSX=750
PAGE_SLEEP_MIN=45000
IN_STOCK_WAIT_TIME=1800
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lehdihs** [comment]
literally starving to death trying to use the walmart website
