### ISSUE TITLE
[Feature]: RTX 4000 series

### ISSUE THREAD

**Issue by emike09** [jef/streetmerchant#3053]
### Proposed solution

I'd love to see some updates for the RTX 4000 series. Or ideas on how I could add that myself? 

### Objective

Find an RTX 4000 series card. 

### Goals

Find an RTX 4000 series card. 

### Non-goals

Perhaps the upcoming RDNA3 cards as well? 

### Anti-goals

Have my IP blocked.

**Comment by leogobb** [comment]
Hi, I'm looking for the same thing.
I haven't had time yet but gonna be working on trying to make it work for RTX 4000 series, doesn't seem too hard honestly but we'll see.
If you're interested, documentation on how to do this can be found at https://www.jef.buzz/streetmerchant/help/general/

**Comment by hellbinder** [comment]
[store -> model folder] (https://github.com/jef/streetmerchant/tree/main/src/store/model) contains all the stores and the URL for each item. You'd have to add each new item and its URL to each store you'd want to search for.

Also need to add the new series '4090' to the Series variable in store.ts

**Comment by hellbinder** [comment]
![image](https://user-images.githubusercontent.com/1791215/197075226-fbd7f7a9-3ea1-444d-988d-ff4eb2a13fc9.png)

Started looking into this for us sites.

**Comment by jef** [comment]
Awesome! Love to see it!

**Comment by mrmos** [comment]
opened a [PR](https://github.com/jef/streetmerchant/pull/3085) to get this going

@jhs232 I'd be happy to add the european stores for you if you have it. 

just copy and paste the `store/model` files you updated into a [gist](https://gist.github.com/) and I can get them added to this PR.

**Comment by jef** [comment]
thanks for the help @mrmos! @jhs232, feel free to add here as well and someone will be able to add to a PR

**Comment by jef** [comment]
Fixed with https://github.com/jef/streetmerchant/pull/3085

**Comment by jhs232** [comment]
@mrmos Sorry I never got back to you earlier. I added them to the #3805 thread.
