### ISSUE TITLE
[Feature]: Add Matrix as a notification option

### ISSUE THREAD

**Issue by Kerobyte** [jef/streetmerchant#3087]
### Proposed solution

https://github.com/dgtlmoon/changedetection.io has this feature, it could be examined.

### Objective

Add Matrix as a notification option.

### Goals

Receive notifications over the Matrix protocol.

### Non-goals

None.

### Anti-goals

None.

**Comment by Mr-Tech-13** [comment]
Im not sure if this can notify you, it seems to be a checking service that pushes out notifications to different services
