### ISSUE TITLE
[Feature]: Support AMD RX 7900 XT/XTX

### ISSUE THREAD

**Issue by gpuhunting** [jef/streetmerchant#3108]
### Proposed solution

Added support to search for the new GPUs

### Objective

Added support to search for the new GPUs

### Goals

Added support to search for the new GPUs

### Non-goals

none

### Anti-goals

none

**Comment by Mr-Tech-13** [comment]
Ill update my PR tomorrow

**Comment by Mr-Tech-13** [comment]
Updated
