### ISSUE TITLE
Link the product page instead of add to cart link option

### ISSUE THREAD

**Issue by gahmee** [jef/streetmerchant#362]
Having an option to link the product page instead of the add to cart link for notifications to avoid being voided out by certain websites for using the add to cart link

**Comment by jef** [comment]
> to avoid being voided out by certain websites

What do you mean by this? Are the cart URLs not working? Because if they aren't we should remove them. Otherwise, I don't know if there is any added benefit.

**Comment by gahmee** [comment]
> What do you mean by this? Are the cart URLs not working? Because if they aren't we should remove them. Otherwise, I don't know if there is any added benefit.

Some websites like newegg void orders for bot usage by using the cart URL

**Comment by jef** [comment]
Solved by using `AUTO_ADD_TO_CART`.
