### ISSUE TITLE
ASUS changed something so now their cards are in stock when they are not

### ISSUE THREAD

**Issue by matjam** [jef/streetmerchant#368]
### Description

https://store.asus.com/us/item/202009AM160000001/

Says "Coming Soon" but the bot is alerting every time saying it's in stock.

### Possible solution

I think the page needs a second or two to finish loading. I see the initial "Add To Cart" button then it changes to "Coming Soon". Disabling javascript shows the "Add To Cart" button.

**Comment by matjam** [comment]
JS enabled:

![image](https://user-images.githubusercontent.com/578676/94476735-b7bfa380-0185-11eb-8852-16050d77f0bd.png)

JS disabled:

![image](https://user-images.githubusercontent.com/578676/94476771-c443fc00-0185-11eb-9ad9-01868d4e7f57.png)

**Comment by jef** [comment]
I've been getting 403s for Asus, but not this behavior.

Need more feedback from others to continue.

**Comment by Ghoddy** [comment]
I get the same thing, It says add to cart and then goes to arrival notice right after

**Comment by matjam** [comment]
> I've been getting 403s for Asus, but not this behavior.
> 
> Need more feedback from others to continue.

The 403's are probably due to either VPN usage or your IP being banned. I get 403's from my work VPN.

Off the VPN, as of right now, if I search for 3080 on the asus store, I get no results.

Direct link to the current URL https://store.asus.com/us/item/202009AM160000001/ gives a 503.

They appear to have removed the cards from the store?

**Comment by jef** [comment]
> your IP being banned

My IP is definitely banned. So I can't really do any testing here. If you have any fixes though, please feel free to create a PR. Sorry I can't be of much help.

**Comment by jef** [comment]
We have `lables.inStock` and `labels.outOfStock`, using both should help clear this up.

**Comment by notjhoan** [comment]
Has there been a solution to this issue? I've been getting a few false positives for the dark hero with the exact same problem.

> We have `lables.inStock` and `labels.outOfStock`, using both should help clear this up.

Where exactly could I find these to solve this? I've been getting 404s as well but have got a free trial VPN to try and fix it in the meantime.

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/blob/459e9af34cb3111eed5e24741615134394584624/src/store/model/asus.ts#L7-L12

**Comment by jef** [comment]
Opening a PR for this fix now. Thanks!
