### ISSUE TITLE
Email/SMS notifications and a VPN

### ISSUE THREAD

**Issue by towerjunkie** [jef/streetmerchant#370]
First of all, i want to thank you guys for making such a useful and simple software. 

The only real issue i have is that my notifications work fine when i'm on my actual machine but when i switch to a VPN, none of these notifications work. 
This is the error i receive: couldn't send email Invalid login: 534-5.7.14

I'm using Gmail and i already set it up to allow less trustworthy sign-ins.

**Comment by gonkar193** [comment]
Odd, I have mine going through a VPN and everything is working perfectly fine. Are you sure you have your .env set up correctly?

**Comment by towerjunkie** [comment]
Yeah. I have it working fine when I'm going through my regular machine. I
just get an error when using nord vpn.
Here is a screenshot of on and Off.

But listen, I'll deal with it. I don't want you to have to focus on this
issue if a solution is not on hand.

Again, thank you for creating this open software.

**Comment by jxjftw** [comment]
Maybe the smtp relay is blocking the VPN external IP?

**Comment by tempestbk** [comment]
Firstly, thank you for creating the wonderful piece of software. I've tried all the solutions and I still cannot get the program to notify me via email or sms. I've turned on less secure app access. I've tried plugging in the default smtp info for gmail. What am I doing wrong? any suggestions?

**Comment by jef** [comment]
That's gotta be frustrating. Are you also running in a VPN?

**Comment by tempestbk** [comment]
Hello Jef,

no problem somebody in your discord helped me out. We both don't know what
it was copied his config and everything worked.

P.S. I know you are busy is there any chance you will add more Canadian
stores to the project in the future? Like Canada Computers, Memory Express

**Comment by jef** [comment]
I don't know all of those stores and rely a lot on contributors. But it's definitely a possibility!

**Comment by tempestbk** [comment]
Where should I put the suggestion?

**Comment by jef** [comment]
If you want to create a new issue there, that works great.
