### ISSUE TITLE
Req Add Store Support: Newegg Business

### ISSUE THREAD

**Issue by daddysspecialboy** [jef/streetmerchant#371]
Anyone with a small business or self employed might have an easier time catching a restock on newegg business. Or, yknow, thinking of starting a business of some kind.

**Comment by jef** [comment]
Do you need any sort of special account to checkout?

**Comment by Rawwrrrrr** [comment]
> Do you need any sort of special account to checkout?

No, you just need to create your NewEgg Business account. You can only purchase a product as guest once as a curtesy. The process is marginally different from creating a normal NewEgg account with the addition of them asking you about your "Business" during the account setup.

**Comment by jxjftw** [comment]
This is my NEB file.

`import {Store} from './store';

export const NeweggBusiness: Store = {
	labels: {
		captcha: {
			container: 'body',
			text: ['are you a human?']
		},
		inStock: {
			container: '.btn-group',
			text: ['add to cart']
		}
	},
	links: [
		{
			brand: 'test:brand',
			model: 'test:model',
			series: 'test:series',
			url: 'https://www.newegg.com/evga-geforce-rtx-2060-06g-p4-2066-kr/p/N82E16814487488'
		},
		{
			brand: 'msi',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-137-597',
			model: 'gaming x trio',
			series: '3080',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-137-597'
		},
		{
			brand: 'evga',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-487-520',
			model: 'xc3 ultra',
			series: '3080',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-487-520'
		},
		{
			brand: 'asus',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-126-453',
			model: 'tuf',
			series: '3080',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-126-453'
		},
		{
			brand: 'gigabyte',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-932-327',
			model: 'gaming oc',
			series: '3090',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-932-327'
		},
		{
			brand: 'evga',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-487-524&tpk=9b14-487-524',
			model: 'xc3 ultra',
			series: '3090',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-487-524&tpk=9b14-487-524'
		},
		{
			brand: 'asus',
			cartUrl: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-126-455',
			model: 'tuf',
			series: '3090',
			url: 'https://www.neweggbusiness.com/product/product.aspx?item=9b-14-126-455'
		},
		
	],
	name: 'neweggbusiness'
};
`

**Comment by jef** [comment]
We'll get a PR going soon. Thanks @jxjftw.
