### ISSUE TITLE
Snatcher gets stuck if more than one store exceeds navigation timeout

### ISSUE THREAD

**Issue by Intruder2110** [jef/streetmerchant#410]
I've noticed that the snatcher will stop running if more than one store exceeds the navigation timeout at the same time. I have to press Enter to get it running again. Has anyone else seen this?

![nvidia-snatcher_stuck](https://user-images.githubusercontent.com/72046502/94864238-8a2a6280-03f0-11eb-8d88-aaa7f867a06d.png)

**Comment by MRizkBV** [comment]
No issue here. Running it on 3 PCs. All running the latest version of Windows 10.

**Comment by jef** [comment]
Doesn't look like you pressed enter or that it's stuck. I'm a little lost 😞

**Comment by Intruder2110** [comment]
> Doesn't look like you pressed enter or that it's stuck. I'm a little lost 😞

The timestamp of the first timeout (12:43:51) is more than 60 seconds after the last successful check (12:41:51).

The snatcher was basically stuck for 2 minutes and 9 seconds at the 12:41:42 line. At that point I hit Enter and it spit out the 4 timeouts then resumed as usual.

**Comment by Intruder2110** [comment]
Happened again. This time I was away for ~1 hour. Note the gap in the time stamps.

![nvidia-snatcher_stuck_02](https://user-images.githubusercontent.com/72046502/94975294-19557a00-04c6-11eb-8385-c3020825a2bc.png)

**Comment by jef** [comment]
Kind of strange... Not sure if I can reproduce. Are you on the latest version?

**Comment by OmenLW** [comment]
I had the same issue tonight. 3 or 4 sites were stacked with "Navigation timeout" alerts. You do not see the timeout alerts until you hit enter. You might be able to reproduce the issue if you pull your ethernet from your PC to mimic a timeout.

**Comment by jef** [comment]
Sounds like an internet issue more than a nvidia-snatcher issue. I suppose we could try to hard reset the browser if it doesn't move anywhere. I don't know where it's getting stuck either though.

I'll do some digging and report back. Thanks!

**Comment by monstermac77** [comment]
Having the same issue here. Hanging on-start, have tried with multiple networks (home and office), also tried every configuration of stores/models that I'm looking for and all yield the same hanging. Just have to control-C, traceback doesn't appear to be helpful (to my eyes anyway). 
![image](https://user-images.githubusercontent.com/3255298/95632601-fdb51b00-0a53-11eb-82eb-ec3b114ba70f.png)

Thanks very much for this, I started the company Coursicle to do exactly this but for college classes (getting notified when seats open up) and didn't really want to recreate the effort to get myself a damn graphics card!

**Comment by monstermac77** [comment]
Here's the full output of one of the logs after control+Cing when it's stuck:

```pooch@Little-Bro-Peep _logs % cat 2020-10-10T01_19_52_413Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nvidia-snatcher@1.5.0~prestart: nvidia-snatcher@1.5.0
6 info lifecycle nvidia-snatcher@1.5.0~start: nvidia-snatcher@1.5.0
7 verbose lifecycle nvidia-snatcher@1.5.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle nvidia-snatcher@1.5.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pooch/Desktop/nvidia-snatcher/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle nvidia-snatcher@1.5.0~start: CWD: /Users/pooch/Desktop/nvidia-snatcher
10 silly lifecycle nvidia-snatcher@1.5.0~start: Args: [ '-c', 'npm run build && node build/index.js' ]
11 silly lifecycle nvidia-snatcher@1.5.0~start: Returned: code: 130  signal: null
12 info lifecycle nvidia-snatcher@1.5.0~start: Failed to exec start script
13 verbose stack Error: nvidia-snatcher@1.5.0 start: `npm run build && node build/index.js`
13 verbose stack Exit status 130
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid nvidia-snatcher@1.5.0
15 verbose cwd /Users/pooch/Desktop/nvidia-snatcher
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 130
22 error nvidia-snatcher@1.5.0 start: `npm run build && node build/index.js`
22 error Exit status 130
23 error Failed at the nvidia-snatcher@1.5.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 130, true ]
```

**Comment by monstermac77** [comment]
Ah, never mind. Looks like the issue was actually a silent config problem. Specifically, I had `founders` as the `SHOW_ONLY_MODELS` rather than `founders edition`.  This new line break in the docs really threw me for a loop. 

![image](https://user-images.githubusercontent.com/3255298/95642508-fd7a4700-0a76-11eb-8919-10c3166e12e2.png)

**Comment by jef** [comment]
Is it working fine now?

**Comment by monstermac77** [comment]
@jef Indeed it is! Thank you.

**Comment by jef** [comment]
@Intruder2110, was this your problem as well? If so, then I think I'm going to close out this issue.

**Comment by Intruder2110** [comment]
> @Intruder2110, was this your problem as well? If so, then I think I'm going to close out this issue.

@jef Not at all. I think as someone else mentioned a network glitch can cause the snatcher to get stuck.

Shouldn't it continue after the timeout though? It's not like a ping -t to an unreachable host stops after the first unsuccessful attempt. :)

**Comment by jef** [comment]
Yeah it definitely should. I've seen it hang up while in a Docker container, but I'm running now on bare metal and going to do wait and see if there is any problems.

**Comment by colemickens** [comment]
When I run this, via docker, it stops working after a "Navigation timeout". Every single time without fail.

try 1:
<details>

```
[9:25:31 PM] info :: ℹ selected stores: newegg
[9:25:31 PM] info :: ℹ selected series: ryzen5950, rx6800xt, sonyps5c, sonyps5de
[9:25:42 PM] info :: ✖ [newegg] [amd (ryzen5950)] 5950x :: OUT OF STOCK
[9:25:46 PM] info :: ✖ [newegg] [gigabyte (rx6800xt)] amd reference :: OUT OF STOCK
[9:25:49 PM] info :: ✖ [newegg] [msi (rx6800xt)] amd reference :: OUT OF STOCK
[9:25:52 PM] info :: ✖ [newegg] [sapphire (rx6800xt)] amd reference :: OUT OF STOCK
[9:25:55 PM] info :: ✖ [newegg] [asrock (rx6800xt)] amd reference :: OUT OF STOCK
[9:25:58 PM] info :: ✖ [newegg] [asus (rx6800xt)] amd reference :: OUT OF STOCK
[9:26:07 PM] info :: ✖ [newegg] [amd (ryzen5950)] 5950x :: OUT OF STOCK
[9:26:10 PM] info :: ✖ [newegg] [gigabyte (rx6800xt)] amd reference :: OUT OF STOCK
[9:26:14 PM] info :: ✖ [newegg] [msi (rx6800xt)] amd reference :: OUT OF STOCK
[9:26:16 PM] info :: ✖ [newegg] [sapphire (rx6800xt)] amd reference :: OUT OF STOCK
[9:26:46 PM] error :: ✖ [newegg] asrock rx6800xt amd reference - Navigation timeout of 30000 ms exceeded
```

</details>

try 2: this time it failed immediately, and I waited 20 minutes and it is still stuck.

<details>

```
ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.1.0

[9:28:28 PM] info :: ℹ selected stores: newegg
[9:28:28 PM] info :: ℹ selected series: ryzen5950, rx6800xt, sonyps5c, sonyps5de
[9:29:08 PM] error :: ✖ [newegg] amd ryzen5950 5950x - Navigation timeout of 30000 ms exceeded

```

</details>

**Comment by jef** [comment]
It's probably because you've been banned and there aren't any backoff status codes.
