### ISSUE TITLE
Removing spamming channel 

### ISSUE THREAD

**Issue by TheTabKey** [jef/streetmerchant#447]
### Description

When something is in stock, it spams discord channel. And it may not even be in stock (just like a bestbuy glitch for example, which is fine but...)

### Possible solution

Can you make it so it just posts it once and has "in stock" on that message, then once it is out of stock, update that message to "out of stock" instead of spamming the channel?

**Comment by jef** [comment]
Probably not, but we can keep it on the backlog if someone wants to tackle this.
