### ISSUE TITLE
Add Support for Custom Items in Env Variables

### ISSUE THREAD

**Issue by aharris02** [jef/streetmerchant#450]
### Description

I'd like to track the stock for other items - the Lian Li SL120 Unifans on Newegg, in my case.

### Possible solution
I know this can easily be added to the current newegg.ts file with the code below, however if there was a way to add custom items to the environment variables, that would expand functionality of the library. This could also allow use for the upcoming AMD launches.
```
{
	brand: 'nvidia',
	cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=9SIAFSTBGD1237',
	model: 'sl120',
	series: '3080',
	url: 'https://www.newegg.com/p/1YF-005G-00014'
}

```

**Comment by jef** [comment]
This is too much configuration for an environment variable. We could include a different file that would load in these JSON payloads though potentially for custom usage.

Cool idea.

**Comment by jef** [comment]
Working on something like this in a prerelease. Will keep the project board (https://github.com/jef/streetmerchant/projects/4) updated.
