### ISSUE TITLE
Not checking strix 3080 on Amazon.co.uk even though there is a listing

### ISSUE THREAD

**Issue by SomeRandomName105** [jef/streetmerchant#474]
### Description

 Even though Amazon.co.uk has a 3080 strix (oc and non oc) listing my nvidia snatcher isn't checking it (Have only tried non oc as of right now)
 Here is my .env:
DESKTOP_NOTIFICATIONS="true"
IN_STOCK_WAIT_TIME="0"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PAGE_BACKOFF_MIN="5000"
PAGE_BACKOFF_MAX="150000"
SHOW_ONLY_BRANDS="asus,gigabyte,evga,msi"
SHOW_ONLY_MODELS="rog strix,ftw 3,ftw 3 ultra,gaming x trio,tuf,tuf oc,aorus master"
SHOW_ONLY_SERIES="3080"
STORES="amazon,amazon-uk"
SCREENSHOT="false"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

Here is the listing on Amazon.co.uk for oc and non oc versions: Non OC: https://www.amazon.co.uk/dp/B08HN7VVLJ/?th=1 OC: https://www.amazon.co.uk/ASUS-Graphics-Axial-tech-pressure-ROG-STRIX-RTX3080-O10G-GAMING/dp/B08HN6KYS3
 Windows 10

**Comment by andrewmackrodt** [comment]
Working fine for me:

```
[08:30:08] info :: ✖ [amazon-uk] [asus (3080)] rog strix :: OUT OF STOCK
```

**Comment by SomeRandomName105** [comment]
> Working fine for me:
> 
> ```
> [08:30:08] info :: ✖ [amazon-uk] [asus (3080)] rog strix :: OUT OF STOCK
> ```

What do you suggest I do? I downloaded the latest code about a day ago.

**Comment by andrewmackrodt** [comment]
You've not provided any output; there's been several occasions on discord where someone thinks a card isn't being checked despite it being in the screenshot. However, the most likely result is you are receiving no amazon-uk checks whatsoever because you've been detected as bot traffic.

**Comment by SomeRandomName105** [comment]
> You've not provided any output; there's been several occasions on discord where someone thinks a card isn't being checked despite it being in the screenshot. However, the most likely result is you are receiving no amazon-uk checks whatsoever because you've been detected as bot traffic.

So you think I should put a vpn on? I'll try that now.

**Comment by SomeRandomName105** [comment]
Still no dice with a vpn, I've turned on screenshots so I'll just have to wait.

**Comment by andrewmackrodt** [comment]
I'm not sure how screenshots relate to the problem, screenshots are only taken when something becomes in stock. If you think a card is not being checked, it's useful to provide output from the last 5 minutes or so of log output.

**Comment by SomeRandomName105** [comment]
How would I do that? Sorry not so well versed in this stuff.

**Comment by jxjftw** [comment]
How do you know it isn't being checked? Can you provide a screenshot of the text that scrolls across the screen? (The console output).

**Comment by SomeRandomName105** [comment]
Sorry It works now, I changed my .env (just changed models to "rog strix,rog strix oc,aorus master" and manufacturer to "asus,gigabyte") and it didn't work but after a couple of hours it just started checking the strix on amazon uk. Here is the screenshot of when it didn't work 
![image](https://user-images.githubusercontent.com/71745404/95664656-a5187780-0b52-11eb-81e1-de73316d39cd.png)
I don't know what I did to fix it but it got fixed, thank you for the help.
