### ISSUE TITLE
Best Buy CA False positive EVGA 3080

### ISSUE THREAD

**Issue by MrRobot245** [jef/streetmerchant#490]
### Description

Looks like the BB site loads initially to an In Stock button, but then loads the out of stock message.
Snatcher doesnt pick up on this, and only sends a false positive

https://www.bestbuy.ca/en-ca/product/evga-nvidia-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-video-card/14961449

### Possible solution

Wait on page for longer?

**Comment by jxjftw** [comment]
Front end waiting for api call for stock - needs to add specified wait time if the page is going to be scraped.

**Comment by maxcroy1** [comment]
Just wanted to add that this is happening for multiple products - I encountered the same issue this morning with PS5 and ASUS 3080 Strix. Looks like it is showing positive even if the PDP says "Sold Out"

**Comment by phtp** [comment]
Seems like it needs a 2-3 second delay.

**Comment by jef** [comment]
I believe this was fixed by using the disabled add to cart button. @maxcroy1, have you gotten any more pings after pulling latest?

**Comment by phtp** [comment]
I updated last night and not getting any more false positives. Thanks!

**Comment by Brydom** [comment]
@jef I am getting lots of false positives on EVGA 3070/3080 on bestbuy-ca right now
