### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by AdamSaketume26** [jef/streetmerchant#498]
### Description

Could you add support for authenticating proxies via username and password?

**Comment by jxjftw** [comment]
Have you tried "username:password"@proxy_ip?

**Comment by GRINSPANKER13** [comment]
> Have you tried "username:password"@proxy_ip?

I've tied it with my NordVPN Credentials and it didn't work. I had to use "await page.authenticate(credentials)".
I tried adding it to "lookup.ts" and it works, but since it creates a new page each time, it is rather slow.

**Comment by Macaddict42** [comment]
I tried using it with nordvpn proxy credentials and also found it didn't work. The credentials are based on this tutorial.

https://support.nordvpn.com/Connectivity/Proxy/1047410682/Proxy-setup-on-Chrome.htm
