### ISSUE TITLE
Add Xbox Series X/S and PS5

### ISSUE THREAD

**Issue by zerocarbthirty** [jef/streetmerchant#506]
### Description

Would be cool if we could add Xbox Series X/S and PS5 to this project so that it retains it's usefulness as more people get the RTX 3080.

### Possible solution

Just add the URLs, etc.

**Comment by jef** [comment]
This is way outside of the goal of this project, but that doesn't mean we can't do it. I plan to start implementing other products when we get a few fundamental features merged in.

**Comment by FrankFioretti** [comment]
I was toying with this already. Either just doing it myself one by one or adding another config file with comma-separated ASINs (Amazon) and a for loop. Now, if this was in powershell I'd actually be able to accomplish the latter myself ;o)

**Comment by mven** [comment]
Linking PR for PS5 support: https://github.com/jef/streetmerchant/pull/709

**Comment by happytambi** [comment]
I was really hoping someone would be able to add the xbox models as well before they go live on the 10th.  All of the stores in my area are doing online sales only.   I'm definitely concerned about stock.  Thanks in advance for all the amazing work

**Comment by jef** [comment]
There were some comments made on Discord that we can probably get this through before tomorrow!

**Comment by rrbailey89** [comment]
sad that this didnt happen :(

**Comment by zerocarbthirty** [comment]
yep
