### ISSUE TITLE
Nvidia-snatcher not working

### ISSUE THREAD

**Issue by ThatGirlll** [jef/streetmerchant#512]
I downloaded everything needed for the install and managed to type npm install into the cmd window but everytime I do, I only end up seeing a window that briefly closes before I can even read its contents. I don't get the nvidia snatcher window with all the listings. I checked all the other older issues but none of them are similar to my situation.

I edited the .env to 'nvidiasnatcher.env'. Would that cause an issue?

When you say to "clone" am I suppose too use git or Node.js? I am too confused about the instructions because when you mentioned 'npm run install' I used the windows command line.

**Comment by nathanf96** [comment]
i think you'll find following this tutorial a good idea https://www.youtube.com/watch?v=bVgIpjBkRLY

**Comment by AndyinMission** [comment]
The ".env" file needs to be named ".env".   I messed that up too initially.

**Comment by ThatGirlll** [comment]
> i think you'll find following this tutorial a good idea https://www.youtube.com/watch?v=bVgIpjBkRLY

Thanks! This should be linked to this by default.

**Comment by ThatGirlll** [comment]
> The ".env" file needs to be named ".env". I messed that up too initially.

How'd you do that? When I do it, windows tells me to name the file.

**Comment by jef** [comment]
I didn't know about this YT video. Thanks for posting. I'll link it in the README.
