### ISSUE TITLE
Missed stock alert for BestBuy 3080 FE cards

### ISSUE THREAD

**Issue by landonairey** [jef/streetmerchant#527]
The script didn't report a stock alert for BestBuy early today.

nowinstock.net show these two entries from today:
Oct 15 2020 - 3:05 PM EST | Best Buy - NVIDIA RTX 3080 FE Out of Stock
Oct 15 2020 - 3:01 PM EST | Best Buy - NVIDIA RTX 3080 FE In Stock for $699.99

Variables were set to:
IN_STOCK_WAIT_TIME="30"
PAGE_TIMEOUT="0"
SHOW_ONLY_SERIES="3080"
STORES="bestbuy,asus,evga,gamestop,microcenter,newegg,zotac"

Did anyone else manage to catch this?

**Comment by Nickiler** [comment]
I did catch any alerts on BestBuy today either... 
![image](https://user-images.githubusercontent.com/1026924/96194006-48c0a980-0efe-11eb-9961-ad78b30284fd.png)

**Comment by petersona95** [comment]
I received multiple stock alerts on my end for the FE and xc3 Ultra

**Comment by Nickiler** [comment]
Is there a way to test this on something in stock now instead of waiting for drops and finding out later... What could make the system report bad results? I would like to be able do a dry run on an in stock item and then I would be able to better troubleshoot maybe

**Comment by Nickiler** [comment]
@petersona95 Do you have the logs you can share... would be good to correlate with what you are stating

**Comment by NickThaRuler** [comment]
I find it hard to believe that a targeted bot to one store wouldn't catch anything.

**Comment by GRINSPANKER13** [comment]
Mine didn't go off either, seems to be only bestbuy, I'm guessing the "container" is at fault.

**Comment by NickThaRuler** [comment]
I just tested this by adding a coffee maker to the list of links and it's official this code is now BUSTED!!! It reported it was out of stock even those the "Add to Cart" popped up right away. I ran it with Headless false.

**Comment by GRINSPANKER13** [comment]
I figured out what the problem is.

LOW_BANDWIDTH=""

When you set that setting to "true" the bot somehow seems to skip the actual InStock check.
After changing it back to "false" and running my test:link script, it functions normally.

**Comment by landonairey** [comment]
Tried setting LOW_BANDWIDTH="false" but perhaps there is still an issue because after ~10minutes it stops reporting stock information. 

I noticed that in the original report from this bug report, the log showed stock information for all stores listed except bestbuy, maybe it stopped reporting bestbuy a long time ago and I never realized!

**Comment by GRINSPANKER13** [comment]
> Tried setting LOW_BANDWIDTH="false" but perhaps there is still an issue because after ~10minutes it stops reporting stock information.
> 
> I noticed that in the original report from this bug report, the log showed stock information for all stores listed except bestbuy, maybe it stopped reporting bestbuy a long time ago and I never realized!

I've tested it without using the low_bandwidth mode, and it was still pinging after 10 minutes.

![003](https://user-images.githubusercontent.com/20674650/96351982-e93cd800-107c-11eb-8898-86a9d17ca131.png)

**Comment by daviderickson** [comment]
If you run this with headless="false" and low_bandwidth="true", you can see that BestBuy's page is doing some kind of redirect to a page with a single graphic prior to when snatcher does it's in stock test, thus always returning out of stock.

![image](https://user-images.githubusercontent.com/107007/96552926-4a290380-1269-11eb-96ff-db161f621705.png)

If you add 'script' to blocked types at the top of index.ts it will solve this problem on the BestBuy page, but breaks other stores.  If snatcher could be modified to only block scripts on BestBuy when in low bandwidth mode that would be great.  It looks like it should be possible to dynamically do this based on the docs at https://www.npmjs.com/package/puppeteer-extra-plugin-block-resources - I tried for a bit and had problems that as a non-Node developer I couldn't easily resolve, but maybe one of the devs can make it work.

**Comment by daviderickson** [comment]
@jef Can requests to multiple stores be interleaved with each other?  If so that makes it hard to use block resources dynamically on a per store basis, since the puppeteer settings apply globally.
