### ISSUE TITLE
nvidia-snatcher loops one shop only

### ISSUE THREAD

**Issue by Warlord711** [jef/streetmerchant#537]
Not sure if it is a bug or a feature, but after running for several minutes (need to check how long but I guess 15+min), nvidia-snatcher starts to scan ONE shop only. For me it is proshop-de, I also have some more DE located shops enabled, so it starts pretty normal but runs on proshop only after some time.

I do run nightly Docker container.

**Comment by jef** [comment]
Make sure you setup your `STORES` correctly.

**Comment by patricklewis** [comment]
Same issue here. 

When I start nvidia-snatcher via Docker it polls for all the cards I selected at Amazon, Newegg, and Best Buy. 

After a few minutes, it stops checking Newegg and Best Buy and only loops through the Amazon listings.

**Comment by jef** [comment]
Strange... What other environment variables do you have set? Other filters? The filtering right now is not spectacular, but gets the job done for now.

Do you mind sharing?

**Comment by patricklewis** [comment]
@jef My changes to .env are pretty minimal, just setting up Pushover/Slack notifications in addition to defining the brands/series to monitor:

```diff
44,45c44,45
< PUSHOVER_TOKEN=
< PUSHOVER_USER=
---
> PUSHOVER_TOKEN=[redacted]
> PUSHOVER_USER=nvidia
48c48,49
< SHOW_ONLY_BRANDS=
---
> SHOW_ONLY_BRANDS=asus,evga,gigabyte,msi,nvidia
50,52c51,53
< SHOW_ONLY_SERIES=
< SLACK_CHANNEL=
< SLACK_TOKEN=
---
> SHOW_ONLY_SERIES=3080
> SLACK_CHANNEL=games
> SLACK_TOKEN=[redacted]
55c56
< STORES=
---
> STORES=amazon,bestbuy,newegg
```

I have since switched from using the Docker container version on a Linux host to just running nvidia-snatcher natively in macOS. 

I don't have this issue when using the same .env file in macOS; I have had the app running for an hour and it is still correctly polling all of the stores I configured.

**Comment by jef** [comment]
> I have since switched from using the Docker container version on a Linux host to just running nvidia-snatcher natively in macOS.
> 
> I don't have this issue when using the same .env file in macOS; I have had the app running for an hour and it is still correctly polling all of the stores I configured.

If I read this right, you're saying that it's fine with macOS, but not working with the Docker image?

**Comment by patricklewis** [comment]
Yes, I am using the same .env file in both places and it works correctly via `npm run start` in macOS but exhibits the issue originally raised by @Warlord711 if I run the Docker container from a Linux host.
