### ISSUE TITLE
Handle Amazon preorder

### ISSUE THREAD

**Issue by daviderickson** [jef/streetmerchant#556]
### Description

Amazon seems to offer pre-order options occasionally that the current application does not seem to handle.  Enable alerting for an available preorder option so a user can put in an order.

EX:
![image](https://user-images.githubusercontent.com/107007/96642755-71b8b400-12db-11eb-9655-b6d48f878bc8.png)

But my running system missed it:

![image](https://user-images.githubusercontent.com/107007/96642870-9dd43500-12db-11eb-94f1-ddc0ff6143a5.png)
![image](https://user-images.githubusercontent.com/107007/96642925-b2b0c880-12db-11eb-88f9-8d7e012159ab.png)

**Comment by GRINSPANKER13** [comment]
Tested with the following link: [here](https://www.amazon.com/dp/B087XTT5GZ) and the bot is detecting the pre-order.

**Comment by daviderickson** [comment]
> Tested with the following link: [here](https://www.amazon.com/dp/B087XTT5GZ) and the bot is detecting the pre-order.

Interesting, thanks for sharing.. I wonder why mine missed it twice then?  I've also noticed that Amazon seems to be sometimes popping up captchas that have to be solved before forwarding to the product listing.. could that have been the issue?

**Comment by GRINSPANKER13** [comment]
> > Tested with the following link: [here](https://www.amazon.com/dp/B087XTT5GZ) and the bot is detecting the pre-order.
> 
> Interesting, thanks for sharing.. I wonder why mine missed it twice then? I've also noticed that Amazon seems to be sometimes popping up captchas that have to be solved before forwarding to the product listing.. could that have been the issue?

I'm not sure, might of happened to fast for the bot to catch it.

**Comment by jef** [comment]
> > Tested with the following link: [here](https://www.amazon.com/dp/B087XTT5GZ) and the bot is detecting the pre-order.
> 
> Interesting, thanks for sharing.. I wonder why mine missed it twice then? I've also noticed that Amazon seems to be sometimes popping up captchas that have to be solved before forwarding to the product listing.. could that have been the issue?

You'll need to set up your `USER_AGENT`. This is usually the issue with captcha on Amazon.
