### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Tiffys** [jef/streetmerchant#570]
### Description

It seems the chromium the bot uses doesn't cache and thus reloads a good 10MB+ per website on every load. This seems an inefficient use of bandwidth. Perhaps caching could be implemented to reduce reloading of files already downloaded and only update on a change?

Related to issue #438

### Possible solution

There are HTTP Cache and Disk Cache modules.

**Comment by fatmoo5** [comment]
Caching isnt a good idea for these kind of scrappers. For example with newegg and bestbuy, the add to cart would be stuck on page due to cache bringing hours of false positives. You want to reload the page without cache to get accurate response from api.
