### ISSUE TITLE
Request Interception is not enabled.

### ISSUE THREAD

**Issue by DrFarber** [jef/streetmerchant#575]
I'm just reporting that my version of it (current) is crashing, with the aforementioned error in the title. Feel free to make suggestions, but I'm just doing my part and reporting it.

**Comment by DrFarber** [comment]
I think it has something to do with the ad-blocker?

**Comment by jef** [comment]
Could you pull latest and see if it works? Thanks.

**Comment by jef** [comment]
https://github.com/cliqz-oss/adblocker/issues/1495
https://github.com/jef/streetmerchant/issues/826
