### ISSUE TITLE
Docker container missing dependencies required for notifications

### ISSUE THREAD

**Issue by hazza64** [jef/streetmerchant#587]
### Description

Docker image cannot notify user.

If `sudo npm install` has not been done in container console
![image](https://user-images.githubusercontent.com/4714966/97059691-f9096000-1545-11eb-90bf-04f429b2dc26.png)

If `sudo npm install` has been run within container:
![image](https://user-images.githubusercontent.com/4714966/97059839-81880080-1546-11eb-8645-8b79316224b7.png)

UnraidOS Docker

**Comment by jef** [comment]
Thanks! I'll do some testing with the Docker image.
