### ISSUE TITLE
Amazon not being searched for 3090 FTW3 Ultra

### ISSUE THREAD

**Issue by GeneralDripps** [jef/streetmerchant#588]
Issue:

I noticed Amazon is not being searched for the 3090 FTW3 Ultra. There was a drop of that card today and it was never discovered. I have never seen the script attempt so search for that card on Amazon in the log. I have the both the card and the store selected, along with 9 other card variations and 5 other stores. 

The Amazon file in the stores folder does have the information for the card.

I attempted to edit my .env file to only look for the 3090 FTW3 Ultra at Amazon. The script identified the selections but did not run any search.

I apologize but as my coding experience is limited I do not have any possible solutions. I just wanted to bring attention to the issue.

**Comment by fatmoo5** [comment]
submitted for pull request
