### ISSUE TITLE
Efficiency - storefront, not individual card

### ISSUE THREAD

**Issue by Tiffys** [jef/streetmerchant#590]
### Description

It seems to me that the way the bot works at the moment is opening a new chromium window with no cache to check each and every card. This wastes a ton of bandwidth, and time.

### Possible solution

Search storefronts for every card you want to check instead. Instead of a dozen individual card's pages getting checked you can just check one storefront. For instance, the big three in the US:

https://www.bestbuy.com/site/computer-cards-components/video-graphics-cards/abcat0507002.c?id=abcat0507002&qp=brand_facet%3DBrand~ASUS%5Ebrand_facet%3DBrand~EVGA%5Ebrand_facet%3DBrand~NVIDIA%5Egpusv_facet%3DGraphics%20Processing%20Unit%20(GPU)~NVIDIA%20GeForce%20RTX%203080&intl=nosplash

https://www.amazon.com/stores/GeForce/RTX3080_GEFORCERTX30SERIES/page/6B204EA4-AAAC-4776-82B1-D7C3BD9DDC82

https://www.newegg.com/p/pl?d=rtx+3080&N=601357282%20100007709

**Comment by TheTabKey** [comment]
Its not that simple otherwise it would have been done already. Each add to cart button has the same class name. A complete overhaul would be needed. Have any ideas how to deal with buttons of the same class?

**Comment by Tiffys** [comment]
> Its not that simple otherwise it would have been done already. Each add to cart button has the same class name. A complete overhaul would be needed. Have any ideas how to deal with buttons of the same class?

Newegg for instance, check this sorta stuff:

`<div class="item-stock" id="stock_14-487-518"></div>`
`<div class="item-stock" id="stock_14-137-598"></div>`

Then move up the tree & check...
`<div class="item-button-area">`

Or you could just check the larger element & compare against changes, sorta like what distill.io does.

**Comment by rotemgrim** [comment]
> Its not that simple otherwise it would have been done already. Each add to cart button has the same class name. A complete overhaul would be needed. Have any ideas how to deal with buttons of the same class?

no need to deal with buttons - when an item on storefront is seen as "in stock" just navigate to the items page and use default add to cart method.

**Comment by jef** [comment]
Not a bad idea. I think we originally did this with `nvidia`, but quickly changed to a different format because the "overall view" did not show in stock, whereas the individual did. I can't be certain that this won't be the same for other sites, but realistically should not be the case.

I'd be interested in testing this in the future as this is good idea.

**Comment by TheTabKey** [comment]
mentioned here: https://github.com/jef/nvidia-snatcher/issues/646

**Comment by jef** [comment]
Superseded by: https://github.com/jef/streetmerchant/issues/1208
