### ISSUE TITLE
Could not find browser revision 809590 Run "PUPPETEER_PRODUCT=firefox npm install"

### ISSUE THREAD

**Issue by DrFarber** [jef/streetmerchant#598]
I don't know much about any of the internal workings of the code, but I do need some assistance and would really appreciate any help. I am attempting to port over a successful install of nvidia-snatcher to a VM (from my daily driver), and after attempting to go through the install process, this happens on first run:

Any ideas on what needs to be done? Thanks so much

```
                   \__|      $$ |\__|                                                 $$ |              $$ |
$$$$$$$\ $$\    $$\ $$\  $$$$$$$ |$$\  $$$$$$\           $$$$$$$\ $$$$$$$\   $$$$$$\ $$$$$$\    $$$$$$$\ $$$$$$$\   $$$$$$\   $$$$$$\
$$  __$$\\$$\  $$  |$$ |$$  __$$ |$$ | \____$$\ $$$$$$\ $$  _____|$$  __$$\  \____$$\\_$$  _|  $$  _____|$$  __$$\ $$  __$$\ $$  __$$\
$$ |  $$ |\$$\$$  / $$ |$$ /  $$ |$$ | $$$$$$$ |\______|\$$$$$$\  $$ |  $$ | $$$$$$$ | $$ |    $$ /      $$ |  $$ |$$$$$$$$ |$$ |  \__|
$$ |  $$ | \$$$  /  $$ |$$ |  $$ |$$ |$$  __$$ |         \____$$\ $$ |  $$ |$$  __$$ | $$ |$$\ $$ |      $$ |  $$ |$$   ____|$$ |
$$ |  $$ |  \$  /   $$ |\$$$$$$$ |$$ |\$$$$$$$ |        $$$$$$$  |$$ |  $$ |\$$$$$$$ | \$$$$  |\$$$$$$$\ $$ |  $$ |\$$$$$$$\ $$ |
\__|  \__|   \_/    \__| \_______|\__| \_______|        \_______/ \__|  \__| \_______|  \____/  \_______|\__|  \__| \_______|\__|

[7:02:34 PM] info :: ℹ selected stores: bestbuy, nvidia, adorama, amazon, aria, asus, bandh, bestbuy-ca, ccl, computeruniverse, coolblue, currys, cyberport, ebuyer, evga, evga-eu, gamestop, mediamarkt, microcenter, newegg, newegg-ca, novatech, overclockers, pny, scan, very, zotac
[7:02:34 PM] info :: ℹ selected brands: asus, evga, gigabyte, msi, nvidia, palit, pny, zotac
[7:02:34 PM] info :: ℹ selected models: rog strix, rog strix oc, tuf, tuf oc, ftw3, ftw3 ultra, xc3, xc3 black, xc3 ultra, aorus master, aorus xtreme, eagle oc, eagle, gaming, gaming oc, turbo, gaming x trio, ventus 3x, ventus 3x oc, founders edition, gaming pro, gaming pro oc, dual fan, xlr8, xlr8 rgb, amp holo, amp extreme holo, trinity, trinity oc
[7:02:34 PM] info :: ℹ selected series: 3080, 3090
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
[7:02:35 PM] info :: ✔ sound player found: cmdmp3
Z:\snatcher\nvidia-snatcher\node_modules\puppeteer-core\lib\cjs\puppeteer\node\Launcher.js:79
                throw new Error(missingText);
                      ^

Error: Could not find browser revision 809590. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (Z:\snatcher\nvidia-snatcher\node_modules\puppeteer-core\lib\cjs\puppeteer\node\Launcher.js:79:23)
    at async PuppeteerExtra.launch (Z:\snatcher\nvidia-snatcher\node_modules\puppeteer-extra\dist\index.cjs.js:129:25)
npm ERR! code 1
npm ERR! path Z:\snatcher\nvidia-snatcher
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "npm run build && node build/index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nucc\AppData\Local\npm-cache\_logs\2020-10-25T02_02_38_338Z-debug.log
```

**Comment by DrFarber** [comment]
Also, I tried "PUPPETEER_PRODUCT=firefox npm install" and "PUPPETEER_PRODUCT=firefox yarn install" to no avail:

PS Z:\snatcher\nvidia-snatcher> PUPPETEER_PRODUCT=firefox npm install
PUPPETEER_PRODUCT=firefox : The term 'PUPPETEER_PRODUCT=firefox' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ PUPPETEER_PRODUCT=firefox npm install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PUPPETEER_PRODUCT=firefox:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by TheTabKey** [comment]
As repo suggests, run "npm install" inside of the nvidia-snatcher directory

**Comment by N3il101** [comment]
Having the same problem, ran the "npm install" inside of the nvidia-snatcher directory.

**Comment by Kryptyle** [comment]
Having the same issue, ran 'npm install' inside of the nvidia-snatcher directory as well.

`[12:32:38 AM] error :: ✖ something bad happened, resetting nvidia-snatcher in 5 seconds Could not find browser revision 809590. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.`

**Comment by jef** [comment]
@N3il101, @Kryptyle having the same issue as in running a VM and can't get it working?

What is everyone's VM OSes?

**Comment by Kryptyle** [comment]
@jef Great timing, so I got it to work finally.

VM OS is Windows 10, I had nvidia-snatcher installed on C: root. I made a secondary partition and installed nvidia-snatcher there and it worked no problem.

I'm not smart enough to know why though but thought I'd let you know in case you can figure it out. Thanks for all of your work!

**Comment by jef** [comment]
> VM OS is Windows 10, I had nvidia-snatcher installed on C: root. I made a secondary partition and installed nvidia-snatcher there and it worked no problem.

Now that's interesting... Lol -- no idea! Perhaps just recloning it did the trick for you.

> Thanks for all of your work!

Of course! Good luck.

**Comment by supra1960** [comment]
typing export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
resolve that issue for me

**Comment by lebyanelm** [comment]
> typing: export PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium-browser'
> resolve that issue for me

This definitely did the trick for me. Thanks!
