### ISSUE TITLE
BB still pinging

### ISSUE THREAD

**Issue by TheTabKey** [jef/streetmerchant#624]
After drop today at 131pm(PST), it is 803pm and it is still wanting to ping that a card on bestbuy is still in stock. I ran with "INCOGNITO" enabled to see if it was a cache issue and its still wanting to ping. Also, "IN_STOCK_WAIT_TIME" seems to want to wait indefinately no matter what it is set to, need to restart to research item stock.

**Comment by rrbailey89** [comment]
After pulling latest main BB is still pinging the founders edition

**Comment by lime517** [comment]
Same here - maybe we need a delay after pageload? Usually the Add to Cart button changes to Sold Out after a few seconds on a normal Chrome browser.

**Comment by jef** [comment]
Probably has to do with the incognito plugin and how JavaScript loads.
