### ISSUE TITLE
Pause lookup when in break time?

### ISSUE THREAD

**Issue by SesioN** [jef/streetmerchant#629]
### Description

I've added for myself a feature, where you can define a break time, in which the bot does not lookup. 

Use-Case:
I run the bot on a server and only want notifications and thus cards getting lookup when I'm available. 
E.g. no need to spam the shops all night and it's annoying to start/stop the app manually.

Do we want this? We could in the future also support something like a schedule, especially in the WebApp.

### Possible solution
I haven't added a PR because my implementation was just a quick-dirty-thing. 

If we want this, I could refine the code a little. Maybe not only support military time. Also missing readme entry etc.

https://github.com/SesioN/nvidia-snatcher/commit/b2928a85b07a598fc8433fcf2a9f32b22eec53e6

**Comment by jef** [comment]
I'd say it's a pretty good idea! Your implementation seems extensive; do you think creating a wrapper for the lookup with a `Date.now()` call around two variables (`BLOCK_START_TIME`, `BLOCK_END_TIME`) to see if we want to run the lookup?
