### ISSUE TITLE
Newegg not searching for the Asus strix Rog 3090 OC

### ISSUE THREAD

**Issue by alrowa7i** [jef/streetmerchant#641]
### Description

![image](https://user-images.githubusercontent.com/58651218/97674908-c1e80100-1aa7-11eb-8d57-628c0711cdf3.png)

it is only searching amazon for the OC version of ASIS strix rog 3090
### Possible solution

add the newegg link for the strix rog OC:
https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-gaming/p/N82E16814126456?Description=3090&cm_re=3090-_-14-126-456-_-Product

**Comment by jef** [comment]
I have no problem adding the card, but I'm trying to understand the different between Rog Strix OC and Rog Strix.

The link provided isn't an OC Edition, I don't believe.

**Comment by alrowa7i** [comment]
The O letter before 24g stands for the overclock version
https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-gaming/p/N82E16814126456?Description=3090&cm_re=3090-_-14-126-456-_-Product

I don't see them selling the regular version.

**Comment by jef** [comment]
Got it. Alright, I'll go through an update soon. I think for now just include your filter to also have `rog strix` until I push this out.

Thanks!
