### ISSUE TITLE
Could not find files for the given pattern(s) 

### ISSUE THREAD

**Issue by wdrury-uk** [jef/streetmerchant#645]
### Description
To ensure not same issue as #182 

1. Rename .env.example to .env
2. Config .env file
3. Listed 8x stores in UK  --- hidden in below example by xx
4. npm run start

[17:34:28] info :: ℹ selected stores: xx, xx, xx, xx, xx
[17:34:28] info :: ℹ selected brands: yyy, yyy , yyy
[17:34:28] info :: ℹ selected series: zzzz
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).

continue to run but only does stores first 1st, 2nd, 5th, 7th stores

Have checked store names as per list and copy/pasted the names as required.

### Possible solution

Tried all solutions under issue #183 and check no file extension of .txt - its not, just .env file.

**Comment by wdrury-uk** [comment]
UPD: I have just move the .env out of the folder to see if INFO: cant find files error stop.  Confirmed no messages and defaults used.

Next check is reset the .env file to the default one and run.

**Comment by wdrury-uk** [comment]
Continue to test.

PASS Brands = asus,zotac,evga,msi,gigabyte,palit
PASS UK Stores = amazon-uk,currys,aria,ebuyer,box

FAIL = nvidia (COUNTRY=great_britain) - hangs, does not scan
FAIL = overclockers - hangs, does not scan
FAIL = scan - hangs, does not scan
FAIL = ccl - fails with STATUS CODE ERROR 503
FAIL = novatech - hangs, does not scan
FAIL = very - hangs, does not scan

continuing to verify other changed settings to find INFO root cause.

**Comment by wdrury-uk** [comment]
**ROOT Cause identified** its the PLAY_SOUND setting on Windows.

PLAY_SOUND=swiftly.mp3

followed the [Windows Audio Notification Guide](https://github.com/jef/nvidia-snatcher/wiki/Installation:-Windows#audio-notifications) therefore put the file in the folder of the code "nvidia-snatcher" as per wiki guide linked recommends.

**Comment by jef** [comment]
> FAIL = nvidia (COUNTRY=great_britain) - hangs, does not scan

Just as a heads up, this API is _kind of_ deprecated. Not sure if/when it will be online again.

**Comment by ethanwc** [comment]
I also was facing this issue. I added the c files to play the sound which made that portion work. For me the warning is there only when I specify a sound file:

PLAY_SOUND=notification.wav

**Comment by wdrury-uk** [comment]
@jef 
The PLAY_SOUND is set as above states

PLAY_SOUND=swiftly.mp3

If I remove the setting to:

PLAY_SOUND=

The warnings not longer appear.

So as a developer I be looking for code which detects a file set to play, then the code its validate players and exclude any players not for Windows if the execution OS is Windows.  As it does play the sound because I have installed the cmdmp3 binaries.

**Comment by jef** [comment]
Use `PLAY_SOUND=./sound.mp3` if `sound.mp3` is in the same folder as streetmerchant.
