### ISSUE TITLE
Please add the ability to track AMD cards as i'm sure they'll be scalped as well. Thanks for all you're doing!

### ISSUE THREAD

**Issue by historypsi** [jef/streetmerchant#648]
Hoping to grab a card before the scalpers get them all.

**Comment by jef** [comment]
I'm doing a bit of refactoring and should hopefully get these on track.

Thanks!

**Comment by v1ct0rv** [comment]
> I'm doing a bit of refactoring and should hopefully get these on track.
> 
> Thanks!

If you need help on that, I'm available!

**Comment by jef** [comment]
Will do @v1ct0rv. Maybe I'll create some tickets this weekend and ping you in them.

Thanks for that :)

**Comment by v1ct0rv** [comment]
> Will do @v1ct0rv. Maybe I'll create some tickets this weekend and ping you in them.
> 
> Thanks for that :)

@jef any update on this? would be great to have something before AMD launch...

**Comment by jef** [comment]
AMD CPUs were added recently and I'm sure we'll have GPU cards in the future.

**Comment by historypsi** [comment]
Awesome! You rock! I didn't see the Parameters for the .env file on your wiki page to add the CPUs in there.

**Comment by veev-code** [comment]
> 
> 
> AMD CPUs were added recently and I'm sure we'll have GPU cards in the future.

Super excited to see this! Are there instructions for setting up the AMD CPUs?

**Comment by veev-code** [comment]
In case anyone else stumbles upon this looking for AMD/Ryzen support, I found the supported AMD parameters here:

https://github.com/jef/streetmerchant/search?q=5900x

**Comment by jef** [comment]
@historypsi https://github.com/jef/streetmerchant#filters

**Comment by veev-code** [comment]
> 
> 
> @historypsi https://github.com/jef/streetmerchant#filters
> 
> It's under https://github.com/jef/streetmerchant#customization

I do not see it listed in the README:

```
Brand | Model
-- | --
asus | dual, dual oc, rog strix, rog strix oc, tuf, tuf oc
evga | ftw3, ftw3 ultra, xc3, xc3 black, xc3 ultra
gainward | phantom gs, phoenix, phoenix gs, phoenix gs oc
gigabyte | aorus master, aorus xtreme, eagle, eagle oc, gaming, gaming oc, turbo, vision, vision oc
inno3d | gaming x3, ichill x3, ichill x4, twin x2 oc
kfa2 | sg oc
msi | gaming x trio, ventus 2x oc, ventus 3x, ventus 3x oc
nvidia | founders edition
palit | gamerock oc, gaming pro, gaming pro oc
pny | dual fan, xlr8, xlr8 rgb
zotac | amp holo, amp extreme holo, trinity, trinity oc, twin edge, twin edge oc
```

Everything looks Nvidia-related.

**Comment by lngchn** [comment]
@veev-code README is outdated. AMD parameters will work if you set it.

**Comment by jef** [comment]
> @veev-code README is outdated. AMD parameters will work if you set it.

Sorry, but this is not true.

![image](https://user-images.githubusercontent.com/12074633/98885213-9f6ac600-245f-11eb-81d3-9deca835df28.png)
