### ISSUE TITLE
Zotac 3070 not being searched for

### ISSUE THREAD

**Issue by Camere** [jef/streetmerchant#671]
### Description

Zotac 3070 is not being searched for.

### Possible solution

I'm not sure of the cartURL.  There are two cards - regular and OC

 {
            brand: 'zotac',
            cartUrl: 'https://store.zotac.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-zt-a30700h-10p',
            model: 'Twin Edge OC',
            series: '3070',
            url: 'https://store.zotac.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-zt-a30700h-10p'
        },

 {
            brand: 'zotac',
            cartUrl: 'https://store.zotac.com/zotac-gaming-geforce-rtx-3070-twin-edge-zt-a30700e-10p,
            model: 'Twin Edge',
            series: '3070',
            url: 'https://store.zotac.com/zotac-gaming-geforce-rtx-3070-twin-edge-zt-a30700e-10p'
        },

**Comment by jef** [comment]
Cool! If you want to make a PR I can merge or put them in. Up to you.

**Comment by darwinchangz** [comment]
Is there an update on this? What exactly is a PR? Attempting to add the sites myself to the .js doesn't seem to work
