### ISSUE TITLE
1.7.0 Nvidia Deprecation Notices

### ISSUE THREAD

**Issue by xcharlesy** [jef/streetmerchant#673]
warn :: nvidia is deprecated in favor of bestbuy

If I receive this new notice does this mean it is no longer checking nvidia and is instead only checking bestbuy?

**Comment by GoBLiN-aK** [comment]
I removed Nvidia from my store list because they are sending their stock to Best Buy. If you check the Nvidia website, you can see that they are showing what other retailers you can buy their cards at.

**Comment by xcharlesy** [comment]
> I removed Nvidia from my store list because they are sending their stock to Best Buy. If you check the Nvidia website, you can see that they are showing what other retailers you can buy their cards at.

Didn't the official communication from Nvidia state that they are "working to improve the experience"? I took that as a temporary measure.

Additionally, they also say "In Europe, we will restart fulfilment of Founders Edition products in the coming days and plan to expand our country coverage in due course" - since nvidia-snatcher supports many countries wouldn't this create an issue if you are trying to shop Nvidia exclusively for a FE card? For example, I have changed my country selection to Canada as a test and it still uses the deprecation notice even though the FE card can't be purchased by Best Buy Canada.

Would like to confirm if all of the above is working as intended.

**Comment by jef** [comment]
Good question! This deprecation notice is only a notice, it won't stop the functionality.

And for future reference, when usually you see 'deprecated` functionality, it just means that it's there, but may not be working or perhaps no longer updated.

In this case, it works, but do not know of the outcome.
