### ISSUE TITLE
Zen 3 CPUs

### ISSUE THREAD

**Issue by serg06** [jef/streetmerchant#686]
### Description

Would it be possible to add the Zen 3 CPUs to this tool? I know they're technically not Nvidia products, but this tool is amazing, and I'd love to be able to use it for Zen 3.

### Possible solution

We currently have 3 series options, 3070 3080 3090. We could add 4 more, 5600x 5800x 5900x 5950x, to cover the Zen 3 CPUs. I think it should be really easy to do.

**Comment by MarioAC2** [comment]
That would be amazing, I got a 3090 thanks to this tool and now I ran out of luck again for the 5950x

**Comment by stevezub** [comment]
I'd love to see this, too. Waited in line at Micro Center for a while this morning for a 5900x, but no luck.

**Comment by The-Distal** [comment]
*This is not mine*

https://github.com/njgreb/nvidia-snatcher/tree/amd5950

*This is mine*

The branch above only includes support for the 5950x at AMD and Bestbuy in the US. Here's the code to edit the files in \nvidia-snatcher\src\store\model for 5950x support at Amazon and Newegg. Other models can be added similarly.

Amazon
		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B0815Y8J9N&Quantity.1=1',
			model: '5950x',
			series: '5950',
			url: 'https://www.amazon.com/dp/product/B0815Y8J9N'
		}

Newegg

		{
			brand: 'amd',
			cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16819113663',
			itemNumber: '19-113-663',
			model: '5950x',
			series: '5950',
			url: 'https://www.newegg.com/amd-ryzen-9-5950x/p/N82E16819113663'
		}

**Comment by stevezub** [comment]
Thanks! Since I'm interested in the 3900x, I took a stab at modifying these for the 3900x:

Amazon

		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08164VTWH&Quantity.1=1',
			model: '5900x',
			series: '5900',
			url: 'https://www.amazon.com/dp/product/B08164VTWH'
		}

Newegg


		{
			brand: 'amd',
			cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16819113664',
			itemNumber: '19-113-664',
			model: '5900x',
			series: '5900',
			url: 'https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664'
		}

**Comment by The-Distal** [comment]
> 
> 
> Thanks! Since I'm interested in the 3900x, I took a stab at modifying these for the 3900x:
> 
> Amazon
> 
> ```
> 	{
> 		brand: 'amd',
> 		cartUrl: 'https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08164VTWH&Quantity.1=1',
> 		model: '5900x',
> 		series: '5900',
> 		url: 'https://www.amazon.com/dp/product/B08164VTWH'
> 	}
> ```
> 
> Newegg
> 
> ```
> 	{
> 		brand: 'amd',
> 		cartUrl: 'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16819113664',
> 		itemNumber: '19-113-664',
> 		model: '5900x',
> 		series: '5900',
> 		url: 'https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664'
> 	}
> ```

Let me know if it works. I haven't tried new models. I'm not much of a programmer; I just recognized enough that I knew that edit would work.

**Comment by emike09** [comment]
I get an error when I add those entries.

src/store/model/amazon.ts:26:4 - error TS2322: Type '"amd"' is not assignable to type '"nvidia" | "test:brand" | "asus" | "evga" | "gainward" | "gigabyte" | "inno3d" | "kfa2" | "msi" | "palit" | "pny" | "zotac"'.

26              brand: 'amd',

  src/store/model/store.ts:16:2
    16  brand: 'test:brand' | 'asus' | 'evga' | 'gainward' | 'gigabyte' | 'inno3d' | 'kfa2' | 'msi' | 'nvidia' | 'palit' | 'pny' | 'zotac';
        ~~~~~
    The expected type comes from property 'brand' which is declared here on type 'Link'

I assume I need to edit another files so that AMD is recognized?

**Comment by stevezub** [comment]
You would need to pull down the rest of the changes in https://github.com/njgreb/nvidia-snatcher/tree/amd5950.

He's adding the rest of the Ryzen series as well

**Comment by njgreb** [comment]
That PR has been merged!  Good luck on getting those sweet new cpu's ;)

**Comment by emike09** [comment]
I pulled the latest version of jef/streetmerchant, added amd to stores in .env, but I'm not seeing and AMD chips in the display output. Just nvidia cards. I don't have and limits on showing any brands, models, or series. Is there something else that needs to be done to look for AMD chips?

**Comment by njgreb** [comment]
The default set of devices is still "['3070', '3080', '3090']".  I didn't add these to the set since it felt a bit odd with the "nvidia-snatcher" name.  With the new name, I am less against that and could do make a change to include them all.

**Comment by njgreb** [comment]
But to add them in your .env:
SHOW_ONLY_SERIES="ryzen5950,ryzen5900,ryzen5800,ryzen5600"

**Comment by njgreb** [comment]
PR with them in the default: https://github.com/jef/streetmerchant/pull/696
