### ISSUE TITLE
Why am I getting square characters instead of the "I" "X" and "STREETMERCHANT"?

### ISSUE THREAD

**Issue by TunaErtemalp** [jef/streetmerchant#692]
Maybe this is a stupid question. My apologies... I run this on Win10, either under CMD or PowerShell or git's CMD, starting with 1.5.0. Since the start, I could never see the "I" and "X" in front of the log output, instead just little empty squares (in CMD) or little squares with a "?" in them (in PowerShell). With 2.0.0, I can't see the "STREETMERCHANT" at the top, either. When I copy/paste that output into here or MSWord, they show up fine. So, I am guessing the characters used are Unicode or come from a charset that is not default in CMD/PS, and somehow CMD/Git CMD/PowerShell are not able to interpret them properly. Any idea how to force those shells use the right charset?

Interestingly, Git Bash shows them fine... 

Tuna

**Comment by jef** [comment]
Yep! That's right! You should use a font that can handle unicode characters.

https://www.nerdfonts.com/ is a good place to get these.

**Comment by TunaErtemalp** [comment]
Changing the console font to `MS Gothic` enables the display of the fun characters, but then the backslash character for folder separation becomes the "Yen" character, for the Japanese currency. D'oh!

**Comment by jef** [comment]
Yeah, I would choose something from that link above or perhaps something from this list: https://www.programmingfonts.org/

Most of these fonts have unicode support.
