### ISSUE TITLE
After 2.0 release, Wiki & homepage directions are diverging...

### ISSUE THREAD

**Issue by TunaErtemalp** [jef/streetmerchant#693]
https://github.com/jef/streetmerchant/wiki/Installation:-Windows says `Node.js 14`, but the homepage says `Node.js 15`, which is why I just now installed the latest 15.1.0.

Plus: Many references  to the old app & folder name.

**Comment by jef** [comment]
Thanks! I forgot about this part 😅  I'll go through the Wiki and update.
