### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by thetimothyp** [jef/streetmerchant#701]
### Description
Automated testing for PR security/quality control as code base/number of contributors grows.

### Possible solution
Jest + Puppeteer?

**Comment by jef** [comment]
We have ava and is not in use at all. But we could use jest if it has puppeteer plugins. Are you familiar with this? TS isn't my bread and butter.

**Comment by thetimothyp** [comment]
I haven't used ava before, but from a quick look at the docs it seems to play fine with Puppeteer. If ava is already part of the project we can just start there and think about switching frameworks if the need arises. I don't think there is a need to overthink it at this stage. I can owkr on incrementally adding some small tests with ava and see where things go.

**Comment by jef** [comment]
I think I removed it since I wasn't using it yet :smile: I think ava should be sufficient enough. I look forward to your tests!
