### ISSUE TITLE
Add ncurses like windowing support to monitor multiple products

### ISSUE THREAD

**Issue by njgreb** [jef/streetmerchant#705]
### Description

Now...I might be crazy, but would it be nice to have an ncurses based layout to have separate "windows" in the shell showing tracking of each product type?

### Possible solution

Could use a library like https://github.com/chjj/blessed to render the layout.

**Comment by jef** [comment]
As a rice lover (but not doer), I find this extremely cool. But the effort here I think will outweigh the return (in my opinion). As a workaround (not optimal, of course) would be to spin up a couple tmux/screen windows and boot each one with a different config (inline, as files I don't think are supported right now, but easy to do).

BUT! That being said, I think something like this is important and @michaelzhou1987 has been working on a [VueJS frontend](https://github.com/michaelzhou1987/streetmerchant/tree/vue-ui). It's in its early stages, but I think this type of work would appeal to more people rather than us nerds.

What are your thoughts?

**Comment by njgreb** [comment]
Ok, real talk time I guess!  I think the best route for a long life of this project is to break the backend and frontend up.  Have the backend support a nice REST API + maybe something like WebSockets.  Then UI creation can be whatever a UI author wants it to be.  I think a lot of normal users would LOVE a web ui like what you already referenced...and crazy nerds (like me!) would dig some terminal view.

**Comment by jef** [comment]
> I think the best route for a long life of this project is to break the backend and frontend up.

I agree 100%

This also warrants transitioning the discussion to: https://github.com/jef/streetmerchant/issues/706

In my opinion. I think keeping the two "projects" (if you will) in the same repository makes sense as well. I think using WS is a great candidate for keeping open connections and live feeding. Someone has implemented GraphQL which is also pretty cool https://github.com/jef/streetmerchant/pull/700.

To be honest, I think we're at a really good turning point here and think the project can go in many directions.

**Comment by thetimothyp** [comment]
>  Someone has implemented GraphQL which is also pretty cool #700.
This was me. Not sure if this is the place for this discussion to be continuing, but IMO creating a separate API becomes more and more essential as scale/complexity grow; the data and the views shouldn't be so tightly coupled, especially as complexity grows. Ideally, we would host the API and a default client, and the average user (not developer) would never see a single line of code or configuration (aside from a UI). Of course, this brings up the topic of hosting costs, which the current self hosted solution only incurs for the individual user.

> But I think some default UI and terminal would equally be important for those who are using on their own.
I think this is fair, and could be a good way of dogfooding an API.

**Comment by jef** [comment]
> but IMO creating a separate API becomes more and more essential as scale/complexity grow; the data and the views shouldn't be so tightly coupled when the data starts getting complex.

Yes, yes, yes! I don't want to push micro services here (completely separate projects), but I think separating these implementations will be much better. (Kind of #706; and I've mentioned a bit more in the Discord.) This is one of the side effects you see in this project as it initialized as a gist.

I do have an org for streetmerchant and there is opportunity there as well (backend, frontend, etc), but I think as of now, we can let it grow naturally to that if it becomes that.

**Comment by thetimothyp** [comment]
> Yes, yes, yes! I don't want to push micro services here (completely separate projects), but I think separating these implementations will be much better.

I agree with this; the size of this project isn't big enough to warrant splitting into micro services. A monorepo with separation of frontend/backend within it is easier to manage for something of this size.
