### ISSUE TITLE
Stock checks stop after encountering navigation timeout

### ISSUE THREAD

**Issue by cyburgee** [jef/streetmerchant#708]
### Description
After hitting a navigation timeout for Best Buy US founders edition, it stops checking for stock. 

I have the options configured to only look for the founders edition card on Best Buy US. Maybe it's still checking for stock but it isn't logging the fact.

![Screen Shot 2020-11-06 at 11 45 52 AM](https://user-images.githubusercontent.com/5669821/98392325-d7b87180-2025-11eb-8475-79694b4bdc1e.png)

**Comment by cyburgee** [comment]
some more detail: this only seemed to happen when i was running another instance of the program that i had configured with a different set of stores, cards, and alert recipient

**Comment by michaelzhou1987** [comment]
> some more detail: this only seemed to happen when i was running another instance of the program that i had configured with a different set of stores, cards, and alert recipient

could be both instance are using the same port?

**Comment by cyburgee** [comment]
i haven't set an option for the web port so i assume it's not using that functionality

**Comment by cyburgee** [comment]
so after testing a bit more, it doesn't just happen when running multiple instances. it seems to affect a single store when there's a navigation timeout. no items for that store log checks any more.

**Comment by cyburgee** [comment]
might be that i ran out of disk space. there were a lot of puppeteer files in /tmp that had taken up lots of space after running this for a few weeks

**Comment by treydott** [comment]
This looks related to #677

**Comment by jef** [comment]
I'm going to run streetmerchant over night with your settings and see if I can reproduce. I'll let you know soon enough! Thank you.

**Comment by jef** [comment]
I've been running this now for a good 24 hours and haven't ran into this issue. I'm going to close this out. It could potentially be client side

**Comment by cyburgee** [comment]
thanks for looking into it. was probably related to my lack of disk space

**Comment by jef** [comment]
Sorry @cyburgee :(

I'll look into that caching and creating a script to clean up.
