### ISSUE TITLE
How to test notification with the new .env file with the docker run?

### ISSUE THREAD

**Issue by JeffLuoo** [jef/streetmerchant#710]
as titled

**Comment by mrmos** [comment]
I test by cloning the repo to my server and running the `test:notification` to make sure everything is configured correctly and then `docker run` command, passing in the same `.env` file

You could also `docker exec -it <container> /bin/sh` to get into the container and run tests from there

There might be a better way, but this works for me

**Comment by jef** [comment]
Good question! Usually modifying the `entrypoint` of the container is done, but I didn't really set this up great for that, as we aren't copying over the `package.json` either. I'm going to modify the Dockerfile to make this easier.

Thanks for the question 😄

**Comment by jef** [comment]
Okay, now you can run:

```
docker run --cap-add=SYS_ADMIN \
  -it --rm --env-file ./.env \
  streetmerchant:localhost test:notification:production
```

**Comment by jef** [comment]
Let me know how that goes. Thanks!

**Comment by JeffLuoo** [comment]
appreciate that! Thank you

**Comment by jef** [comment]
You're welcome!
