### ISSUE TITLE
Add AMD Direct Buy for Ryzen 5000 series

### ISSUE THREAD

**Issue by Replica17** [jef/streetmerchant#714]
Please add AMD Direct Buy website for the Ryzen 5000 series.
https://www.amd.com/en/direct-buy/us

Thanks!

**Comment by jef** [comment]
I believe they are already.

**Comment by mven** [comment]
@Replica17 AMD Direct Buy is being utilized per https://github.com/jef/streetmerchant/blob/main/src/store/model/amd.ts#L19

Looks like you can close this issue.
