### ISSUE TITLE
New StreetMerchant User

### ISSUE THREAD

**Issue by FutureHasGame** [jef/streetmerchant#723]
Hello friends :) I am new to using git in generally, and even newer to scripting/coding. I am overly enthusiastic with the resources that have been allocated for us plebians. My question is, is there a open forum discussion I can join on this, I don't want to have this in the issues section but I can't seem to find where I can ask questions and such. I am a very easy guy to work with so, if you could please welcome me nicely. :) If anyone wants to leave their discord, that would be greatly appreciated, I have a few questions I'm guessing almost anyone who uses this program can answer. I'm just a noob trying to learn a little bit if you have free time. 
Thanks, FutureHasGame.
#notanissue

**Comment by jef** [comment]
I have a Discord that I go into from time to time. I know others also are in there willing to help. Feel free to join anytime.

https://discord.gg/gbVY4vB9JF

That being said, GitHub is in the process of making "Discussions" public and we will use that as soon at is.

It seems like [this thread](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/415) is for asking to join?

I'll post in there. Thanks!
