### ISSUE TITLE
Possible to add Xbox Series X / S before the mostly online launch on the 10th?  TIA

### ISSUE THREAD

**Issue by happytambi** [jef/streetmerchant#728]
### Description
It would make my year if we could get the Xbox Series X/S added in before the mostly online launch on the 10th.  I saw the PS5 & PS5 digital were added, I'm sure it would be similar. 

### Possible solution
Adding URLs to config?  Glad to assist if I know how/where

**Comment by jef** [comment]
Duplicate of #506
