### ISSUE TITLE
Amazon Links Invalid

### ISSUE THREAD

**Issue by gabriwong** [jef/streetmerchant#733]
Hi,
The amazon link generated in discord is in this format which throws an error on Amazon.

https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08HR9D2JS&Quantity.1=1

I was able to view the page through 
https://www.amazon.com/dp/B08HR9D2JS

I do have HEADLESS=true

**Comment by jef** [comment]
This is intended, as it was probably no longer available.

Take a look at this link: https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08CKDLN91&Quantity.1=1

This graphics card is in stock, whereas yours is not (in stock via third-party sellers though).

**Comment by gabriwong** [comment]
Got it. I think I noticed that after trying to add things manually.

Happy to help update FAQs if needed!

Thanks!

**Comment by jef** [comment]
@gabriwong Yeah, could be a good thing to add to the FAQ. Do you mind adding? Thanks!
