### ISSUE TITLE
something bad happened, resetting streetmerchant in 5 seconds Could not find browser revision 809590. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

### ISSUE THREAD

**Issue by TheSweeet** [jef/streetmerchant#734]
**Tried cloning on a different drive still getting the same error. I ran npm run install in the street merchant directory. Not sure what to do. I looked into the last guy who posted this error bot couldn't seem to find a resolution in the thread.** 

> "[5:00:13 PM] warn :: nvidia is deprecated in favor of bestbuy
> [5:00:13 PM] info :: ℹ selected stores: nvidia
> [5:00:13 PM] info :: ℹ selected series: 3070, 3080, 3090, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de
> [5:00:14 PM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find browser revision 809590. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary."

EDIT: Been messing around trying to figure out what the problem was. I found out that during my installation I thought that "NPM Install" had finished but it was just stuck on a package. I stopped the installation (twice) by typing "npm run start" which caused me to get this error.

**Comment by TheSweeet** [comment]
Been messing around trying to figure out what the problem was. I found out that during my installation I thought that "NPM Install" had finished but it was just stuck on a package. I stopped the installation (twice) by typing "npm run start" which caused me to get this error.

**Comment by AlphaOmega2020** [comment]
Hi, im getting this exact error but NPM installed fine...
