### ISSUE TITLE
Mac installation does not respect .ENV

### ISSUE THREAD

**Issue by Ben7530** [jef/streetmerchant#735]
### Description

(Note: I am not a developer!) I got StreetMerchant up and running almost perfectly on my desktop PC, and when I went to install it on my MacBook, the directory structure is different, and while Mac StreetMerchant runs, does not respect the .ENV file I copied into its directory from the Windows installation.

Help?

### Possible solution

Are things building differently on mac and PC? Weird.

**Comment by omelettedufromagee** [comment]
Is it name .env (not .ENV) and is correctly on the root directory of streetmerchant?
I don't have a Mac to test unfortunately .

**Comment by Ben7530** [comment]
> Is it name .env (not .ENV) and is correctly in the root directory of streetmerchant?
> I don't have a Mac to test unfortunately .

Thanks for your response. Yes, sorry, I was trying to draw attention: it is lowercase .env on PC and Mac. Both in the root directories.

**Comment by jef** [comment]
Unfortunately (and fortunately), this is not the case. There have been many issues around this.

https://github.com/jef/streetmerchant/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+env

Please try to find your solution in there.

Thanks!
