### ISSUE TITLE
Please add Apprise support for notifications!

### ISSUE THREAD

**Issue by essteewhy** [jef/streetmerchant#739]
Looking for JOIN push notification support, apprise <https://github.com/caronc/apprise> supports many of these 3rd party notification systems!

**Comment by jef** [comment]
That's a really cool tool! Unfortunately, it's a library for Python and streetmerchant is built on Node.js.

**Comment by jef** [comment]
We do have many notification options though. Please look under https://github.com/jef/streetmerchant#customization to find what you're looking for!

**Comment by essteewhy** [comment]
I see, ok.. was hoping to get Join support through apprise, was hoping that was possible.. perhaps you can add Join support in another way?  https://joaoapps.com/join/

**Comment by jef** [comment]
I'll take a look at that. Thanks!

**Comment by essteewhy** [comment]
awesome thanks!!
