### ISSUE TITLE
SFF Folks Need Love

### ISSUE THREAD

**Issue by lngchn** [jef/streetmerchant#758]
### Description

I'd like to suggest adding Corsair SF Series 750W power supply to the list of items to check. This product has always been out of stock for as long as I could remember, and every time it's back in stock at somewhere, it doesn't last more than 5 minutes.

Possible places to check:
[Newegg](https://www.newegg.com/corsair-sf750-cp-9020186-na-750w/p/N82E16817139080?Item=N82E16817139080&nm_mc=AFC-RAN-COM&cm_mmc=AFC-RAN-COM&utm_medium=affiliates&utm_source=afc-NowInStock&AFFID=1709054&AFFNAME=NowInStock&ACRID=1&ASUBID=nismain&ASID=https%3a%2f%2fwww.nowinstock.net%2f&ranMID=44583&ranEAID=1709054&ranSiteID=AKGBlS8SPlM-erM3_Lbm5mQL7oFt5nQ5Sg)
[Bestbuy](https://www.bestbuy.com/site/corsair-sf-series-750w-atx12v-2-4-eps12v-2-92-sfx12v-80-plus-platinum-modular-power-supply-black/6351845.p?skuId=6351845)
[Corsair](https://www.corsair.com/us/en/Categories/Products/Power-Supply-Units/Power-Supply-Units-Advanced/SF-Series/p/CP-9020186-NA?utm_source=Troposphere%20LLC_62662&utm_medium=Affiliate&utm_campaign=490888_Online%20Tracking%20Link&utm_content=Content&clickid=xoaVvDQcBxyJRi-wUx0Mo382UkE25F35yT7QSU0&irgwc=1)
[B&H](https://www.bhphotovideo.com/c/product/1560680-REG/corsair_cp_9020186_na_corsair_sf750_power_supply.html/DFF/d10-v21-t1-x1041471/SID/103810X1560435X251e6bfc2c4a77e4a3aadb8707f65ee5)

Other similar items are [Cooler Master V750](https://www.amazon.com/Cooler-Master-Efficiency-Semi-fanless-Operation/dp/B08LP7B7FM) and [Cooler Master V850 SFX](https://www.amazon.com/gp/product/B08LP6WS35/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)

**Comment by rrbailey89** [comment]
Newegg will let you back order it https://www.newegg.com/corsair-rmx-white-series-rm750x-white-cp-9020187-na-750w/p/N82E16817139246

**Comment by whiskeytangofoxy** [comment]
I'd like to second this request. I've manually added a few links to the SF750 (which has kept me from updating to 3.0.0) but the scarcity of these items is just as bad as Ryzens, if not moreso.

**Comment by jef** [comment]
Sure! We can put this on the to-do list for sure.

**Comment by Replica17** [comment]
Upvote for this! Thanks for all your work
