### ISSUE TITLE
Only checking Nvidia store while others also are selected

### ISSUE THREAD

**Issue by ron-tg** [jef/streetmerchant#764]
### Description
Hey,

In the `.env` file I've put additional stores in the `STORES` argument, including Nvidia, but the only store that the script is checking is Nvidia.

![image](https://user-images.githubusercontent.com/59559611/98796983-ae785680-2414-11eb-82e4-373702332bcd.png)
![image](https://user-images.githubusercontent.com/59559611/98797018-b637fb00-2414-11eb-8be8-217d71bb4443.png)

`.env` file code:
```
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

ASCII_BANNER=
ASCII_COLOR=
BROWSER_TRUSTED=
COUNTRY=
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=nvidia
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=3070, 3080, 3090
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=nvidia, amazon, asus, evga-eu, gamestop, newegg, officedepot
TELEGRAM_ACCESS_TOKEN=MY_REAL_TOKEN_IS_HERE
TELEGRAM_CHAT_ID=MY_REAL_ID_IS_HERE
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
USER_AGENT=
WEB_PORT=
```

### OS:
Windows 10 Version 2004 (OS Build 19041.610)

**Comment by jef** [comment]
It's working great! The problem here is that `nvidia` branded cards are only on `bestbuy` and `nvidia`, which you don't have selected 😄 Remove `nvidia` brand and see if it starts searching!

**Comment by ron-tg** [comment]
@jef I removed Nvidia from the `STORES` argument but now it looks like it doesn't search at all.
![image](https://user-images.githubusercontent.com/59559611/98822838-fc538580-2439-11eb-862d-bacea55699a2.png)

**Comment by vp-cshow** [comment]
The "nvidia" brand is the FE. Follow the instructions in the customization section of the README (found at https://github.com/jef/streetmerchant) to tell the program card models you want to monitor.

**Comment by ron-tg** [comment]
@vp-cshow I did read it already and I've put `SHOW_ONLY_MODELS=founders edition`, still the same output.

**Comment by vp-cshow** [comment]
None of the stores you selected sell the founders edition. Only best buy is selling the FE in the US.

**Comment by jef** [comment]
Sorry. I mean to say, remove `nvidia` from `SHOW_ONLY_BRANDS`. Also, what @vp-cshow said.
