### ISSUE TITLE
Ubuntu Server

### ISSUE THREAD

**Issue by B1022** [jef/streetmerchant#783]
### Description

Everytime I attempt to start the script "sudo npm run start" it throws an error saying that "sc -c tsc" and "sh -c npm run build && node build/index.js" failed
OS Is Ubuntu Server 

I have node installed same with all the files and everything needed

**Comment by B1022** [comment]
alright well I got it to start now but throws issue that something bad happened, failed to launch the browser process

**Comment by B1022** [comment]
chromium is installed on the ubuntu server

**Comment by B1022** [comment]
Alright well it works but every time I use CTRL + C to close it then it says command failed "csh -c npm run build && node build/index.js" will that effect anything?

**Comment by B1022** [comment]
and having 2 ubuntu screens with 2 different trackers it throws a ton of timeout 300000 ms exceeded errors

**Comment by B1022** [comment]
now im getting a ton of binary issues on 1 session of it. in pink it says "something bad happened....resetting...could not find browser revison"

**Comment by jef** [comment]
Hi there! It's really hard to understand any of issues because I don't have a console log. Can you provide that?

**Comment by B1022** [comment]
Yeah sure. I fixed the binary issue. Now its just throwing a ton of exceed navigation errors when I open 2 or more streetmerchants. Let me get a console log for you

**Comment by B1022** [comment]
![image3](https://user-images.githubusercontent.com/64097512/99094408-c4ffe880-25a1-11eb-8070-91ab1cc75583.jpeg)
![image1](https://user-images.githubusercontent.com/64097512/99094414-c5987f00-25a1-11eb-869f-fd67b647aa26.jpeg)
![image0](https://user-images.githubusercontent.com/64097512/99094425-cc26f680-25a1-11eb-8b4d-0031ea583f78.jpeg)

One is from my 3070 screen other is from 3080 and other is from console (3 different webhooks and ping roles on discord)

**Comment by B1022** [comment]
always seems to exceed on newegg, bestbuy and sometimes walmart and target

**Comment by jef** [comment]
I'd make sure you have `USER_AGENT` setup. https://www.google.com/search?q=what+is+my+user+agent

Another thing to mention is that if you have 3 bots running at once, all with amazon, then you will be hitting amazon 3x as much, so you may be getting a lot more timeouts or other status codes.

This is all well known behavior and is a side effect of scraping _many_ pages from the same domain.

**Comment by B1022** [comment]
alright. If I set the timeout to 0 will it not continue until it can ping that page?

**Comment by jef** [comment]
Yep, that's correct.

**Comment by B1022** [comment]
Alright ill try setting up my user agent. Do you know any method to get it on ubuntu? If not its fine ill google it

**Comment by jef** [comment]
You would get it the same way you did with Windows/macOS. Yes, use that whole string if that's where you're running it.

`USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"`

**Comment by B1022** [comment]
Alright thanks
