### ISSUE TITLE
Different ping roles for 1 script

### ISSUE THREAD

**Issue by B1022** [jef/streetmerchant#784]
### Description

Have 1 script checking cards, cpus, consoles and all of the models of them but if it finds a 3080 in stock it sends to discord and only pings 3080 or if it finds zen 3 3900x it sends to discord and only pings 3900x. Might not be possible but worth a shot

**Comment by jef** [comment]
Your best (easiest as of now) is to run X streetmerchants with different settings. This will be possible at some point in the future, but not sure when.

**Comment by B1022** [comment]
alright do you have any tutorial on how to setup that?

**Comment by B1022** [comment]
thanks

**Comment by B1022** [comment]
ive been doing that right now but have been running into some issues

**Comment by B1022** [comment]
Did this myself :D
