### ISSUE TITLE
Canada Computers results slightly messed up because of the way they handle stock (if a card shows up in a physical store, the bot has no way of knowing)

### ISSUE THREAD

**Issue by mAustinKos** [jef/streetmerchant#788]
Stock appears to be slowly trickling into random Canada Computer stores throughout Canada, and they aren't being put on line (presumably because this is better for PR), but _are_ being listed publicly so anyone can go form an angry mob in Vaughan at 10am today and one of them will get a 3070 (I'm trying to talk someone into being that person)

This basically means that the bot reports a ton of false negatives, because the value it checks only relates to the online stock (which it's reasonable to expect is going to stay at zero for a while). 

This is easily fixed by going to the CanadaComputers.ts file and changing 

labels: {
		outOfStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['not available online']
		}

to 

labels: {
		outOfStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['In-Store Back Order']
		}
Which represents the same situation (they have no cards to sell), but triggers the flag when one turns up in-store. I don't know about it as a long term solution, but it's getting correct results for me right now. 

This is a quick and dirty solution, so I definitely wouldn't mind if someone came up with a better one. This is my first time doing this - seeing a problem in an open source project, 'fixing it', and coming back to try to help everyone, so I apologize if I did not act in accordance with some set of rules or decorum.

**Comment by kade-robertson** [comment]
This could arguably also produce a lot of false positives as well -- just because it shows up in _a_ store doesn't mean it shows up in one you can actually buy from yourself. Maybe this makes sense as being a setting you can change, i.e. specified by an environment variable: `CC_ONLINE_ONLY=true/false`

**Comment by rodrigorodrigo** [comment]
> 
> 
> Stock appears to be slowly trickling into random Canada Computer stores throughout Canada, and they aren't being put on line (presumably because this is better for PR), but _are_ being listed publicly so anyone can go form an angry mob in Vaughan at 10am today and one of them will get a 3070 (I'm trying to talk someone into being that person)
> 
> This basically means that the bot reports a ton of false negatives, because the value it checks only relates to the online stock (which it's reasonable to expect is going to stay at zero for a while).
> 
> This is easily fixed by going to the CanadaComputers.ts file and changing
> 
> labels: {
> outOfStock: {
> container: 'div[class="pi-prod-availability"]',
> text: ['not available online']
> }
> 
> to
> 
> labels: {
> outOfStock: {
> container: 'div[class="pi-prod-availability"]',
> text: ['In-Store Back Order']
> }
> Which represents the same situation (they have no cards to sell), but triggers the flag when one turns up in-store. I don't know about it as a long term solution, but it's getting correct results for me right now.
> 
> This is a quick and dirty solution, so I definitely wouldn't mind if someone came up with a better one. This is my first time doing this - seeing a problem in an open source project, 'fixing it', and coming back to try to help everyone, so I apologize if I did not act in accordance with some set of rules or decorum.

When I did canadacomputers.ts I noticed exactly this. But, as @kade-robertson said, this would produce a lot of false positives (and it did, when I was testing). Adding a new variable could be a good approach (there are a few others that are also needed, as PS5 max price for example) but we'd need @jef approval for that I suppose :P

**Comment by mAustinKos** [comment]
Yeah, I said it was quick and dirty. There are a few potentially better solutions, I'm just not super familiar with typescript (I was surprised to find the way things were being done so different from the kinds of JS I'm used to) and wanted to change as little as possible so as to avoid stepping on anyone's toes. I'm going to go try out a few of those options and hopefully come back with whatever works best to see what others think of it. 

Given that Canada Computers' site already has built in functionality to let you select which local store is most relevant to you, something involving that seems like the best option to me, and is probably what I'll spend most of my time on, but I'm mentioning it to see if anyone else actually thinks that option is worth exploring.

**Comment by BigShoots** [comment]
I fixed it by changing this. 

		outOfStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['not available online']
		}

to 

		inStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['Online In Stock']
		}

**Comment by jef** [comment]
Fixed
