### ISSUE TITLE
Ryzen 5900x uk will only check AMD and no of the other sites

### ISSUE THREAD

**Issue by pete234** [jef/streetmerchant#795]
Out of all of the sites I selected it will only search on the AMD website for the 5900x
![image](https://user-images.githubusercontent.com/44713472/99122572-80eb0300-25f6-11eb-98a2-860bd680dcae.png)

**Comment by sgruz** [comment]
Looking at pull #743 have added this to my amazon-uk.ts, at least it will start searching on amazon uk:

`		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.co.uk/gp/aws/cart/add.html?ASIN.1=B08166SLDF&Quantity.1=1',
			model: '5600x',
			series: 'ryzen5600',
			url: 'https://www.amazon.co.uk/dp/B08166SLDF'
		},
		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.co.uk/gp/aws/cart/add.html?ASIN.1=B0815XFSGK&Quantity.1=1',
			model: '5800x',
			series: 'ryzen5800',
			url: 'https://www.amazon.co.uk/dp/B0815XFSGK'
		},
		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.co.uk/gp/aws/cart/add.html?ASIN.1=B08164VTWH&Quantity.1=1',
			model: '5900x',
			series: 'ryzen5900',
			url: 'https://www.amazon.co.uk/dp/B08164VTWH'
		},
		{
			brand: 'amd',
			cartUrl: 'https://www.amazon.co.uk/gp/aws/cart/add.html?ASIN.1=B0815Y8J9N&Quantity.1=1',
			model: '5950x',
			series: 'ryzen5950',
			url: 'https://www.amazon.co.uk/dp/B0815Y8J9N'
		}`

Also lines 42, 45 and 50 have wrong site name .com instead of co.uk

**Comment by jef** [comment]
We have merged that and you should be good now!
