### ISSUE TITLE
Best Buy not working

### ISSUE THREAD

**Issue by Rhylen** [jef/streetmerchant#797]
### Description
I had street merchant running ever since best buy canada was added and haven't got a single hit, but today I was reading online that there had apparently been a few drops on best buy canada that this script didn't catch. So I thought I would try and test it with a 2060 that was in stock and still it kept outputting that it was out of stock. 
See attachment. (Ignore the different band, model name and series I only changed the URL) cause I couldn't get the test to work.

### Possible solution
not sure. I'm not that experienced in coding. 
<img width="1182" alt="Screen Shot 2020-11-13 at 7 46 59 PM" src="https://user-images.githubusercontent.com/71900390/99136284-a9203500-25e9-11eb-8260-a0994b661e39.png">

**Comment by FabledNinja** [comment]
I am dying to know who to specify urls like you did, assuming it is the correct way. OP, could you please say how to?

**Comment by Rhylen** [comment]
well I'm not sure if I even did it right, but you go into streetmerchant/scr/store/model/'pick the store here.ts' (open in text editor) then you can change what urls are attached to what card for that specific store. Not sure if this answer your question.

**Comment by mven** [comment]
Found the issue. Fixed in linked PR.

**Comment by Rhylen** [comment]
I added your changes to my bestbuy-ca.ts and it works!
Thanks mate!
@mven

**Comment by us1v1an** [comment]
Bestbuy US doesn't seem to be working for me either.

**Comment by mven** [comment]
Best Buy US is working fine for me.

**Comment by jef** [comment]
Probably didn't pull latest from `main`. I'm going to close this out now. Thanks @mven!
