### ISSUE TITLE
False alerts for saturn/mediamarkt

### ISSUE THREAD

**Issue by jafricola** [jef/streetmerchant#800]
I am getting false alerts for mediamarkt and saturn for any model of 3080.

**Comment by bulls45** [comment]
Same here, basically all products for Mediamarkt and Saturn trigger alerts, pop-ups etc. although they have nothing available except for some 3090s

**Comment by Apington** [comment]
I had the same problem and altered the depending .ts files a bit. Add the following code before the `outOfStock` element of the saturn.ts and mediamarkt.ts

`inStock: [
			{
				container: '#root',
				text : ['Lieferung']
			}, 
			{
				container: '#root',
				text : ['abholbereit']
			}
		],`

As the default items are not available right now I tested it against a manually added item. Maybe give it a try 😃.

**Comment by scaryval** [comment]
@Apington Could you pls show me the whole code of saturn.ts after your adds?

**Comment by Apington** [comment]
sure, no problem. I altered the mediamarkt.ts with the same flags. Just rename the file to .ts or copy paste the content in your .ts files.

[saturn.txt](https://github.com/jef/streetmerchant/files/5587822/saturn.txt)

**Comment by jef** [comment]
This needs updating... I'll update.
