### ISSUE TITLE
Check the "See all buying options page" for Amazon

### ISSUE THREAD

**Issue by B1022** [jef/streetmerchant#803]
### Description

Check the "See all buying options page" for Amazon and see if any of them are below the price set in .env. This will give more accurate readings.

### Possible solution

Change this to fix it. Ill update all the links myself.

		inStock: {
			container: '#desktop_buybox',
			text: ['add to cart']

**Comment by B1022** [comment]
also do the same for microcenter to check for the "Limited Availability" on the website

**Comment by us1v1an** [comment]
I agree, there are many listings on Amazon that have no buybox on the main page. The only way to get accurate info is to check the "all offers" page. 

For example:

https://www.amazon.com/dp/B08L8JNTXQ

https://www.amazon.com/gp/offer-listing/https://www.amazon.com/dp/B08L8JNTXQ

**Comment by B1022** [comment]
Yeah. If anyone knows how to add this or Jef if you figure it out lmk what to change

**Comment by jef** [comment]
I'm sure we could do something like this, but I personally don't want to go down into other links and scrape those pages before solving some other enhancements. I think this is fine, but low on my personal list. If anyone else wants to take a crack at it, feel free!

**Comment by B1022** [comment]
Im happy to scrape the links but how would I change this set of code to find the add to cart buttons on that page? Anyone know?

export const Amazon: Store = {
	labels: {
		captcha: {
			container: 'body',
			text: ['enter the characters you see below']
		},
		inStock: {
			container: '#desktop_buybox',
			text: ['add to cart']
		},
		maxPrice: {
			container: 'span[class*="PriceString"]'
		}

**Comment by jef** [comment]
We'd probably add another label to look for. Like `external` or something.

**Comment by B1022** [comment]
Alright, ill try to figure that part out

**Comment by B1022** [comment]
If anyone else has any ideas feel free to comment. Trying to get this to work but no luck so far.

**Comment by B1022** [comment]
Pings the first listing but wont continue checking the others and just throws 503 errors

**Comment by B1022** [comment]
export const Amazon: Store = {
	labels: {
		captcha: {
			container: 'body',
			text: ['enter the characters you see below']
		},
		inStock: {
			container: 'div[class*="olpAtcBtnWrap"]',
			text: ['add to cart']
		},
		maxPrice: {
			container: 'span[class*="OfferPrice"]'
		}

Using that setup btw

**Comment by us1v1an** [comment]
Ideally, it should look for the listing that's sold by Amazon, or any listing below a certain price. But for the purpose of this tool, the only listing that really matters is the one sold by Amazon. Everyone else is a reseller and their price will always be much higher than retail price.

**Comment by B1022** [comment]
Yeah but sometimes Amazons listings don't come up on the main page

**Comment by B1022** [comment]
Every other discord pings based off the offer page since its more accurate

**Comment by B1022** [comment]
My method works using 

		inStock: {
			container: 'div[class*="olpBuyColumn"]',
			text: ['add to cart']

but it wont continue looking for other offers on the page. only sees first one

**Comment by J-Hinton** [comment]
Personally, I feel we should be only using the Buy Box. This is designed for a reason... as a seller you must reach criteria to win the buy box (e.g. trusted seller, competitive price, fba or prime self-fulfilled, new items only, in stock etc.). Any seller meeting their hidden criteria is able to win the buy box.
If we go down the route of using all sellers, you're going to get a load of notifications of in stock for resellers charging extremely high prices.

I'm happy to have a new environment variable to specify the type of Amazon seller; Buy-box (default) or all. But I don't think we should be forcing everyone down to having all sellers of a product.

**Comment by us1v1an** [comment]
I agree with you that we should only look for offers sold by Amazon. However, there are many times when something comes in stock (offer by Amazon) and gets sold out before the buybox even gets activated. 

Therefore, I think the best option is to make SM search for offers by Amazon only in the “all offers” page. Searching only the main page for the buybox is never going to work, specially for these high in demand products that come in stock and get sold out in seconds.

**Comment by B1022** [comment]
Yeah. We dont have to force someone. I just want to know how I can add this so I can do it. Been trying and got

	inStock: {
		container: 'div[class*="olpBuyColumn"]',
		text: ['add to cart']

to ping the first item but wont ping the rest. If anyone knows how to do it let me know. Im going to use it even if no one else wants to

**Comment by J-Hinton** [comment]
@B1022 Please can you send an example link. I don't see any products with the class *olpBuyColumn*

**Comment by B1022** [comment]
https://www.amazon.com/gp/offer-listing/B08HJQ182D/ref=dp_olp_unknown_mbc

**Comment by B1022** [comment]
Let me know if you figure it out

**Comment by B1022** [comment]
Did that link help you @J-Hinton?

**Comment by lys1030** [comment]
Amazon sets rate limit on the /offer-listing page quite harshly. I tried and started to see Captcha very soon.
