### ISSUE TITLE
Add Support for Playstation Direct Store for the PS5

### ISSUE THREAD

**Issue by noblesin** [jef/streetmerchant#804]
### Description

Add Support for the Playstation Direct Store for the PS5 Disc and the PS5 Digital Editions

### Possible solution

Here are the PS5 Product URLs that display 'Out of Stock' currently and the 'Add' Button is not visible:

PS5 Disc Edition:
https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816

PS5 Digital Edition:
https://direct.playstation.com/en-us/consoles/console/playstation5-digital-edition-console.3005817

Here is a Product where the 'Add' Button is visible:

https://direct.playstation.com/en-us/accessories/accessory/dualsense-wireless-controller.3005715

A Queuing System Workaround will be required to be coded into StreetMerchant to get into the Playstation Direct store to check availability when PS5 are about to become available. As of today, The Playstation Direct Store implements a Queuing System which gets put into place typically 30 minutes to an Hour before both Consoles are about to be available for purchase. In order to get into the Playstation Direct Store to check availability in this situation and get around the Queueing System, One can manually install the 'UBlock' Google Chrome plugin and add below filters to block/ignore all requests involving:

queue
queue-it.net
*queue-it.net

With this workaround, Even when the queuing System is in place, One can get into the Playstation Direct store and look at the Product Page to see if it is available. I don't know how this could be integrated/coded into the StreetMerchant Solution.

**Comment by J-Hinton** [comment]
Another alternative would be to implement `realTimeInventoryLookup`, where we can use the `api.direct.playstation.com` to assist with this real-time stock level status.

Example GET request URL:
`https://api.direct.playstation.com/commercewebservices/ps-direct-us/products/productList?fields=BASIC&productCodes=3005816`

Happy to work on this and implement it later today.

**Comment by DamnNewbie** [comment]
So for both playstaion direct and the walmart release at 3pm today these never showed as in stock.  Not sure if anyone has a working example, but right now it is not helpful for PS5 since they never show in stock.

**Comment by DamnNewbie** [comment]
Currently ps5 digital shows instock when hitting this browser: https://api.direct.playstation.com/commercewebservices/ps-direct-us/products/productList?fields=BASIC&productCodes=3005817 

applications is reporting out of stock.
