### ISSUE TITLE
Issue with Debian based distro's and puppeteer 

### ISSUE THREAD

**Issue by hmontesdeoca** [jef/streetmerchant#805]
### Description

I had an error with puppeteer on both WSL and ARM running debian based distributions  

![image](https://user-images.githubusercontent.com/36084984/99160806-15f60680-26a0-11eb-8934-4c74375b322e.png)

### Possible solution

This solution is exclusive to my raspberry pi 

I manually installed chromium browser then I simply edited the line in puppeteer to detect a local version via linux filesystems. This is a temporary solution for linux users but not all file systems are the same. 
this is located in src/index.ts line 60
![image](https://user-images.githubusercontent.com/36084984/99160882-f90e0300-26a0-11eb-8b0e-861f5d77d484.png)

**Comment by jef** [comment]
You can also do `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser` without having to update the code. This is a common issue with others running Rasbian or other linux distros that don't have all of these libraries. I should probably add to FAQ.

Thanks!
