### ISSUE TITLE
Big Navi GPUS

### ISSUE THREAD

**Issue by B1022** [jef/streetmerchant#808]
### Description

Add support for tracking Big Navi GPUS

**Comment by Replica17** [comment]
Yes please

**Comment by yourpalsneakers** [comment]
Yes, really hoping this will be added!

**Comment by Hamburgpriat** [comment]
There are no known store links yet. Only when the graphics cards are listed, he can add them to the program

**Comment by B1022** [comment]
Yeah I know

**Comment by Hamburgpriat** [comment]
Good luck  without Bot :-(

**Comment by mickhuska** [comment]
links are up!

**Comment by historypsi** [comment]
Here are the links...please and thank you!

BestBuy Links:

***6800XT***
https://www.bestbuy.com/site/xfx-amd-radeon-rx-6800xt-16gb-gddr6-pci-express-4-0-gaming-graphics-card-black/6441226.p?skuId=6441226
https://www.bestbuy.com/site/msi-radeon-rx-6800-xt-16g-16gb-gddr6-pci-express-4-0-graphics-card-black-black/6440913.p?skuId=6440913
***6800***
https://www.bestbuy.com/site/xfx-amd-radeon-rx-6800-16gb-gddr6-pci-express-4-0-gaming-graphics-card-black/6442077.p?skuId=6442077
https://www.bestbuy.com/site/msi-radeon-rx-6800-16g-16gb-gddr6-pci-express-4-0-graphics-card-black-black/6441020.p?skuId=6441020

Amazon Links:

***6800XT***
https://www.amazon.com/Sapphire-Radeon-Gaming-Graphics-GDDR6/dp/B08MVC76SR?ref_=ast_sto_dp
https://www.amazon.com/XFX-GDDR6-USB-C-Graphics-RX-68TMATFD8/dp/B08N6ZLX9B?ref_=ast_sto_dp
***6800***
https://www.amazon.com/PowerColor-Graphics-Powered-Raytracing-Infinity/dp/B08MNZM5TK?ref_=ast_sto_dp
https://www.amazon.com/Sapphire-Radeon-Gaming-Graphics-GDDR6/dp/B08MVCLBWK?ref_=ast_sto_dp

**Comment by mickhuska** [comment]
newegg: https://www.newegg.com/p/pl?d=6800&N=100007709&cm_sp=Category-_-INFOCARD-_-6800XT-_-L48-_-1&name=Desktop-Graphics-Cards

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/pull/832

**Comment by guorilla** [comment]
Here are links for Newegg.ca, for we poor folks in the Great White North who got even less stock... Thanks so much for your work!

MSI 

6800 xt
https://www.newegg.ca/msi-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814137607

6800
https://www.newegg.ca/msi-radeon-rx-6800-rx-6800-16g/p/N82E16814137608

ASUS

6800 xt
https://www.newegg.ca/asus-radeon-rx-6800-xt-rx6800xt-16g/p/N82E16814126472

6800
https://www.newegg.ca/asus-radeon-rx-6800-rx6800-16g/p/N82E16814126473

ASRock

6800 xt
https://www.newegg.ca/asrock-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814930045

6800
https://www.newegg.ca/asrock-radeon-rx-6800-rx-6800-16g/p/N82E16814930046

Gigabyte

6800 xt
https://www.newegg.ca/gigabyte-radeon-rx-6800-xt-gv-r68xt-16gc-b/p/N82E16814932373

6800
https://www.newegg.ca/gigabyte-radeon-rx-6800-gv-r68-16gc-b/p/N82E16814932374

Sapphire

6800 xt
https://www.newegg.ca/sapphire-radeon-rx-6800-xt-21304-01-20g/p/N82E16814202388

6800
https://www.newegg.ca/sapphire-radeon-rx-6800-21305-01-20g/p/N82E16814202389

**Comment by Brodieman** [comment]
6800XT is not working for me.  I have this "SHOW_ONLY_SERIES="RX6800XT"".  It shows the stores I listed and the series but never starts

**Comment by newfieboy1983** [comment]
> 6800XT is not working for me. I have this "SHOW_ONLY_SERIES="RX6800XT"". It shows the stores I listed and the series but never starts

Can confirm the same thing is happening to me.  I'm only searching from the following stores (Canadian): 
"STORES=amazon-ca, bestbuy-ca, newegg-ca, memoryexpress, amd, canadacomputers, bandh"

Works great for the 3080s, but not the RX6800XT

**Comment by jef** [comment]
> 6800XT is not working for me. I have this "SHOW_ONLY_SERIES="RX6800XT"". It shows the stores I listed and the series but never starts

Use `SHOW_ONLY_SERIES="rx6800xt"`. We could lowercase everything, but I'd rather not work on that -- instead start loading in new configs.
