### ISSUE TITLE
Couldn't find sound player

### ISSUE THREAD

**Issue by BARRETTshot** [jef/streetmerchant#810]
### Description

 The script/program is not finding the .mp3 or .wav file for the sound notification
 My sound notif is called "swiftlytone.wav". I tried using path/to/switflytone.wav , tried the location string, and tried just inputting the name "swiftlytone.wav". All output with the same message, "couldn't find sound player"

![Capture](https://user-images.githubusercontent.com/64364239/99196077-a9d2db80-274f-11eb-98cf-8f030f8de216.PNG)

**Comment by B1022** [comment]
https://github.com/jef/streetmerchant/wiki/Installation:-Windows

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/issues/191
https://github.com/jef/streetmerchant/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+Sound

Thanks!
