### ISSUE TITLE
Ryzen not being scanned in UK?

### ISSUE THREAD

**Issue by wdrury-uk** [jef/streetmerchant#821]
Not seeing any scans for Ryzen processors?

The .env configured as follows, key sections only shown:

```
COUNTRY=great_britain
SHOW_ONLY_BRANDS=amd
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=5900x
```

Result is no scans, initial output below then nothing happens.

```
[16:15:32] info :: selected stores: amazon-uk, currys, ebuyer
[16:15:32] info :: selected brands: amd
[16:15:32] info :: selected series: 5900x
```

**Comment by davidsyoung** [comment]
It's ryzen5900 matey!

**Comment by wdrury-uk** [comment]
That could be it, but the How to Configure Brands/Model section states AMD / 5800x, 5900x, 5950x, etc.
I give it a go now, thanks.

**Comment by wdrury-uk** [comment]
Just tried and its still not scanning with below customisation.

```
SHOW_ONLY_BRANDS=amd
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=ryzen5900
```

**Comment by wdrury-uk** [comment]
thanks @MHayward89 - I have pulled the same files into my local source and can confirm 1x supplier working currently.
