### ISSUE TITLE
Amd 6000 series graphics cards?

### ISSUE THREAD

**Issue by rrbailey89** [jef/streetmerchant#822]
### Description

The AMD 6000 series graphics cards go live tomorrow morning, it would be outstanding if we could get those added to this before hand.

**Comment by B1022** [comment]
They haven't posted the links for them so he can't add them yet

**Comment by psiberfunk** [comment]
This is a dupe to 808

**Comment by maocardona** [comment]
the link to the 6000 are here https://www.amazon.com/stores/page/14A8C84F-E4B1-48CA-8502-E2CC2AC0D9EA?ingress=0&visitId=016b8147-d028-411c-a9df-f2717cc6cc06

**Comment by iNfeKTzia** [comment]
https://www.newegg.com/p/pl?d=Radeon+rx+6800

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/pull/832
https://github.com/jef/streetmerchant/issues/808
