### ISSUE TITLE
just can't find it

### ISSUE THREAD

**Issue by MattDA1** [jef/streetmerchant#825]
so, I've read the thread and the README and still can't find how to narrow the search
I don't wanna buy Xbox and I kinda only looking for the Nvidia FE cards but for the life of me I can't find the option to change it to be FE only\remove xbox\ remove 30670 and 3090
help?

**Comment by shortywz** [comment]
You'll want to change the appropriate options in the .env file, as explained here:
https://github.com/jef/streetmerchant#filters

**Comment by jef** [comment]
I should probably change this and have a table of contents. Looks better now, but not so user friendly.

Thanks @shortywz
