### ISSUE TITLE
Add Xbox.com store 

### ISSUE THREAD

**Issue by jacktriplesec** [jef/streetmerchant#836]
### Description
Really just add another store. Would be nice. Thanks!

**Comment by twerkingFrog28** [comment]
were you able to set a filter?? I dont even have the .env file.

**Comment by jacktriplesec** [comment]
setting a filter is not a problem. but microsoft.com is not an option (though it might be that they only do pre-orders, I'm not sure)

**Comment by jef** [comment]
Doesn't look like Microsoft is selling the consoles... Do you have a link that shows otherwise?

**Comment by jacktriplesec** [comment]
it used to be available and then removed when its out of stock (haven't seen it since I originally posted. Funnily enough , I still have an xbox in my cart, but can't buy. I will let you know if it come back up again.

**Comment by jef** [comment]
Thanks @jacktriplesec!

**Comment by jacktriplesec** [comment]
Hey Jef . See link for the Xbox store. https://www.xbox.com/en-us/configure/8WJ714N3RBTL 

But also wanted to thank you . I got a sound/email and text from your bot once the bestbuy had availability for Xboxsx and  I was able to grab one. Thank you so much! I really hope we can get rid of scalpers to make this all easier .

**Comment by jef** [comment]
Adding now!

And great news! Congrats!
