### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by AfterTh0ught** [jef/streetmerchant#839]
I may sound stupid here but I can't Figure out how to run "npm install"  where is this located? Thank you in advance for your help

**Comment by jef** [comment]
If you've installed npm and cloned (downloaded using `git clone`) streetmerchant, you'll need to navigate to where you've clone the repository and run the `npm install` command.

I'm assuming you're on Windows: take a look at [this](https://github.com/jef/streetmerchant/wiki/Installation:-Windows).

**Comment by AfterTh0ught** [comment]
Thank you so much, I think I have it all up and running. Last thing I'm trying to do is trying to use the PLAY_SOUND. I cannot seem to get it to work. I have a folder in street merchant called MP3 and within that a mp3 file called READY. I tried MP3\READY.mp3 and a few others and it seems to not work. any advice?

**Comment by B1022** [comment]
Use this to help you. https://github.com/jef/streetmerchant/wiki/Installation:-Windows

Then for PLAY_SOUND make it say PLAY_SOUND=READY.mp3

Might throw error saying sound pattern not found but it works perfectly

**Comment by jef** [comment]
@B1022 Thanks for the help!

@AfterTh0ught, `PLAY_SOUND=` looks for a file from the context of whatever folder streetmerchant is working from (AKA current working directory). If you put the `.mp3` in the same folder you have the `.env` file, you can reference it from there.

---

Example:

- You have a file named `notification.mp3`
- Put it in the same folder as `.env` (this folder is probably named `streetmerchant`)
- Update the `PLAY_SOUND=notification.mp3`

Should be good to go!

If not, you might be missing some executables that are needed to run sound in the terminal. Make sure you read the instructions in that doc that will help with those dependencies.
