### ISSUE TITLE
5600x Amazon buy out problems, rx6800xt code?

### ISSUE THREAD

**Issue by thirdeyesteve** [jef/streetmerchant#848]
### Description

Hello, I just recently started to use streetmerchant and just now it detected stock in Amazon for Amd ryzen 5600x. I clicked for it to go to my cart but a second after it just disappears. I see the buy it now on the page but when I click its gone. Is it cause I'm too slow or is street merchant sending false positives? 

I also have a question on the rx6800xt graphics card, I am also in the market for this item and was wondering if a code has been made for this in the models/series section. 

Thank you.

**Comment by Brodieman** [comment]
> ### Description
> Hello, I just recently started to use streetmerchant and just now it detected stock in Amazon for Amd ryzen 5600x. I clicked for it to go to my cart but a second after it just disappears. I see the buy it now on the page but when I click its gone. Is it cause I'm too slow or is street merchant sending false positives?
> 
> I also have a question on the rx6800xt graphics card, I am also in the market for this item and was wondering if a code has been made for this in the models/series section.
> 
> Thank you.

I am trying this as well.  I have tried SHOW_ONLY_SERIES="6800XT" and SHOW_ONLY_SERIES="RX6800XT" neither seem to work.  Lists the stores I selected and the series I put in but never starts looking.

**Comment by jef** [comment]
> I see the buy it now on the page but when I click its gone. Is it cause I'm too slow or is street merchant sending false positives?

Perhaps too slow.

> I am trying this as well. I have tried SHOW_ONLY_SERIES="6800XT" and SHOW_ONLY_SERIES="RX6800XT" neither seem to work. Lists the stores I selected and the series I put in but never starts looking.

You need to use `SHOW_ONLY_SERIES="rx6800,rx6800xt"`
