### ISSUE TITLE
Can the newegg links for Ryzen bundles be added?

### ISSUE THREAD

**Issue by historypsi** [jef/streetmerchant#852]
### Description

Newegg only throws up ryzen cpus in bundles now.

### Possible solution

Add bundle links

**Comment by Proryanator** [comment]
Yeah this would be super helpful, I'm running streetmerchant and it's not grabbing the bundles.

**Comment by TyrantRex** [comment]
You can add the bundles yourself now with the steps from the link below.
https://github.com/jef/streetmerchant/issues/912#issuecomment-735340030
