### ISSUE TITLE
env updated for RX6800XT support but not logging RX6800XT search

### ISSUE THREAD

**Issue by lame-duk** [jef/streetmerchant#859]
I saw a code merge adding some support for RX6800XT searches and did an updated install which patched those in, however when I add it to env series as "RX6800XT" it does not log a search for it like it does the 3080.  Is code still missing to make this work or do I have an error somewhere?  Below is my env file changes aside from adding notification sound

SHOW_ONLY_SERIES=3080,RX6800XT,RX6900XT,6800XT,6900XT
STORES=amd,amazon,asus,bandh,bestbuy,evga,gamestop,newegg,nvidia,pny,officedepot,target,walmart,zotac

**Comment by tmehmen2** [comment]
type lowercase ex: "rx6800xt"

**Comment by lame-duk** [comment]
> 
> 
> type lowercase ex: "rx6800xt"

That worked. Thank you

**Comment by jef** [comment]
I should lowercase these...
