### ISSUE TITLE
Canada Computers giving false positive 

### ISSUE THREAD

**Issue by BigShoots** [jef/streetmerchant#863]
I'm not sure why, but streetmerchant is picking up some cards at canadacomputers as in stock when they aren't. 

![image](https://user-images.githubusercontent.com/31416585/99815834-7bb71800-2b10-11eb-9bc4-35d2e5ce01f4.png)
![image](https://user-images.githubusercontent.com/31416585/99815860-8376bc80-2b10-11eb-9694-68bd7f4e6b9d.png)

To add to this, it also picks up in store stock sometimes that can't be purchased online, would be nice to disable this.

**Comment by Tofupocket** [comment]
looks like its one item number off maybe.

item in return shows 181416 if you go to 181415 if put you to the correct card.

![image](https://user-images.githubusercontent.com/48359495/99888057-67e9df80-2bfe-11eb-9256-025d2d57e2ae.png)

**Comment by BigShoots** [comment]
@Tofupocket That was one of the issues. The other issue is that sometimes the product is available to buy online and pick up in store, but not available for shipping. To get around this I changed this in canadacomputers.ts

		outOfStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['not available online']
		}

to 

		inStock: {
			container: 'div[class="pi-prod-availability"]',
			text: ['Online In Stock']
		}

**Comment by BigShoots** [comment]
Also worth noting, Don't try to ping canadacomputers every 5 seconds, it will get your banned. They will redirect you to their instagram page.

**Comment by cloutid** [comment]
> Also worth noting, Don't try to ping canadacomputers every 5 seconds, it will get your banned. They will redirect you to their instagram page.

yikes wish I saw this before, hopefully it's a temp ban :/

**Comment by abeth66** [comment]
So, is the ban temporary?

**Comment by cloutid** [comment]
> So, is the ban temporary?

still banned so wel'll see how long this goes

**Comment by BigShoots** [comment]
I'm still banned too, I just use a vpn to get around it.

**Comment by cloutid** [comment]
> I'm still banned too, I just use a vpn to get around it. Probably need to email them to find out more.

what rate are you now using to ping them?

**Comment by jef** [comment]
Superseded by https://github.com/jef/streetmerchant/issues/788.
