### ISSUE TITLE
Target reporting in stock when showing "there was a temporary issue"

### ISSUE THREAD

**Issue by scot-onet** [jef/streetmerchant#864]
Looking at the images from the search for PS5/XBSX the success pngs show "there was a temporary issue".  The page that is triggered has no units available, so I think the fact it is giving an error is causing the code to believe there is a unit available. 

![success-1605882557215](https://user-images.githubusercontent.com/22639725/99823312-3ac7ff00-2b22-11eb-97ac-878a366c0968.png)

**Comment by stevezub** [comment]
I was just coming here to create this issue, myself. Been getting a ton of false positives from Target, this morning in particular. I noticed the same thing - it's always when there's the "temporary issue" error.

**Comment by devinvisible** [comment]
> I was just coming here to create this issue, myself. Been getting a ton of false positives from Target, this morning in particular. I noticed the same thing - it's always when there's the "temporary issue" error.

same <3

**Comment by claygraffix** [comment]
A couple nights ago I had one in my cart, and got an error.  I didn't have my card info added, so I was too slow.  

So far today there's been at least 6 times the browser has spawned, and there's just nothing available when it loads.  I just assume some false-positives from Target?  StreetMerchant seems to be doing its job.  

I haven't seen the "Temporary Issue" like that before.  Has anyone gotten one from Target on here?

**Comment by jef** [comment]
This is happened for many sites before. Especially if the site is seeing a lot of traffic.

If you want streetmerchant to stop going to the site after it's been in stock, you can set a timer to not have it keep on notifying you.

Use `IN_STOCK_WAIT_TIME`, the time is in seconds. Example: `IN_STOCK_WAIT_TIME=600` would not check again for 10 minutes.
