### ISSUE TITLE
Couldnt send sms to phone number, invalid login? 

### ISSUE THREAD

**Issue by zack-later** [jef/streetmerchant#865]
https://support.google.com/mail/?p=BadCredentials c19sm4332330pfp.1 - gsmtp {
  "code": "EAUTH",
  "response": "535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials c19sm4332330pfp.1 - gsmtp",
  "responseCode": 535,
  "command": "AUTH PLAIN",
  "stack": "Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials c19sm4332330pfp.1 - gsmtp\n    at SMTPConnection._formatError (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:774:19)\n    at SMTPConnection._actionAUTHComplete (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1513:34)\n    at SMTPConnection.<anonymous> (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:540:26)\n    at SMTPConnection._processResponse (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:932:20)\n    at SMTPConnection._onData (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:739:14)\n    at TLSSocket.SMTPConnection._onSocketData (c:\\nvidia-snatcher\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:189:44)\n    at TLSSocket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:307:12)\n    at readableAddChunk (_stream_readable.js:282:9)\n    at TLSSocket.Readable.push (_stream_readable.js:221:10)"

**Comment by zack-later** [comment]
Also seeing a similar issue with gmail account. This had been working for me in the past and nothing has changed on my side specifically in my .env file

**Comment by zack-later** [comment]
Update as of this afternoon. I started getting email and text notifications from target. Im not sure if it matter and it was store specific before? If not then im not sure what changed but they are coming through now.

**Comment by newspaperr** [comment]
Having same issue for both gmail and sms. There's no 2fa on the account I am trying to log into, and the password is correct. All other alerts are working really well though and I'm using pushbullet as a backup.

**Comment by jef** [comment]
Have you ran `npm install` lately? This dependency got updated.

**Comment by jef** [comment]
![image](https://user-images.githubusercontent.com/12074633/99889049-b9569680-2c1f-11eb-834e-a2b394bb744a.png)

![image](https://user-images.githubusercontent.com/12074633/99889053-c8d5df80-2c1f-11eb-84b8-d30f8e775a89.png)


I'm on latest and have MFA.

**Comment by zack-later** [comment]
Yeah thats the weird thing i run that fairly often to pull down the latest. I have started getting notifications the last two days from various stores so it seems to be working again at least for me. I think we are ok to close this one out @jef

**Comment by jef** [comment]
Thanks zack!
