### ISSUE TITLE
Failing to lauch to the browser

### ISSUE THREAD

**Issue by scaryval** [jef/streetmerchant#866]
It is failing to launch the browser process.

Everytime when i type npm run start it is showing up the following error:
![Bild_2020-11-20_184347](https://user-images.githubusercontent.com/74787794/99832083-53570a00-2b60-11eb-9afe-96b2136e7171.png)

Then if i go in my explorer and check this path: C:\streetmerchant\node_modules\puppeteer\.local-chromium\win64-818858\chrome-win\chrome.exe i am not able to find the file chrome.exe
![image](https://user-images.githubusercontent.com/74787794/99832337-ac26a280-2b60-11eb-834e-5ad4491cdfc9.png)

I hope you can help me.

**Comment by jef** [comment]
Have you ran `npm install`? puppeteer as been updated.

**Comment by scaryval** [comment]
Thank you very much. It is working fine now.

**Comment by scaryval** [comment]
Hmm. I thought I fixed this error but I have the same error again.

**Comment by jef** [comment]
If you pull the latest code, make sure you run an `npm install` afterward.

**Comment by scaryval** [comment]
Yes. Im reinstalling npm but i have to delete the whole project to get it working.

**Comment by MujiSayed** [comment]
shouldn't need to. a git pull origin main, and then a npm install should do the trick

**Comment by scaryval** [comment]
Ok i will try git pull origin main.
Lets hope it will work.

**Comment by MrTriske** [comment]
i have the same [problem.
![image](https://user-images.githubusercontent.com/80903836/112447691-e5ab2c80-8d51-11eb-8a11-1637f22743d8.png)

**Comment by jef** [comment]
`node node_modules/puppeteer/install.js`

**Comment by BattlemageBob** [comment]
> `node node_modules/puppeteer/install.js`

Huh.  `npm install` wasn't doing that.  Had the same issue, and looks like that was the fix.  Thanks @jef

**Comment by jef** [comment]
Yeah, I think npm 7 doesn't like install scripts .
