### ISSUE TITLE
Reports stock for mediamarkt and saturn for 3070 and 3080 when there is none

### ISSUE THREAD

**Issue by Lukalion** [jef/streetmerchant#868]
### Description

 Well obvious from the title. It reports stock on stores: saturn and mediamarkt when adding 3070 and 3080 graphics. You click on the link but they are then out of stock. Since i know the shops i can confirm that they were out of stocks pretty much since launch.

Im on Windows. i had my buddies test in on their machines same issue.

**Comment by jef** [comment]
Probably because it was in stock or it's reporting it's in stock, then shows as out of stock. This is due to the images and JavaScript loading slowly on the page. You should have screenshots of the page when it found it in stock. That will confirm this.
