### ISSUE TITLE
Parse error and wrong connection attempt

### ISSUE THREAD

**Issue by Karawasa** [jef/streetmerchant#869]
Why the Zotac error and why the attempt to go to currys.co.uk? See below.

![123](https://user-images.githubusercontent.com/7691068/99861582-21dc3f80-2b5c-11eb-8a0c-709306ff1c3a.PNG)

**Comment by B1022** [comment]
It always fails to parse the first zotac card. For curry's it's not actually checking it, it just fetches all the links before the script starts.
