### ISSUE TITLE
Add Newegg Bundles to Scraping

### ISSUE THREAD

**Issue by lngchn** [jef/streetmerchant#870]
### Description

Newegg is bundling all inventories like RTX 3000 or 5000XT as combo.

### Possible solution

Add bundle links.

**Comment by TyrantRex** [comment]
If you're tired of waiting, I've provided some steps in the link below as an example on how to add your own links/combos from newegg.
https://github.com/jef/streetmerchant/issues/912#issuecomment-735340030
