### ISSUE TITLE
when a card is in stock the bot does not alert

### ISSUE THREAD

**Issue by Ebrahemz** [jef/streetmerchant#871]
so the first pic is when the card is in stock in newegg no alarts or anything (gaming x trio):
![111111111111111](https://user-images.githubusercontent.com/20641930/99866259-cb551c80-2bc0-11eb-8376-72d5471d58dd.png)
--------
here the second pic when the card is out of stock:

![22222222222](https://user-images.githubusercontent.com/20641930/99866283-fa6b8e00-2bc0-11eb-954e-73cdbe373895.png)
-----
1-i'm not sure what the problem is.
2-and the first time i installed the bot, the bot was opening chromium now it doesn't, any solutions?

**Comment by jef** [comment]
Perhaps it went into stock after it searched and then went back out of stock when it went around again. I imagine it's not the streetmerchant because other people have had success. Something to look out for though.

Thanks!

**Comment by Ebrahemz** [comment]
hey, Jef i'm not using newegg USA nor newegg Canada I edited the links from newegg.ts to check for newegg other country, what I discovered that when an item is in stock the bot knows that it is in stock but doesn't send a notification nor a message display that it is in stock, when item is out of stock the bot scan for it and display the out of stock message.
