### ISSUE TITLE
bot report wrong stock for ps5digital

### ISSUE THREAD

**Issue by mohandshamada** [jef/streetmerchant#873]
the bot report that ps5digital is in stock at amazon-de while it is not. is this a bug ?

**Comment by jef** [comment]
Unfortunately, the link is not unique to the ps5. Amazon does not have a separate link for the ps5, but will show the ps5 when it's in stock (from what I've seen).

If we can get a unique link only to ps5, then we can add it. Otherwise, this is a side effect.
