### ISSUE TITLE
Not starting? -Docker

### ISSUE THREAD

**Issue by ATLTVHEAD** [jef/streetmerchant#875]
### Description
I have cloned and built the docker image for Streetmerchant, but cannot get past this point. Errorno 130, npm ERR! Failed at the streetmerchant@ start:production script. 

My .env is as follows:
BROWSER_TRUSTED="false"
COUNTRY="usa"
DESKTOP_NOTIFICATIONS="true"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PLAY_SOUND="notification.mp3"
STORES="bestbuy,newegg,amazon"
SHOW_ONLY_SERIES="ryzen5900,ryzen5950"

Any ideas of what to try next? 

![image](https://user-images.githubusercontent.com/12835768/99884859-2e65a400-2bff-11eb-97c5-dffc68027a14.png)

**Comment by jef** [comment]
I can reproduce this issue. I can probably take a look at it later today.

Thanks for the report!

**Comment by trillejs** [comment]
If you remove the log_level parameter then it starts.

**Comment by trillejs** [comment]
Actually it is all due to how --env-file parameter is interpreted by docker:
https://github.com/docker/compose/issues/3702
It might be good to add a bit in the doc to tell people to remove the quotes from the values for the .env if it is used for the docker container mode or have a different file.

**Comment by jef** [comment]
Good idea. I hope to get rid of these environment variables soon enough...
