### ISSUE TITLE
Issue with MemoryExpress monitoring

### ISSUE THREAD

**Issue by larathydo** [jef/streetmerchant#877]
Hello,

I'm using StreetMerchant to monitor EVGA 3080 XC3 Gaming and XC3 Ultra Gaming GPUs in Canada. (This is the only 3080 2.2 slot GPU I think will fit in my Phanteks Enthoo Evolv ITX case, hence why I'm searching specifically for just these cards)

Here are the settings I use:

STORES="memoryexpress,amazon-ca,bestbuy-ca,canadacomputers,newegg-ca"
SHOW_ONLY_BRANDS="evga"
SHOW_ONLY_MODELS="xc3,xc3 ultra"
SHOW_ONLY_SERIES="3080"

I see the reference to memoryexpress being an enabled store at startup, but I never see any stock updates for that store showing up in the rolling logs. That said, I do see the cards listed on their site: https://www.memoryexpress.com/Search/Products?Search=evga+3080

Anyone else having the same issue? Also, duno if it's relevant but I am seeing some of the following messages in the rolling logs - perhaps they are related? **_**Update: They are not - disabled memoryexpress in the config and the error messages still appear._**

[7:42:23 p.m.] error :: Failed to parse card: Zotac ZT-A30800J-10P graphics card NVIDIA GeForce RTX 3080 10 GB GDDR6X ZT-A30800J-10P, GeForce RTX 3080, 10 GB, GDDR6X, 320 bit, 7680 x 4320 pixels, PCI Express x16 4.0
[7:42:58 p.m.] error :: Navigation timeout of 30000 ms exceeded
[7:47:42 p.m.] error :: Failed to parse card: Zotac ZT-A30800J-10P graphics card NVIDIA GeForce RTX 3080 10 GB GDDR6X ZT-A30800J-10P, GeForce RTX 3080, 10 GB, GDDR6X, 320 bit, 7680 x 4320 pixels, PCI Express x16 4.0

One other additional question, can StreetMerchant be configured to also monitor RX 6800 stock (non XT)? If so, what would be the BRANDS / MODELS / SERIES values for the AMD reference / AIB cards? That was the only other kind of video card that seems to be compatible with my case, so wouldn't mind keeping an eye on them as well (don't think any 2.2 slot RX 6800 XT AIB cards were announced yet for when they go on sale)

**Comment by abeth66** [comment]
I am experiencing the same problem with streetmerchant not scraping memoryexpresss for stock. I am specifically setup to look for 3090 & 3080 asus tuf & tuf oc, gigabyte eagle & eagle oc. Streetmerchant successfully scrapes bestbuy-ca, newegg-ca, amazon-ca, and canadiancomputers, but not memoryexpress.

On the topic of Rx 6800, I was able to get scraping results using SERIES "rx6800xt" and MODELS "amd reference"; I also put all of the reference board manufacturers in BRANDS. Perhaps using SERIES "rx6800" with my above-mentioned settings will work for RX 6800.

**Comment by RitoFaith** [comment]
That is because the 3080 isnt added in the .ts files

**Comment by larathydo** [comment]
> That is because the 3080 isnt added in the .ts files
> If the card isn't added in there it won't search for it, so you are right when you say it doesn't show up.

Thanks @RitoFaith! I was able to get this to work by adding the following to the "C:\streetmerchant\src\store\model\memoryexpress.ts" file on my installation:

So if anyone else needs to add these cards (or use this as a template to add other card BRANDS/MODELS/SERIES) here's what I used and I now see it monitored!

`{
			brand: 'evga',
			model: 'xc3',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00114095'
		},
		{
			brand: 'evga',
			model: 'xc3 ultra',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00113972'
		},`

**Comment by larathydo** [comment]
> I am experiencing the same problem with streetmerchant not scraping memoryexpresss for stock. I am specifically setup to look for 3090 & 3080 asus tuf & tuf oc, gigabyte eagle & eagle oc. Streetmerchant successfully scrapes bestbuy-ca, newegg-ca, amazon-ca, and canadiancomputers, but not memoryexpress.
> 
> On the topic of Rx 6800, I was able to get scraping results using SERIES "rx6800xt" and MODELS "amd reference"; I also put all of the reference board manufacturers in BRANDS. Perhaps using SERIES "rx6800" with my above-mentioned settings will work for RX 6800.

I can confirm that I got it working with the following configuration on most of my monitored sites - Thanks @abeth66!:

SHOW_ONLY_BRANDS="evga,asus,gigabyte,msi,sapphire,asrock"
SHOW_ONLY_MODELS="xc3,xc3 ultra,amd reference"
SHOW_ONLY_SERIES="3080,rx6800"
STORES="memoryexpress,amazon-ca,bestbuy-ca,canadacomputers,newegg-ca"

Note I still didn't see the RX6800 entries on memoryexpress in the rolling logs, but then I realized it's probably because of [THIS](https://www.reddit.com/r/Amd/comments/jvub3t/canada_memory_express_6800_6800xt_availability/). I.E. there are no listings for any RX 6000 series cards on their website as of this writing due to stock issues...

https://www.reddit.com/r/Amd/comments/jvub3t/canada_memory_express_6800_6800xt_availability/

**Comment by abeth66** [comment]
Thank you @RitoFaith for directing me to the .ts files. I wrote in the memoryexpress listings as @larathydo did and got it working. I'm learning a lot here and can't wait to learn more.

**Comment by larathydo** [comment]
Update on my MemoryExpress experience... while monitoring seems to be working for the most part now, though every couple hours or so I occasionally get false positive alerts from Street Merchant...

When I go look at the site link, the item is still sold out. I look at the screenshot that Street Merchant captured at the time of the "In Stock" moment, but it looks like it just encountered a "500 Server Error" and considered that "In Stock" for some reason...

https://imgur.com/a/3clFEYL

Anyone else occasionally encountering this too / know how to stop these errors as being flagged as in stock events?

**Comment by BigShoots** [comment]
One can most likely fix memory express by editing memoryexpress.ts and changing 

`		outOfStock: {
			container:
				'.c-capr-inventory-selector__details-online .c-capr-inventory-store__availability',
			text: ['Out of Stock']
		}`

to 

`		inStock: {
			container:
				'.c-shth-page__main-content .c-shco-grad-button',
			text: ['Add To Cart']
		}`

**Comment by larathydo** [comment]
> One can fix memory express false positive pings by editing memoryexpress.ts and changing
> 
> ```
> 	outOfStock: {
> 		container:
> 			'.c-capr-inventory-selector__details-online .c-capr-inventory-store__availability',
> 		text: ['Out of Stock']
> 	}
> ```
> 
> to
> 
> ```
> 	inStock: {
> 		container:
> 			'.c-shth-page__main-content .c-shco-grad-button',
> 		text: ['Add To Cart']
> 	}
> ```
> 
> It's working for me right now and haven't had any false pings. I also manually added the links for the all the cards I'm waiting for.

Hmm, that didn't seem to work with me. It crashes when I try to start StreetMerchant.

This is what I'm using - any ideas / see anything out of place?:

```
import {Store} from './store';

export const MemoryExpress: Store = {
	labels: {
		maxPrice: {
			container:
				'#ProductPricing .GrandTotal.c-capr-pricing__grand-total > div',
			euroFormat: false
		},
		inStock: {
			container:
				'.c-shth-page__main-content .c-shco-grad-button',
			text: ['Add To Cart']
		}
	},
	links: [
		{
			brand: 'test:brand',
			model: 'test:model',
			series: 'test:series',
			url: 'https://www.memoryexpress.com/Products/MX79473'
		},
		{
			brand: 'amd',
			model: '5950x',
			series: 'ryzen5950',
			url: 'https://www.memoryexpress.com/Products/MX00114450'
		},
		{
			brand: 'amd',
			model: '5900x',
			series: 'ryzen5900',
			url: 'https://www.memoryexpress.com/Products/MX00114451'
		},
		{
			brand: 'amd',
			model: '5800x',
			series: 'ryzen5800',
			url: 'https://www.memoryexpress.com/Products/MX00114452'
		},
		{
			brand: 'amd',
			model: '5600x',
			series: 'ryzen5600',
			url: 'https://www.memoryexpress.com/Products/MX00114455'
		},
		{
			brand: 'evga',
			model: 'xc3',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00114095'
		},
		{
			brand: 'evga',
			model: 'xc3 ultra',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00113972'
		},
		{
			brand: 'evga',
			model: 'xc3 black',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00114094'
		},
		
	],
	name: 'memoryexpress',
	waitUntil: 'domcontentloaded'
};

```

**Comment by BigShoots** [comment]
remove comma from end of the last card.

		{
			brand: 'evga',
			model: 'xc3 black',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00114094'
		}, <<<<<


should look like this 

		{
			brand: 'evga',
			model: 'xc3 black',
			series: '3080',
			url: 'https://www.memoryexpress.com/Products/MX00114094'
		}

**Comment by larathydo** [comment]
> remove comma from end of the last card.
> 
> ```
> 	{
> 		brand: 'evga',
> 		model: 'xc3 black',
> 		series: '3080',
> 		url: 'https://www.memoryexpress.com/Products/MX00114094'
> 	}, <<<<<
> ```
> 
> should look like this
> 
> ```
> 	{
> 		brand: 'evga',
> 		model: 'xc3 black',
> 		series: '3080',
> 		url: 'https://www.memoryexpress.com/Products/MX00114094'
> 	}
> ```

Thanks @BigShoots, initially that didn't seem to work, but pretty sure I hosed my install, so I reinstalled from scratch and made your suggestions and it seemed to work (also successfully tested with an instock URL to confirm the changes work - they did).

Thanks! We'll see if this runs any smoother.

**Comment by phtp** [comment]
Anyone else having this issue? I updated today and maybe it's just my issue. But every time it hits memex links it would do the following: "(node:18516) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!"

**Comment by coreyinoz** [comment]
> Anyone else having this issue? I updated today and maybe it's just my issue. But every time it hits memex links it would do the following: "(node:18516) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!"

Same problem here with MemEx, just updated this morning.

**Comment by jef** [comment]
@phtp @coreyinoz 

https://github.com/cliqz-oss/adblocker/issues/1495
https://github.com/jef/streetmerchant/issues/826
