### ISSUE TITLE
Email notification: Less secure app blocked

### ISSUE THREAD

**Issue by jiglesiasc** [jef/streetmerchant#884]
Hello everyone,

I tested the email notification. The sound alert works like a charm, but the email notification doesn't seems to work due to some kind of security feature on gmail side. I get this alert message from gmail:

_Less secure app blocked
Google blocked the app you were trying to use because it doesn't meet our security standards.
Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used._

Is there a way to disable that gmail protection so I can receive the email notification?

**Comment by jiglesiasc** [comment]
Found the answer on google:
[](
https://support.google.com/accounts/answer/6010255?hl=en)

**Comment by jef** [comment]
I would not recommend lowering your Google account settings. I have my Google account with full security and MFA. Create an app password and this should help!

**Comment by jef** [comment]
If this works for you, do you mind closing this out :smiley:

**Comment by jiglesiasc** [comment]
> 
> 
> If this works for you, do you mind closing this out 😃

Thank you very much, your solution is much more secure and works great! 😃

**Comment by jef** [comment]
Awesome! Glad it worked. Thanks!
