### ISSUE TITLE
Flaw with BestBuy Detection

### ISSUE THREAD

**Issue by oZanderr** [jef/streetmerchant#895]
Sometimes BestBuy will only show the “Find a Store” button when in stock, but it actually won’t show the yellow “Add to Cart” button. This is probably because of store pickup availability, but not shipping. That’s what happened for around the first 30+ min of the last PS5 drop and it wasn’t detected until the button changed to the regular ATC one. Anyone who caught on after this time was massively behind.

**Comment by DamnNewbie** [comment]
This is similar to issues reported for PS5 and multiple stores in #851 .  The individual causes by website are all likely different, using walmart as an example, the crashes likely killed the ability to scrap.

**Comment by oZanderr** [comment]
> This is similar to issues reported for PS5 and multiple stores in #851 . The individual causes by website are all likely different. Using walmart as an example, the website crashes likely killed the ability to scrap and the program never showed it as in stock.

Yeah, except that this issue doesn't pertain only to the PS5. It affects many other products across the BestBuy store. If you just look around you can see a bunch of products with only the "Find a store" button while still in stock.

**Comment by jef** [comment]
If you're using bestbuy-ca, this is resolved now.

**Comment by Rowno** [comment]
Since yesterday I've been getting a lot of false positive alerts for bestbuy-ca RTX 3070 stock (unless they're selling out in literal seconds 😅 ).

**Comment by phtp** [comment]
I'm randomly getting false positives as well. Not sure if it's lag for the Pick Up At Store button.

**Comment by Mansomaniac** [comment]
I am getting false positives for Asus tuf 3080 on bestbuy-ca.
Checked various streams and stock checkers no report of stock update, so am sure it's a false!
