### ISSUE TITLE
Shell closing after finding an available graphicscard.

### ISSUE THREAD

**Issue by scaryval** [jef/streetmerchant#899]
I have the problem that everytime the bot opens a new tab with the link to the available rtx 3080 the shell closes automaticly. When I try to start streetmerchant again with "npm run start" it is showing me an error code. To fix this issue i have to restart my whole Pc and to reinstall npm. After that its working fine until the next graphic card is available. I hope you are able to find a possible solution.

**Comment by jiglesiasc** [comment]
I have my script running since saturday and it haven't found any 3080 so I can't tell, lol

**Comment by jef** [comment]
We can reproduce this by using `SHOW_ONLY_SERIES="test:series"`. Unfortunately, I can't reproduce this.

```
❯ npm run start               

> npm run build && node build/index.js


> build
> tsc

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.1.0

[2:46:45 PM] info :: ℹ selected stores: amazon, bestbuy
[2:46:45 PM] info :: ℹ selected series: test:series
[2:46:58 PM] info :: 🚀🚨 [amazon] [test:brand (test:series)] test:model :: IN STOCK 🚨🚀
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B01DOFD0G8&Quantity.1=1
[2:47:00 PM] info :: ✖ [bestbuy] [test:brand (test:series)] test:model :: OUT OF STOCK
[2:47:13 PM] info :: 🚀🚨 [amazon] [test:brand (test:series)] test:model :: IN STOCK 🚨🚀
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B01DOFD0G8&Quantity.1=1
[2:47:13 PM] info :: ✖ [bestbuy] [test:brand (test:series)] test:model :: OUT OF STOCK
```

```
❯ cat .env                     
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .env
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ STORES="amazon,bestbuy"
   2   │ SHOW_ONLY_SERIES="test:series"
   3   │ USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36"
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I had to update the test link for amazon as it was actually out of stock as well 🤣 But I still can't reproduce. Perhaps someone with Windows can to see if it's a platform issue?

Thanks!

**Comment by jiglesiasc** [comment]
I'm running the script on a Windows 10 platform. Tried to use the SHOW_ONLY_SERIES="test:series" config but I still get out of stock

**Comment by jef** [comment]
I'll have to update some of the test models, because those are also out of stock 😅

**Comment by jiglesiasc** [comment]
> 
> 
> I'll have to update some of the test models, because those are also out of stock 😅

This demand for video cards is crazy, lol XD

**Comment by jiglesiasc** [comment]
Update here: I got a couple of notifications and I can say that streetmerch works fine to me. I get the sound notification, the email notification and the web browser launch. After that streetmerch keeps working without restarting my PC or anything, I don't have to do anything. I'm on Windows 10, so the issue is not related to the OS but to some particular configuration/setup of the OP.
