### ISSUE TITLE
Doesn't Pickup Newegg Drops Often

### ISSUE THREAD

**Issue by B1022** [jef/streetmerchant#902]
### Description

Half the time, other servers im in pick up Newegg drops but the snatcher doesn't. I was messing around with the top part (Where it looks for add to cart btn) to see if I could try to make it pick it up but it doesn't seem to work. For example, there was a Newegg 3090 drop today for a gigabyte gaming OC multiple times, and it didn't pick up on it once. Any ideas?

**Comment by B1022** [comment]
I've noticed the same issue with BestBuy sometimes as well

**Comment by B1022** [comment]
Now it just picked up on a newegg drop that happened 10+ Minutes ago (Checked the website it posted to make sure of it)

**Comment by peacepenguin** [comment]
Works fine. Just doesn't check often enough if you have lots of stores and models selected.

Run multiple instances each on one store only as a workaround. Or decrease time between checks. But you'll get banned sometimes too.

Also the newegg drop was pathetic, couple seconds of availability, easy to miss when streetmerchant is scanning lots of stores and models.

**Comment by B1022** [comment]
Yeah I'm going to try running seperate scripts for each store and see if that helps.
