### ISSUE TITLE
Adding A Store

### ISSUE THREAD

**Issue by newspaperr** [jef/streetmerchant#905]
### Description

Trying to add a store (amazon.co.jp) and cannot for the life of me figure out what needs to change (as it seems NPM, on surface level, doesn't have a good indication of what's being accessed at what point much like GDB can set breakpoints in C++).

I'm trying to set this one store up specifically for PS5 (versions don't matter) but it is telling me that "No store named amazon-jp, skipping" when I have the .ts file made and named just as such and looked at any other file it imports from to verify I'm not missing another line somewhere that needs to be added. 

This is the amazon-jp.ts file.
```import {Store} from './store';

export const AmazonJp: Store = {
	backoffStatusCodes: [403, 429, 503],
	labels: {
		captcha: {
			container: 'body',
			text: ['enter the characters you see below']
		},
		inStock: {
			container: '#desktop_buybox',
			text: ['add to cart']
		},
		maxPrice: {
			container: 'span[class*="PriceString"]'
		}
	},
	links: [
		{
			brand: 'test:brand',
			model: 'test:model',
			series: 'test:series',
			url: 'https://www.amazon.co.jp/gp/product/B08GGCGS39'
		},
		{
			brand: 'sony',
			cartUrl:
				'https://www.amazon.co.jp/gp/aws/cart/add.html?ASIN.1=B08GGCGS39&Quantity.1=1',
			model: 'ps5 console',
			series: 'sonyps5c',
			url: 'https://www.amazon.co.jp/gp/product/B08GGCGS39'
		}
	],
	name: 'amazon-jp'
};
```

Any direction I can be pointed in would be great. I'm specifically singling out this one product as scalpers have gone nuts in Japan with PS5 and am trying to help a friend. Thank you.

**Comment by newspaperr** [comment]
Never mind! Some wonderful people who have also messed around have helped me on the discord. Wish I knew if they had a github or if it were the same name but Screech over there pointed me in the right direction.

**Comment by realcapo** [comment]
Hey @newspaperr , can you invite me over to the discord channel please? I'm also waiting on what the solution for your problem is =)

**Comment by LazG7** [comment]
@realcapo I used a template .ts for amazon-jp.ts and then followed this persons guidance.  https://discordapp.com/channels/756303724095471617/756941548415090729/780874609134272543
