### ISSUE TITLE
Adding new product from newegg

### ISSUE THREAD

**Issue by alrowa7i** [jef/streetmerchant#912]
### Description
What is the best way to add a new product from newegg to the bot?

**Comment by TyrantRex** [comment]
> ### Description
> What is the best way to add a new product from newegg to the bot?

These are the files you'll be modifying:
```
1. /streetmerchant/.env
2. /streetmerchant/src/store/model/store.ts
3. /streetmerchant/src/store/model/newegg.ts
```

**1. /streetmerchant/.env**
Modify the two lines below:
```
SHOW_ONLY_BRANDS="[yourbrandhere]"
SHOW_ONLY_MODELS="[yourmodelhere]"
```

**2. /streetmerchant/src/store/model/store.ts**

Under "export type Brand =" add..
```
| '[yourbrandhere]'
```
Under "export type Model =" add..
```
| '[yourmodelhere]'
```

**3. /streetmerchant/src/store/model/newegg.ts**
Scroll down to the links and add the product you want. I'm going to use a random 3080 + psu combo deal as an example for the carturl, itemnumber, series, and url.
```
{
    brand: '[yourbrandhere]',
    cartUrl:
        'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=Combo.4190361',
    itemNumber: 'Combo.4190361', #you can find this in the url
    model: '[yourmodelhere]',
    series: '3080', #optional but some examples are 3070, 3080
    url:
        'https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4190361'
},
```

**Comment by rodalpho** [comment]
Thank you for the tutorial! Was a bit tricky but I managed to get it to work. Hope the devs can add the combos natively soon as I guess I can't update from source now.

**Comment by howdoicomputer** [comment]
Something to note is that you don't need a custom brand. You can use the same brand of the card in the bundle. I only customized the model and just appended a b<number> on the end of it to indicate the bundle number.

It wouldn't be hard to draft a PR for this. Though... it'd probably be a good idea to add support for using an environment variable to toggle querying for bundles.
