### ISSUE TITLE
3080s @ Amazon.com are not properly being scalped.

### ISSUE THREAD

**Issue by lngchn** [jef/streetmerchant#916]
### Description

3080 shows as in stock at Amazon.com but the app reads it as out of stock and never get any notifications. In fact, I have never gotten a notification for Amazon 3080 stocks.

An example is Gigabyte RTX 3080 Gaming OC 3x Windforce (B08HJTH61J)
https://www.amazon.com/GIGABYTE-Graphics-WINDFORCE-GV-N3080GAMING-OC-10GD/dp/B08HJTH61J?ref_=ast_sto_dp

**Comment by jef** [comment]
It's out of stock. Maybe what you're referring to is 'See all available options'. If you want that, then you'll get things like this:

![image](https://user-images.githubusercontent.com/12074633/100153812-aab3ed80-2e72-11eb-91ef-e697b35dc3cd.png)

I would recommend not to use the bot in this case and buy on your own.

> In fact, I have never gotten a notification for Amazon 3080 stocks.

In this case, having stock on Amazon is: a, rare; and b, sells out very fast. There have been many other have gotten cards from Amazon using the app, so it's really just luck of the draw.

Good luck! Thanks.

**Comment by lngchn** [comment]
@jef It's out of stock now, but it was in stock earlier, shipped and sold by Amazon at MSRP price.
