### ISSUE TITLE
Max price doesn’t work with EU shops

### ISSUE THREAD

**Issue by MRizkBV** [jef/streetmerchant#920]
### Description

EU based shops list price is in many different formats. Amazon for example shows a 1999 card as 1.999 so of course putting 1900 as the limit let’s it through. 

Some other shops put 1999 as 1 999 which I guess the bot fails to read to sees it as 1 euro. 

Do you think there is a way around this?

**Comment by jef** [comment]
Fixed with `euroFormat`.
