### ISSUE TITLE
canadacomputers check if in stock at store location

### ISSUE THREAD

**Issue by kraujas1** [jef/streetmerchant#921]
Canadacomputers looks right now if there is stock online. Would it be possible to make it look if there is stock at a specific store location ?

![Untitled](https://user-images.githubusercontent.com/74998462/100179991-347cae80-2ea5-11eb-8946-e4cef3b599b6.png)

**Comment by jef** [comment]
Duplicate https://github.com/jef/streetmerchant/issues/788
