### ISSUE TITLE
Not detecting stock at Walmart

### ISSUE THREAD

**Issue by MRizkBV** [jef/streetmerchant#924]
### Description

Noticed Walmart started listing more 3070/3080/3090 cards today like (https://www.walmart.com/ip/645698577) which is available in stock right now at $1799 and sold/shipped by Walmart. I added it to Walmart.ts but it reports it as out of stock. Is Walmart still working?

**Comment by jpconfessor** [comment]
disregard my update above. Linked wrong issue number.
