### ISSUE TITLE
Bot selects HDMI cable when it thinks of 6800xt

### ISSUE THREAD

**Issue by louij2** [jef/streetmerchant#927]
### Description

Windows 10. Is it possible to "ignore" this listing?
![image](https://user-images.githubusercontent.com/2940588/100215470-f3b68100-2f08-11eb-92e8-c9d187241f1a.png)

**Comment by devon-badman** [comment]
This is an issue with the link builder picking up on a related item at the bottom of the list.

I fixed this by amending the productsSelector in src/store/model/scan.ts to read
`productsSelector: 'div.productList ul.productColumns li.product',`

**Comment by devon-badman** [comment]
duplicate of #919

**Comment by louij2** [comment]
> 
> 
> duplicate of #919

Thanks for the help and sorry about duplicate tried to look for my issue but am new to GitHub

**Comment by magma82** [comment]
@devon-badman - genius that has sorted it :) Will this be committed to live branch @jef ?

**Comment by Dimitah** [comment]
This didn't actually work for me (the bot stops when encountering the cable), any other suggestions?

**Comment by louij2** [comment]
> 
> 
> This didn't actually work for me (the bot stops when encountering the cable), any other suggestions?

Yeah sometimes get issues where it stops too

**Comment by jef** [comment]
Fixed here https://github.com/jef/streetmerchant/pull/1161
