### ISSUE TITLE
Add New Big Navi links for AIBs (Included)

### ISSUE THREAD

**Issue by historypsi** [jef/streetmerchant#931]
### Description

New links for big Navi

ASRock Radeon RX 6800 Challenger Pro Gaming Graphics Card with 16GB GDDR6, AMD RDNA 2 (RX6800 CLP 16GO)
https://www.newegg.com/asrock-radeon-rx-6800-rx6800-clp-16go/p/N82E16814930047?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-930-047-_-Product

ASRock Radeon RX 6800 Phantom Gaming D Gaming Graphics Card with 16GB GDDR6, AMD RDNA 2 (RX6800 PGD 16GO)
https://www.newegg.com/asrock-radeon-rx-6800-rx6800-pgd-16go/p/N82E16814930048?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-930-048-_-Product

ASUS ROG STRIX Radeon RX 6800 ROG-STRIX-RX6800-O16G-GAMING 16GB 256-Bit GDDR6 PCI Express 4.0 HDCP Ready Video Card
https://www.newegg.com/asus-radeon-rx-6800-rog-strix-rx6800-o16g-gaming/p/N82E16814126477?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-126-477-_-Product

ASRock Radeon RX 6800 XT Taichi X 16G OC Gaming Graphics Card, RX6800XT TCX 16GO, AMD RDNA 2
https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-tcx-16go/p/N82E16814930050?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-930-050-_-Product

ASUS ROG STRIX Radeon RX 6800 XT ROG-STRIX-LC-RX6800XT-O16G-GAMING 16GB 256-Bit GDDR6 PCI Express 4.0 HDCP Ready Video Card
https://www.newegg.com/asus-radeon-rx-6800-xt-rog-strix-lc-rx6800xt-o16g-gaming/p/N82E16814126475?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-126-475-_-Product

ASUS TUF Gaming Radeon RX 6800 XT TUF-RX6800XT-O16G-GAMING 16GB 256-Bit GDDR6 PCI Express 4.0 HDCP Ready Video Card
https://www.newegg.com/asus-radeon-rx-6800-xt-tuf-rx6800xt-o16g-gaming/p/N82E16814126476?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-126-476-_-Product

PowerColor Red Devil Limited Edition AMD Radeon RX 6800 XT Gaming Graphics Card with 16GB GDDR6 Memory, Powered by AMD RDNA 2, Raytracing, PCI Express 4.0, HDMI 2.1, AMD Infinity Cache
https://www.newegg.com/powercolor-radeon-rx-6800-xt-axrx-6800xt-16gbd6-2dhce-oc/p/N82E16814131767?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-131-767-_-Product

XFX Radeon RX 6800 XT RX-68XTACBD9 16GB GDDR6 Video Card
https://www.newegg.com/xfx-radeon-rx-6800-xt-rx-68xtacbd9/p/N82E16814150844?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-150-844-_-Product

ASRock Radeon RX 6800 XT Phantom Gaming D Gaming Graphics Card with 16GB GDDR6, AMD RDNA 2 (RX6800XT PGD 16GO)
https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-pgd-16go/p/N82E16814930049?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-930-049-_-Product

SAPPHIRE NITRO+ Radeon RX 6800 XT DirectX 12 11304-01-20G 16GB 256-Bit GDDR6 PCI Express 4.0 ATX SE Gaming Graphics Card, AMD RDNA 2
https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-01-20g/p/N82E16814202390?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-202-390-_-Product

SAPPHIRE NITRO+ Radeon RX 6800 XT DirectX 12 11304-02-20G 16GB 256-Bit GDDR6 PCI Express 4.0 ATX Gaming Graphics Card, AMD RDNA 2
https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-02-20g/p/N82E16814202391?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-202-391-_-Product

ASUS TUF Gaming Radeon RX 6800 TUF-RX6800-O16G-GAMING 16GB 256-Bit GDDR6 PCI Express 4.0 HDCP Ready Video Card
https://www.newegg.com/asus-radeon-rx-6800-tuf-rx6800-o16g-gaming/p/N82E16814126478?Description=radeon%20rx%206800&cm_re=radeon_rx%206800-_-14-126-478-_-Product

### Possible solution

Add links

**Comment by trinitron79** [comment]
For the bestbuy.ts file could also add the XFX
Brand - XFX
Model - Merc 319 AMD Radeon™ RX 6800XT 16GB GDDR6 PCI Express 4.0 Gaming Graphics Card - Black
Model:RX-68XTACBD9
SKU:6442585 

Possible code (don't trust me on this)
<code>
bestbuy.ts
{
			brand: 'xfx',
			model: 'merc 319',
			series: 'rx6800xt',
			url:
				'https://www.bestbuy.com/site/xfx-merc-319-amd-radeon-rx-6800xt-16gb-gddr6-pci-express-4-0-gaming-graphics-card-black/6442585.p?skuId=6442585'
		},
</code>

**Comment by MuerteDeDios** [comment]
When updates are made to the SKUs the bot looks for (like these 6800 models) do we need to pull the latest code? Or is there a different way of updating them?

**Comment by trinitron79** [comment]
Here's what i've got for the newegg.ts for the above links in opening comment.   I have no idea how to help push the code so I'll just drop it here.

```
{   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930047',
			model: 'challenger',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-rx6800-clp-16go/p/N82E16814930047'
		},
        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930048',
			model: 'phantom',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-rx6800-pgd-16go/p/N82E16814930048'
		},
        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930049',
			model: 'phantom',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-pgd-16go/p/N82E16814930049'
		},
        {   
			brand: 'asrock',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814930050',
			model: 'taichi',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asrock-radeon-rx-6800-xt-rx6800xt-tcx-16go/p/N82E16814930050'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126478',
			model: 'tuf',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-tuf-rx6800-o16g-gaming/p/N82E16814126478'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126476',
			model: 'tuf',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-xt-tuf-rx6800xt-o16g-gaming/p/N82E16814126476'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126477',
			model: 'strix',
			series: 'rx6800',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-rog-strix-rx6800-o16g-gaming/p/N82E16814126477'
		},
        {   
			brand: 'asus',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814126475',
			model: 'strix lc',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/asus-radeon-rx-6800-xt-rog-strix-lc-rx6800xt-o16g-gaming/p/N82E16814126475'
		},
        {   
			brand: 'powercolor',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814131767',
			model: 'red devil',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/powercolor-radeon-rx-6800-xt-axrx-6800xt-16gbd6-2dhce-oc/p/N82E16814131767'
		},
        {   
			brand: 'sapphire',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202391',
			model: 'nitro+',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-02-20g/p/N82E16814202391'
		},
        {   
			brand: 'sapphire',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202390',
			model: 'nitro+ se',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-01-20g/p/N82E16814202390'
		},
        {   
			brand: 'xfx',
			cartUrl:
				'https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814150844',
			model: 'merc319',
			series: 'rx6800xt',
			url:
				'https://www.newegg.com/xfx-radeon-rx-6800-xt-rx-68xtacbd9/p/N82E16814150844'
		},
```

**Comment by trinitron79** [comment]
Don't forget the bestbuy.ts file :)

**Comment by historypsi** [comment]
Any word on these?

**Comment by trinitron79** [comment]
hasn't been committed to released code yet.

**Comment by jef** [comment]
I believe I only added some of the cards that were in #1098. I'll add these in later.

**Comment by jef** [comment]
> Here's what i've got for the newegg.ts for the above links in opening comment. I have no idea how to help push the code so I'll just drop it here.

I slightly altered the names, but you'll notice that. I need to merge the nitro cards...

**Comment by jef** [comment]
Added. Feel free to close if it's complete.

Thanks!
