### ISSUE TITLE
Error Opening Sound File

### ISSUE THREAD

**Issue by itzyoungen** [jef/streetmerchant#939]
### Description
everything works fine but I get this error: 

[7:11:12 PM] info :: 🚀🚨 [amazon-ca] [evga (3080)] ftw3 ultra :: IN STOCK 🚨🚀
https://www.amazon.ca/gp/aws/cart/add.html?ASIN.1=B08HR3Y5GQ&Quantity.1=1
[7:11:12 PM] error :: ✖ error opening sound file: ENOENT: no such file or directory, access 'yes'

running on a macbook pro.

**Comment by MujiSayed** [comment]
from what I'm getting there, looks like you need to link a sound file where you wrote 'yes'. Not 100% sure since i'm running mine on a remote server and haven't used that feature

**Comment by itzyoungen** [comment]
how would i go about linking a sound file?

**Comment by itzyoungen** [comment]
> from what I'm getting there, looks like you need to link a sound file where you wrote 'yes'. Not 100% sure since i'm running mine on a remote server and haven't used that feature
> 
> Edit: by linking the sound file, i mean the full path of the location of the sound file
I figured that much. but where do I put the path to the sound file?

**Comment by itzyoungen** [comment]
> from what I'm getting there, looks like you need to link a sound file where you wrote 'yes'. Not 100% sure since i'm running mine on a remote server and haven't used that feature
> 
> Edit: by linking the sound file, i mean the full path of the location of the sound file

**Comment by itzyoungen** [comment]
I  got it. thanks for the info.
