### ISSUE TITLE
Cannot get the bot to scrape stores for xbox series x

### ISSUE THREAD

**Issue by iamsapu** [jef/streetmerchant#940]
The bot has no problem searching for 3080, ps5, etc but it will not search for xbox series x whatsoever and I have it filled out just as it says in the .env instructions page. Am I doing something wrong or filling it in wrong maybe? I have the bot up to date, I'll post a copy of my current .env as well below.

BROWSER_TRUSTED="false"
COUNTRY="usa"
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_USERNAME=""
EMAIL_TO=""
EMAIL_PASSWORD=""
HEADLESS="true"
IN_STOCK_WAIT_TIME="0"
LOG_LEVEL="info"
LOW_BANDWIDTH="false"
MAX_PRICE_3070=""
MAX_PRICE_3080="850"
MAX_PRICE_3090=""
MICROCENTER_LOCATION="web"
NVIDIA_ADD_TO_CART_ATTEMPTS="10"
NVIDIA_SESSION_TTL="60000"
OPEN_BROWSER="true"
PAGE_BACKOFF_MIN="10000"
PAGE_BACKOFF_MAX="3600000"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
PAGE_TIMEOUT="60000"
PHONE_NUMBER=""
PHONE_CARRIER=""
PLAY_SOUND=""
PROXY_ADDRESS=""
PROXY_PORT="80"
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
SCREENSHOT="false"
SHOW_ONLY_BRANDS="nvidia,asus,evga,microsoft,sony"
SHOW_ONLY_MODELS="founders edition,rog strix,tuf,ftw3,xboxsx,ps5 console,ps5 digital"
SHOW_ONLY_SERIES="3080,sonyps5c,sonyps5de,xboxsx"
SLACK_CHANNEL=""
SLACK_TOKEN=""
SMTP_ADDRESS=""
SMTP_PORT="25"
STORES="bestbuy,newegg,playstation,walmart,target,gamestop,amazon"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
TWILIO_TO_NUMBER=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT="Chrome/78.0.3904.108"

**Comment by mbellman** [comment]
@iamsapu It looks like the **Models** README section has a typo for the Xbox Series X/S. The model identifiers are `xbox series x`/`xbox series s`, whereas the _series_ identifiers are `xboxsx`/`xboxss`.

Change `SHOW_ONLY_MODELS` to include `xbox series x` and you should be golden.

**Comment by iamsapu** [comment]
Thanks that fixed it right up!!
