### ISSUE TITLE
npm run start not working

### ISSUE THREAD

**Issue by Eribaeri** [jef/streetmerchant#957]
npm run start not working, a lot of syntax possibillities given by cmd

I fixed my directory issues by simply copying the package file out of c/Users/Username/streetmerchant into c/Users/Username. 
Npm run install worked this way with two warnings. 
Npm run starts causes the following: 
> streetmerchant@ start C:\Users\Username
> npm run build && node build/index.js

> build
> tsc

Version 4.1.2
Syntax:   tsc [options] [file...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
          tsc --build tsconfig.json

Options: Literally like 200 comands, everything that would be possible

npm ERR! code 1
npm ERR! path C:\Users\Username
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-11-26T16_25_49_224Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streetmerchant@ start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the streetmerchant@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-11-26T16_25_49_243Z-debug.log

Please help me to get the Bot starting, i would really like to use it for getting an RX6800 in Germany. 
Kind regards,
Erik

**Comment by Lo0n** [comment]
Hello,

I am experiencing the same issue. What was the solution?

Thanks in advance,
Brandon

**Comment by Eribaeri** [comment]
Hi Brandon,
I had two problems. 
My first problem was that I didn't select the right directory. This can be fixed with "CD" "[space]" "[insert the right directory, like where you installed streetmerchant]".
Then you can run npm-install / npm run start.
If cmd doesn't find "package", copy into the folder the folder "street-merchant" is in as well, so one step further "upwards".
Edit the .env-file and run npm run start.
This helped me and I do not know anything more since I didn't encounter any further problems. 
Greetings,
Erik

**Comment by jackroutledge** [comment]
c:\>npm run start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path c:\/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'c:\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jack\AppData\Local\npm-cache\_logs\2020-12-03T08_05_02_333Z-debug.log

i think im just going to give up

**Comment by Eribaeri** [comment]
Jack,
you have the exact same problem as Brandon and therefore you need to read my answer to Brandon.
First of all, you need to get to the right directory (or folder, i don't know the right word).
Therefore you have to enter "CD" "Path". You can get the path by browsing the location of the folder and then copying the path. Paste the path after "CD", press enter, and suddenly, npm commands will work. 
Greetings,
Erik

**Comment by superoloyt** [comment]
not working for me.
