### ISSUE TITLE
"bestbuy-ca" for STORES is not working

### ISSUE THREAD

**Issue by holloxob** [jef/streetmerchant#962]
Used to do `STORES="amazon-ca, walmart, playstation, bestbuy-ca"`
Only bestbuy-ca is not being checked.
Edited to have only bestbuy-ca, `STORES="bestbuy-ca"`, now no info is coming out.

I pasted an image of me waiting for 10 mins and it is still not showing any info.
![image](https://user-images.githubusercontent.com/73460193/100391867-b70e8680-2fe9-11eb-93b1-3340c540ce89.png)

**Comment by cloutid** [comment]
the bestbuy-ca store doesn't have the links within it's ts file to check the ps5.
