### ISSUE TITLE
Add support for EVGA's water cooled GPU's 

### ISSUE THREAD

**Issue by Shadow223** [jef/streetmerchant#965]
Hey!  Is it possible to add support for EVGA's water-cooled cards?  This is the main one I am looking to add: https://www.evga.com/products/product.aspx?pn=10G-P5-3899-KR

If not is it possible for me to manually add this myself?

**Comment by HunterAP23** [comment]
I second this, as well as adding other AIB's watercooled cards like the Gigabyte XTREME Waterforce and Asus XTREME Waterforce (coincidentally also named the same thing).
