### ISSUE TITLE
keep getting this error

### ISSUE THREAD

**Issue by RealityMyx** [jef/streetmerchant#966]
### I keep getting this error every time i try to run it with nothing i try working.

 error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary. {
  "stack": "Error: Could not find browser revision 818858. Run \"PUPPETEER_PRODUCT=firefox npm install\" or \"PUPPETEER_PRODUCT=firefox yarn install\" to download a supported Firefox browser binary.\n    at ChromeLauncher.launch (C:\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\Launcher.js:79:23)\n    at async PuppeteerExtra.launch (C:\\streetmerchant\\node_modules\\puppeteer-extra\\dist\\index.cjs.js:129:25)\n    at async main (C:\\streetmerchant\\build\\index.js:46:15)\n    at async loopMain (C:\\streetmerchant\\build\\index.js:82:9)"

**Comment by maglat** [comment]
same for me on my raspberry

**Comment by subroot-dev** [comment]
Run this command: PUPPETEER_PRODUCT=firefox npm i puppeteer

**Comment by stucarney** [comment]
I had the same error.  I fixed it by running 'npm install' in ./node_modules/puppeteer-extra/ dir.

**Comment by jef** [comment]
https://github.com/jef/streetmerchant/wiki/Installation:-Windows
