### ISSUE TITLE
Troubleshooting adding store Amazon-it

### ISSUE THREAD

**Issue by Maecenass** [jef/streetmerchant#972]
**DESCRIPTION**
I'm trying to add at least amazon-it compatibility, i've already read the the amazon-jp issue opened and i noticed there are strings that i do not understand, and i don't know _how to understand_ to write the right code because _indeed_ i don't know how to code. Any help troubleshooting guys ? :))

**MY AMAZON-IT.TS code right now**
import {Store} from './store';

export const AmazonIt: Store = {
	labels: {
		inStock: {
			container: '#desktop_buybox',
			text: ['aggiungi al carrello']
		},
		maxPrice: {
			container: 'span[class*="PriceString"]',
			euroFormat: false
		}
	},
	links: [
		{
			brand: 'sony',
			model: 'ps5 console',
			series: 'sonyps5c',
			url: 'https://www.amazon.it/dp/B08KKJ37F7'
		},
		{
			brand: 'sony',
			model: 'ps5 digital',
			series: 'sonyps5de',
			url: 'https://www.amazon.it/dp/B08KJF2D25'
		}
	],
	name: 'amazon-it'
};

**NOTES**
the indexing of the website is working, right now the program find the store and the series sonyps5c and sonyps5de but it can't ping them.

**Comment by lucarin91** [comment]
I recently write a Pull Request in which I add Amazon-it and other Italian stores with the PlayStation 5 links.
I am now waiting for @jef to review my changes, but you can anyway check them here #976.

**Comment by Maecenass** [comment]
> I recently write a Pull Request in which I add Amazon-it and other Italian stores with the PlayStation 5 links.
> I am now waiting for @jef to review my changes, but you can anyway check them here #976.

Hey lucarin91, in the end i managed to make the bot work on amazon-it but seeing you wrote the code for the other stores is very heart-warming. In the mouth of the wolf!
