### ISSUE TITLE
Telegram notify

### ISSUE THREAD

**Issue by Maecenass** [jef/streetmerchant#973]
**DESCRIPTION**
Anyone can help me understand how the telegram notification works?
What
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
actually stand for and how can i program them to chat in a group ?
Thank you very much.

**Comment by PhriZ** [comment]
You need to create bot first. (Search for @botfather in Telegram and create a /newbot)
You will get a HTTP Access Token too.

After that put im in a group or search for your new bot and chat with him (or in that group). 
You will then be able to call https://api.telegram.org/bot[HTTP-TOKEN]/getUpdates (without []) in a browser and look for the [...]"chat":{"id":374629384, [...]
