### ISSUE TITLE
i had this error

### ISSUE THREAD

**Issue by UBoot361** [jef/streetmerchant#984]
<--- Last few GCs --->

[19952:00000211B765A820]    55155 ms: Mark-sweep (reduce) 4096.7 (4109.0) -> 4093.9 (4110.5) MB, 2186.5 / 0.0 ms  (+ 0.0 ms in 66 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2215 ms) (average mu = 0.121, current mu =[19952:00000211B765A820]    57164 ms: Mark-sweep (reduce) 4095.1 (4106.5) -> 4094.3 (4106.7) MB, 2003.2 / 0.0 ms  (average mu = 0.062, current mu = 0.003) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 00007FF6F1DF021F napi_wrap+109311
 2: 00007FF6F1D95286 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfElementsOffset+33302
 3: 00007FF6F1D96056 node::OnFatalError+294
 4: 00007FF6F266054E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6F26453CD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6F24EF85C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6F24DA49B v8::internal::NativeContextInferrer::Infer+59243
 8: 00007FF6F24BF9CF v8::internal::MarkingWorklists::SwitchToContextSlow+57327
 9: 00007FF6F24D361B v8::internal::NativeContextInferrer::Infer+30955
10: 00007FF6F24CA73D v8::internal::MarkCompactCollector::EnsureSweepingCompleted+6269
11: 00007FF6F24D286E v8::internal::NativeContextInferrer::Infer+27454
12: 00007FF6F24D67FB v8::internal::NativeContextInferrer::Infer+43723
13: 00007FF6F24E0052 v8::internal::ItemParallelJob::Task::RunInternal+18
14: 00007FF6F24DFFE1 v8::internal::ItemParallelJob::Run+641
15: 00007FF6F24B38E3 v8::internal::MarkingWorklists::SwitchToContextSlow+7939
16: 00007FF6F24CABEC v8::internal::MarkCompactCollector::EnsureSweepingCompleted+7468
17: 00007FF6F24C9434 v8::internal::MarkCompactCollector::EnsureSweepingCompleted+1396
18: 00007FF6F24C6F98 v8::internal::MarkingWorklists::SwitchToContextSlow+87480
19: 00007FF6F24F55E1 v8::internal::Heap::LeftTrimFixedArray+929
20: 00007FF6F24F76C5 v8::internal::Heap::PageFlagsAreConsistent+789
21: 00007FF6F24EC971 v8::internal::Heap::CollectGarbage+2033
22: 00007FF6F24EAB75 v8::internal::Heap::AllocateExternalBackingStore+1317
23: 00007FF6F250AF67 v8::internal::Factory::NewFillerObject+183
24: 00007FF6F223AFF1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
25: 00007FF6F26E8EFD v8::internal::SetupIsolateDelegate::SetupHeap+463949
26: 00007FF6F2682FDD v8::internal::SetupIsolateDelegate::SetupHeap+46381
27: 0000016D9728405C
npm ERR! code 134
npm ERR! path C:\Users\jswis
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jswis\AppData\Roaming\npm-cache\_logs\2020-11-27T20_50_19_554Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! streetmerchant@ start: `npm run build && node build/index.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the streetmerchant@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jswis\AppData\Roaming\npm-cache\_logs\2020-11-27T20_50_19_573Z-debug.log

**Comment by jef** [comment]
You ran out of memory. This happens when A) your computer doesn't have a lot of RAM or B) you are searching too many products and your computer can't handle that many tabs.
