### ISSUE TITLE
Some Pretty dumb but simple Q's

### ISSUE THREAD

**Issue by Niswendel** [jef/streetmerchant#987]
### Description

So I have it all setup, but I have a few questions.
How do I edit the env file, for example making INCOGNITO true. Lastly how do I change the selected stores/item?

Sorry for the stupidity,
Thanks!

**Comment by Niswendel** [comment]
Also how do I set up notifications and test the whole thing?

**Comment by Niswendel** [comment]
I tried PHONE_NUMBER=xxxxxxxxxx (my number) and got something saying that that is not a valid command

**Comment by RJMoise** [comment]
> how do I change the selected stores/item?
Did you read through the setup at all? It explains everything.
Open the .env, go to STORES and enter the ones you want it to search for. The main page has a list of available options. This goes for items as well, go to BRANDS/MODELS/SERIES and enter the ones you want it to search for.

> Also how do I set up notifications and test the whole thing?
Again, its in the setup if you read through it. Add your email, emailpassword, and the email you want the Notis to go to. You can also add your phone carrier and number. All of this is in the .env. I recommend notepad++ or visualStudio Code to open it in.

**Comment by jiglesiasc** [comment]
This video made it pretty easy for me:

https://www.youtube.com/watch?v=bVgIpjBkRLY
