### ISSUE TITLE
lot of errors

### ISSUE THREAD

**Issue by lofiy** [jef/streetmerchant#995]
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'allowJs'.
error TS5023: Unknown compiler option 'strict'.
error TS5023: Unknown compiler option 'esModuleInterop'.
error TS5023: Unknown compiler option 'resolveJsonModule'.
error TS5023: Unknown compiler option 'skipLibCheck'.
error TS5023: Unknown compiler option 'forceConsistentCasingInFileNames'.
npm ERR! code 1
npm ERR! path C:\Users\vlogg\Desktop\streetmerchant-main\streetmerchant
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vlogg\AppData\Local\npm-cache\_logs\2020-11-28T05_38_03_748Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\vlogg\Desktop\streetmerchant-main\streetmerchant
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build && node build/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vlogg\AppData\Local\npm-cache\_logs\2020-11-28T05_38_03_782Z-debug.log

**Comment by jef** [comment]
https://jef.codes/streetmerchant/getting-started/
https://github.com/jef/streetmerchant/wiki/Installation:-Windows
