### ISSUE TITLE
DONT USE GAMESTOP

### ISSUE THREAD

**Issue by Niswendel** [jef/streetmerchant#999]
My server was banned from gamestop using the software.

**Comment by controledxchaos** [comment]
same here!

**Comment by jef** [comment]
Same with Asus. This will happen if you reach rate limits.

**Comment by huntinganswers** [comment]
same here!  gamestop is a shitstorm anyway

**Comment by faaaaq** [comment]
Add newegg to the list now as well.  I was using Streetmerchant for over a week every day all day no problem, and as of sometime in the last couple hours Newegg has IP banned me.  I'm not mad at the tool obvs, just adding another store to the list of stores people need to be careful with.

**Comment by huntinganswers** [comment]
same here .. 2 or so hours ago.  The funny thing - I've spent 10s of thousands of dollars there over the years.  I won't anymore.

**Comment by faaaaq** [comment]
> same here .. 2 or so hours ago. The funny thing - I've spent 10s of thousands of dollars there over the years. I won't anymore.

That is a silly response to them punishing you for doing something you knew (or should have known) is against their TOS..  They are clearly enforcing it now, finally, to try to stop scalpers.  The fact that I got blocked even though I'm not a scalper (I just want a 3080 :( ) isn't their fault.  If you're a scalper and you're upset, then I no longer care about your feelings either way, so, yea.  If you aren't a scalper, email them per the 403 page message and say you're sorry and it won't happen again, and I'm sure they'll unblock you fairly quickly.  Then if you wish to use StreetMerchant again just set up a proxy.

**Comment by huntinganswers** [comment]
> > same here .. 2 or so hours ago. The funny thing - I've spent 10s of thousands of dollars there over the years. I won't anymore.
> 
> That is a silly response to them punishing you for doing something you knew (or should have known) is against their TOS.. They are clearly enforcing it now, finally, to try to stop scalpers. The fact that I got blocked even though I'm not a scalper (I just want a 3080 :( ) isn't their fault. If you're a scalper and you're upset, then I no longer care about your feelings either way, so, yea. If you aren't a scalper, email them per the 403 page message and say you're sorry and it won't happen again, and I'm sure they'll unblock you fairly quickly. Then if you wish to use StreetMerchant again just set up a proxy.

im not a scalper dipshit - I'm a geologist attempting to get a ps5 for my nephew.  I couldn't care less about the TOS

**Comment by jef** [comment]
Going to lock and close this before this gets out of hand :sweat_smile: 

Thanks everyone.
